### PR TITLE
Fix default target in Makefile and add custom command clean to setup.py

### PR DESCRIPTION
**Pull request by ana**
This is part of a split of PR https://github.com/avocado-framework/avocado-vt/pull/3173

### CODE REVIEW

**Comment by chunfuwen** [comment]
Can we squash two commits as one ?

**Comment by ana** [comment]
> Can we squash two commits as one ?

done!

**Comment by ana** [comment]
@chunfuwen I have squashed the commits, could you please check if this ready to merge? Thanks.

**Review by Yingshun — APPROVED** [review]
LGTM. Tested in my env and 'clean' worked well - /build and __pycache__ and other related dirs were removed correctly.

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
