### PR TITLE
pyvmomi: fix connection issue in latest pyvmomi

### PR DESCRIPTION
**Pull request by xiaodwan**

### CODE REVIEW

**Comment by xiaodwan** [comment]
```
>>> connect_args = {'host': "xxx", 'user': 'xxx', 'pwd': 'xxx'}
>>> with VSphereConnection(**connect_args) as conn:
...     conn.target_vm = "xxx"
...     print(conn.get_vm_summary()['mac_address'])
... 
['00:50:56:a0:11:ac']

```

**Comment by vwu-vera** [comment]
It is working on RHEL10. :)
 (1/1) type_specific.io-github-autotest-libvirt.nbdkit.run.vddk7_0.esx: PASS (194.52 s)

**Comment by vwu-vera** [comment]
@chunfuwen Please help to review and merge. Thanks.:)

**Review by chunfuwen — APPROVED** [review]
lgtm

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
