### PR TITLE
hotfix for memory hotplug test in windows guest

### PR DESCRIPTION
**Pull request by xutian**
Fix windows guest report wrong memory size issue

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1329947

**Comment by spcui** [comment]
Tested and pass, so Acked-by: scui@redhat.com

**Comment by MiriamDeng** [comment]
Run it on windows but got the following errors 
VMCreateError: VM creation command failed:    "MALLOC_PERTURB_=1  /usr/libexec/qemu-kvm -S  -name 'avocado-vt-vm1'  -sandbox off  -machine pc  -nodefaults  -vga std  -chardev socket,id=qmp_id_qmpmonitor1,path=/var/tmp/avocado_VAuFWx/monitor-qmpmonitor1-20160504-175336-zk8uHiwG,server,nowait -mon chardev=qmp_id_qmpmonitor1,mode=control  -chardev socket,id=qmp_id_catch_monitor,path=/var/tmp/avocado_VAuFWx/monitor-catch_monitor-20160504-175336-zk8uHiwG,server,nowait -mon chardev=qmp_id_catch_monitor,mode=control -device pvpanic,ioport=0x505,id=idpyfHYN  -chardev socket,id=serial_id_serial0,path=/var/tmp/avocado_VAuFWx/serial-serial0-20160504-175336-zk8uHiwG,server,nowait -device isa-serial,chardev=serial_id_serial0  -chardev socket,id=seabioslog_id_20160504-175336-zk8uHiwG,path=/var/tmp/avocado_VAuFWx/seabios-20160504-175336-zk8uHiwG,server,nowait -device isa-debugcon,chardev=seabioslog_id_20160504-175336-zk8uHiwG,iobase=0x402 -device ich9-usb-ehci1,id=usb1,addr=1d.7,multifunction=on,bus=pci.0 -device ich9-usb-uhci1,id=usb1.0,multifunction=on,masterbus=usb1.0,addr=1d.0,firstport=0,bus=pci.0 -device ich9-usb-uhci2,id=usb1.1,multifunction=on,masterbus=usb1.0,addr=1d.2,firstport=2,bus=pci.0 -device ich9-usb-uhci3,id=usb1.2,multifunction=on,masterbus=usb1.0,addr=1d.4,firstport=4,bus=pci.0 -device virtio-scsi-pci,id=virtio_scsi_pci0,bus=pci.0,addr=03 -drive id=drive_image1,if=none,cache=unsafe,snapshot=off,aio=native,format=qcow2,file=/home/staf-kvm-devel/workspace/usr/share/avocado/data/avocado-vt/images/win7-64-sp1-virtio-scsi.qcow2 -device scsi-hd,id=image1,drive=drive_image1 -device virtio-net-pci,mac=9a:86:87:88:89:8a,id=idKWNyvK,vectors=4,netdev=idCBGlYA,bus=pci.0,addr=04  -netdev tap,id=idCBGlYA,vhost=on,vhostfd=20,fd=19 -m 1024,slots=4,maxmem=32G -object memory-backend-ram,policy=default,size=1G,id=mem-mem1 -device pc-dimm,id=dimm-mem1,memdev=mem-mem1  -smp 2,maxcpus=2,cores=1,threads=1,sockets=2  -numa node  -cpu 'SandyBridge',hv_relaxed,+kvm_pv_unhalt,hv_spinlocks=0x1fff,hv_vapic,hv_time -drive id=drive_cd1,if=none,snapshot=off,aio=native,media=cdrom,file=/home/staf-kvm-devel/workspace/usr/share/avocado/data/avocado-vt/isos/windows/winutils.iso -device scsi-cd,id=cd1,drive=drive_cd1 -device usb-tablet,id=usb-tablet1,bus=usb1.0,port=1  -vnc :0  -rtc base=localtime,clock=host,driftfix=slew  -boot order=cdn,once=c,menu=off,strict=off -enable-kvm"    (status: 1,    output: 'qemu: invalid ram size: 1024,slots=4,maxmem=32G')

**Comment by xutian** [comment]
@MiriamDeng which version qemu you used to verify this PR, let me have a try. below qemu command line works on my host.

/usr/libexec/qemu-kvm  -m 1024,slots=4,maxmem=32G -object memory-backend-ram,policy=default,size=1G,id=mem-mem1 -device pc-dimm,id=dimm-mem1,memdev=mem-mem1 -smp 2,maxcpus=2,cores=1,threads=1,sockets=2  -vnc :0 -monitor stdio -enable-kvm

**Comment by MiriamDeng** [comment]
Communicated with xutian and I was told  qemu-kvm version doesn't support hotplug memory so I will have a try on qemu-kvm-rhev version.I will update results as soon as I complete testing.

**Comment by MiriamDeng** [comment]
Test it on qemu-kvm-rhev version and job can pass without errors so giving 
Acked-by: Min Deng <mdeng@redhat.com>

**Comment by xutian** [comment]
Merged, thanks @spcui and @MiriamDeng.

**Pull request merged**
