### PR TITLE
qdevices: Add --terminate option for swtpm command

### PR DESCRIPTION
**Pull request by qcheng-redhat**
qdevices: Add --terminate option for swtpm command
Signed-off-by: qcheng <qcheng@redhat.com>

ID: 2028018

### CODE REVIEW

**Comment by qcheng-redhat** [comment]
Test results:

RHEL 9:
 (1/4) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.tpm_verify_device.with_emulator.q35: PASS (118.09 s)
 (2/4) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.tpm_verify_device.with_emulator.with_check_ovmf.q35: PASS (85.79 s)
 (3/4) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.tpm_verify_device.with_emulator.with_reboot.q35: PASS (879.51 s)
 (4/4) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.tpm_verify_device.with_emulator.with_multi_vms.q35: PASS (228.70 s)

RHEL 8.6
 (1/5) Host_RHEL.m8.u6.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.tpm_verify_device.with_emulator.q35: PASS (113.95 s)
 (2/5) Host_RHEL.m8.u6.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.tpm_verify_device.with_emulator.with_check_ovmf.q35: PASS (80.89 s)
 (3/5) Host_RHEL.m8.u6.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.tpm_verify_device.with_emulator.with_reboot.q35: PASS (775.48 s)
 (4/5) Host_RHEL.m8.u6.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.tpm_verify_device.with_emulator.with_multi_vms.q35: PASS (227.65 s)
 (5/5) Host_RHEL.m8.u6.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.tpm_verify_device.with_passthrough.q35: CANCEL: No found TPM device on host, output: ls: cannot access '/dev/tpm0': No such file or directory (2.56 s)

**Comment by qcheng-redhat** [comment]
@YongxueHong Can you help review this patch when you have time. Thanks.

**Comment by YongxueHong** [comment]
Hi, @qcheng-redhat 
Please update your commit message:
```
qdevices: Add --terminate option for swtpm command

Signed-off-by: qcheng <qcheng@redhat.com>

ID: 2028018
Signed-off-by: qcheng <qcheng@redhat.com>
```
1. Delete the info : `ID: 2028018`
2. Delete the redundant info: `Signed-off-by: qcheng <qcheng@redhat.com>`

**Comment by qcheng-redhat** [comment]
Updated.

**Review by YongxueHong — APPROVED** [review]

**Pull request merged**
