### PR TITLE
Run vm.get_address() method on certain interfaces.

### PR DESCRIPTION
**Pull request by Andrei-Stepanov**
Up to this moment vm.get_address() went through all host's NICs to get
VM's address. This was very time consuming for hosts with several NICs.
It was because each call vm.wait_for_login() always called
vm.get_address(). Wich, in its turn, could be paused for 1 minute for
'wrong' interface.

Signed-off-by: Andrei Stepanov <astepano@redhat.com>

### CODE REVIEW

**Comment by Andrei-Stepanov** [comment]
Could someone try to run tests with this patch?
It works for me, but I do not know how it will be influence other tests.

**Comment by will-Do** [comment]
This should affect lots of libvirt test cases, I will run our job with patch and give feedback later

**Comment by will-Do** [comment]
libvirt tests work fine with this patch

**Comment by Andrei-Stepanov** [comment]
Hi ) Could someone please merge this pull req?) @xutian ?
Thank you.

**Pull request merged**
