### PR TITLE
virtio_mem: includes virtio_mem device hotplug

### PR DESCRIPTION
**Pull request by mcasquer**
Includes support for virtio_mem device hotplug

ID: 2127829
Signed-off-by: mcasquer <mcasquer@redhat.com>

### CODE REVIEW

**Comment by mcasquer** [comment]
@PaulYuuu @luckyh could you review this PR? Thanks!

**Comment by mcasquer** [comment]
@PaulYuuu @luckyh could you review this PR? Thanks!

**Review by PaulYuuu — APPROVED** [review]

**Review by luckyh — APPROVED** [review]
LGTM

**Comment by mcasquer** [comment]
@PaulYuuu @luckyh since you both have approved this, could this PR be merged? Thanks!

**Comment by luckyh** [comment]
> @PaulYuuu @luckyh since you both have approved this, could this PR be merged? Thanks!

Sure, let's get it :)

**Pull request merged**
