### PR TITLE
virttest.gluster: echo the confirm infomation for gluster volume stop/delete command.

### PR DESCRIPTION
**Pull request by rbian**
gluster volume stop/delete command promote user to confirm the
operation, the code should handle stdin and input the confirmation
string. Otherwise, the command will timeout.

### CODE REVIEW

**Comment by rbian** [comment]
The patch seems can not work, I will submit another later.

**Comment by rbian** [comment]
It has passed my test.

**Comment by PandaWei** [comment]
Looks good

**Comment by will-Do** [comment]
ACK and merge this pr.

**Pull request merged**
