### PR TITLE
Update to check libvirt version by 'libvirtd' or 'virtqemud' command

### PR DESCRIPTION
**Pull request by Yingshun**
If there was an issue while connecting to virsh client, it would
be failed to get libvirtd version.

Signed-off-by: Yingshun Cui <yicui@redhat.com>

### CODE REVIEW

**Comment by Yingshun** [comment]
**Test result:**
```
[root@hpe-bl460cgen9-01 ~]# virsh version
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Connection refused

[root@hpe-bl460cgen9-01 ~]# 

>>> libvirt_version.version_compare(6,0,0,session)
True
>>> libvirt_version.version_compare(6,5,0,session)
False

```

**Comment by Yingshun** [comment]
@yafu-1  Can you please help review?

**Comment by sathnaga** [comment]
@Yingshun one thing I noticed with latest libvirt versions, `virsh version` command starts the libvirtd even if stopped

```
$ service libvirtd status|grep Active
Redirecting to /bin/systemctl status libvirtd.service
   Active: inactive (dead) since Wed 2020-07-15 10:16:40 EDT; 12s ago

$ virsh version
Compiled against library: libvirt 6.4.0
Using library: libvirt 6.4.0
Using API: QEMU 6.4.0
Running hypervisor: QEMU 4.1.1

$ service libvirtd status|grep Active
Redirecting to /bin/systemctl status libvirtd.service
   Active: active (running) since Wed 2020-07-15 10:17:18 EDT; 3s ago

```
This kind of make this change not necessary right?

I guess `virsh version` should not change anytime in future but  I am not sure `libvirtd` naming for dameon, given that libvirt daemons are split into many.

suggestions to explore in those lines. tnx!

**Comment by Yingshun** [comment]
> @Yingshun one thing I noticed with latest libvirt versions, `virsh version` command starts the libvirtd even if stopped
> 
> ```
> $ service libvirtd status|grep Active
> Redirecting to /bin/systemctl status libvirtd.service
>    Active: inactive (dead) since Wed 2020-07-15 10:16:40 EDT; 12s ago
> 
> $ virsh version
> Compiled against library: libvirt 6.4.0
> Using library: libvirt 6.4.0
> Using API: QEMU 6.4.0
> Running hypervisor: QEMU 4.1.1
> 
> $ service libvirtd status|grep Active
> Redirecting to /bin/systemctl status libvirtd.service
>    Active: active (running) since Wed 2020-07-15 10:17:18 EDT; 3s ago
> ```
> 
> This kind of make this change not necessary right?
> 
> I guess `virsh version` should not change anytime in future but I am not sure `libvirtd` naming for dameon, given that libvirt daemons are split into many.
> 
> suggestions to explore in those lines. tnx!

@sathnaga Thanks for your comments.
It looks like libvirtd.socket which starts libvirtd.service once 'virsh' command's executed is running in your environment.
Below is one of cases that libvirtd.service cannot be up.
# systemctl stop libvirtd.socket
# systemctl stop libvirtd.service
# virsh version
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Connection refused

And for 'libvirtd' command line, that's a good point, let wait for @yafu-1 's response, she is feature owner of this feature.

**Comment by sathnaga** [comment]
> > @Yingshun one thing I noticed with latest libvirt versions, `virsh version` command starts the libvirtd even if stopped
> > ```
> > $ service libvirtd status|grep Active
> > Redirecting to /bin/systemctl status libvirtd.service
> >    Active: inactive (dead) since Wed 2020-07-15 10:16:40 EDT; 12s ago
> > 
> > $ virsh version
> > Compiled against library: libvirt 6.4.0
> > Using library: libvirt 6.4.0
> > Using API: QEMU 6.4.0
> > Running hypervisor: QEMU 4.1.1
> > 
> > $ service libvirtd status|grep Active
> > Redirecting to /bin/systemctl status libvirtd.service
> >    Active: active (running) since Wed 2020-07-15 10:17:18 EDT; 3s ago
> > ```
> > 
> > 
> > This kind of make this change not necessary right?
> > I guess `virsh version` should not change anytime in future but I am not sure `libvirtd` naming for dameon, given that libvirt daemons are split into many.
> > suggestions to explore in those lines. tnx!
> 
> @sathnaga Thanks for your comments.
> It looks like libvirtd.socket which starts libvirtd.service once 'virsh' command's executed is running in your environment.
> Below is one of cases that libvirtd.service cannot be up.
>

Ah, okies, thanks for the explain!.
 
> ```
> $ systemctl stop libvirtd.socket
> $ systemctl stop libvirtd.service
> $ virsh version
> error: failed to connect to the hypervisor
> error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Connection refused
> ```
> 
> And for 'libvirtd' command line, that's a good point, let wait for @yafu-1 's response, she is feature owner of this feature.

Sure.

**Comment by yafu-1** [comment]
> > > @Yingshun one thing I noticed with latest libvirt versions, `virsh version` command starts the libvirtd even if stopped
> > > ```
> > > $ service libvirtd status|grep Active
> > > Redirecting to /bin/systemctl status libvirtd.service
> > >    Active: inactive (dead) since Wed 2020-07-15 10:16:40 EDT; 12s ago
> > > 
> > > $ virsh version
> > > Compiled against library: libvirt 6.4.0
> > > Using library: libvirt 6.4.0
> > > Using API: QEMU 6.4.0
> > > Running hypervisor: QEMU 4.1.1
> > > 
> > > $ service libvirtd status|grep Active
> > > Redirecting to /bin/systemctl status libvirtd.service
> > >    Active: active (running) since Wed 2020-07-15 10:17:18 EDT; 3s ago
> > > ```
> > > 
> > > 
> > > This kind of make this change not necessary right?
> > > I guess `virsh version` should not change anytime in future but I am not sure `libvirtd` naming for dameon, given that libvirt daemons are split into many.
> > > suggestions to explore in those lines. tnx!
> > 
> > 
> > @sathnaga Thanks for your comments.
> > It looks like libvirtd.socket which starts libvirtd.service once 'virsh' command's executed is running in your environment.
> > Below is one of cases that libvirtd.service cannot be up.
> 
> Ah, okies, thanks for the explain!.
> 
> > ```
> > $ systemctl stop libvirtd.socket
> > $ systemctl stop libvirtd.service
> > $ virsh version
> > error: failed to connect to the hypervisor
> > error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Connection refused
> > ```
> > 
> > 
> > And for 'libvirtd' command line, that's a good point, let wait for @yafu-1 's response, she is feature owner of this feature.
> 
> Sure.
@Yingshun @sathnaga 
Yes, we should consider the split deamons which will be the default mode latter.  
How about check whether /usr/sbin/virtqemud exists? If exists, using 'virtqemud -V', otherwise using 'libvirtd -V'.

**Comment by Yingshun** [comment]
@sathnaga @yafu-1 @chloerh Updated, please help review again. 

**Test result:** please ignore 'cmd is xxx', it's a debug info, I've removed it from code.
no virtqemud:
```
>>> libvirt_version.version_compare(6,6,0, session)
cmd is libvirtd
False
>>> libvirt_version.version_compare(6,5,0, session)
cmd is libvirtd
True
>>> libvirt_version.version_compare(6,6,0)
cmd is libvirtd
False
>>> libvirt_version.version_compare(6,5,0)
cmd is libvirtd
True
>>> 
```

virtqemud exists：
```
>>> libvirt_version.version_compare(6,5,0, session)
cmd is virtqemud
True
>>> libvirt_version.version_compare(6,6,0, session)
cmd is virtqemud
False
>>> libvirt_version.version_compare(6,5,0)
cmd is virtqemud
True
>>> libvirt_version.version_compare(6,6,0)
cmd is virtqemud
False

```

**Pull request merged**
