### PR TITLE
Add missing attributes to the test status

### PR DESCRIPTION
**Pull request by richtja**
In avocado #5586 we added missing tributes for result plugins. This is a fix for avocado-vt runner.

Reference: https://github.com/avocado-framework/avocado/pull/5586
Signed-off-by: Jan Richter <jarichte@redhat.com>

### CODE REVIEW

**Comment by richtja** [comment]
Hi @luckyh can you please check if this together with avocado master fixes your issue from https://github.com/avocado-framework/avocado/issues/5332, thanks.

**Comment by yanan-fu** [comment]
Thanks for letting me know !  I will check it together with https://github.com/avocado-framework/avocado/pull/5586 soon.

**Comment by yanan-fu** [comment]
I have confirmed that with the fix in avocado https://github.com/avocado-framework/avocado/pull/5586 and the avocado vt runner https://github.com/avocado-framework/avocado-vt/pull/3618, no missing field with the final xunit file now.

**Comment by luckyh** [comment]
Hi @richtja the code looks good to me, but I see some of the ci checks were still failed and I'm not sure whether it was a separated issue, would you please help check that?

Thanks!

**Comment by richtja** [comment]
> Hi @richtja the code looks good to me, but I see some of the ci checks were still failed and I'm not sure whether it was a separated issue, would you please help check that?
> 
> Thanks!

Hi @luckyh I was able to fix CI issues with `force-push`, please have a look.

**Review by luckyh — APPROVED** [review]

**Comment by luckyh** [comment]
Thanks to all!

**Pull request merged**
