### PR TITLE
qcontainer: Fix aio unset error

### PR DESCRIPTION
**Pull request by YongxueHong**
ID: 1746697
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
@XueqiangWei @luckyh  pls help review, thanks.

**Comment by XueqiangWei** [comment]
Tested with drive and blockdev, all passed. And set aio option correctly.

(1/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.fio_linux.aio_native.q35: PASS (594.37 s)
 (2/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.fio_linux.aio_threads.q35: PASS (594.94 s)

LGTM,
Acked-by xuwei@redhat.com

**Comment by luckyh** [comment]
Thanks all.

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
