### PR TITLE
CI updates: cirrus, gha and requirements-travis.txt

### PR DESCRIPTION
**Pull request by ana**
* Cirrus CI: add dockerfile for Fedora 35
    
This dockerfile is the source for the pre-built container at https://quay.io/repository/avocado-framework/avocado-vt-ci-fedora-35
Remove old dockerfiles.

* CI: add test on Python 3.10.1
* `requirements-travis.txt`: update and use fixed versions

### CODE REVIEW

**Comment by ana** [comment]
Once https://github.com/avocado-framework/avocado-vt/pull/3328 is merged, this PR can be rebased and test should work.

**Comment by ana** [comment]
FTR the 2 jobs failing are the ones with a fix at https://github.com/avocado-framework/avocado-vt/pull/3295

**Review by clebergnu — APPROVED** [review]
LGTM, thanks!

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
