### PR TITLE
RFC: Added version file and updated the respective files

### PR DESCRIPTION
**Pull request by sathnaga**
Added version file and updated respective files to use it

### CODE REVIEW

**Comment by sathnaga** [comment]
RFC code for addressing this card https://trello.com/c/3HKsnsRU

**Comment by sathnaga** [comment]
@clebergnu @ldoktor RFC code for addressing this card https://trello.com/c/3HKsnsRU, let me know your comments

**Comment by clebergnu** [comment]
@sathnaga one approach we've used before on Avocado, was to have the version in `avocado/core/version.py`, which would also be a runnable script that would print out the version number.  While that approach is not perfect (downside is, if we want to import the version module from `setup.py`, all modules and deps along the way will be loaded) it seems like it's better than using grep/awk.

Since Avocado-VT installation is not supported (yet?) from standard Python repos, the `avocado_vt/version.py` approach could be a good compromise.

**Comment by ldoktor** [comment]
Well how about `VERSION` file which contains the `40.0` and could be simply `open("VERSION", "r").read()` or `cat VERSION` to get the value?

**Comment by sathnaga** [comment]
@ldoktor yep, that ll workout as well, much simpler hack.
@clebergnu @ldoktor , If we go by this RFC approach, right now it is a hack for setup.py but can be modified later when we have Avocado-VT installation as standard python package?

**Comment by clebergnu** [comment]
A `VERSION` file is fine indeed.

**Comment by sathnaga** [comment]
@ldoktor @clebergnu https://github.com/avocado-framework/avocado-vt/pull/704

**Comment by sathnaga** [comment]
Created newer versions

**Pull request closed without merging**
