### PR TITLE
Revert c8de82a to get things working

### PR DESCRIPTION
**Pull request by luckyh**
This reverts commit c8de82a32e6ed30c3751ff4bb64646491c4aec6a.

Signed-off-by: Xu Han <xuhan@redhat.com>

### CODE REVIEW

**Comment by luckyh** [comment]
Currently, running tests would get the following error:
```
Failed to load plugin from module "avocado_vt.plugins.vt_list": ImportError('cannot import name libvirt_vm',)
Failed to load plugin from module "avocado_vt.plugins.vt": ImportError('cannot import name qemu',)
```

After reverted c8de82a, it could work:
```
 (1/1) Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.boot: CANCEL: Test cancelled due to --dry-run (0.00 s)
```

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by luckyh** [comment]
@hereischen @chunfuwen thanks!

**Comment by rdkdd** [comment]
@luckyh thanks!

**Comment by luckyh** [comment]
@rdkdd no problem :)

**Pull request merged**
