### PR TITLE
libvirt_migration: Add a function to check established connection

### PR DESCRIPTION
**Pull request by Yingshun**
Some of migration cases need to check the established connection
on destination host.

Signed-off-by: Yingshun Cui <yicui@redhat.com>

**Test result:**
` (1/7) type_specific.io-github-autotest-libvirt.virsh.migrate_storage.migrateuri.default.ipv4.copy_storage_all: PASS (156.52 s)`

### CODE REVIEW

**Comment by Yingshun** [comment]
@dzhengfy Would you please help review this PR? Thank you!

**Review by dzhengfy — APPROVED** [review]
LGTM

**Comment by Yingshun** [comment]
@chloerh  would you please help review this PR?

**Comment by chunfuwen** [comment]
For migration, virttest/migration.py  wrap Migration Relative functions, is there other reasons to create separate python util file?

**Comment by Yingshun** [comment]
> For migration, virttest/migration.py wrap Migration Relative functions, is there other reasons to create separate python util file?

migration.py is under virttest, so we plan to manage migration process related operations there. And we have some new common functions for libvirt migration test, for example, the function I added in this PR, it's to check the established connection during migration. It's not about migration process, but about testing.

**Review by chloerh — APPROVED** [review]

**Comment by chunfuwen** [comment]
@fangge1212 
@smitterl 
Could you please provide your feedbacks about this PR?

**Comment by chunfuwen** [comment]
> > For migration, virttest/migration.py wrap Migration Relative functions, is there other reasons to create separate python util file?
> 
> migration.py is under virttest, so we plan to manage migration process related operations there. And we have some new common functions for libvirt migration test, for example, the function I added in this PR, it's to check the established connection during migration. It's not about migration process, but about testing.

From migratioin.py, I saw  checking functions there:post_migration_check,ping_vm,cleanup_dest_vm ,etc.
I am not sure where there is difference between established connection and currently existed methods

**Comment by Yingshun** [comment]
> > > For migration, virttest/migration.py wrap Migration Relative functions, is there other reasons to create separate python util file?
> > 
> > 
> > migration.py is under virttest, so we plan to manage migration process related operations there. And we have some new common functions for libvirt migration test, for example, the function I added in this PR, it's to check the established connection during migration. It's not about migration process, but about testing.
> 
> From migratioin.py, I saw checking functions there:post_migration_check,ping_vm,cleanup_dest_vm ,etc.
> I am not sure where there is difference between established connection and currently existed methods

Checking the established connections during migration is a checkpoint of some cases and it will be used in more than one tp-libvirt scripts. post_migration_check,ping_vm and cleanup_dest_vm are common actions.

**Comment by dzhengfy** [comment]
> > > For migration, virttest/migration.py wrap Migration Relative functions, is there other reasons to create separate python util file?
> > 
> > 
> > migration.py is under virttest, so we plan to manage migration process related operations there. And we have some new common functions for libvirt migration test, for example, the function I added in this PR, it's to check the established connection during migration. It's not about migration process, but about testing.
> 
> From migratioin.py, I saw checking functions there:post_migration_check,ping_vm,cleanup_dest_vm ,etc.
> I am not sure where there is difference between established connection and currently existed methods

The difference is that those functions in migration.py is just common functions which may apply to most migration cases, but 'established connection' function is only for some specific cases. So 'established connection' should only be treated as an utility one which can be used in certain test scenarios.

**Comment by chunfuwen** [comment]
> common



> > > > For migration, virttest/migration.py wrap Migration Relative functions, is there other reasons to create separate python util file?
> > > 
> > > 
> > > migration.py is under virttest, so we plan to manage migration process related operations there. And we have some new common functions for libvirt migration test, for example, the function I added in this PR, it's to check the established connection during migration. It's not about migration process, but about testing.
> > 
> > 
> > From migratioin.py, I saw checking functions there:post_migration_check,ping_vm,cleanup_dest_vm ,etc.
> > I am not sure where there is difference between established connection and currently existed methods
> 
> The difference is that those functions in migration.py is just common functions which may apply to most migration cases, but 'established connection' function is only for some specific cases. So 'established connection' should only be treated as an utility one which can be used in certain test scenarios.

Strictly speaking, do we  really have efforts to distinguish so called 'few' or 'many' functions in practice?
What I can see here is that we need maintain two copies of migration utilities , one is migration.py, the other one is newly created one.

**Comment by kylazhang** [comment]
From the function usage I think it can be added to the migration.py or libvirt.py but I saw it also call libvirt.check_result so I think separate it also because want to avoid circle import and do not broaden the libvirt.py file?

**Comment by chunfuwen** [comment]
https://docs.python-guide.org/writing/structure/#structure-of-the-repository, Structure of Code is Key. 
I believe that more comments and feedbacks contribute to long term health of project

**Comment by Yingshun** [comment]
> From the function usage I think it can be added to the migration.py or libvirt.py but I saw it also call libvirt.check_result so I think separate it also because want to avoid circle import and do not broaden the libvirt.py file?

libvirt.py was froze last year... It has more than 3800 lines.So we decided to freeze it and no more new utilities in it. At that time, we created a package named utils_libvirt and planned to add some libvirt testing related utils into it.

**Comment by fangge1212** [comment]
I'm thinking can we make the function more general? Not bind it to migration. Other features may need to check network connection too, e.g. graphical framebuffer.

And also make the parameters more specific. Here I mean use more meaningful variable name( e.g. "ip_local" "ip_remote" "port" "process name" and "connection status") as function parameter name to be passed, and add params description in functions so others can know  what parameters are expected. It's hard to know what parameters are expected when "params" is used.

**Comment by fangge1212** [comment]
As mentioned in last comment, I think this function is not limited to migration feature, it can also be used by other features. So I think we need to find a new place for it

**Comment by Yingshun** [comment]
> As mentioned in last comment, I think this function is not limited to migration feature, it can also be used by other features. So I think we need to find a new place for it

@fangge1212  The purpose of this function is to check the ESTABLISHED.*qemu-kvm connection on a remote host. It's not a wrapper func of 'netstat' command line. 
BTW, Can you please show the caseIDs of other features what may use it?
I just found one iface case(virtual_network/iface_options.py) that checks multicast ip of local host via netstat command, it's a different checkpoint.

**Review by chloerh — APPROVED** [review]

**Review by dzhengfy — APPROVED** [review]
LGTM

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
