### PR TITLE
New flag added to customize_libvirt_config to support some tests

### PR DESCRIPTION
**Pull request by kamilvarga**
The restart libvirt flag(parameter) added to customize_libvirt_config
since the restart of the libvirt after applying config changes is not
always needed/intended. Parameter remains true for existing tests,
but can be changed to false for future tests that do not need/require
the libvirt service restarted.

Signed-off-by: Kamil Varga <kvarga@redhat.com>

### CODE REVIEW

**Comment by kamilvarga** [comment]
Supports https://github.com/autotest/tp-libvirt/pull/3524

**Review by chunfuwen — APPROVED** [review]
lgtm

**Review by Yingshun — COMMENTED** [review]
you missed the libvirtd on the remote host. Can you please update the code for 
remotely_control_libvirtd() as well?

**Comment by kamilvarga** [comment]
> you missed the libvirtd on the remote host. Can you please update the code for
> remotely_control_libvirtd() as well?

Thank you for heads up. Updated per your suggestion in last commit.

**Review by Yingshun — APPROVED** [review]

**Pull request merged**
