### PR TITLE
qcontainer: Support virtio-serial-ccw on s390x

### PR DESCRIPTION
**Pull request by ngu-niny**
Support to boot a guest with virtio-serial-ccw device on s390x host

ID: 1941879
Signed-off-by: Nini Gu <ngu@redhat.com>

### CODE REVIEW

**Comment by ngu-niny** [comment]
Test PASS:

 (1/4) Host_RHEL.m8.u4.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.s390x.io-github-autotest-qemu.blockdev_inc_backup_with_guest_agent.s390-virtio: PASS (62.05 s)
 (2/4) Host_RHEL.m8.u4.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.s390x.io-github-autotest-qemu.virtio_serial_file_transfer.unix_socket.s390-virtio: PASS (26.11 s)
 (3/4) Host_RHEL.m8.u4.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.s390x.io-github-autotest-qemu.virtio_serial_file_transfer.tcp_socket.s390-virtio: PASS (25.04 s)
 (4/4) Host_RHEL.m8.u4.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.s390x.io-github-autotest-qemu.virtio_serial_file_transfer.pty.s390-virtio: PASS (24.90 s)

**Comment by ngu-niny** [comment]
@PaulYuuu @yanan-fu @fbq815 Could you help to have a review? Thanks.

**Comment by ngu-niny** [comment]
@vivianQizhu Could you help to review? Thanks.

**Review by PaulYuuu — APPROVED** [review]

**Comment by ngu-niny** [comment]
Regression test on power PASS:

 (1/1) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_with_guest_agent:  PASS (197.55 s)

**Comment by fbq815** [comment]
seems fine from my side

**Pull request merged**
