### PR TITLE
pmsocat: Replace @coroutine with 'async def'

### PR DESCRIPTION
**Pull request by Yingshun**
It reports DeprecationWarning: "@coroutine" decorator is deprecated
since Python 3.8, use "async def" instead. So update the code
accordingly. For details please check
https://docs.python.org/3/reference/compound_stmts.html#async-def

Signed-off-by: Yingshun Cui <yicui@redhat.com>

### CODE REVIEW

**Comment by Yingshun** [comment]
**Test result:**
python 3.9:
```
2021-04-06 05:13:48,736 client           L1144 DEBUG| Sending command: /var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/shared/scripts/pmsocat/pmsocat36.py unix2tcp -c system_u:system_r:svirt_socket_t:s0 /tmp/desturi-socket 10.73.114.63 22222 &
2021-04-06 05:13:48,839 client           L1144 DEBUG| Sending command: echo $?
2021-04-06 05:13:48,941 client           L1144 DEBUG| Sending command: /var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/shared/scripts/pmsocat/pmsocat36.py unix2tcp -c system_u:system_r:svirt_socket_t:s0 /var/lib/libvirt/qemu/migrateuri-socket 10.73.114.63 33333 &
2021-04-06 05:13:49,045 client           L1144 DEBUG| Sending command: echo $?
2021-04-06 05:13:49,146 client           L1144 DEBUG| Sending command: /var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/shared/scripts/pmsocat/pmsocat36.py unix2tcp -c system_u:system_r:svirt_socket_t:s0 /var/lib/libvirt/qemu/disks-uri-socket 10.73.114.63 44444 &
2021-04-06 05:13:49,250 client           L1144 DEBUG| Sending command: echo $?
```

python 3.6.8:
`# python3 pmsocat36.py unix2tcp -c system_u:system_r:svirt_socket_t:s0 /tmp/desturi-socket 10.73.114.63 22222`

**Comment by Yingshun** [comment]
@fangge1212  @dzhengfy Would you please help review it? Thank you!

**Comment by fangge1212** [comment]
Sorry, I'm not familiar with python networking.

**Comment by fangge1212** [comment]
But I can try the pr in ci job

**Review by chunfuwen — APPROVED** [review]
lgtm

**Review by chloerh — APPROVED** [review]
Nice fix! Really forward-looking!

**Comment by chloerh** [comment]
@fangge1212 would you like to help provide test result on jenkins? I could wait for your result. But it's ok without result since @Yingshun has provided result of target case.

**Comment by fangge1212** [comment]
Tested on RHEL9, the patch works.

**Comment by Yingshun** [comment]
> Tested on RHEL9, the patch works.

Thanks @fangge1212 for testing it.

**Comment by chloerh** [comment]
@fangge1212 Thank you for providing test result. I'll merge it.

**Pull request merged**
