### PR TITLE
[V7] Merge avocado-vt with virt-test

### PR DESCRIPTION
**Pull request by lmr**
Merge virt-test inside avocado-vt. This involves picking up virt-test's entire history and bringing it to avocado-vt.

Instructions on how to test it can be found here:

https://github.com/avocado-framework/avocado-vt/blob/0a7aedc34ee84157206b4a56f255a0827744166f/README.rst

Changes from v6:
* Fixed a couple of problems found by @ldoktor during his review, such as location of subtests.cfg file and asset restore.

Changes from v5:
* Updated the documentation to make references to `avocado` instead of `virt-test` and the old virt-test runner, as @adereis pointed out it was missing from this work.
* Added --yes-to-all to `vt-bootstrap`, per @adereis's request. Sorry, I forgot to put that into the previous PR's changelog.

Changes from v4:
* Now the tests report correctly their status, they were not doing that correctly so as @adereis pointed out during testing. In order to fix that, we did reintroduce the dependency on autotest, but it's small, contained, and eventually we can get rid of it. A good test for the correct reporting is:

    $ avocado run type_specific.io-github-autotest-qemu.qemu_cpu.cpuid

Changes from v3:
* Removed a mistaken commit that butchered the subdir `shared`, causing bootstrap to fail. Pointed out by @adereis during testing.

Changes from v1, v2:
* Completely rebased the branch and moved avocado-vt to a subdir instead of virt-test
* Fixed the security problems described in https://trello.com/c/YvSmaKD5/449-bug-insecure-usage-of-tmp-in-avocado-vt-virt-test

Changes from V0:
* Consolidated the last commits, making them more cohesive and easy to follow.

### CODE REVIEW

**Comment by ldoktor** [comment]
Hello Lucas, I'm on it, just leaving Brno so let me summarize my intermediary problems before I go offline:

* Unittest requries newer module six (1.4.1 fails)
* Unittest requries newer module setuptools (Stock F20 fails, you need to run --upgrade to work)
* Unittest requries funcsigs which is not installed by requirements

Also selftest on fresh F20 machine fails. I added some logging:

```diff
-                         "Test post dir is not empty")
+                         "Test post dir is not empty\n%s\n%s" % (job_postdir, os.listdir(job_postdir)) )
```

```
./selftests/run selftests/all/unit/avocado/sysinfo_unittest.py
....F
======================================================================
FAIL: test_logger_test_hooks (sysinfo_unittest.SysinfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/avocado/selftests/all/unit/avocado/sysinfo_unittest.py", line 95, in test_logger_test_hooks
    "Test post dir is not empty\n%s\n%s" % (job_postdir, os.listdir(job_postdir)) )
AssertionError: Test post dir is not empty
/tmp/sysinfo_unittestbPSUWI/job/test1/post
['messages.gz']
-------------------- >> begin captured logging << --------------------
avocado.sysinfo: INFO: Commands configured by file: /etc/avocado/sysinfo/commands
avocado.sysinfo: INFO: Files configured by file: /etc/avocado/sysinfo/files
avocado.sysinfo: INFO: Profilers configured by file: /etc/avocado/sysinfo/profilers
avocado.sysinfo: INFO: Profilers declared: []
avocado.sysinfo: INFO: Profiler disabled: no profiler commands configured
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 5 tests in 0.005s
```

I need to investigate it further, but if you know the cause....

**Comment by ldoktor** [comment]
Btw mainly it works fine...

**Comment by lmr** [comment]
@ldoktor, super strange. I don't think it's related to the avocado-vt PR, though. We'd be seen this in the main avocado repo jobs,  think.

**Comment by ldoktor** [comment]
@lmr the `avocado-vt` also require `qemu` and `7za` (7za is a bit optional, RHEL7 doesn't have it by default).

Never mind, most things I tested worked fine. Even the `remote` plugin somehow works ( https://trello.com/c/OdwqFumT/458-bug-remote-plugin-doesn-t-work-nicely-with-multiplex-files https://trello.com/c/a1EyfMjd/459-rfe-remote-plugin-should-talk-to-discover-plugins-to-handle-copying-of-the-test-files-properly ).

Apart from mentioned things my tests went mostly well. I tested execution with `autotest` from git, I tested everything run from `build-rpm-all`, I tested multiple virttest tests, greedy match on virttest tests, mixed avocado tests + virttest tests, multiplexed avocado tests, running with `keep... = yes`, listing tests with and without bootstrap, running with `remote` plugin.

There is one odd behavior, not really know what to blame, but running the `boot` test without internet connection always takes 3-times longer than running it with connection:

```
# ONLINE
[medic@t530 avocado ]$ AUTOTEST_PATH=../../autotest/autotest ./scripts/avocado run boot
JOB ID     : 5eee8e5899a41d111f41bba81faad7fd05ba0981
JOB LOG    : /home/medic/avocado/job-results/job-2015-07-30T19.24-5eee8e5/job.log
JOB HTML   : /home/medic/avocado/job-results/job-2015-07-30T19.24-5eee8e5/html/results.html
TESTS      : 1
(1/1) io-github-autotest-qemu.boot: PASS (11.97 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TIME       : 11.97 s

19:24:52 error            L0085 INFO | Context: Try to log into guest 'virt-tests-vm1'.
19:24:52 virt_vm          L1030 DEBUG| Attempting to log into 'virt-tests-vm1' (timeout 240s)
19:24:52 remote           L0248 DEBUG| Login command: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PreferredAuthentications=password -p 5000 root@192.168.122.1'
19:24:59 qemu_vm          L2768 DEBUG| Destroying VM virt-tests-vm1 (PID 2438)
19:24:59 qemu_vm          L2685 DEBUG| Shutting down VM virt-tests-vm1 (shell)
19:24:59 remote           L0248 DEBUG| Login command: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PreferredAuthentications=password -p 5000 root@192.168.1.184'
19:25:01 client           L0541 INFO | [qemu output] (Process terminated with status 0)
19:25:02 qemu_vm          L2775 DEBUG| VM virt-tests-vm1 down (shell)
```

```
# OFFLINE
[medic@t530 avocado ]$ AUTOTEST_PATH=../../autotest/autotest ./scripts/avocado run boot
JOB ID     : 903abeaaa1951e62a8efb0d24ec8856938534dc8
JOB LOG    : /home/medic/avocado/job-results/job-2015-07-30T19.19-903abea/job.log
JOB HTML   : /home/medic/avocado/job-results/job-2015-07-30T19.19-903abea/html/results.html
TESTS      : 1
(1/1) io-github-autotest-qemu.boot: PASS (33.38 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TIME       : 33.38 s

19:19:41 virt_vm          L1030 DEBUG| Attempting to log into 'virt-tests-vm1' (timeout 240s)
19:19:41 remote           L0248 DEBUG| Login command: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PreferredAuthentications=password -p 5000 root@192.168.122.1'
19:20:00 qemu_vm          L2768 DEBUG| Destroying VM virt-tests-vm1 (PID 1468)
19:20:00 qemu_vm          L2685 DEBUG| Shutting down VM virt-tests-vm1 (shell)
19:20:00 remote           L0248 DEBUG| Login command: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PreferredAuthentications=password -p 5000 root@192.168.122.1'
19:20:11 client           L0541 INFO | [qemu output] (Process terminated with status 0)
19:20:12 qemu_vm          L2775 DEBUG| VM virt-tests-vm1 down (shell)
```

Anyway, when the dependencies are sorted out I agree with merging this PR. @clebergnu, would you please also have a look and either merge it (when the `spec` and `requirements are sorted out) or just ack afterwards so I can merge it tomorrow morning and run the manual test cases?

**Comment by ldoktor** [comment]
Oh btw one remark, do you know what is the `stdout` of the `boot` test?

```
0.26.0-1513-g5a7d
HEAD
5a7d568b657bbda833a474e1e663e68edc54f7b0
COMMAND
systemd
COMMAND
systemd
```

I wonder what would be expected and if we should select what goes there (eg. ssh connections, serial sessions, ...) or simply ignore it....

**Comment by lmr** [comment]
@ldoktor the stdout of any test is basically the outputs of every subprocess executed with the `process` APIs. It shouldn't really be taken seriously for now. Maybe in the future we want to do something about it, but it doesn't strike me as something important.

**Comment by lmr** [comment]
@ldoktor as for the dependencies on qemu, given that qemu is the software under test and it may come from a multitude of places, I'd not add `qemu` as a dependency. `7za` is something I'd definitely consider, but as you said yourself, it's optional. The fact most users will need it makes me to strongly consider adding it though.

**Comment by lmr** [comment]
@ldoktor and @clebergnu, I've updated the spec file to require all programs and headers we check for in bootstrap:

    +Requires: python, avocado, autotest-framework, p7zip, tcpdump, nmap-ncat, iproute, iputils, gcc, glibc-headers, python-devel

I guess this should seal the deal. Let me know if you want me to address any other concerns before the merge.

**Comment by ldoktor** [comment]
Btw, @lmr, while reviewing this I thought about the Frankenstein mode and there is something I missed. This might solve it:

Patch for `avocado`
```diff
commit 7ed6658122db02be364f4cd9a837a9f5b6d74391
Author: Lukáš Doktor <ldoktor@redhat.com>
Date:   Thu Jul 30 21:03:49 2015 +0200

    avocado.core.multiplexer: Support to iteritems on a given path
    
    Support to limit the AvocadoParams.iteritems() on given path only.
    
    Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>

diff --git a/avocado/core/multiplexer.py b/avocado/core/multiplexer.py
index b8c1760..1f8e157 100644
--- a/avocado/core/multiplexer.py
+++ b/avocado/core/multiplexer.py
@@ -297,16 +297,17 @@ class AvocadoParams(object):
         """
         return self.get(path, key, "").split()
 
-    def iteritems(self):
+    def iteritems(self, path=None):
         """
         Very basic implementation which iterates through __ALL__ params,
         which generates lots of duplicite entries due to inherited values.
         """
+        if path:
+            path = self._greedy_path(path)
         for param in self._rel_paths:
-            for pair in param.iteritems():
-                self.log(pair[0], '/*', None, pair[1])
+            for pair in param.iteritems(path):
                 yield pair
-        for pair in self._abs_path.iteritems():
+        for pair in self._abs_path.iteritems(path):
             yield pair
 
 
@@ -371,12 +372,12 @@ class AvocadoParam(object):
                                 ["%s=>%s" % (_[1].path, _[0])
                                  for _ in ret]))
 
-    def iteritems(self):
+    def iteritems(self, path=None):
         """
         Very basic implementation which iterates through __ALL__ params,
         which generates lots of duplicite entries due to inherited values.
         """
-        for leaf in self._leaves:
+        for leaf in self._get_leaves(path) if path else self._leaves:
             for pair in leaf.environment.iteritems():
                 yield pair
 
```

Patch for avocado-vt
```diff
commit 884c3fbf1bea84e15a4e0b03d6947c275f24fa76
Author: Lukáš Doktor <ldoktor@redhat.com>
Date:   Thu Jul 30 21:05:33 2015 +0200

    virt_test: Override some params from AvocadoParams
    
    This patch overrides virt-test params of all values from avocado
    `--multiplex-files` from `/plugins/avocado-vt/params` location. This way
    you can for example execute simple test with different setting without
    touching the virt-test config files:
    
        avocado run -m /plugins/avocado-vt/params:2variants.yaml boot
    
    Executes two variants of the boot test, using default virt-test params +
    params from `2variants.yaml` per variant.
    
    Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>

diff --git a/avocado/core/plugins/virt_test.py b/avocado/core/plugins/virt_test.py
index e1d3abe..d7c689d 100644
--- a/avocado/core/plugins/virt_test.py
+++ b/avocado/core/plugins/virt_test.py
@@ -357,21 +357,26 @@ class VirtTest(test.Test):
                                      params.get("vm_type"))
         self.tmpdir = os.path.dirname(self.workdir)
 
-        self.params = utils_params.Params(params)
         # Here we turn the data the multiplexer injected into the params and
         # turn it into an AvocadoParams object, that will allow users to
         # access data from it. Example:
         # sleep_length = test.avocado_params.get('sleep_length', default=1)
         p = params.get('avocado_params', None)
         if p is not None:
-            params, mux_path = p[0], p[1]
+            _params, mux_path = p[0], p[1]
         else:
-            params, mux_path = [], []
-        self.avocado_params = multiplexer.AvocadoParams(params, self.name,
+            _params, mux_path = [], []
+        self.avocado_params = multiplexer.AvocadoParams(_params, self.name,
                                                         self.tag,
                                                         mux_path,
                                                         self.default_params)
 
+        for key, value in self.avocado_params.iteritems("/plugins/avocado-vt/"
+                                                        "params/*"):
+            params[key] = value
+
+        self.params = utils_params.Params(params)
+
         self.debugdir = self.logdir
         utils_misc.set_log_file_dir(self.logdir)
 
```

The values listed in test execution are correct, the only a bit confusing thing is the `test_name` as it comes from cartesian variants. So when you set `smp = 1` and `smp = 2`, booth tests are named `smp2`. But apart from that it works fine and IMO is very useful. You might even include it in you PR if you want to.

**Comment by ldoktor** [comment]
@lmr would you please also add the `setuptools`, `six` and `funcsigs` to `requirements-selftests.txt`?

**Comment by ldoktor** [comment]
Oh and debian dependencies as well.

**Comment by ldoktor** [comment]
Btw about the `qemu` deps, I'd require them, because it's simpler for newbies. (otherwise they'll get message that command `kvm` is missing, which is a bit confusing). But I don't have a strong opinion on that.

**Comment by lmr** [comment]
@ldoktor absolutely. I'm going to have a v8 sent today, that will be cleaner and have those comments fixed.

**Comment by lmr** [comment]
Closing in favor of #39.

**Pull request closed without merging**
