### PR TITLE
qemu_storage.QemuImg.commit: support luks

### PR DESCRIPTION
**Pull request by lolyu**
1. add support of luks in method commit.
2. add `base` to specify base image to commit to.
3. add `drop` to support drop image after commit.

Signed-off-by: lolyu <lolyu@redhat.com>

### CODE REVIEW

**Comment by hellohellenmao** [comment]
Qcow2 commit works okay with this patch.

(1/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.qemu_disk_img.commit: PASS (198.01 s)
 (2/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.qemu_disk_img.commit.cache_mode.none: PASS (182.78 s)
 (3/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.qemu_disk_img.commit.cache_mode.writeback: PASS (179.89 s)
 (4/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.qemu_disk_img.commit.cache_mode.unsafe: PASS (173.91 s)
 (5/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.qemu_disk_img.commit.cache_mode.directsync: PASS (171.46 s)
 (6/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.qemu_disk_img.commit.cache_mode.writethrough: PASS (173.25 s)

(1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.thin_write_in_qemu_img_commit: PASS (5.46 s)

**Comment by lolyu** [comment]
```
 (1/1) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.commit_with_backing: PASS (220.52 s)
```
```
 (1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.commit_with_backing: PASS (221.37 s)
```
```
 (1/1) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.commit_with_backing: PASS (217.72 s)
```
```
 (1/1) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.commit_with_backing: PASS (505.73 s)
```

**Comment by lolyu** [comment]
@luckyh please take a review

**Comment by hellohellenmao** [comment]
And commit with win2019 also passed. 

(1/1) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.commit_with_backing: PASS (448.11 s)

**Pull request merged**
