### PR TITLE
qemu_vm: removing unecessary arguments inside add_{floopy,uuid,vnc,...}.

### PR DESCRIPTION
**Pull request by jcfaracco**
The function make_create_command() has many functions inside with unused
"devices" parameter. This parameter is not being used inside many of them.
So, this commit clean up the functions.
Referecing the commit number: c3ae5874b40127.

Signed-off-by: Julio Faracco <jcfaracco@gmail.com>

### CODE REVIEW

**Comment by jcfaracco** [comment]
Hi guys,

There is a discussion about if this parameter is really necessary.
Should we keep this parameter due to coding patterns or remove because it is not being used?
If we keep, some changes are necessary because some functions does not have the "devices" parameter. If we don't keep, we need to remove.

**Comment by PandaWei** [comment]
Personally, I like keep this parameter better.
Formerly，the first parameter named help_text, not "devices".
It's useful for debugging.

**Comment by jcfaracco** [comment]
Well, if we need to keep this pattern we need to add the "devices" parameter inside other functions.
In my opinion, the function scopes needs to have a pattern: or remove, or keep.

**Comment by clebergnu** [comment]
@PandaWei I'm interested in knowing how this extra parameter can help debugging.  Can you give a brief explanation?

**Comment by PandaWei** [comment]
For some failed cases which caused at startup stage of qemu,
and I doubt there's something wrong with options or parameters. 
But I couldn't found any useful clues from the log of failed cases,
I will add  output statements in the sub-functions add_xxx of make_create_command to print the atrributes of the object devices.
or call  functions of DevContainer. such as cmd_line()/has_option/has_device ...
and then, run failed case again to confirm my doubt.

**Comment by PandaWei** [comment]
BTW, I don't mind to delete the unused parameter devices.

**Comment by clebergnu** [comment]
@PandaWei thanks for the explanation. So, if I understand correctly, you can still get the `devices` info from the caller of one of the `add_*()` methods, say, `make_create_command()`, right?

@jcfaracco I found at least one case where `add_vnc()` is being called with `devices` as the first parameter:

https://github.com/jcfaracco/avocado-vt/blob/master/virttest/qemu_vm.py#L1862

There may be more.  I think cleaning up the unused parameters is a good thing, but, it should be thoroughly tested.  It's better to have extra parameters and working code than cleaned up parameters and random breakage.

Thanks to all you guys!

**Comment by PandaWei** [comment]
@clebergnu  Yes, That's what I want to say.
@jcfaracco   
In view of the same modification as this PR had been accepted,  I‘m OK for clean up unused parameters. 

Please fix the problem  @clebergnu pointed,
and remember to check the callers of methods you changed.

Besides above, I found there‘re another methods with unused 'devices', such as add_kernel, add_initrd, add_virtio_port .., i
t's better to fix all of them.

After you have finished the work mentioned above,
Please feel free to push again,  I'll  follow this PR and let it pass if there's no problem.

**Comment by PandaWei** [comment]
@clebergnu  Yes, That's what I want to say.
@jcfaracco   
In view of the same modification as this PR had been accepted,  I‘m OK for clean up unused parameters. 

Please fix the problem  @clebergnu pointed out,
and remember to remove the parameter 'devices' for the callers of add_xxx you changed.

Besides above,
 I found there‘re another methods with unused 'devices', such as add_kernel, add_initrd, add_virtio_port ..,
It's better to fix all of them.

After you have finished the work mentioned above,
Please feel free to push again,  I'll  follow this PR and let it pass if there's no problem.

**Comment by jcfaracco** [comment]
Hi guys,

I changed again and created another pull request (#499) that removes all occurrences of "devices".
I tested here all methods that were changed. I'm not seeing any problems right now.

Should I close this pull request and continue the discussion using the new one?
Thanks for your feedback guys.

**Comment by PandaWei** [comment]
Let's close this one and discuss it on #499.
I'll check the new one  and give feedback later

**Pull request closed without merging**
