### PR TITLE
virttest.qemu_storage: add support for new parameters of convert

### PR DESCRIPTION
**Pull request by XueqiangWei**
1. add parameter --target-is-zero to convert
2. add parameter -B to convert

Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 1942220, 1942222, 1942223, 1942225, 1942226, 1942227

### CODE REVIEW

**Comment by XueqiangWei** [comment]
(1/1) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_convert_with_target_is_zero.to_qcow2.q35: PASS (202.22 s)
(1/1) Host_RHEL.m8.u4.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_convert_with_target_is_zero.to_raw.q35: PASS (120.00 s)
(1/1) Host_RHEL.m8.u4.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_convert_with_target_is_zero.to_qcow2.q35: PASS (118.75 s)

(1/1) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_convert_with_backing_file.q35: PASS (201.20 s)
(1/1) Host_RHEL.m8.u4.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_convert_with_backing_file.q35: PASS (515.30 s)

**Comment by XueqiangWei** [comment]
@zhencliu Please help review it. Many thanks.

**Comment by zhencliu** [comment]
LGTM

**Comment by XueqiangWei** [comment]
@YongxueHong Please help review it. Many thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM

**Comment by YongxueHong** [comment]
Please fix the CI check error.
Thanks

**Comment by XueqiangWei** [comment]
> Please fix the CI check error.
> Thanks

It's not related to the new added codes. Thanks.

**Comment by YongxueHong** [comment]
Yes, maybe you could avoid it by following steps:
1. git checkout master
2. git fetch --all
3. git pull [upstream] master
4. git checkout [devel]
5. git rebase master
6. git push -f origin [devel]

**Comment by XueqiangWei** [comment]
> Yes, maybe you could avoid it by following steps:
> 
>     1. git checkout master
> 
>     2. git fetch --all
> 
>     3. git pull [upstream] master
> 
>     4. git checkout [devel]
> 
>     5. git rebase master
> 
>     6. git push -f origin [devel]

`
# git checkout master
# git fetch --all
# git merge upstream/master
Updating 1f809d6e..c25d78b2
Fast-forward
 virttest/libvirt_xml/devices/hostdev.py | 27 ++++++++++++++++++++++++++-
 1 file changed, 26 insertions(+), 1 deletion(-)
`

**Pull request merged**
