### PR TITLE
Add support for shared image mode in qemu-img's snapshot list

### PR DESCRIPTION
**Pull request by pevogam**
We take a small extra step in documenting this parameter wherever
it is available but ultimately one would want to define a command
format and reuse class attributes as much as possible.

Signed-off-by: Plamen Dimitrov <plamen.dimitrov@intra2net.com>

### CODE REVIEW

**Review by luckyh — APPROVED** [review]
LGTM

**Review by YongxueHong — APPROVED** [review]

**Review by YongxueHong — COMMENTED** [review]
LGTM.

**Comment by pevogam** [comment]
I am not sure what the problem with the CI is, if you have any suggestion on how to make it pass let me know. From first look it doesn't seem to be related.

**Comment by pevogam** [comment]
@luckyh Since we have two approvals can we merge in order to avoid potential later merge conflicts? Thanks!

**Comment by luckyh** [comment]
> I am not sure what the problem with the CI is, if you have any suggestion on how to make it pass let me know. From first look it doesn't seem to be related.

@pevogam not sure if rebasing with the latest master could solve this issue, but it's worth to try, thanks!

**Comment by pevogam** [comment]
Not sure if it was the rebase that helped or just rerunning but the tests are passing now.

**Comment by luckyh** [comment]
Thanks to all.

**Pull request merged**
