### PR TITLE
qemu_vm: fix no attribute 'DeviceHotplugError' error

### PR DESCRIPTION
**Pull request by yanan-fu**
id: 1879610

Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
@PaulYuuu  Call for your review, thanks!

**Comment by yanan-fu** [comment]
Test result:
```
'1-Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.pcie_hotplug_opt.q35' Finshed 2020-09-17 01:42:29 2020-09-17 01:44:30 PASS 120.302599
```

**Review by PaulYuuu — APPROVED** [review]

**Comment by PaulYuuu** [comment]
Thank you for the fix.
Ack.

**Comment by yanan-fu** [comment]
@vivianQizhu  Could you help review ? thanks !

**Review by vivianQizhu — APPROVED** [review]

**Pull request merged**
