### PR TITLE
v2v: save value of '-on' option in cmd line

### PR DESCRIPTION
**Pull request by xiaodwan**
Save the final values in v2v cmd line to make it easy to do the result check.
Note: the variant format is like 'v2v_cmd_opt_xxx'.

### CODE REVIEW

**Comment by xiaodwan** [comment]
```
JOB ID     : 93627a00ed4f08c13d70592c5afe19ab8066c7ad
JOB LOG    : /root/avocado/job-results/job-2023-02-20T04.25-93627a0/job.log
 (1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.multiple_disks.esx_70.kubevirt.it_vddk.vpx_uri: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.multiple_disks.esx_70.kubevirt.it_vddk.vpx_uri: PASS (178.23 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 180.02 s
```

**Comment by xiaodwan** [comment]
@chunfuwen @yantian0 please help to review this PR, thanks.

**Comment by dzhengfy** [comment]
@xiaodwan Could you help solve this failure

**Comment by xiaodwan** [comment]
For Some unknown issue, the code has been merged but the PR is till open. So I closed it.

**Pull request closed without merging**
