### PR TITLE
Minorfix: Update to able to remove disks

### PR DESCRIPTION
**Pull request by Yingshun**
Need to cleanup disks before attach in some cases, so add an entry
to remove all disks before testing.

Signed-off-by: Yingshun Cui <yicui@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
Applying: Minorfix: Update to able to remove disks
.git/rebase-apply/patch:23: trailing whitespace.
            continue 
warning: 1 line adds whitespace errors.

**Comment by vivianQizhu** [comment]
Seems not work, add debug info print('cleanup_disks', del_disks):
```
05:03:35 DEBUG|     cleanup_disks = yes

05:03:37 DEBUG| [stdout] cleanup_disks
05:03:37 DEBUG| [stdout]
05:03:37 DEBUG| [stdout] True
05:03:37 DEBUG| [stdout]
```
Still have two image:
```
    <disk device="disk" type="file">
      <driver name="qemu" type="qcow2" />
      <source file="/var/lib/avocado/data/avocado-vt/images/rhel810-64-virtio-scsi.qcow2" />
      <target bus="virtio" dev="vda" />
      <address bus="0x04" domain="0x0000" function="0x0" slot="0x00" type="pci" />
    </disk>
    <disk device="disk" type="file">
      <driver cache="none" name="qemu" type="qcow2" />
      <source file="/var/lib/avocado/data/avocado-vt/images/rhel810-64-virtio-scsi.qcow2" />
      <target bus="scsi" dev="sda" />
      <address bus="0" controller="0" target="0" type="drive" unit="0" />
    </disk>
```

**Comment by Yingshun** [comment]
> Seems not work, add debug info `print('cleanup_disks', del_disks)`:
> 
> ```
> 05:03:35 DEBUG|     cleanup_disks = yes
> 
> 05:03:37 DEBUG| [stdout] cleanup_disks
> 05:03:37 DEBUG| [stdout]
> 05:03:37 DEBUG| [stdout] True
> 05:03:37 DEBUG| [stdout]
> ```
> 
> Still have two image:
> 
> ```
>     <disk device="disk" type="file">
>       <driver name="qemu" type="qcow2" />
>       <source file="/var/lib/avocado/data/avocado-vt/images/rhel810-64-virtio-scsi.qcow2" />
>       <target bus="virtio" dev="vda" />
>       <address bus="0x04" domain="0x0000" function="0x0" slot="0x00" type="pci" />
>     </disk>
>     <disk device="disk" type="file">
>       <driver cache="none" name="qemu" type="qcow2" />
>       <source file="/var/lib/avocado/data/avocado-vt/images/rhel810-64-virtio-scsi.qcow2" />
>       <target bus="scsi" dev="sda" />
>       <address bus="0" controller="0" target="0" type="drive" unit="0" />
>     </disk>
> ```

xml needs sync up, can you please have a try again?

**Comment by vivianQizhu** [comment]
This version works:
 (1/1) type_specific.io-github-autotest-libvirt.virtio_transitional_blk.default.with_virtio_scsi.boot_test.virtio: PASS (45.37 s)

**Pull request merged**
