### PR TITLE
Import and script cleanups

### PR DESCRIPTION
**Pull request by lmr**
Same base import cleanup + more file cleanups I found when doing a routine check on avocado-vt.

### CODE REVIEW

**Comment by lmr** [comment]
@clebergnu, Yep, I'll fix the indexes, and publish another version of the script

**Comment by lmr** [comment]
@clebergnu and there is a problem with one import that wasn't supposed to be removed (virsh import check)

**Comment by lmr** [comment]
@clebergnu And about the isos, according to

https://fedoraproject.org/wiki/Windows_Virtio_Drivers#Direct_download

The location

http://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso

Is not deprecated, and it's OK to have it in our files

**Comment by lmr** [comment]
I think now it's better:

    scripts/download_manager.py 
    Available download assets:

    1 - [Missing] CentOS 6.6 amd64 (/home/lmr/avocado/data/avocado-vt/isos/linux/CentOS-6.6-x86_64-minimal.iso)
    2 - [Missing] CentOS 6.6 i386 (/home/lmr/avocado/data/avocado-vt/isos/linux/CentOS-6.6-i386-minimal.iso)
    3 - [Missing] CentOS 7.0 amd64 (/home/lmr/avocado/data/avocado-vt/isos/linux/CentOS-7-x86_64-Minimal-1503-01.iso)
    4 - [Missing] Fedora 17 x86_64 DVD (/home/lmr/avocado/data/avocado-vt/isos/linux/Fedora-17-x86_64-DVD.iso)
    5 - [Missing] Fedora 18 x86_64 DVD (/home/lmr/avocado/data/avocado-vt/isos/linux/Fedora-18-x86_64-DVD.iso)
    6 - [Missing] Fedora 19 x86_64 DVD (/home/lmr/avocado/data/avocado-vt/isos/linux/Fedora-19-x86_64-DVD.iso)
    7 - [Missing] Fedora 20 x86_64 DVD (/home/lmr/avocado/data/avocado-vt/isos/linux/Fedora-20-x86_64-DVD.iso)
    8 - [Missing] JeOS 19 x86_64 (/home/lmr/avocado/data/avocado-vt/images/jeos-19-64.qcow2.7z)
    9 - [Missing] JeOS 20 x86_64 (/home/lmr/avocado/data/avocado-vt/images/jeos-20-64.qcow2.7z)
    10 - [Present] JeOS 21 x86_64 (/home/lmr/avocado/data/avocado-vt/images/jeos-21-64.qcow2.7z)
    11 - [Missing] Ubuntu 12.04.5 Server amd64 (/home/lmr/avocado/data/avocado-vt/isos/linux/ubuntu-12.04-server-amd64.iso)
    12 - [Missing] Ubuntu 12.04.5 Server i386 (/home/lmr/avocado/data/avocado-vt/isos/linux/ubuntu-12.04-server-i386.iso)
    13 - [Missing] Ubuntu 14.04 Server amd64 (/home/lmr/avocado/data/avocado-vt/isos/linux/ubuntu-14.04-server-amd64.iso)
    14 - [Missing] Ubuntu 14.04 Server i386 (/home/lmr/avocado/data/avocado-vt/isos/linux/ubuntu-14.04-server-i386.iso)
    15 - [Missing] Windows Utils ISO (/home/lmr/avocado/data/avocado-vt/isos/windows/winutils.iso)
    16 - [Missing] Windows Virtio Stable Drivers ISO (/home/lmr/avocado/data/avocado-vt/isos/windows/virtio-win.iso)

**Comment by clebergnu** [comment]
Right! I missed that part.

**Comment by lmr** [comment]
Damn, I made a mistake on the download script again. Let me send a fix in a minute.

**Comment by lmr** [comment]
Now that I'm looking at the list, I reckon that Fedora 17 and 18 are so old they're not worth to be in that convenience pool anymore.

**Comment by lmr** [comment]
@clebergnu let me know what you think of this latest version.

**Comment by clebergnu** [comment]
@lmr yep, looks good!

**Pull request merged**
