### PR TITLE
Update cmd timeout of partation creation

### PR DESCRIPTION
**Pull request by suqinhuang**
Create partation timeout sometime, update the cmd timeout

Signed-off-by: Suqin Huang <shuang@redhat.com>

### CODE REVIEW

**Comment by CongLi** [comment]
Met similar problem recently, could you share the id which I take a look?

Thanks.

**Comment by balamuruhans** [comment]
typo in commit message, %s/partition/partation %s/creation/creatation

**Comment by suqinhuang** [comment]
it happen when review patch https://github.com/autotest/tp-qemu/pull/906

**Comment by CongLi** [comment]
Is it https://github.com/autotest/tp-qemu/pull/906/files ?
I did not see format_windows_disk() in it.

**Pull request closed without merging**
