### PR TITLE
test_setup: fix backup virtqemud.conf file

### PR DESCRIPTION
**Pull request by dzhengfy**
Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by Yingshun** [comment]
@dzhengfy Could you please upload test results?

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by dzhengfy** [comment]
> @dzhengfy Could you please upload test results?
This fix could be used in any test case which uses 'libvirtd_debug_file' parameter for  LibvirtdDebugLog object.
Take https://github.com/autotest/tp-libvirt/pull/4095 as example,
```
# avocado run --vt-type libvirt --vt-machine-type q35 numa_memory.possitive_test
 (01/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.no_vcpu.mem_auto.strict: PASS (50.12 s)
 (02/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.no_vcpu.mem_auto.interleave: PASS (50.37 s)
 (03/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.no_vcpu.mem_nodeset.node1.strict: PASS (48.33 s)
 (04/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.no_vcpu.mem_nodeset.node1.preferred: PASS (47.46 s)
 (05/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.no_vcpu.mem_nodeset.node2.strict: PASS (50.61 s)
 (06/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.no_vcpu.mem_nodeset.node2.interleave: PASS (51.69 s)
 (07/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.vcpu.vcpu_auto.mem_auto.strict: PASS (55.34 s)
 (08/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.vcpu.vcpu_auto.mem_auto.interleave: PASS (51.11 s)
 (09/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.vcpu.vcpu_auto.mem_nodeset.node1.strict: PASS (51.96 s)
 (10/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.vcpu.vcpu_auto.mem_nodeset.node1.preferred: PASS (52.62 s)
 (11/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.vcpu.vcpu_auto.mem_nodeset.node2.strict: PASS (51.37 s)
 (12/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.vcpu.vcpu_auto.mem_nodeset.node2.interleave: PASS (50.07 s)
 (13/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.vcpu.vcpu_static.mem_auto.strict: PASS (51.89 s)
 (14/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.vcpu.vcpu_static.mem_auto.interleave: PASS (50.02 s)
 (15/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.vcpu.vcpu_static.mem_nodeset.node1.strict: PASS (51.25 s)
 (16/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.vcpu.vcpu_static.mem_nodeset.node1.preferred: PASS (47.75 s)
 (17/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.vcpu.vcpu_static.mem_nodeset.node2.strict: PASS (48.90 s)
 (18/18) type_specific.io-github-autotest-libvirt.numa_memory.possitive_test.vcpu.vcpu_static.mem_nodeset.node2.interleave: PASS (47.72 s)
RESULTS    : PASS 18 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 910.87 s
 
```

**Review by Yingshun — APPROVED** [review]
LGTM.

**Pull request merged**
