### PR TITLE
test_setup: fix TypeError in error message

### PR DESCRIPTION
**Pull request by mcasquer**
test_setup: fix TypeError in error message

Fixes the TypeError produced by the bad string formatting.

ID: 1488
Signed-off-by: mcasquer <mcasquer@redhat.com>

### CODE REVIEW

**Comment by mcasquer** [comment]
After bypassing **locally** the condition, now the error message is triggered adequately.
```
 (1/1) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hugepage_specify_node.1G.specify_hp_file.q35: STARTED
 (1/1) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hugepage_specify_node.1G.specify_hp_file.q35: ERROR: 4 (expecting 4) hugepages is set on node 0, please check if the node has enough memory (13.65 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Comment by mcasquer** [comment]
@luckyh @PaulYuuu could you review this PR? Thanks !

**Review by PaulYuuu — APPROVED** [review]

**Comment by PaulYuuu** [comment]
Hello @dzhengfy, you introduced this code, so could you also have a check?

**Review by luckyh — APPROVED** [review]
@mcasquer good catch, thanks for the fix!

**Comment by luckyh** [comment]
ok, let's merge this minor fix.

**Pull request merged**
