### PR TITLE
virttest/test_setup: cleanup for class PciAssignable

### PR DESCRIPTION
**Pull request by PandaWei**
Remove unused variable and codes.

### CODE REVIEW

**Comment by PandaWei** [comment]
The CI doesn't work well.
who can solve this problem？

**Comment by PandaWei** [comment]
The CI doesn't work well.
who can solve this problem？

**Comment by lmr** [comment]
@PandaWei I did solve it. You can rebase and then the problem will go away.

**Comment by will-Do** [comment]
ACK and merge this trivial cleanup

**Pull request merged**
