### PR TITLE
shared/cfg/guest-os/Windows.cfg: Add windows command for qmp_event_no…

### PR DESCRIPTION
**Pull request by spcui**
…tification

Signed-off-by: Shuping Cui <scui@redhat.com>

ID: 1143902 1143904

### CODE REVIEW

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by ypu** [comment]
LGTM

Acked-by: Yiqiao Pu <ypu@redhat.com>

**Comment by lmr** [comment]
@suqinhuang and @ypu, I've invited you to the vt-maintainers group, as soon as you accept the invite you'll be able to freely approve pull requests. I'm helping with pull requests, but just short term.

**Comment by ypu** [comment]
Thanks @lmr for your help to set up this.

**Comment by ypu** [comment]
Thanks @spcui will merge this.

**Pull request merged**
