### PR TITLE
virttest/remote.py: Add new param for RemoteFile.add()

### PR DESCRIPTION
**Pull request by PandaWei**
Add new param 'linesep' to indicate the content of file
ends up with newline or not.

### CODE REVIEW

**Comment by PandaWei** [comment]
@will-Do 
Update as your suggestion.
The old PR is https://github.com/autotest/virt-test/pull/2295

Due to this problem appears again when tester run the macvtap cases,
If you haven't any comments,  Please let it pass.

**Comment by will-Do** [comment]
Sure, It's OK for me.
Give the ACK

**Comment by PandaWei** [comment]
Thanks @will-Do 
Merge Now

**Comment by PandaWei** [comment]
Thanks @will-Do 
Merge now

**Pull request merged**
