### PR TITLE
vm_xml: Update super class from VMXML to base.LibvirtXMLBase

### PR DESCRIPTION
**Pull request by chloerh**
xml classes which inherit from VMXML will also inherit VMXML's slots, along with other methods, which will make comparison of 2 xml instances impossible.

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

### CODE REVIEW

**Comment by chloerh** [comment]
Test result:

1. https://github.com/autotest/tp-libvirt/pull/3790 
2.  (1/1) type_specific.io-github-autotest-libvirt.libvirt_cputune.normal_test.wo_cachetune: PASS (10.63 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 12.59 s
3.  (1/1) type_specific.io-github-autotest-libvirt.memory_discard.hot_plug: PASS (39.24 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 41.23 s
4. guest_numa:

测试名称 | 运行时间 | 结果
-- | -- | --
misc_test.vcpu_fill.set_not_to | 43 sec | Passed
misc_test.vcpu_fill.set_to | 47 sec | Passed
negative_test.strict_memnode_insufficent | 23 sec | Passed
possitive_test.hugepage.host_total.no_topo.no_numatune_memnode.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.host_total.no_topo.no_numatune_memnode.numatune_mem | 43 sec | Passed
possitive_test.hugepage.host_total.no_topo.numatune_memnode.m_interleave.no_numatune_mem | 47 sec | Passed
possitive_test.hugepage.host_total.no_topo.numatune_memnode.m_interleave.numatune_mem | 43 sec | Passed
possitive_test.hugepage.host_total.no_topo.numatune_memnode.m_preferred.no_numatune_mem | 47 sec | Passed
possitive_test.hugepage.host_total.no_topo.numatune_memnode.m_preferred.numatune_mem | 47 sec | Passed
possitive_test.hugepage.host_total.no_topo.numatune_memnode.m_strict.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.host_total.no_topo.numatune_memnode.m_strict.numatune_mem | 44 sec | Passed
possitive_test.hugepage.host_total.topology.no_numatune_memnode.no_numatune_mem | 42 sec | Passed
possitive_test.hugepage.host_total.topology.no_numatune_memnode.numatune_mem | 44 sec | Passed
possitive_test.hugepage.host_total.topology.numatune_memnode.m_interleave.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.host_total.topology.numatune_memnode.m_interleave.numatune_mem | 44 sec | Passed
possitive_test.hugepage.host_total.topology.numatune_memnode.m_preferred.no_numatune_mem | 48 sec | Passed
possitive_test.hugepage.host_total.topology.numatune_memnode.m_preferred.numatune_mem | 45 sec | Passed
possitive_test.hugepage.host_total.topology.numatune_memnode.m_strict.no_numatune_mem | 47 sec | Passed
possitive_test.hugepage.host_total.topology.numatune_memnode.m_strict.numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.16M.no_topo.no_numatune_memnode.no_numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.no_topo.no_numatune_memnode.numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.no_topo.numatune_memnode.m_interleave.no_numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.no_topo.numatune_memnode.m_interleave.numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.no_topo.numatune_memnode.m_preferred.no_numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.no_topo.numatune_memnode.m_preferred.numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.no_topo.numatune_memnode.m_strict.no_numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.no_topo.numatune_memnode.m_strict.numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.topology.no_numatune_memnode.no_numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.topology.no_numatune_memnode.numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.topology.numatune_memnode.m_interleave.no_numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.topology.numatune_memnode.m_interleave.numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.topology.numatune_memnode.m_preferred.no_numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.topology.numatune_memnode.m_preferred.numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.topology.numatune_memnode.m_strict.no_numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.16M.topology.numatune_memnode.m_strict.numatune_mem | 0 ms | Skipped
possitive_test.hugepage.per_node.1G.no_topo.no_numatune_memnode.no_numatune_mem | 47 sec | Passed
possitive_test.hugepage.per_node.1G.no_topo.no_numatune_memnode.numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.1G.no_topo.numatune_memnode.m_interleave.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.1G.no_topo.numatune_memnode.m_interleave.numatune_mem | 47 sec | Passed
possitive_test.hugepage.per_node.1G.no_topo.numatune_memnode.m_preferred.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.1G.no_topo.numatune_memnode.m_preferred.numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.1G.no_topo.numatune_memnode.m_strict.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.1G.no_topo.numatune_memnode.m_strict.numatune_mem | 48 sec | Passed
possitive_test.hugepage.per_node.1G.topology.no_numatune_memnode.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.1G.topology.no_numatune_memnode.numatune_mem | 48 sec | Passed
possitive_test.hugepage.per_node.1G.topology.numatune_memnode.m_interleave.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.1G.topology.numatune_memnode.m_interleave.numatune_mem | 47 sec | Passed
possitive_test.hugepage.per_node.1G.topology.numatune_memnode.m_preferred.no_numatune_mem | 47 sec | Passed
possitive_test.hugepage.per_node.1G.topology.numatune_memnode.m_preferred.numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.1G.topology.numatune_memnode.m_strict.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.1G.topology.numatune_memnode.m_strict.numatune_mem | 47 sec | Passed
possitive_test.hugepage.per_node.2M.no_topo.no_numatune_memnode.no_numatune_mem | 43 sec | Passed
possitive_test.hugepage.per_node.2M.no_topo.no_numatune_memnode.numatune_mem | 43 sec | Passed
possitive_test.hugepage.per_node.2M.no_topo.numatune_memnode.m_interleave.no_numatune_mem | 46 sec | Passed
possitive_test.hugepage.per_node.2M.no_topo.numatune_memnode.m_interleave.numatune_mem | 43 sec | Passed
possitive_test.hugepage.per_node.2M.no_topo.numatune_memnode.m_preferred.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.2M.no_topo.numatune_memnode.m_preferred.numatune_mem | 43 sec | Passed
possitive_test.hugepage.per_node.2M.no_topo.numatune_memnode.m_strict.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.2M.no_topo.numatune_memnode.m_strict.numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.2M.topology.no_numatune_memnode.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.2M.topology.no_numatune_memnode.numatune_mem | 45 sec | Passed
possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_interleave.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_interleave.numatune_mem | 43 sec | Passed
possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_preferred.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_preferred.numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.no_numatune_mem | 44 sec | Passed
possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.numatune_mem | 44 sec | Passed
possitive_test.no_hugepage.mem_backend.no_topo.no_numatune_memnode.no_numatune_mem | 46 sec | Passed
possitive_test.no_hugepage.mem_backend.no_topo.numatune_memnode.m_interleave.no_numatune_mem | 43 sec | Passed
possitive_test.no_hugepage.mem_backend.no_topo.numatune_memnode.m_interleave.numatune_mem | 44 sec | Passed
possitive_test.no_hugepage.mem_backend.no_topo.numatune_memnode.m_preferred.no_numatune_mem | 46 sec | Passed
possitive_test.no_hugepage.mem_backend.no_topo.numatune_memnode.m_preferred.numatune_mem | 45 sec | Passed
possitive_test.no_hugepage.mem_backend.no_topo.numatune_memnode.m_strict.no_numatune_mem | 43 sec | Passed
possitive_test.no_hugepage.mem_backend.no_topo.numatune_memnode.m_strict.numatune_mem | 43 sec | Passed
possitive_test.no_hugepage.mem_backend.topology.no_numatune_memnode.no_numatune_mem | 44 sec | Passed
possitive_test.no_hugepage.mem_backend.topology.numatune_memnode.m_interleave.no_numatune_mem | 46 sec | Passed
possitive_test.no_hugepage.mem_backend.topology.numatune_memnode.m_interleave.numatune_mem | 44 sec | Passed
possitive_test.no_hugepage.mem_backend.topology.numatune_memnode.m_preferred.no_numatune_mem | 46 sec | Passed
possitive_test.no_hugepage.mem_backend.topology.numatune_memnode.m_preferred.numatune_mem | 44 sec | Passed
possitive_test.no_hugepage.mem_backend.topology.numatune_memnode.m_strict.no_numatune_mem | 44 sec | Passed
possitive_test.no_hugepage.mem_backend.topology.numatune_memnode.m_strict.numatune_mem | 46 sec | Passed
possitive_test.no_hugepage.no_mem_backend.no_topo.no_numatune_memnode.numatune_mem | 39 sec | Passed
possitive_test.no_hugepage.no_mem_backend.topology.no_numatune_memnode.numatune_mem | 1 min 2 sec | Passed

**Review by kylazhang — APPROVED** [review]

**Review by Yingshun — APPROVED** [review]
LGTM

**Review by dzhengfy — COMMENTED** [review]
Please help provide test results for below cases:
- virsh.iothreadadd.normal_test.guest_on.id_option.option_live or simiar one
- virsh.perf.normal_test.current.common_events.enable.vm_active or similar one
- libvirt_cputune.normal_test.with_cachetune
And please help add some explanation about the reason you need change VMXML to base.LibvirtXMLBase in PR description field. Thanks.

**Review by dzhengfy — COMMENTED** [review]
Please help provide test results for below cases:
- virsh.iothreadadd.normal_test.guest_on.id_option.option_live or simiar one
- virsh.perf.normal_test.current.common_events.enable.vm_active or similar one
- libvirt_cputune.normal_test.with_cachetune
And please help add some explanation about the reason you need change VMXML to base.LibvirtXMLBase in PR description field. Thanks.

**Comment by chloerh** [comment]
> Please help provide test results for below cases:
> 
> * virsh.iothreadadd.normal_test.guest_on.id_option.option_live or simiar one


Class | 花的时间 | 失败 | (区别) | 跳过 | (区别) | Pass | (区别) | 总数 | (区别)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
iothreadadd | 6 min 1 sec | 0 |   | 0 |   | 8 |   | 8 |
-- | -- | -- | -- | -- | -- | -- | -- | --



> * virsh.perf.normal_test.current.common_events.enable.vm_active or similar one

 (1/1) type_specific.local.virsh.perf.normal_test.current.common_events.enable.vm_active: PASS (3.33 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 3.64 s

> * libvirt_cputune.normal_test.with_cachetune

Not in our test scope
>   And please help add some explanation about the reason you need change VMXML to base.LibvirtXMLBase in PR description field. Thanks.

xml classes which inherit from VMXML will also inherit VMXML's __slots__, along with other methods, which will make comparison of 2 xml instances impossible.

**Comment by dzhengfy** [comment]
> > Please help provide test results for below cases:
> > 
> > * virsh.iothreadadd.normal_test.guest_on.id_option.option_live or simiar one
> 
> Class	花的时间	失败	(区别)	跳过	(区别)	Pass	(区别)	总数	(区别)
> iothreadadd	6 min 1 sec	0	 	0	 	8	 	8	
> --	--	--	--	--	--	--	--	--	
> > * virsh.perf.normal_test.current.common_events.enable.vm_active or similar one
> 
> (1/1) type_specific.local.virsh.perf.normal_test.current.common_events.enable.vm_active: PASS (3.33 s)
> RESULTS : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> JOB TIME : 3.64 s
> 
> > * libvirt_cputune.normal_test.with_cachetune
> 
> Not in our test scope
> 
> > And please help add some explanation about the reason you need change VMXML to base.LibvirtXMLBase in PR description field. Thanks.
> 
> xml classes which inherit from VMXML will also inherit VMXML's **slots**, along with other methods, which will make comparison of 2 xml instances impossible.

I added your last description into the PR description.

**Review by dzhengfy — APPROVED** [review]

**Pull request merged**
