### PR TITLE
v2v: add a new function to set LIBGEUSTFS_BACKEND

### PR DESCRIPTION
**Pull request by xiaodwan**
Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>

### CODE REVIEW

**Comment by xiaodwan** [comment]
(1/1) type_specific.io-github-autotest-libvirt.function_test_xen.positive_test.libvirt.pool_uuid.output_mode.libvirt: PASS (299.00 s)

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by xiaodwan** [comment]
@Yingshun please help to review it, thanks.

**Review by Yingshun — APPROVED** [review]
LGTM

**Pull request merged**
