### PR TITLE
utils_disk: Add a timeout parameter

### PR DESCRIPTION
**Pull request by YongxueHong**
Add a timeout parameter for getting multiple
disks in windows.

ID: 1699204
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by xuwei@redhat.com

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by YongxueHong** [comment]
@peixiu  Could you help me to review, thanks?

**Comment by peixiu** [comment]
LGTM,
Acked-by: Peixiu Hou phou@redhat.com

**Review by peixiu — APPROVED** [review]

**Pull request merged**
