### PR TITLE
Add cfg file for SLES 12.1

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
ID 1319605

**Comment by xutian** [comment]
Hi @XueqiangWei  why not autoyast.xml for SLES guest.

Thanks,
Xu

**Comment by XueqiangWei** [comment]
Hi @xutian use SLES-12.xml for SLES.12.1 guest unattended installation. And test it by avocado, it is Good for me.

**Comment by xutian** [comment]
Looks good to me, thanks @XueqiangWei

**Pull request merged**
