### PR TITLE
[WIP] migration: Support multiple hosts migration

### PR DESCRIPTION
**Pull request by YongxueHong**
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by pevogam** [comment]
Interesting! Is there a whitepaper or a blueprint about this where we can read more about the planned architecture changes and approach to this?

**Comment by YongxueHong** [comment]
> Interesting! Is there a whitepaper or a blueprint about this where we can read more about the planned architecture changes and approach to this?

Hi @pevogam 
For the blueprint, we are clearing up the data, but there are still some places we haven't a conclusion yet, however, we will handle it ASAP.

For the general architecture, I think you could refer to this draft PR.

**Comment by pevogam** [comment]
By the way @YongxueHong, just in case you are interested we also have a remote spawner PR in https://github.com/avocado-framework/avocado/pull/5621 using which I have already managed to run VT tests remotely and distribute them among multiple host machines.

**Comment by YongxueHong** [comment]
> By the way @YongxueHong, just in case you are interested we also have a remote spawner PR in [avocado-framework/avocado#5621](https://github.com/avocado-framework/avocado/pull/5621) using which I have already managed to run VT tests remotely and distribute them among multiple host machines.

Hi @pevogam 
Thanks for your information.

**Comment by pevogam** [comment]
The main benefit is that we don't need any additional effort on the Avocado VT side since Avocado has already put most of the functionality in place. The same solution also easily integrates with the existing architecture.

**Pull request closed without merging**
