### PR TITLE
shared.cfg.machines: Change the default pci bus for q35 and arm64-pci

### PR DESCRIPTION
**Pull request by ldoktor**
This probably controversial PR is inspired by running `nic_hotplug.additional.nic_virtio` test, which does not work on q35, nor on arm64-pci, because when no bus is specified on hotplug, first PCI-like bus is used, which does not supports hotplug.

The first patch changes the arm64-pci definition to add use by default a custom `root_port`, which is recommended here https://libvirt.org/pci-hotplug.html with note that unlike on q35 the pci_bridge is most probably not necessary.

The second patch changes the default pci bus from the Q35's main-system-bus to the first added root_port. This might require some changes in config where legacy devices are added (images, nics and other devices that use `vm._get_pci_bus` should be fine), but overall it should use for other devices the recommended setup.

The last patch adds support to `vm.activate_nic` to reflect `pci_bus` parameter, which is necessary as that way nic-hotplug respects the chosen pci bus. With this patch devices on arm64-pci and q35 are going to end in the first root_port. There is no change on i440fx as it's main bus is undefined.

Tested on x86+q35 x86+i440fx and aarch64+arm64-pci.

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@ldoktor  Hi, I am kvm qe, we are recommended by developer that we should add a specific pcie-root-port for each device we add by default(if multifunction off), so I am working on modify current q35 topology to fit this requirement, and also from https://libvirt.org/pci-hotplug.html it says that "If you plan to hotplug more than a single PCI Express device, you should add a suitable number of pcie-root-port controllers when defining the guest". Besides, we have other pcie bus type need to be considered like pxb-pcie(which also plugged to pcie.0), so I think it probably not a good idea to replace pcie.0 with a single pcie-root-port in machine.cfg.

**Comment by ldoktor** [comment]
Fair enough, yes I read about separating one device per root complex, but Avocado-vt does not currently scale to that. Do you know the expected time frame of the q35 rework? Arm could probably benefit from it as well...

**Comment by vivianQizhu** [comment]
@ldoktor We will finish it recently, to meet next vesrion product testing soon(Oct). Yes arm should use pcie frame as well.

**Comment by ldoktor** [comment]
@vivianQizhu I removed the q35 change and kept only that part to respect bus and also the single-root-complex solution for arm, which prevents us from testing. Would this be suitable for now, until you finish the proper solution?

**Comment by vivianQizhu** [comment]
@ldoktor Thanks, I am okay with current version, hotplug of q35 has specific requirement too, I am supposed to cover it too.

**Comment by ldoktor** [comment]
Actually this only works from qemu side (because of a missing assert) an in the OS only devices plugged into slot 0x0 are visible. New version can be found here, @vivianQizhu please take a look there and let me know about the status of your version. Perhaps we can combine the ideas but I can't wait much longer...

**Comment by vivianQizhu** [comment]
@ldoktor I have submitted a patch to add root port for pcie devices, and will submit similar hotplug solution if this one is accepted. Please help review: https://github.com/avocado-framework/avocado-vt/pull/1174 Thanks.

**Pull request closed without merging**
