### PR TITLE
Fix issue: the args "cmp" is rejected in function sorted() on python3

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 1643337

### CODE REVIEW

**Comment by XueqiangWei** [comment]
(1/1) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block: PASS (140.83 s)
 (1/1) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block: PASS (309.07 s)
(1/1) Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block: PASS (120.55 s)

**Comment by luckyh** [comment]
@YongxueHong

**Comment by CongLi** [comment]
Ack.

**Comment by YongxueHong** [comment]
Acked-by: Yongxue Hong <yhong@redhat.com>

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
