### PR TITLE
bump to aexpect 1.6.1

### PR DESCRIPTION
**Pull request by xiaodwan**
aexpect 1.6.1 fixes v2v rhv-upload testing

Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>

### CODE REVIEW

**Comment by pevogam** [comment]
Hi @xiaodwan, as of present I am not aware of an existing 1.6.1 release of aexpect. Is this some local versioning or are you suggesting that the aexpect project should add this minor release too?

**Comment by xiaodwan** [comment]
> Hi @xiaodwan, as of present I am not aware of an existing 1.6.1 release of aexpect. Is this some local versioning or are you suggesting that the aexpect project should add this minor release too?

Hi @pevogam ,  aexpect 1.6.1 was released yesterday. v2v testing needs the change in latest 1.6.1.
https://github.com/avocado-framework/aexpect/commit/ebca61259851710a443b4e93b31fa74d3978b3b9

**Review by sathnaga — APPROVED** [review]
Changed part works fine in travis CI, but has some other failures, have a look once, otherwise LGTM
```
Collecting aexpect==1.6.1

  Downloading aexpect-1.6.1.tar.gz (41 kB)
```

**Comment by pevogam** [comment]
I see but I am confused. @lmr Why is there no tag for the release? As far as I see that `aexpect` has [tags](https://github.com/avocado-framework/aexpect/releases) for both minor and major releases and this one is not there. Also, the commit has a typo in the title "Relase", maybe we can quickly fix this to "Release".

@xiaodwan I guess this release means that we can also get rid of the two `*_to_migrate` [functions](https://github.com/avocado-framework/avocado-vt/blob/977f4c67ac285abe8e4eb852ce856734ae55cce5/virttest/remote.py#L24) thanks to your fixes on the aexpect side but I can take a look at it if you want.

**Comment by pevogam** [comment]
@lmr I assume the aexpect was manually uploaded to PyPI which is why we have https://github.com/avocado-framework/aexpect/pull/66 in place or the alternative I suggested which will always check for a tag and auto-upload to PyPI thus automating and completing the entire process. It might be worth to look into it later on.

**Review by pevogam — APPROVED** [review]

**Comment by xiaodwan** [comment]
> @xiaodwan I guess this release means that we can also get rid of the two `*_to_migrate` [functions](https://github.com/avocado-framework/avocado-vt/blob/977f4c67ac285abe8e4eb852ce856734ae55cce5/virttest/remote.py#L24) thanks to your fixes on the aexpect side but I can take a look at it if you want.
@pevogam I guess it's caused by latest aexpect desn't support python2? Am I right?
Python: 2.7 failed because of syntaxerror in aexpect. 

```
$ AVOCADO_LOG_DEBUG=yes avocado vt-bootstrap --vt-skip-verify-download-assets --yes-to-all

Failed to load plugin from module "avocado_vt.plugins.vt_list": SyntaxError('invalid syntax', ('/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/aexpect/client.py', 1151, 53, '            raise ShellTimeoutError(cmd, output) from error\n')) :

Traceback not available

Failed to load plugin from module "avocado_vt.plugins.vt": SyntaxError('invalid syntax', ('/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/aexpect/client.py', 1151, 53, '            raise ShellTimeoutError(cmd, output) from error\n')) :

Traceback not available

Running bootstrap for qemu

**Comment by xiaodwan** [comment]
This patch may fix the problem.
https://github.com/avocado-framework/avocado-vt/pull/2809

**Comment by sathnaga** [comment]
> This patch may fix the problem.
> #2809

that will if we use setup.py install, but here I assume we directly install via requirements.txt, which still needs address, I believe

**Comment by xiaodwan** [comment]
> > This patch may fix the problem.
> > #2809
> 
> that will if we use setup.py install, but here I assume we directly install via requirements.txt, which still needs address, I believe

Looks like without this PR, the latest aexpect can still be found and installed.
It's better to do nothing now, utilll a better solution to solve the Travis problem.
so I'm going to close this PR, thanks @sathnaga @pevogam .

**Comment by xiaodwan** [comment]
After testing, the latest aexpect still can be installed without this PR, so close it.

**Comment by pevogam** [comment]
I will still wait for @lmr or somebody from the aexpect maintainers to see their comments on the missing tag but committed release. We can keep this closed of course.

**Pull request closed without merging**
