### PR TITLE
Add wait_change_event into change-media command

### PR DESCRIPTION
**Pull request by chunfuwen**
this exend change-media to allow certain time waiting for event,
in some test cases, it help to avoid timeout issue

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virsh.change_media_matrix.pre_vm_state_paused.cdrom_test.current.action_twice.live.insert_update

DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virsh.change_media_matrix.pre_vm_state_paused.cdrom_test.force.action_twice.live.insert_update

**Comment by qiankehan** [comment]
> some cases encounter below issues without event waiting,
> 2021-03-06 09:42:54,127 process L0686 INFO | Command '/bin/virsh change-media avocado-vt-vm1 hdc --update --live /tmp/avocado_xvtzfc4w/change_media_new.iso ' finished with 1 after 5.068805456161499s
> 2021-03-06 09:42:54,181 virsh L0709 DEBUG| status: 1
> 2021-03-06 09:42:54,182 virsh L0710 DEBUG| stdout:
> 2021-03-06 09:42:54,182 virsh L0711 DEBUG| stderr: error: Failed to complete action update on mediaerror: operation failed: timed out waiting to open tray of 'hdc'
This error comes from the waiting trey open code of libvirt: https://github.com/libvirt/libvirt/blob/a1229335f6ce999e53c649c1c006944650462d55/src/qemu/qemu_hotplug.c#L222
I think this error could happens when the update cdrom is associated with trey open, such as update the iso media file.

What's more, the case **change_media_matrix.pre_vm_state_paused.cdrom_test.current.action_twice.live.insert_update** fails by accident. It's hard to tell if this patch really works by several results of pass.
> 2021-03-06 09:42:54,320 libvirt_vm L2573 DEBUG| Resumed VM avocado-vt-vm1
> 
> with changes, below cases passed
> 
> DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
> DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
> DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
> PASS 1-type_specific.io-github-autotest-libvirt.virsh.change_media_matrix.pre_vm_state_paused.cdrom_test.current.action_twice.live.insert_update
> 
> DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
> DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
> DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
> PASS 1-type_specific.io-github-autotest-libvirt.virsh.change_media_matrix.pre_vm_state_paused.cdrom_test.force.action_twice.live.insert_update

**Comment by chunfuwen** [comment]
> > some cases encounter below issues without event waiting,
> > 2021-03-06 09:42:54,127 process L0686 INFO | Command '/bin/virsh change-media avocado-vt-vm1 hdc --update --live /tmp/avocado_xvtzfc4w/change_media_new.iso ' finished with 1 after 5.068805456161499s
> > 2021-03-06 09:42:54,181 virsh L0709 DEBUG| status: 1
> > 2021-03-06 09:42:54,182 virsh L0710 DEBUG| stdout:
> > 2021-03-06 09:42:54,182 virsh L0711 DEBUG| stderr: error: Failed to complete action update on mediaerror: operation failed: timed out waiting to open tray of 'hdc'
> 
> This error comes from the waiting trey open code of libvirt: https://github.com/libvirt/libvirt/blob/a1229335f6ce999e53c649c1c006944650462d55/src/qemu/qemu_hotplug.c#L222
> I think this error could happens when the update cdrom is associated with trey open, such as update the iso media file.
> 
> What's more, the case **change_media_matrix.pre_vm_state_paused.cdrom_test.current.action_twice.live.insert_update** fails by accident. It's hard to tell if this patch really works by several results of pass.
> 
> > 2021-03-06 09:42:54,320 libvirt_vm L2573 DEBUG| Resumed VM avocado-vt-vm1
> > with changes, below cases passed
> > DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
> > DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
> > DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
> > PASS 1-type_specific.io-github-autotest-libvirt.virsh.change_media_matrix.pre_vm_state_paused.cdrom_test.current.action_twice.live.insert_update
> > DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
> > DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
> > DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
> > PASS 1-type_specific.io-github-autotest-libvirt.virsh.change_media_matrix.pre_vm_state_paused.cdrom_test.force.action_twice.live.insert_update

This solution is similar to previous virsh.detach_device() to enable one parameter to allow whether it need wait for certain event, then it is a good practice that subsequent actions happen  only after certain event received showing object state is ready

**Review by dzhengfy — APPROVED** [review]
The fix is similar to the existing solution for other functions. So LGTM.

**Pull request merged**
