### PR TITLE
virtio_console_guest: Install module six if missing

### PR DESCRIPTION
**Pull request by michiboo**
ID: 1798383

Signed-off-by: Micky Yun Chan <michan@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
@michiboo  Code LGTM.
But, this file is not used for windows guest only, please update the commit title.

**Comment by michiboo** [comment]
> @michiboo Code LGTM.
> But, this file is not used for windows guest only, please update the commit title.

Hi but is it only in window OS that module six is not installed

**Comment by yanan-fu** [comment]
@michiboo yes, only windows guest have this issue, but this file is not used by windows guest only.
I mean:
```
virtio_console_guest: Install module six if missing

some windows guest don't install six by default, install it to avoid this issue
```

**Comment by yanan-fu** [comment]
Acked-by; Yanan Fu <yfu@redhat.com>

**Comment by yanan-fu** [comment]
@luckyh could you help review ? thanks!

**Comment by luckyh** [comment]
please provide the test result, thanks.

**Comment by yanan-fu** [comment]
@luckyh 
1. First time, test with Win2016 guest, hit this issue with error:
```
08:57:39 ERROR| Traceback (most recent call last):
08:57:39 ERROR|   File "C:\virtio_console_guest.py", line 25, in <module>
08:57:39 ERROR|     import six
08:57:39 ERROR| ImportError: No module named six
08:57:39 ERROR| FAIL: Compile virtio_guest failed
```

2. After apply this patch, test pass;
```
09:08:48 DEBUG| Sending command: for %I in (C:\virtio_console_guest.py) do @echo %~zI
09:08:48 DEBUG| Sending command: dir C:\virtio_console_guest.pyo
09:08:48 DEBUG| Sending command: echo %errorlevel%
09:08:48 DEBUG| Starting virtio_console_guest.pyo on guest avocado-vt-vm1
09:08:48 DEBUG| Executing 'C:\virtio_console_guest.pyo && echo PASS: virtio_guest finished || echo FAIL: virtio_guest failed' on virtio_console_guest.py, vm: avocado-vt-vm1, timeout: 120
...
09:09:01 INFO | PASS 1-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.virtio_serial_throttling
```

**Comment by yanan-fu** [comment]
@luckyh  commit info have updated, could you help review again, thanks!

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
