### PR TITLE
virttest.libvirt_vm: Perform package update if package was already installed

### PR DESCRIPTION
**Pull request by rbian**
Latest package should be used for testing, we need to update packages if it's
installed, such as qemu-guest-agent, selinux-policy.

Signed-off-by: Ruifeng Bian <rbian@redhat.com>

### CODE REVIEW

**Comment by will-Do** [comment]
Maybe you can calling 'utils_misc.yum_install' directly

**Comment by lmr** [comment]
@rbian the failures are not your fault, you can simply rebase against the latest master and then the problem will go away. Please do that, thanks!

**Comment by rbian** [comment]
@will-Do , "utils_misc.yum_install" has same problem. It just install the package if it's not installed, it can't update the package.  I think this is right place to do it.

**Comment by will-Do** [comment]
Okay, I'm good with this pr, so ACK

**Comment by waynesun09** [comment]
Found remove_numa_cells function be used in another PR:
https://github.com/autotest/tp-libvirt/pull/657

**Comment by waynesun09** [comment]
ACK

**Pull request merged**
