### PR TITLE
qemu_virtio_port: Adopt guest 'python' command to python3

### PR DESCRIPTION
**Pull request by vivianQizhu**
Note: the test cases still fail for other issue within virtio_console_guest(or maybe qemu issue, investigating).

id: 1610670
Signed-off-by: qizhu <qizhu@redhat.com>

### CODE REVIEW

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by luckyh** [comment]
I see there are still three places needed to be changed in this module, would you please have a check? thanks.

**Comment by vivianQizhu** [comment]
@luckyh Thanks for being careful, updated, please help double check.

**Comment by vivianQizhu** [comment]
Test passed together with later on fix https://github.com/avocado-framework/avocado-vt/pull/1719, for both python2 and python3:
```
 (1/1) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.x86_64.my-provider.virtio_console.spread_linear.virtserialport.virtio_console_smoke.rw_host_offline: PASS (64.51 s)
```
```
15:06:05 INFO | PASS 1-Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.myprovider.virtio_console.spread_linear.virtserialport.virtio_console_smoke.rw_host_offline
```

**Pull request merged**
