### PR TITLE
Change the detach-interface get event timeout

### PR DESCRIPTION
**Pull request by kylazhang**
Signed-off-by: Kyla Zhang <weizhan@redhat.com>

### CODE REVIEW

**Comment by kylazhang** [comment]
```
 (1/1) type_specific.io-github-autotest-libvirt.virsh.attach_detach_interface.normal_test.vm_running.direct.default.domuuid: PASS (81.35 s)
 (1/1) type_specific.io-github-autotest-libvirt.virsh.attach_detach_interface.normal_test.vm_paused.direct.default.domuuid: PASS (83.59 s)
```

**Comment by kylazhang** [comment]
@yalzhang Please check if the timeout is acceptable, thanks

**Review by chunfuwen — APPROVED** [review]
LGTM

**Review by yalzhang — APPROVED** [review]
LGTM

**Pull request merged**
