### PR TITLE
Add unittest of memory device

### PR DESCRIPTION
**Pull request by chloerh**
Test setting all attributes of a memory device

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

### CODE REVIEW

**Comment by chloerh** [comment]
Test
Ran 1 test in 0.048s

OK

**Comment by chloerh** [comment]
@dzhengfy @Yingshun Could you guys help review?

**Review by Yingshun — APPROVED** [review]
Thank you @chloerh for adding it. Test passed:
` (1/1) test_device_xml.TestMemoryXML.test_setup_memory_default: PASS (0.33 s)`

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
