### PR TITLE
libvirt_version: Fix a typo in is_libvirt_feature_supported

### PR DESCRIPTION
**Pull request by Yingshun**
Signed-off-by: Yingshun Cui <yicui@redhat.com>

### CODE REVIEW

**Review by cliping — APPROVED** [review]
LGTM

**Review by chunfuwen — APPROVED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]
There are 17 places in tp-libvirt to use this variable. Do you have a plan to update them, too?

**Comment by Yingshun** [comment]
@dzhengfy I've updated them in tp-libvirt https://github.com/autotest/tp-libvirt/pull/3850, could you plz help check them?

**Pull request merged**
