### PR TITLE
qemu_vm: Make commands of hotplug_nic and hotunlug_nic more accurate

### PR DESCRIPTION
**Pull request by PaulYuuu**
Fix formatting issue in hotplug_nic and hotunplug_nic, otherwise they
will hot plug/unplug with incorrect `device_id` and `netdev_id`.

Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
@kimi1978wy I guess this patch can help you to develop your hotunplug test case.
https://github.com/autotest/tp-qemu/pull/1859
Please have a try, it is best to provide your test result, thanks.

**Comment by kimi1978wy** [comment]
@PaulYuuu It works good for me. Thanks a lot
LGTM
Acked by : Yu Wang <wyu@redhat.com>
 (1/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.nic_hotplug.migration.after_nichotunplug.nic_8139: PASS (127.72 s)
 (2/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.nic_hotplug.migration.after_nichotunplug.nic_virtio: PASS (110.52 s)
 (3/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.nic_hotplug.migration.after_nichotunplug.nic_e1000: PASS (111.15 s)
 (4/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.nic_hotplug.migration.after_nichotunplug.nic_e1000e: PASS (112.31 s)

**Comment by PaulYuuu** [comment]
This modification did not lead to regression.
 (01/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.nic_hotplug.one_pci.nic_virtio: PASS (234.86 s)
 (02/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.nic_hotplug.one_pci.nic_virtio.with_repetition: PASS (5215.13 s)
 (03/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.nic_hotplug.one_pci.nic_virtio.with_reboot: PASS (247.68 s)
 (04/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.nic_hotplug.one_pci.nic_virtio.with_shutdown.after_plug: PASS (125.41 s)
 (05/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.nic_hotplug.one_pci.nic_virtio.with_shutdown.after_unplug: PASS (123.80 s)
 (06/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.nic_hotplug.one_pci.nic_virtio.with_system_reset: PASS (258.47 s)
 (07/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.nic_hotplug.multi_pci.nic_virtio: PASS (292.31 s)
 (08/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.nic_hotplug.additional.nic_virtio: PASS (130.96 s)
 (09/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.nic_hotplug.migration.after_nichotplug.nic_virtio: PASS (398.44 s)
 (10/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.nic_hotplug.migration.after_nichotunplug.nic_virtio: PASS (234.44 s)
 (11/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.nic_hotplug.vhost_nic.nic_virtio: PASS (130.76 s)
 (12/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.nic_hotplug.used_netdev.nic_virtio: PASS (85.60 s)

**Comment by vivianQizhu** [comment]
Ack

**Pull request merged**
