### PR TITLE
qemu_vm: Enable pause-before-switchover and late-block-activate

### PR DESCRIPTION
**Pull request by YongxueHong**
Enable migration capabilities "pause-before-switchover" on source
host and "late-block-activate" destination host before migrating
guest, Then continue migration on source host after the status of
migration is "pre-switchover".
    
ID: 1881805
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
Hi @wangxianxian  @leexiaohui32 @luckyh 
Please help me to review, thanks.

**Comment by wangxianxian** [comment]
Test PASS on ppc side.
```
 (1/3) type_specific.io-github-autotest-qemu.migrate.with_set_speed.tcp.default: PASS (118.36 s)
 (2/3) type_specific.io-github-autotest-qemu.migrate.with_set_speed.tcp.with_filter_off.with_post_copy: PASS (113.06 s)
 (3/3) type_specific.io-github-autotest-qemu.migrate.with_set_speed.tcp.with_filter_off.with_multifd: PASS (112.77 s)
```
ACK

**Comment by YongxueHong** [comment]
Hi @luckyh
I run one migration case by 50 times, all passed.

**Review by luckyh — APPROVED** [review]
LGTM

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
