### PR TITLE
Extend test_timeout

### PR DESCRIPTION
**Pull request by suqinhuang**
Some test need long time, espical for the tests repeat hundreds times.

ID: 1244178

### CODE REVIEW

**Comment by CongSmile** [comment]
I think it's better to set the different timeout for different cases.

**Comment by suqinhuang** [comment]
I don't think it's necessary,

Generally, test_timeout is useless to the test.
the test_timeout is set to avoid the env issue at first.
job may hang because of the machine management before, which will make the job keep running long time.
we never met the env issue now

**Comment by PandaWei** [comment]
I am very curious about 356400.
How do you determine this value？ 
Do we need to expand the recommended value 14400 to 356400？

**Comment by suqinhuang** [comment]
99d is the limit time in beaker

**Comment by CongSmile** [comment]
@suqinhuang 

Could you check the timeout defined in run_test() in avocado/avocado/core/runner.py?
        # At this point, the test is already initialized and we know
        # for sure if there's a timeout set.
        timeout = test_status.early_status.get('timeout')
        timeout = float(timeout or self.DEFAULT_TIMEOUT)

According to the test, should be the above timeout works.

Thanks.

**Comment by suqinhuang** [comment]
Hi coli,
You are right
run_tests in utils_misc.py is useless now, 
will send a patch internal to set timeout.

Thanks
Suqin

**Comment by suqinhuang** [comment]
timeout will be covered with --job-timeout

args.job_timeout = self._validate_job_timeout(args.job_timeout)
        job_instance = job.Job(args)
        return job_instance.run()

**Pull request closed without merging**
