### PR TITLE
vm_xml: set_vm_vcpus() support clusters

### PR DESCRIPTION
**Pull request by rh-jugraham**
Signed-off-by: Julia Graham <jugraham@redhat.com>

Modified set_vm_vcpus() to support clusters.

### CODE REVIEW

**Comment by rh-jugraham** [comment]
Tested implementation on max_vcpus_topology.py (passing tests shown in mentioned PR), topology.py, and virsh_guestvcpus.py.

**Passing topology.py test:**

[root@beaver-6 /]# /usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 topology.positive.hotplug --vt-connect-uri qemu:///system
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : dbc5eb5bdca4fce9083f3aa018ad23e6ee229974
JOB LOG    : /var/log/avocado/job-results/job-2024-09-27T20.39-dbc5eb5/job.log
 (1/1) type_specific.io-github-autotest-libvirt.topology.positive.hotplug: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.topology.positive.hotplug: PASS (63.12 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-09-27T20.39-dbc5eb5/results.html
JOB TIME   : 64.50 s

**Passing virsh_guestvcpus.py tests:**

[root@beaver-6 /]# /usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 virsh.guestvcpus.normal_test --vt-connect-uri qemu:///system
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 547140c73da49ce1f7300d99c91b0bbef651bac7
JOB LOG    : /var/log/avocado/job-results/job-2024-09-27T20.43-547140c/job.log
 (1/4) type_specific.io-github-autotest-libvirt.virsh.guestvcpus.normal_test.no-option: STARTED
 (1/4) type_specific.io-github-autotest-libvirt.virsh.guestvcpus.normal_test.no-option: PASS (532.89 s)
 (2/4) type_specific.io-github-autotest-libvirt.virsh.guestvcpus.normal_test.disable: STARTED
 (2/4) type_specific.io-github-autotest-libvirt.virsh.guestvcpus.normal_test.disable: PASS (199.89 s)
 (3/4) type_specific.io-github-autotest-libvirt.virsh.guestvcpus.normal_test.enable: STARTED
 (3/4) type_specific.io-github-autotest-libvirt.virsh.guestvcpus.normal_test.enable: PASS (186.87 s)
 (4/4) type_specific.io-github-autotest-libvirt.virsh.guestvcpus.normal_test.combine: STARTED
 (4/4) type_specific.io-github-autotest-libvirt.virsh.guestvcpus.normal_test.combine: PASS (187.81 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-09-27T20.43-547140c/results.html
JOB TIME   : 1110.68 s

**Comment by Yingshun** [comment]
@rh-jugraham Plz fix the error in signedoff-check, thx!

**Comment by rh-jugraham** [comment]
> @rh-jugraham Plz fix the error in signedoff-check, thx!

Updated the commit message!

**Comment by Yingshun** [comment]
> > @rh-jugraham Plz fix the error in signedoff-check, thx!
> 
> Updated the commit message!

There is one more failure in static check, plz resolve it, thx!

**Comment by rh-jugraham** [comment]
> There is one more failure in static check, plz resolve it, thx!

Updated! I don't have the permissions to rerun the workflow but I fixed the issue I saw

**Review by chloerh — APPROVED** [review]

**Review by Yingshun — APPROVED** [review]

**Pull request merged**
