### PR TITLE
Update path of tmp_dir to '/var/tmp'

### PR DESCRIPTION
**Pull request by chloerh**
Filesystem changes

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

### CODE REVIEW

**Review by dzhengfy — COMMENTED** [review]
I think it is ok to use '/var/tmp'. This PR will also fix the snapshot failure which has temp fix in https://github.com/avocado-framework/avocado-vt/pull/2914 now. After this PR is merged, 2914 can be closed directly.

**Review by pevogam — COMMENTED** [review]
Hi @chloerh, may I ask what is the reason for this proposed change? This looks like a default value that is internalized in the code instead of suggested at the settings level.

**Comment by chloerh** [comment]
Hi @pevogam the reason that we make this change is that we met a lot of errors like:
`CmdError: Command 'mount -t nfs -o rw 127.0.0.1:/tmp/avocado_ej2i9cr/nfs_server /tmp/avocadoej2i9cr/nfs-mount' failed.stdout: b''stderr: b'mount.nfs: mounting 127.0.0.1:/tmp/avocado_ej2i9cr/nfs_server failed, reason given by server: No such file or directory\n'additional_info: None`

It's because we use '/tmp' as mount source and target. 
This error could be fixed with this commit.

**Comment by chloerh** [comment]
@luckyh Would you mind taking a look? Thanks.

**Review by dzhengfy — APPROVED** [review]
Run multiple tests with this pr, and the result proves it works.

**Comment by luckyh** [comment]
> Hi @pevogam the reason that we make this change is that we met a lot of errors like:
> `CmdError: Command 'mount -t nfs -o rw 127.0.0.1:/tmp/avocado_ej2i9cr/nfs_server /tmp/avocadoej2i9cr/nfs-mount' failed.stdout: b''stderr: b'mount.nfs: mounting 127.0.0.1:/tmp/avocado_ej2i9cr/nfs_server failed, reason given by server: No such file or directory\n'additional_info: None`
> 
> It's because we use '/tmp' as mount source and target.
> This error could be fixed with this commit.

Sorry that I'm still not clear on that issue, would you mind to give any further elaboration here? thanks.

**Comment by chloerh** [comment]
> > Hi @pevogam the reason that we make this change is that we met a lot of errors like:
> > `CmdError: Command 'mount -t nfs -o rw 127.0.0.1:/tmp/avocado_ej2i9cr/nfs_server /tmp/avocadoej2i9cr/nfs-mount' failed.stdout: b''stderr: b'mount.nfs: mounting 127.0.0.1:/tmp/avocado_ej2i9cr/nfs_server failed, reason given by server: No such file or directory\n'additional_info: None`
> > It's because we use '/tmp' as mount source and target.
> > This error could be fixed with this commit.
> 
> Sorry that I'm still not clear on that issue, would you mind to give any further elaboration here? thanks.

@luckyh According to latest change of '/tmp' dir, our test cases with nfs mount which use /tmp dir as  mount point all failed due to 'No such file or directory'. We would like to change the directory that we get from `get_tmp_dir` to fix this issue.

**Comment by luckyh** [comment]
> @luckyh According to latest change of '/tmp' dir, our test cases with nfs mount which use /tmp dir as mount point all failed due to 'No such file or directory'. We would like to change the directory that we get from `get_tmp_dir` to fix this issue.

@chloerh ok, so, if the failure is caused by `No such file or directory` literally it's better to check on whether the logic of preparing src/dst dir is correct. Or else, if it is caused by using tmpfs, I'd suggest making the fix by using the dir pointed by `get_data_dir` instead.

**Comment by pevogam** [comment]
I agree with @luckyh, this is an invasive change that fixes the error for a single party but modifies the behavior for everyone. Simply improving the logic of the mounts should be enough here.

**Comment by chloerh** [comment]
> > @luckyh According to latest change of '/tmp' dir, our test cases with nfs mount which use /tmp dir as mount point all failed due to 'No such file or directory'. We would like to change the directory that we get from `get_tmp_dir` to fix this issue.
> 
> @chloerh ok, so, if the failure is caused by `No such file or directory` literally it's better to check on whether the logic of preparing src/dst dir is correct. Or else, if it is caused by using tmpfs, I'd suggest making the fix by using the dir pointed by `get_data_dir` (for source) instead.

@luckyh  That is a great idea! Thank you for your nice suggestion! I'll take the suggestion of switching to 'data_dir' and run some test.
Again, thank you for your review :+1:

**Comment by chloerh** [comment]
> I agree with @luckyh, this is an invasive change that fixes the error for a single party but modifies the behavior for everyone. Simply improving the logic of the mounts should be enough here.

@pevogam Thank you for you review, too. I'm going to take the suggestion.

**Comment by chloerh** [comment]
I'm closing this and opening another pr focusing on nfs mounting only.

**Comment by chunfuwen** [comment]
@luckyh 
@pevogam 
Actually we also meet below issue beyond nfs mentioned above.
And all root clause is  https://bugzilla.redhat.com/show_bug.cgi?id=1925456#c4
Unfortunately, the impacted cases number is also quite many.
So my suggestion is to add  one condition to switch tmp_dir folder, which is similar to line 207(if distro.detect().name == 'Ubuntu':). So the code may be like:
if get_fs_type('/tmp') -- 'tmpfs':
   tmp_dir = "/var/lib/libvirt/images"
****************************************************************************
open '/tmp/avocado_owf0ji6a/uefi_disk.qcow2': filesystem does not support O_DIRECT&#10" with cache='none' in guest
Reason: The filesystem type of directory "/tmp" is different between xx and xx

**Comment by pevogam** [comment]
Hi @chunfuwen, a couple of things here:

1) The bug you point to is internal to the company (at least a BugZilla account doesn't seem to allow even read access) while this project is public and thus serves both the public and private needs. This means that changing default due to problems that are internal to a particular company and product is only half the factors here.

2) It would be good if you format your code and even add a formatted diff so that it is easier to see what exactly is the change you are proposing instead of trying to figure it out from code within your text.

3) Trying to read still I am guessing you mean to set the tmp directory to your very particular choice of path if tmpfs filesystem type is detected. This does not have any global user logic to me, it seems like a custom fix in your own use.

Do you mind elaborating more on points 1) and 2)?

**Comment by chunfuwen** [comment]
> 1. needs



> Hi @chunfuwen, a couple of things here:
> 
> 1. The bug you point to is internal to the company (at least a BugZilla account doesn't seem to allow even read access) while this project is public and thus serves both the public and private needs. This means that changing default due to problems that are internal to a particular company and product is only half the factors here.
> 2. It would be good if you format your code and even add a formatted diff so that it is easier to see what exactly is the change you are proposing instead of trying to figure it out from code within your text.
> 3. Trying to read still I am guessing you mean to set the tmp directory to your very particular choice of path if tmpfs filesystem type is detected. This does not have any global user logic to me, it seems like a custom fix in your own use.
> 
> Do you mind elaborating more on points 1) and 2)?

Regarding points 1) I don't think it is limit to one company or product,  it is quite similar to the situation in line 207, which handle Ubuntu. Moreover, avocado-vt  is to serve tp-libvirt and tp-qemu, where it is in-place to handle common issues.
points 2) it is very close to your point 3, just detect /tmp file type, if it is tmpfs, and set tmp_dir = "/var/lib/libvirt/images". This is rough idea, but I assume it may not  impact us make decision.

**Comment by pevogam** [comment]
> > 1. needs
> 
> > Hi @chunfuwen, a couple of things here:
> > 
> > 1. The bug you point to is internal to the company (at least a BugZilla account doesn't seem to allow even read access) while this project is public and thus serves both the public and private needs. This means that changing default due to problems that are internal to a particular company and product is only half the factors here.
> > 2. It would be good if you format your code and even add a formatted diff so that it is easier to see what exactly is the change you are proposing instead of trying to figure it out from code within your text.
> > 3. Trying to read still I am guessing you mean to set the tmp directory to your very particular choice of path if tmpfs filesystem type is detected. This does not have any global user logic to me, it seems like a custom fix in your own use.
> > 
> > Do you mind elaborating more on points 1) and 2)?
> 
> Regarding points 1) I don't think it is limit to one company or product, it is quite similar to the situation in line 207, which handle Ubuntu. Moreover, avocado-vt is to serve tp-libvirt and tp-qemu, where it is in-place to handle common issues.
> points 2) it is very close to your point 3, just detect /tmp file type, if it is tmpfs, and set tmp_dir = "/var/lib/libvirt/images". This is rough idea, but I assume it may not impact us make decision. But if really needed diff, I can provides that afterwards

Maybe I miss something in your explanation but `tmp_dir` is meant for the system-generic or at least distro-generic temporary location and "/var/lib/libvirt/images" is not such. Then you should define `tmp_dir_libvirt_images` or something to make this a meaningful change. The setting is fully configurable and can be set to any value so I don't see why we have to change the default, especially adding extra complexity to change it conditionally for tmpfs type or anything of this sort.

**Comment by chunfuwen** [comment]
> > > 1. needs
> > 
> > 
> > > Hi @chunfuwen, a couple of things here:
> > > 
> > > 1. The bug you point to is internal to the company (at least a BugZilla account doesn't seem to allow even read access) while this project is public and thus serves both the public and private needs. This means that changing default due to problems that are internal to a particular company and product is only half the factors here.
> > > 2. It would be good if you format your code and even add a formatted diff so that it is easier to see what exactly is the change you are proposing instead of trying to figure it out from code within your text.
> > > 3. Trying to read still I am guessing you mean to set the tmp directory to your very particular choice of path if tmpfs filesystem type is detected. This does not have any global user logic to me, it seems like a custom fix in your own use.
> > > 
> > > Do you mind elaborating more on points 1) and 2)?
> > 
> > 
> > Regarding points 1) I don't think it is limit to one company or product, it is quite similar to the situation in line 207, which handle Ubuntu. Moreover, avocado-vt is to serve tp-libvirt and tp-qemu, where it is in-place to handle common issues.
> > points 2) it is very close to your point 3, just detect /tmp file type, if it is tmpfs, and set tmp_dir = "/var/lib/libvirt/images". This is rough idea, but I assume it may not impact us make decision. But if really needed diff, I can provides that afterwards
> 
> Maybe I miss something in your explanation but `tmp_dir` is meant for the system-generic or at least distro-generic temporary location and "/var/lib/libvirt/images" is not such. Then you should define `tmp_dir_libvirt_images` or something to make this a meaningful change. The `tmp_dir` setting is fully configurable and can be set to any value so I don't see why we have to change the default, especially adding extra complexity to change it conditionally for tmpfs type or anything of this sort. Correct me if I really miss something.

tmp_dir is default is '/tmp', but in some distribution, they may not be work as expected.
For example, if '/tmp' is tmpfs filesystem, virtual disk created on /tmp throw error 'filesystem does not support O_DIRECT' ,etc.
What I want to achieve here is to set tmp = "/var/lib/libvirt/images" if  /tmp is detected as tmpfs.
And the demo code may follow as:
fs_type = get_fs_type('/tmp')
if fs_type and  fs_type[-1] == "tmpfs":
      tmp_dir = "/var/lib/libvirt/images"

def get_fs_type(fs):
    res = None
    dev = os.lstat(fs).st_dev
    with open("/proc/mounts", "r") as f:
        for line in f:
            # lines are device, mountpoint, filesystem, <rest>
            line = [s for s in line.split()[:3]]
            try:
                if dev == os.lstat(line[1]).st_dev:
                    res = tuple(line)
                    break
            except OSError as err:
                continue 
    return res`
`

**Comment by luckyh** [comment]
> @luckyh
> @pevogam
> Actually we also meet below issue beyond nfs mentioned above.
> And all root clause is https://bugzilla.redhat.com/show_bug.cgi?id=1925456#c4
> Unfortunately, the impacted cases number is also quite many.
> So my suggestion is to add one condition to switch tmp_dir folder, which is similar to line 207(if distro.detect().name == 'Ubuntu':). So the code may be like:
> if get_fs_type('/tmp') -- 'tmpfs':
> tmp_dir = "/var/lib/libvirt/images"
> 
> open '/tmp/avocado_owf0ji6a/uefi_disk.qcow2': filesystem does not support O_DIRECT&#10" with cache='none' in guest
> Reason: The filesystem type of directory "/tmp" is different between xx and xx

@chunfuwen

Well, here are two points to be clarified:

1. `/tmp` being tmpfs as the tmp_dir of avocado_vt is an expected behavior.

And then, about the placement of temporary image files, I'd suggest using the `images` dir (which is under VT's `data_dir`) instead, even though they are "temporary".

2. attempting to fix the issue by changing the dir path is just a workaround which might bring potential side-effects.

While there are a few ways to bypass the issue, and the simplest one (from my POV) is by setting the `TMPDIR` environment variable, according to [the current Avocado's implementation of `data_dir.get_tmp_dir`](https://github.com/avocado-framework/avocado/blob/942e397722705d0ae08053228e1f1040f33347cb/avocado/core/data_dir.py#L254-L271):
```
$ cat t.py
import os
import tempfile

tmp_dir = tempfile.mkdtemp(prefix='avocado_', dir=None)
print(tmp_dir)
os.rmdir(tmp_dir)

$ python3 t.py
/tmp/avocado_mcdcp2v0

$ TMPDIR=/var/tmp python3 t.py
/var/tmp/avocado_uuo_z0ri
```
Or as @pevogam mentioned the tmp_dir path can be configured by [this VT setting](https://github.com/avocado-framework/avocado-vt/blob/8b897e8f236234e95d834391e934024877a9ab13/avocado_vt/conf.d/vt.conf#L15). Either of these two approaches would be a better choice, thanks.

**Comment by chunfuwen** [comment]
> > @luckyh
> > @pevogam
> > Actually we also meet below issue beyond nfs mentioned above.
> > And all root clause is https://bugzilla.redhat.com/show_bug.cgi?id=1925456#c4
> > Unfortunately, the impacted cases number is also quite many.
> > So my suggestion is to add one condition to switch tmp_dir folder, which is similar to line 207(if distro.detect().name == 'Ubuntu':). So the code may be like:
> > if get_fs_type('/tmp') -- 'tmpfs':
> > tmp_dir = "/var/lib/libvirt/images"
> > open '/tmp/avocado_owf0ji6a/uefi_disk.qcow2': filesystem does not support O_DIRECT&#10" with cache='none' in guest
> > Reason: The filesystem type of directory "/tmp" is different between xx and xx
> 
> @chunfuwen
> 
> Well, here are two points to be clarified:
> 
> 1. `/tmp` being tmpfs as the tmp_dir of avocado_vt is an expected behavior.
> 
> And then, about the placement of temporary image files, I'd suggest using the `images` dir (which is under VT's `data_dir`) instead, even though they are "temporary".
> 
> 1. attempting to fix the issue by changing the dir path is just a workaround which might bring potential side-effects.
> 
> While there are a few ways to bypass the issue, and the simplest one (from my POV) is by setting the `TMPDIR` environment variable, according to [the current Avocado's implementation of `data_dir.get_tmp_dir`](https://github.com/avocado-framework/avocado/blob/942e397722705d0ae08053228e1f1040f33347cb/avocado/core/data_dir.py#L254-L271):
> 
> ```
> $ cat t.py
> import os
> import tempfile
> 
> tmp_dir = tempfile.mkdtemp(prefix='avocado_', dir=None)
> print(tmp_dir)
> os.rmdir(tmp_dir)
> 
> $ python3 t.py
> /tmp/avocado_mcdcp2v0
> 
> $ TMPDIR=/var/tmp python3 t.py
> /var/tmp/avocado_uuo_z0ri
> ```
> 
> Or as @pevogam mentioned the tmp_dir path can be configured by [this VT setting](https://github.com/avocado-framework/avocado-vt/blob/8b897e8f236234e95d834391e934024877a9ab13/avocado_vt/conf.d/vt.conf#L15). Either of these two approaches would be a better choice, thanks.

@luckyh 
1)I miss the information that it can be configurable, that could be one way forward to this issue
2)In my understanding, what get_tmp_dir() should attempt is to provide common API to tp-libvirt and tp-qemu by abstracting complexities,e.g Ubuntu variant and tmpfs which already appeared.

**Comment by chunfuwen** [comment]
@ldoktor 
@clebergnu 
Sorry to bring  both of you in.
But I feel it may be related to more general issue that how  we can manage our API life cycle.
Therefore I would like to bring into table for discussion.
Now default value returned by get_tmp_dir()  API can not work as expected in the situation where tmp_dir is tmpfs.
Naturally, there may be two options to move it forward:
1)Fix it in the code to keep API compatible
2)Document the issue somewhere reminding not applicable in particular situation
You are very appreciated if you can provide some feedbacks

**Comment by smitterl** [comment]
@luckyh @pevogam @chunfuwen I'm not sure if I understand this correctly. It makes sense to use the vt.conf to set the tmp dir in special occasions.

Why is 

              "/tmp being tmpfs as the tmp_dir of avocado_vt is an expected behavior."

as mentioned by @luckyh?

I mean we've seen that many tests didn't expect this behavior. Those tests don't seem to have just recently been added, so it looks like not everybody knew of this requirement.

May I ask which code uses tmp_dir as non-tmpfs? Is that in avocado-vt lib or in the test providers?

If it's in avocado-vt, then that contradicts the above requirement, doesn't it? If this was the case, it's been suggested to use the data_dir instead; IMO that makes sense if tmpfs is really the expected type for tmp_dir.

**Comment by luckyh** [comment]
@smitterl 

> Why is
> 
> ```
>           "/tmp being tmpfs as the tmp_dir of avocado_vt is an expected behavior."
> ```
> 
> as mentioned by @luckyh?
> 
> I mean we've seen that many tests didn't expect this behavior. Those tests don't seem to have just recently been added, so it looks like not everybody knew of this requirement.
> 
> May I ask which code uses tmp_dir as non-tmpfs? Is that in avocado-vt lib or in the test providers?

For the use of qemu testing, (generally) temporary image files will not be put into `tmp_dir`, and instead `data_dir/images` is the target place. However for special demands users do can put the image files into `tmp_dir`, so the code would be mostly in the test providers I guess (at least for qemu testing).

Since `tmp_dir` is not dedicated for image placement its filesystem type won't be the thing that matters, thus users are required to be aware of the limitation if they do need to use `tmp_dir` as the image pool to put images in.

So this for me is that, for libvirt testing, there seems no unified API widely used for creating/acquiring temporary image pools and hence it's so painful to fix the issue, but I still encourage to give it a try. Thanks.

**Comment by chunfuwen** [comment]
> @smitterl
> 
> > Why is
> > ```
> >           "/tmp being tmpfs as the tmp_dir of avocado_vt is an expected behavior."
> > ```
> > 
> > 
> > as mentioned by @luckyh?
> > I mean we've seen that many tests didn't expect this behavior. Those tests don't seem to have just recently been added, so it looks like not everybody knew of this requirement.
> > May I ask which code uses tmp_dir as non-tmpfs? Is that in avocado-vt lib or in the test providers?
> 
> For the use of qemu testing, (generally) temporary image files will not be put into `tmp_dir`, and instead `data_dir/images` is the target place. However for special demands users do can put the image files into `tmp_dir`, so the code would be mostly in the test providers I guess (and it's true at least for qemu testing).
> 
> Since `tmp_dir` is not dedicated for image placement its filesystem type won't be the thing that matters, thus users are required to be aware of the limitation if they do need to use `tmp_dir` as the image pool to put images in.
> 
> So this for me is that, for libvirt testing, there seems no unified API widely used for creating/acquiring temporary image pools and hence it's so painful to fix the issue, but I still encourage to give it a try. Thanks.

@luckyh 
quote "thus users are required to be aware of the limitation if they do need to use tmp_dir as the image pool to put images in."
May I ask when and how users are notified to be aware of this limitation?
I list two example cases here,where user didn't know that:
1)libvirt.setup_or_cleanup_iscsi() in libvirt.py was created around year 2015, which use data_dir.get_tmp_dir() to generate
 image
2)Balamuruhan S <bala24@linux.vnet.ibm.com> submited one patch around 2018 (commit id :6a78795ddb63a7c39262188893a5b2223edf46dd)to make data_dir.get_tmp_dir() compatible on Ubuntu(allow put image there),

**Comment by pevogam** [comment]
Hi @chunfuwen, perhaps I am missing something but I don't see you commenting on the option of using the `data_dir/images` path as @luckyh suggested. Is there a problem with this option?

> 2)In my understanding, what get_tmp_dir() should attempt is to provide common API to tp-libvirt and tp-qemu by abstracting complexities and keep compatibility with variant environment,e.g Ubuntu variant and tmpfs which already appeared.

For me and probably other Avocado VT user the tmp directory is not restricted to just placing image files there (temporary or not) and it could contain various small temporary files. It is thus not associated with image files specifically.

Placing images in a temporary directory might also have some security implications considering the permissions that are usually implied there.

**Comment by ldoktor** [comment]
Well my 2 cents would be that the `get_tmp_dir` should respect the configuration as it should be an arbitrary tmp dir. For historic reasons Avocado-vt relies on tmpdir heavily even for things under testing, which might frequently require DIRECT access or other features. I can see a simple fix in adding a FS check into the `get_tmp_dir` similarly to the `ubuntu` one. A proper fix in my opinion would be to fix places where DIRECT access (or other heavy usage like test images and such) are used and use a datadir there, because datadir should be more appropriate location for such usage. The use of tmpfs makes sense in many occasions (eg. to prevent wear of SSD disks or to speedup small-temporary-files creation), but things like perf results using target files in /tmp on tmpfs happen everywhere and it's the user responsibility to make sure they use correct locations for certain workloads.

**Comment by chunfuwen** [comment]
Thank all for your responses.
Personally thinking,
One of  critical reasons Why linux kernel  make so successful is that it can keep kernel ABI compability.
Or why libvirt has value is to provide consistent and compatible API by abstracting underlying complexity. 
Considering the fact that users may not be well aware and notified before, therefore I suggest below two points:
1)In this time, we fix it by coding to avoid breakage,and enable users with transition time to migrate to data_dir if needed
2)Explicitly declare it may run risk if still use tmp_dir for image with direct access, suggest use data_dir instead or configure tmp_dir.

Welcome your feedback

**Comment by luckyh** [comment]
@chunfuwen

> @luckyh
> quote "thus users are required to be aware of the limitation if they do need to use tmp_dir as the image pool to put images in."
> May I ask when and how users are notified to be aware of this limitation?

Unfortunately it fully depends on whether users understand about the tmpdir implementation of Linux distributions, neither the Python [1] nor C [2] API's doc mentions about that. But indeed it'd be helpful by leaving a note there since we've already seen few cases. Would you mind to help update the doc?

[1] https://docs.python.org/3.9/library/tempfile.html?highlight=tempfile#tempfile.mkdtemp
[2] https://man7.org/linux/man-pages/man3/mkdtemp.3.html

> 2)Balamuruhan S [bala24@linux.vnet.ibm.com](mailto:bala24@linux.vnet.ibm.com) submited one patch around 2018 (commit id :6a78795ddb63a7c39262188893a5b2223edf46dd)to make data_dir.get_tmp_dir() compatible on Ubuntu(allow put image there),

Looks like another issue. Anyway I don't think it's a proper fix because `/var/lib/libvirt/images` is not a kind of tmpdir for the general proposal of temp files in Ubuntu, and even worse for qemu testing `FileNotFoundError` could be raised since libvirt may not be installed on host.

**Comment by luckyh** [comment]
> Considering the fact that users may not be well aware or notified before, therefore I suggest below two points:
> 1)In this time, we fix it by coding to avoid breakage,and enable users with transition time to migrate to data_dir if needed
> 2)Explicitly declare it may run risk if still use tmp_dir for image with direct access, suggest use data_dir instead or configure tmp_dir.

Since as I mentioned in previous comments `tmp_dir` is already configurable (in multiple ways) thus I don't feel it is worth to apply another workaround by hardcoding the base path. For the point 2, I'll be agree if it's necessary, thanks.

**Comment by chunfuwen** [comment]
> get_tmp_dir



> @chunfuwen
> 
> > @luckyh
> > quote "thus users are required to be aware of the limitation if they do need to use tmp_dir as the image pool to put images in."
> > May I ask when and how users are notified to be aware of this limitation?
> 
> Unfortunately it fully depends on whether users understand about the tmpdir implementation of Linux distributions, neither the Python [1] nor C [2] API's doc mentions about that. But indeed it'd be helpful by leaving a note there since we've already seen few cases. Would you mind to help update the doc?
> 
> [1] https://docs.python.org/3.9/library/tempfile.html?highlight=tempfile#tempfile.mkdtemp
> [2] https://man7.org/linux/man-pages/man3/mkdtemp.3.html
> 
> > 2)Balamuruhan S [bala24@linux.vnet.ibm.com](mailto:bala24@linux.vnet.ibm.com) submited one patch around 2018 (commit id :6a78795ddb63a7c39262188893a5b2223edf46dd)to make data_dir.get_tmp_dir() compatible on Ubuntu(allow put image there),
> 
> Looks like another issue. Anyway I don't think it's a proper fix because `/var/lib/libvirt/images` is not a kind of tmpdir for the general proposal of temp files in Ubuntu, and even worse for qemu testing `FileNotFoundError` could be raised since libvirt may not be installed on host.

@luckyh 
if `/var/lib/libvirt/images` is not applicable to qemu, '/var/tmp' or ''/var/lib can be candidate folder.

**Comment by chunfuwen** [comment]
@sathnaga
May I have your opinion?

**Comment by smitterl** [comment]
> Thank all for your responses.
> Personally thinking,
> One of critical reasons Why linux kernel make so successful is that it can keep kernel ABI compability.
> Or why libvirt has value is to provide consistent and compatible API by abstracting underlying complexity.
> Considering the fact that users may not be well aware or notified before, therefore I suggest below two points:
> 1)In this time, we fix it by coding to avoid breakage,and enable users with transition time to migrate to data_dir if needed
> 2)Explicitly declare it may run risk if still use tmp_dir for image with direct access, suggest use data_dir instead or configure tmp_dir.
> 
...
> @luckyh
> if `/var/lib/libvirt/images` is not applicable to qemu, '/var/tmp' or ''/var/lib can be candidate folder.

I don't know if I understand the full discussion but to me this looks like this path is more of a libvirt-specific issue. So going forward with configuring the tmp_dir in vt.conf make sense for me. In order to make sure that we don't forget about moving to data_dir in the long term we can do some documentation like https://github.com/avocado-framework/avocado-vt/compare/master...smitterl:tmp_dir?expand=1

I don't know if there are other places. If there was a review / code-style guide in avocado vt, a mention of this could be useful, too.

**Comment by smitterl** [comment]
> > Thank all for your responses.
> > Personally thinking,
> > One of critical reasons Why linux kernel make so successful is that it can keep kernel ABI compability.
> > Or why libvirt has value is to provide consistent and compatible API by abstracting underlying complexity.
> > Considering the fact that users may not be well aware or notified before, therefore I suggest below two points:
> > 1)In this time, we fix it by coding to avoid breakage,and enable users with transition time to migrate to data_dir if needed
> > 2)Explicitly declare it may run risk if still use tmp_dir for image with direct access, suggest use data_dir instead or configure tmp_dir.
> 
> ...
> 
> > @luckyh
> > if `/var/lib/libvirt/images` is not applicable to qemu, '/var/tmp' or ''/var/lib can be candidate folder.
> 
> I don't know if I understand the full discussion but to me this looks like this path is more of a libvirt-specific issue.
> Therefore, going forward with configuring the tmp_dir in vt.conf make sense for me as short term solution. As a compromise and in order to make sure that we don't forget about moving to data_dir in the long term, we can do some documentation like https://github.com/avocado-framework/avocado-vt/compare/master...smitterl:tmp_dir?expand=1
> 
> I don't know if there are other places. If there was a review / code-style guide in avocado vt, a mention of this could be useful, too.

Created https://github.com/avocado-framework/avocado-vt/pull/2999 based on this after first :thumbsup:

**Pull request closed without merging**
