### PR TITLE
ConfigParser: Removed py2 support

### PR DESCRIPTION
**Pull request by bskjois**
Signed-off-by: Kowshik Jois B S <kowsjois@linux.ibm.com>

### CODE REVIEW

**Comment by xiaodwan** [comment]
@bskjois Please fix the static checks issue. The changes look great to me.

**Comment by bskjois** [comment]
@xiaodwan @chloerh 
Even after trying multiple (more than 15) times also I am unable to fix the static issue on few of the files. Whatever the way I try, it still says imports are not sorted/formatted. 
Could you please help me out here?

**Comment by chloerh** [comment]
Hi @bskjois 
You could try `isort  --profile black .` which would fix the import sorting errors.

**Comment by bskjois** [comment]
Thank you @chloerh

I had tried that command earlier too! But it says "unrecognized arguments: --profile"

Even in isort commad's usage, I don't see profile. Looks like it has been removed or so. Could you please confirm.

`kowshik:avocado-vt$ isort --profile black .
usage: isort [-h] [-a ADD_IMPORTS] [-ac] [-af] [-b KNOWN_STANDARD_LIBRARY]
             [-c] [-ca] [-cs] [-d] [-df] [-ds] [-dt] [-e]
             [-f KNOWN_FUTURE_LIBRARY] [-fas] [-fass] [-ff FROM_FIRST]
             [-fgw [FORCE_GRID_WRAP]] [-fss] [-i INDENT] [-j JOBS] [-k]
             [-l LINE_LENGTH] [-lai LINES_AFTER_IMPORTS]
             [-lbt LINES_BETWEEN_TYPES] [-le LINE_ENDING] [-ls]
             [-m {0,1,2,3,4,5,6,7}] [-nis] [-nlb NO_LINES_BEFORE]
             [-ns NOT_SKIP] [-o KNOWN_THIRD_PARTY] [-ot]
             [-p KNOWN_FIRST_PARTY] [-q] [-r] [-rm REMOVE_IMPORTS] [-rr] [-rc]
             [-s SKIP] [-sd DEFAULT_SECTION] [-sg SKIP_GLOB] [-sl]
             [-sp SETTINGS_PATH] [-t FORCE_TO_TOP] [-tc] [-up] [-v] [-vb]
             [--virtual-env VIRTUAL_ENV] [--conda-env CONDA_ENV] [-vn]
             [-w LINE_LENGTH] [-wl WRAP_LENGTH] [-ws] [-y] [--unsafe]
             [--case-sensitive] [--filter-files]
             [files [files ...]]
isort: error: unrecognized arguments: --profile
kowshik:avocado-vt$`


`kowshik:avocado-vt$ isort --profile black virttest/asset.py 
usage: isort [-h] [-a ADD_IMPORTS] [-ac] [-af] [-b KNOWN_STANDARD_LIBRARY]
             [-c] [-ca] [-cs] [-d] [-df] [-ds] [-dt] [-e]
             [-f KNOWN_FUTURE_LIBRARY] [-fas] [-fass] [-ff FROM_FIRST]
             [-fgw [FORCE_GRID_WRAP]] [-fss] [-i INDENT] [-j JOBS] [-k]
             [-l LINE_LENGTH] [-lai LINES_AFTER_IMPORTS]
             [-lbt LINES_BETWEEN_TYPES] [-le LINE_ENDING] [-ls]
             [-m {0,1,2,3,4,5,6,7}] [-nis] [-nlb NO_LINES_BEFORE]
             [-ns NOT_SKIP] [-o KNOWN_THIRD_PARTY] [-ot]
             [-p KNOWN_FIRST_PARTY] [-q] [-r] [-rm REMOVE_IMPORTS] [-rr] [-rc]
             [-s SKIP] [-sd DEFAULT_SECTION] [-sg SKIP_GLOB] [-sl]
             [-sp SETTINGS_PATH] [-t FORCE_TO_TOP] [-tc] [-up] [-v] [-vb]
             [--virtual-env VIRTUAL_ENV] [--conda-env CONDA_ENV] [-vn]
             [-w LINE_LENGTH] [-wl WRAP_LENGTH] [-ws] [-y] [--unsafe]
             [--case-sensitive] [--filter-files]
             [files [files ...]]
isort: error: unrecognized arguments: --profile`

**Review by xiaodwan — APPROVED** [review]

**Comment by bskjois** [comment]
@chloerh I understood what was missing. Instead of using the **isort** command downloaded via **pip3**, I was using the one which was downloaded with **dnf**. Now I used the **pip3** one and all the checks are successful.

**Review by chloerh — APPROVED** [review]

**Pull request merged**
