### PR TITLE
env_process: Refactor storage setup/cleanup into a Setuper

### PR DESCRIPTION
**Pull request by bgartzi**
This patch refactors the VM storage setup and cleanup steps out from the pre- and post-process functions on `env_process.py` into a `Setuper` subclass.

ID: 1970

### CODE REVIEW

**Comment by bgartzi** [comment]
Hi @YongxueHong, @qingwangrh could you help me review this and bring anyone affected by this into the discussion? Thanks!

Apart from that, I'm refactoring 'iscsi', 'lvm' and 'nfs' setup/cleanup into the same `Setuper` subclass `StorageConfig`, as all of them depend on the `'storage_type'` parameter. If you would rather have each of them in a dedicated `Setuper` subclass, please let me know. However, they would be mutually exclusive, as IIUC, `'storage_type'` will just hold one value.

**Comment by YongxueHong** [comment]
CC @zhencliu

**Comment by qingwangrh** [comment]
@bgartzi could you please evaluate this change whether impacts the existing case explicitly or transparently?

**Comment by bgartzi** [comment]
Hi @qingwangrh, there are no logic changes intended with this MR.  That is, existing test cases shouldn't be affected. At least, intentionally.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by qingwangrh** [comment]
@bgartzi Please help to check it

(workspace) root@dell-per430-29 /home/kar/avocado-vt $ git apply 3853.patch -v
Checking patch virttest/env_process.py...
error: while searching for:
from virttest import qemu_storage
from virttest import data_dir
from virttest import utils_net
from virttest import nfs
from virttest import utils_test
from virttest import utils_iptables
from virttest import utils_package

error: patch failed: virttest/env_process.py:36
error: virttest/env_process.py: patch does not apply
Checking patch virttest/test_setup/storage.py...

**Pull request merged**
