### PR TITLE
shared: Drop EOL Fedora/RHEL/JeOS kickstarts and configs

### PR DESCRIPTION
**Pull request by eskultety**
These have been out of support for a long time so any old configs can be
dropped from the repo. JeOS-23+ wasn't removed since these images are
still available as assets on the avocado project website.

Signed-off-by: Erik Skultety <eskultet@redhat.com>

### CODE REVIEW

**Comment by clebergnu** [comment]
@eskultety don't get too attached to the fact that the JeOS 23+ images are available for download.  I'd like to start the deprecation process by removing them from the guest definitions, and then follow up with the removal of the images.

**Comment by eskultety** [comment]
> @eskultety don't get too attached to the fact that the JeOS 23+ images are available for download. I'd like to start the deprecation process by removing them from the guest definitions, and then follow up with the removal of the images.

I agree that those images are old, but I didn't want to touch them as I didn't know how much of a use case you have for them right now and it would take me considerably more time, so I went with the easy way out. On the other hand, I think we can approach the cleanup in a gradual manner, IOW I'm removing a bunch of configs which should not collide with anything so should be safe to merge and we can then continue with a much thorough cleanup, or am I mistaken?

**Comment by clebergnu** [comment]
@eskultety sure it can be tackled in a separate commit/PR.  It's just that, the left over removal may fall into oblivion if we don't act now, or create a tracker for such a task... 

Anyway, I just thought I'd let you know of my intentions to remove them, and this seems to be the right time to do away with their definitions.  Let me know if you want to handle that, if not, I can send a PR (because it's just as much energy as creating a tracker for that task).

Thanks!

**Comment by eskultety** [comment]
@clebergnu feel free to go ahead with the cleanup, I understand your point, but I have enough on my plate already, so if you want to tackle everything in one go, I'm okay with that. I have a couple of tweaks to the remaining kickstarts in mind, so I can wait until the cleanup is taken care of in the proper manner and then send a follow up PR.

**Comment by clebergnu** [comment]
@eskultety OK, sent https://github.com/avocado-framework/avocado-vt/pull/2086

**Comment by ldoktor** [comment]
@eskultety you removed the `Fedora-25.ks` that is still used by F28...

**Comment by ldoktor** [comment]
... next time please make sure at least the latest Fedora is installable after your changes.

**Pull request merged**
