### PR TITLE
qemu_monitor: Introduce "query_cpu_model_expansion" in QMPMonitor

### PR DESCRIPTION
**Pull request by PaulYuuu**
"query-cpu-model-expansion" will return all properties with the provided
CPU model, add it in QMPMonitor and then we can query which features are
supported of the specific CPU model.

ID: 1970784, 1970785, 1970786
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
Hello @luckyh , would you help review? Thanks in advance.

**Review by luckyh — APPROVED** [review]
ACK

**Comment by PaulYuuu** [comment]
Attach test result of some cases:
```
 (1/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.sve_basic.arm64-pci: PASS (402.63 s)
 (2/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.sve_basic.unsupported_length.arm64-pci: PASS (43.86 s)
 (3/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.sve_basic.unsupported_length.invalid_length.arm64-pci: PASS (8.33 s)
```

**Comment by zhenyzha** [comment]
git am 3094.patch
Applying: qemu_monitor: Introduce query_cpu_model_expansion in QMPMonitor

git am 2854.patch
Applying: Add some basic test cases of SVE

python3 ConfigTest.py --guestname=RHEL.8.5.0 --platform=aarch64 --machines=arm64-pci --driveformat=virtio_scsi --nicmodel=virtio_net --mem=8192 --vcpu=8 --testcase=boot

```
(1/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.sve_basic.arm64-pci: PASS (309.38 s)
 (2/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.sve_basic.unsupported_length.arm64-pci: PASS (39.21 s)
 (3/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.sve_basic.unsupported_length.invalid_length.arm64-pci: PASS (8.07 s)
```
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Comment by luckyh** [comment]
Thanks to all.

**Pull request merged**
