### PR TITLE
Shared: add xml and cfg for Win2016 installation

### PR DESCRIPTION
**Pull request by aliang123**
shared.unattended:
1.add win2016-autounattend.xml
2.add win2016-autounattend_ovmf.xml

shared.cfg.guest-os.Windows:
1.add Win2016.cfg
2.add x86_64.cfg under folder "Win2016"

Signed-off-by: Aihua Liang<aliang@redhat.com>

ID:1398079

### CODE REVIEW

**Comment by aliang123** [comment]
Test cmd: 
   python ConfigTest.py --guestname=Win2016 --platform=x86_64 --verbose=yes --testcase=unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native

Test Result:
   PASS 1-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native

**Comment by suqinhuang** [comment]
ack

**Comment by CongLi** [comment]
@aliang123 

Please check the comment in internal, I'm not sure where is the problem.

Thanks.

**Comment by CongLi** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by xutian** [comment]
Thanks @aliang123 @CongLi and @suqinhuang

**Pull request merged**
