### PR TITLE
net/if.py: refactor module

### PR DESCRIPTION
**Pull request by nickzhq**
Refactor the utils_net.py:
1. Split net/if module from utils_net module.

### CODE REVIEW

**Comment by nickzhq** [comment]
@zhencliu @luckyh @YongxueHong  Please take a review, thanks!

**Comment by nickzhq** [comment]
@YongxueHong Please take a review, thanks!

**Comment by chloerh** [comment]
Hi, I found there are 2 `gen_ipv4_addr` functions in virttest and traced back to this pr. I was wondering that are we going to keep both of the functions? Thanks.

**Comment by YongxueHong** [comment]
> Hi, I found there are 2 `gen_ipv4_addr` functions in virttest and traced back to this pr. I was wondering that are we going to keep both of the functions? Thanks.

Hi @chloerh 
Yeah, indeed, it looks like redandunt, but there are lots of calling places need to update, so we separate this task, firstly we will keep both at the same time for a while, and than plan to update the existing functionality with the new module within proper time in the future.  We prefer to use the this module's API for your case. 
Thanks.

**Comment by chloerh** [comment]
@YongxueHong  Thanks for your clarification!
Currently, it seems these modules are not being used by tp-qemu or tp-libvirt. And the code in utils_net keeps changing since then.
So it would be really helpful to be notified when the switch happens. Thanks in advance.

**Comment by YongxueHong** [comment]
> @YongxueHong Thanks for your clarification! Currently, it seems these modules are not being used by tp-qemu or tp-libvirt. And the code in utils_net keeps changing since then. So it would be really helpful to be notified when the switch happens. Thanks in advance.

Hi @chloerh 
Thanks for the kind reminder. We will double-check the `utils_net` with the latest code to keep the consistency when we replace it.

**Pull request merged**
