### PR TITLE
qemu_storage: updated to display qemu-img check cmd and its output

### PR DESCRIPTION
**Pull request by hereischen**
id: 1524774
Signed-off-by: Haotong Chen <hachen@redhat.com>

### CODE REVIEW

**Comment by hereischen** [comment]
Checking image file /home/kvm_autotest_root/images/rhel74-64-virtio-scsi.qcow2
Run qemu-img info comamnd on /home/kvm_autotest_root/images/rhel74-64-virtio-scsi.qcow2
Running: /bin/qemu-img info -U /home/kvm_autotest_root/images/rhel74-64-virtio-scsi.qcow2
Image check output:
image: /home/kvm_autotest_root/images/rhel74-64-virtio-scsi.qcow2
file format: qcow2
virtual size: 20G (21474836480 bytes)
disk size: 4.2G
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: false
    refcount bits: 16
    corrupt: false

**Comment by CongLi** [comment]
IMO, it's better to print it in postprocess().
        else:
            image_info_output = image.info()
            image_info = {}
            if image_info_output is not None:

Thanks.

**Comment by hereischen** [comment]
Running '/bin/qemu-img info -U /home/kvm_autotest_root/images/rhel74-64-virtio-scsi.qcow2'
[stdout] image: /home/kvm_autotest_root/images/rhel74-64-virtio-scsi.qcow2
[stdout] file format: qcow2
[stdout] virtual size: 20G (21474836480 bytes)
[stdout] disk size: 4.2G
[stdout] cluster_size: 65536
[stdout] Format specific information:
Command '/bin/qemu-img info -U /home/kvm_autotest_root/images/rhel74-64-virtio-scsi.qcow2' finished with 0 after 0.106745004654s
[stdout]     compat: 1.1
[stdout]     lazy refcounts: false
[stdout]     refcount bits: 16
[stdout]     corrupt: false

**Comment by CongLi** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Pull request merged**
