### PR TITLE
virttest.utils_test: add remote VM manager

### PR DESCRIPTION
**Pull request by kylazhang**
Add remote vm manager to implement remote vm access, ip check and commands running in vm

### CODE REVIEW

**Comment by lmr** [comment]
Please fix:

    /home/travis/build/avocado-framework/avocado-vt/virttest/utils_test/__init__.py:1975:61: E128 continuation line under-indented for visual indent

**Comment by lmr** [comment]
The commit message here is not helpful either. Please add a descriptive commit message.

**Comment by kylazhang** [comment]
Thanks, fixed

**Comment by PandaWei** [comment]
A lot of codes in this patch is same or similar as codes in /virttest/remote.py.

**Comment by PandaWei** [comment]
Do we really need this new class？
Even so,  It's better to reuse or  do some integrated work  for the codes in /virttest/remote.py

**Comment by kylazhang** [comment]
@PandaWei  It has already called remote.RemoteRunner in the class for our usage, and I do not find ssh-key generate related steps in remote.py. In this class we just want to make our common call more easily

**Comment by will-Do** [comment]
@lmr 
As @kylazhang is on maternity leave, and we are planning to fix some migration cases which base on this patch, so we would like to merge this patch first. And I will raise a new patch to check the exist of id_rsa you mentioned above,  what do you think?

**Comment by lmr** [comment]
@will-Do, well, OK I guess.

**Comment by lmr** [comment]
@will-Do merged, please send the PR update.

**Comment by will-Do** [comment]
@lmr 
Thanks, just raise a new patch: https://github.com/avocado-framework/avocado-vt/pull/301

**Pull request merged**
