### PR TITLE
utils_v2v: Add windows VM init function

### PR DESCRIPTION
**Pull request by will-Do**
Move this function from test case as it's more like a common function,
so other cases which need boot windows guest can reuse it.

Signed-off-by: Yanbing Du <ydu@redhat.com>

### CODE REVIEW

**Comment by will-Do** [comment]
Corresponding tp-libvirt patch: autotest/tp-libvirt#639

**Comment by lmr** [comment]
/home/travis/build/avocado-framework/avocado-vt/virttest/utils_v2v.py:576:5: E303 too many blank lines (2)

Please fix the problem, thanks!

**Comment by lmr** [comment]
Please fix the typos mentioned and re-submit, we should be good from there, thanks!

**Comment by will-Do** [comment]
@lmr 
Thanks, update these sentences according to your comments.

**Pull request merged**
