### PR TITLE
Remove parameters of file_transfer in Linux.cfg and Windows.cfg

### PR DESCRIPTION
**Pull request by PaulYuuu**
Move the specific parameters of test cases into tp-qemu.

ID: 1987211
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
LGTM

Waiting for tp-qemu be updated accordingly ~

**Review by yanan-fu — APPROVED** [review]
Ack

**Comment by yanan-fu** [comment]
@luckyh  Could you help review ? Thanks!

**Comment by luckyh** [comment]
https://github.com/autotest/tp-qemu/pull/2943

**Review by luckyh — APPROVED** [review]
LGTM

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
