### PR TITLE
image_boot: use lazy assignment for image_boot

### PR DESCRIPTION
**Pull request by ybduan**
Change to use lazy assignment for variable image_boot to support
modifying its value in case level.

ID: 1781445
Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
Tested with virtio-blk, the related cases are all passed.

(1/9) Host_RHEL.m8.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios_strict.on: PASS (456.05 s)
 (2/9) Host_RHEL.m8.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios_strict.on.q35: PASS (456.08 s)
 (3/9) Host_RHEL.m8.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios_strict.off: PASS (98.79 s)
 (4/9) Host_RHEL.m8.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios_strict.off.q35: PASS (98.77 s)
 (5/9) Host_RHEL.m8.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.ide_cd.with_bootindex: PASS (53.41 s)
 (6/9) Host_RHEL.m8.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.ahci_cd.with_bootindex: PASS (32.59 s)
 (7/9) Host_RHEL.m8.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.ahci_cd.with_bootindex.q35: PASS (32.56 s)
 (8/9) Host_RHEL.m8.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.scsi_cd.with_bootindex: PASS (48.88 s)
 (9/9) Host_RHEL.m8.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.scsi_cd.with_bootindex.q35: PASS (32.58 s)

LGTM,
Acked-by xuwei@redhat.com

**Comment by ybduan** [comment]
> do we see any issues?, because code already handles for the older qemu and newer qemu cases,
> something like this
> 
> ```
>       if "[,boot=on|off]" not in self.get_help_text():
>             if boot in ('yes', 'on', True):
>                 bootindex = "1"
>             boot = None
> ```
> 
> and it handles individually for all drives,

Yes, we meet issue when running following test.
# python ConfigTest.py --testcase=seabios_strict.off --platform=x86_64 --guestname=RHEL.7.8 --driveformat=virtio_blk --clone=no
 (1/1) Host_RHEL.m7.u8.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.seabios_strict.off: ERROR: VM creation command failed:    "MALLOC_PERTURB_=1  /usr/libexec/qemu-kvm -S  -name 'avocado-vt-vm1'  -sandbox on  -machine pc  -nodefaults -device VGA,bus=pci.0,addr=0x2 -m 7168  -smp 4,maxcpus=4,cores=2,threads=1,sockets=2  -cpu 'IvyBridge',+kvm_pv_unhal... (4.62 s)

ERROR| ERROR 1-Host_RHEL.m7.u8.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.seabios_strict.off -> VMCreateError: VM creation command failed:    "MALLOC_PERTURB_=1  /usr/libexec/qemu-kvm -S  -name 'avocado-vt-vm1'  -sandbox on  -machine pc  -nodefaults -device VGA,bus=pci.0,addr=0x2 -m 7168  -smp 4,maxcpus=4,cores=2,threads=1,sockets=2  -cpu 'IvyBridge',+kvm_pv_unhalt  -chardev socket,id=qmp_id_qmpmonitor1,path=/var/tmp/avocado_dgDh7E/monitor-qmpmonitor1-20200109-170305-rROwLADW,server,nowait -mon chardev=qmp_id_qmpmonitor1,mode=control  -chardev socket,id=qmp_id_catch_monitor,path=/var/tmp/avocado_dgDh7E/monitor-catch_monitor-20200109-170305-rROwLADW,server,nowait -mon chardev=qmp_id_catch_monitor,mode=control -device pvpanic,ioport=0x505,id=id9uW9hX -chardev socket,path=/var/tmp/avocado_dgDh7E/serial-serial0-20200109-170305-rROwLADW,nowait,id=chardev_serial0,server -device isa-serial,id=serial0,chardev=chardev_serial0  -chardev socket,id=seabioslog_id_20200109-170305-rROwLADW,path=/var/tmp/avocado_dgDh7E/seabios-20200109-170305-rROwLADW,server,nowait -device isa-debugcon,chardev=seabioslog_id_20200109-170305-rROwLADW,iobase=0x402 -device nec-usb-xhci,id=usb1,bus=pci.0,addr=0x3 -drive id=drive_stg,if=none,snapshot=off,aio=threads,cache=none,format=qcow2,file=/home/kvm_autotest_root/images/stg.qcow2 -device virtio-blk-pci,id=stg,drive=drive_stg,bootindex=1,bus=pci.0,addr=0x4 -device virtio-net-pci,mac=9a:38:cf:df:f3:fd,bootindex=2,id=idNic1,netdev=idIBwy73,bus=pci.0,addr=0x5  -netdev tap,id=idIBwy73,vhost=on,vhostfd=19,fd=15 -drive id=drive_test,if=none,snapshot=off,aio=threads,cache=none,media=cdrom,file=/tmp/test.iso -device ide-cd,id=test,drive=drive_test,bootindex=1,bus=ide.0,unit=0 -device usb-tablet,id=usb-tablet1,bus=usb1.0,port=1  -vnc :0  -rtc base=utc,clock=host,driftfix=slew  -boot menu=on,strict=off,order=cdn,once=c -enable-kvm  -device sga"    (status: 1,    output: 'qemu-kvm: -device ide-cd,id=test,drive=drive_test,bootindex=1,bus=ide.0,unit=0: The bootindex 1 has already been used')

**Comment by ybduan** [comment]
Mixing using 'image_boot' globally and 'bootindex' in test case may lead to bootindex conflict when with virtio_blk driveformat like I have explained in https://github.com/avocado-framework/avocado-vt/pull/2372#issue-351201035

**Comment by ybduan** [comment]
(1/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios_strict.on: PASS (456.26 s)
 (2/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios_strict.off: PASS (98.33 s)
 (3/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.ide_cd.with_bootindex: PASS (52.95 s)
 (4/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.ahci_cd.with_bootindex: PASS (47.28 s)
 (5/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.scsi_cd.with_bootindex: PASS (47.26 s)

**Comment by ybduan** [comment]
Since it's hard to check the result on all platform, we use lazy assignment instead. Please help review again, thanks! @luckyh

**Comment by XueqiangWei** [comment]
Tested with virtio-blk, the related cases are all passed.

(01/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.ide_cd.with_bootindex: PASS (50.37 s)
 (02/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.ide_cd.with_specify_device: PASS (68.65 s)
 (03/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.ahci_cd.with_bootindex: PASS (55.56 s)
 (04/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.ahci_cd.with_bootindex.q35: PASS (53.45 s)
 (05/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.ahci_cd.with_specify_device: PASS (36.56 s)
 (06/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.ahci_cd.with_specify_device.q35: PASS (54.36 s)
 (07/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.scsi_cd.with_bootindex: PASS (55.30 s)
 (08/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.scsi_cd.with_bootindex.q35: PASS (50.81 s)
 (09/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.scsi_cd.with_specify_device: PASS (36.89 s)
 (10/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.cdrom.scsi_cd.with_specify_device.q35: PASS (54.21 s)
 (11/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.ide_disk.with_bootindex: PASS (39.47 s)
 (12/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.ide_disk.with_specify_device: PASS (36.17 s)
 (13/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.ahci_disk.with_bootindex: PASS (37.81 s)
 (14/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.ahci_disk.with_bootindex.q35: PASS (50.15 s)
 (15/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.ahci_disk.with_specify_device: PASS (36.19 s)
 (16/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.ahci_disk.with_specify_device.q35: PASS (53.52 s)
(17/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.virtio_blk_disk.with_bootindex: PASS (37.48 s)
 (18/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.virtio_blk_disk.with_bootindex.q35: PASS (37.91 s)
 (19/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.virtio_blk_disk.with_specify_device: PASS (53.79 s)
 (20/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.virtio_blk_disk.with_specify_device.q35: PASS (53.32 s)
 (21/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.scsi_hd_disk.with_bootindex: PASS (54.95 s)
 (22/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.scsi_hd_disk.with_bootindex.q35: PASS (37.38 s)
 (23/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.scsi_hd_disk.with_specify_device: PASS (53.78 s)
 (24/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.scsi_hd_disk.with_specify_device.q35: PASS (36.58 s)
 (25/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.usb_storage_disk.usb_uhci.with_bootindex: PASS (37.64 s)
 (26/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.usb_storage_disk.usb_uhci.with_bootindex.q35: PASS (37.96 s)
 (27/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.usb_storage_disk.usb_uhci.with_specify_device: PASS (68.93 s)
 (28/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.usb_storage_disk.usb_uhci.with_specify_device.q35: PASS (51.52 s)
 (29/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.usb_storage_disk.usb_ehci.with_bootindex: PASS (38.22 s)
 (30/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.usb_storage_disk.usb_ehci.with_bootindex.q35: PASS (54.83 s)
 (31/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.usb_storage_disk.usb_ehci.with_specify_device: PASS (51.38 s)
 (32/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.usb_storage_disk.usb_ehci.with_specify_device.q35: PASS (36.39 s)
 (33/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.usb_storage_disk.usb_xhci.with_bootindex: PASS (55.18 s)
 (34/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.usb_storage_disk.usb_xhci.with_bootindex.q35: PASS (37.81 s)
 (35/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.usb_storage_disk.usb_xhci.with_specify_device: PASS (54.02 s)
 (36/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot_from_device.usb_storage_disk.usb_xhci.with_specify_device.q35: PASS (35.81 s)
 (37/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios_strict.on: PASS (527.43 s)
 (38/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios_strict.on.q35: PASS (464.59 s)
 (39/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios_strict.off:PASS (107.30 s)
 (40/80) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios_strict.off.q35: PASS (107.19 s)

LGTM,
Acked-by xuwei@redhat.com

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
