### PR TITLE
Update Memory.__attributes__ to separate options for different backend

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1854713
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by huangyum** [comment]
@yanan-fu @vivianQizhu Please help review, thanks.

**Comment by yanan-fu** [comment]
@huangyum  Thanks for your explanation.
LGTM

Acked-by: Yanan Fu <yfu@redhat.com>

**Comment by vivianQizhu** [comment]
@huangyum Request for a test result, including regression test, thanks.

**Comment by huangyum** [comment]
@vivianQizhu I added the test results in the tp-qemu pr before. Copy here.

(1/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.hotplug_memory.after.guest_reboot.hotplug.backend_ram.no_policy.one: PASS (178.29 s)
(2/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.hotplug_memory.after.guest_reboot.hotplug.backend_ram.no_policy.two: PASS (178.37 s)
(3/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.hotplug_memory.after.guest_reboot.hotplug.backend_file.no_policy.one: PASS (178.68 s)
(4/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.hotplug_memory.after.guest_reboot.hotplug.backend_file.no_policy.two: PASS (178.07 s)

(1/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cpu_device_hotpluggable.hotplug.multi_vcpu.with_numa: PASS (83.41 s)
(2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.cpu_device_hotpluggable.hotplug.multi_vcpu.with_numa: PASS (160.32 s)

(1/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.balloon_memhp.backend_ram: PASS (173.79 s)
(2/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.balloon_memhp.backend_file: PASS (160.50 s)
(3/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.balloon_memhp.backend_ram: PASS (553.17 s)
(4/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.balloon_memhp.backend_file: PASS (436.01 s)

**Comment by vivianQizhu** [comment]
Thanks @huangyum @yanan-fu

**Pull request merged**
