### PR TITLE
[V6] Merge avocado-vt with virt-test

### PR DESCRIPTION
**Pull request by lmr**
Merge virt-test inside avocado-vt. This involves picking up virt-test's entire history and bringing it to avocado-vt.

Instructions on how to test it can be found here:

https://github.com/avocado-framework/avocado-vt/blob/0a7aedc34ee84157206b4a56f255a0827744166f/README.rst

Changes from v5:
* Updated the documentation to make references to `avocado` instead of `virt-test` and the old virt-test runner, as @adereis pointed out it was missing from this work.

Changes from v4:
* Now the tests report correctly their status, they were not doing that correctly so as @adereis pointed out during testing. In order to fix that, we did reintroduce the dependency on autotest, but it's small, contained, and eventually we can get rid of it. A good test for the correct reporting is:

    $ avocado run type_specific.io-github-autotest-qemu.qemu_cpu.cpuid

Changes from v3:
* Removed a mistaken commit that butchered the subdir `shared`, causing bootstrap to fail. Pointed out by @adereis during testing.

Changes from v1, v2:
* Completely rebased the branch and moved avocado-vt to a subdir instead of virt-test
* Fixed the security problems described in https://trello.com/c/YvSmaKD5/449-bug-insecure-usage-of-tmp-in-avocado-vt-virt-test

Changes from V0:
* Consolidated the last commits, making them more cohesive and easy to follow.

### CODE REVIEW

**Comment by ldoktor** [comment]
One more problem with the bootstrap. First run recommended running `avocado vt-bootstrap`. After doing so, avocado-vt is still unusable, because `EnvironmentError: 'include subtests.cfg' (/home/medic/avocado/data/avocado-vt/backends/qemu/cfg/tests-shared.cfg:14): file does not exist or it's not a regular file`.

**Comment by ldoktor** [comment]
@lmr this was needed before I was available to execute `avocado list` successfully:

```patch
diff --git a/avocado/core/plugins/virt_test_bootstrap.py b/avocado/core/plugins/virt_test_bootstrap.py
index cc433ea..30a9b48 100644
--- a/avocado/core/plugins/virt_test_bootstrap.py
+++ b/avocado/core/plugins/virt_test_bootstrap.py
@@ -26,12 +26,6 @@ from virttest.standalone_test import SUPPORTED_TEST_TYPES
 _PROVIDERS_DOWNLOAD_DIR = os.path.join(data_dir.get_test_providers_dir(),
                                        'downloads')
 
-if len(os.listdir(_PROVIDERS_DOWNLOAD_DIR)) == 0:
-    raise EnvironmentError("Bootstrap missing. "
-                           "Execute 'avocado vt-bootstrap' or disable this "
-                           "plugin to get rid of this message")
-
-
 class VirtBootstrap(plugin.Plugin):
 
     """
diff --git a/virttest/bootstrap.py b/virttest/bootstrap.py
index cbf46cd..7cea5bc 100644
--- a/virttest/bootstrap.py
+++ b/virttest/bootstrap.py
@@ -409,7 +409,7 @@ def create_subtests_cfg(t_type):
     if not os.path.isdir(tmp_dir):
         os.makedirs(tmp_dir)
 
-    subtests_cfg = os.path.join(root_dir, 'backends', t_type, 'cfg',
+    subtests_cfg = os.path.join(data_dir.get_backend_dir(t_type), 'cfg',
                                 'subtests.cfg')
     subtests_file = open(subtests_cfg, 'w')
     subtests_file.write(
```

**Comment by ldoktor** [comment]
Hmm, I'm impressed, even the `keep_guest_running` works as expected. Good job, Lucas :smile:

**Comment by lmr** [comment]
Closing in favor of #37

**Pull request closed without merging**
