### PR TITLE
Python 3: Converts the old metaclass with six

### PR DESCRIPTION
**Pull request by hsmj1412**
Signed-off-by: Junxiang Li <junli@redhat.com>

### CODE REVIEW

**Comment by kylazhang** [comment]
seems this is the newer usage?
```
import six

@six.add_metaclass(Meta)
class MyClass(Base):
    pass
```

**Comment by kylazhang** [comment]
@hsmj1412 @chunfuwen

**Comment by chunfuwen** [comment]
@hsmj1412 
@kylazhang 

```
>>> import six
>>> class Base(object):
...     pass
... 
>>> class Meta(object):
...     pass
... 
>>> import six
>>> 
>>> @six.add_metaclass(Meta)
... class MyClass(Base):
...     pass
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.4/site-packages/six.py", line 847, in wrapper
    return metaclass(cls.__name__, cls.__bases__, orig_vars)
TypeError: object() takes no parameters
>>> 

```

**Comment by hsmj1412** [comment]
@kylazhang @chunfuwen Done

**Pull request merged**
