### PR TITLE
migration: Fix OSError

### PR DESCRIPTION
**Pull request by cliping**
Signed-off-by: cliping <lcheng@redhat.com>

### CODE REVIEW

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by Yingshun** [comment]
@cliping Please upload test results, thanks!

**Review by nanli1 — APPROVED** [review]

**Comment by cliping** [comment]
Before:
OSError: [Errno 22] Invalid argument

After:
(1/1) type_specific.io-github-autotest-libvirt.migration.migration_uri.network_data_transport.tcp.migrateuri.dest_host_ipv4.non_p2p: PASS (257.28 s)
RESULTS : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML : /var/lib/avocado/job-results/job-2022-11-21T10.20-d3fd126/results.html
JOB TIME : 257.95 s

**Comment by cliping** [comment]
> @cliping Please upload test results, thanks!

Uploaded. Thanks.

**Review by Yingshun — APPROVED** [review]

**Pull request merged**
