### PR TITLE
virttests: Uses the new logging namespace format

### PR DESCRIPTION
**Pull request by beraldoleal**
Because of recent logging changes in Avocado itself, let's follow suit
of commits adbfa5686 and b26e8032b.

Signed-off-by: Beraldo Leal <bleal@redhat.com>

### CODE REVIEW

**Comment by richtja** [comment]
> > Hi @beraldoleal thanks for this is definitely a step further. Do you planing to split the work into more PR or this is the full update? Because I can find a lot of modules which needs this change also, and I think we should do it all at once.
> 
> Yes, I was planning to split the work here and this it was just a quick-off. I kind of agree with you and I will add more changes here. However any help is welcome. :)

sure, I can go through and update those modules if you want :)

> 
> > Also, with this change, we should update the vt examples and template for tests.
> 
> I just sent a force-push with the changes.

thanks for the change, I think we should update the test template to show how the logging is working in avocado vt tests. Sometnig like:

```
--- a/examples/tests/template.py
+++ b/examples/tests/template.py
@@ -3,6 +3,7 @@
 # $ avocado run template --vt-type qemu to execute it.
 import logging
 
+LOG = logging.getLogger('avocado.test')
 
 def run(test, params, env):
     """
@@ -23,4 +24,4 @@ def run(test, params, env):
     timeout = float(params.get("login_timeout", 240))
     session = vm.wait_for_login(timeout=timeout)
     uptime = session.cmd("uptime")
-    logging.info("Guest uptime result is: %s", uptime)
+    LOG.info("Guest uptime result is: %s", uptime)

```
or
```
--- a/examples/tests/template.py
+++ b/examples/tests/template.py
@@ -1,7 +1,6 @@
 # :difficulty: simple
 # Put this file into $test_provider/tests directory and use
 # $ avocado run template --vt-type qemu to execute it.
-import logging
 
 
 def run(test, params, env):
@@ -23,4 +22,4 @@ def run(test, params, env):
     timeout = float(params.get("login_timeout", 240))
     session = vm.wait_for_login(timeout=timeout)
     uptime = session.cmd("uptime")
-    logging.info("Guest uptime result is: %s", uptime)
+    test.info("Guest uptime result is: %s", uptime)
```

**Comment by clebergnu** [comment]
I believe the same point raised by @richtja wrt test template, applies to the libraries: it's way better if apply a consistent style for the logging usage.  I understand it can take more work, but I believe it's doable.   What do you think?

**Comment by beraldoleal** [comment]
> I can do some testing with this soon if anyone of you is interested but I doubt I will be able to detect which files are missed and which are not just from the testing and can usually only spot the ones that we use and expect to see and still manually so without the best guarantee out there.

That is fine, any test is more than welcome.

@richtja just found an issue with this global variable and Python3.6 (only) not being able to pickle this. Looks like `virttests/utils_env.py` is trying to `cPickle.dump()` the global variables along with the VM object. We are still debugging.

**Review by richtja — APPROVED** [review]

**Comment by pevogam** [comment]
I will test post-merge since I didn't have spare cycles so I am no blocker here.

**Pull request closed without merging**
