### PR TITLE
[V8] Merge avocado-vt with virt-test

### PR DESCRIPTION
**Pull request by lmr**
Merge virt-test inside avocado-vt. This involves picking up virt-test's entire history and bringing it to avocado-vt.

Instructions on how to test it can be found here:

https://github.com/avocado-framework/avocado-vt/blob/0a7aedc34ee84157206b4a56f255a0827744166f/README.rst

Changes from v7:
* Re-created the branch once again, now *all* our changes to virt-tests were made post merge, virt-test was imported unmodified, granting us more flexibility to fix our modifications.
* Dropped the patches that attempted to fix the insecure `/tmp` files creation
* Updated dependencies on spec files and requirement files

Changes from v6:
* Fixed a couple of problems found by @ldoktor during his review, such as location of subtests.cfg file and asset restore.

Changes from v5:
* Updated the documentation to make references to `avocado` instead of `virt-test` and the old virt-test runner, as @adereis pointed out it was missing from this work.
* Added --yes-to-all to `vt-bootstrap`, per @adereis's request. Sorry, I forgot to put that into the previous PR's changelog.

Changes from v4:
* Now the tests report correctly their status, they were not doing that correctly so as @adereis pointed out during testing. In order to fix that, we did reintroduce the dependency on autotest, but it's small, contained, and eventually we can get rid of it. A good test for the correct reporting is:

    $ avocado run type_specific.io-github-autotest-qemu.qemu_cpu.cpuid

Changes from v3:
* Removed a mistaken commit that butchered the subdir `shared`, causing bootstrap to fail. Pointed out by @adereis during testing.

Changes from v1, v2:
* Completely rebased the branch and moved avocado-vt to a subdir instead of virt-test
* Fixed the security problems described in https://trello.com/c/YvSmaKD5/449-bug-insecure-usage-of-tmp-in-avocado-vt-virt-test

Changes from V0:
* Consolidated the last commits, making them more cohesive and easy to follow.

### CODE REVIEW

**Comment by ldoktor** [comment]
@clebergnu any objections or can I merge this?

**Comment by clebergnu** [comment]
@ldoktor I'm going through it. Hang on a while please!

**Comment by clebergnu** [comment]
Yep, ran a bunch of tests and things look to be in very good shape. Let me do the honors!

**Comment by lmr** [comment]
We did it! Thanks guys!

**Comment by clebergnu** [comment]
\0/

**Pull request merged**
