### PR TITLE
enforce_quit:Win8 guest lack of 'enforce' params to the cmd line

### PR DESCRIPTION
**Pull request by XueqiangWei**
removed "+sep", bug 821741 is fixed

### CODE REVIEW

**Comment by XueqiangWei** [comment]
ID: 1182917

**Comment by CongSmile** [comment]
Hi @XueqiangWei 

As we talked, could you please help check whether this problem still exist in RHEL.7 host?

Thanks.

**Comment by XueqiangWei** [comment]
Hi @CongSmile

Have checked, not hit this problem in RHEL.7 host

Thanks.

**Comment by CongSmile** [comment]
@XueqiangWei 

Thanks.

Acked-by: Cong Li <coli@redhat.com>

**Pull request merged**
