### PR TITLE
utils_misc:modify used_mem match pattern for win2008 guest

### PR DESCRIPTION
**Pull request by aliang123**
utils_misc:
1.modify pattern for used_mem match of win2008 guest.

Signed-off-by: Aihua Liang  <aliang@redhat.com>

ID:1396326

### CODE REVIEW

**Comment by aliang123** [comment]
ID:1396326

**Comment by CongLi** [comment]
It's better to set pattern 'In Use: (.+) MB' as a variant, and can set a separate param for Win2008.

**Comment by pingl2016** [comment]
After checked win7, win8, win10, win2008, win2008r2, win2012, win2012r2 and win2016, only win2008 display used memory as "Page File: In Use:    XXX MB", the other os display it as "Virtual Memory: In Use: X,XXX MB". Also there is no where else to use "In Use:" in the log of systeminfo on windows guest. So I think the code modification is acceptable.

Acked-by: Ping Li <pingl@redhat.com>

**Comment by ngu-niny** [comment]
After apply both patch https://github.com/autotest/tp-qemu/pull/826/ and this patch, following case works well:

PASS 1-smp_4.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2008.x86_64.sp2.io-github-autotest-qemu.balloon_check.balloon_evict.balloon-reboot

Acked-by: Nini Gu <ngu@redhat.com>

**Comment by aliang123** [comment]
Guest: Win8.1
  Test cmd:
      python ConfigTest.py --guestname=Win8..1 --platform=x86_64 --verbose=yes --testcase=balloon_check.balloon_evict
   Test Result:
  2-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win8.x86_64.1.io-github-autotest-qemu.balloon_check.balloon_evict.balloon-reboot' Finshed 2016-12-01 13:01:00 2016-12-01 13:08:52 PASS 472.401563
'3-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win8.x86_64.1.io-github-autotest-qemu.balloon_check.balloon_evict.balloon-shutdown' Finshed 2016-12-01 13:08:52 2016-12-01 13:13:28 PASS 275.808966
'4-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win8.x86_64.1.io-github-autotest-qemu.balloon_check.balloon_evict.balloon-stop_continue' Finshed 2016-12-01 13:13:28 2016-12-01 13:18:15 PASS 286.061595

Guest:Win2008
  Test cmd:
   python ConfigTest.py --guestname=Win2008..sp2 --platform=x86_64 --verbose=yes --testcase=balloon_check.balloon_evict.balloon-reboot
  Test Result:
     PASS 1-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2008.x86_64.sp2.io-github-autotest-qemu.balloon_check.balloon_evict.balloon-reboot

**Comment by xutian** [comment]
merged, thanks @aliang123

**Pull request merged**
