### PR TITLE
qemu_storage: Support host device in function filename_to_file_opts

### PR DESCRIPTION
**Pull request by YongxueHong**
ID: 1782159
Signed-off-by: Yongxue Hong yhong@redhat.com

### CODE REVIEW

**Comment by YongxueHong** [comment]
@luckyh  @zhencliu 
Please help me to review it if you are free, thanks.

**Comment by zhencliu** [comment]
LGTM

**Comment by qingwangrh** [comment]
python3 ConfigTest.py --testcase=block_with_share_rw.default.turn_on.passthrough --guestname=RHEL.8.2.0 --imageformat=qcow2 --driveformat=virtio_scsi --nicmodel=virtio_net --machines=i440fx --platform=x86_64 --customsparams="image_aio=native" --clone=no

 (1/2) Host_RHEL.m8.u1.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.block_with_share_rw.turn_on.with_scsi_block: PASS (56.66 s)
 (2/2) Host_RHEL.m8.u1.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.block_with_share_rw.turn_on.with_scsi_generic: PASS (54.36 s)


LGTM

**Comment by YongxueHong** [comment]
Regression testing:
python3 ConfigTest.py --guestname=RHEL.8.2 --platform=x86_64 --driveformat=virtio_scsi,virtio_blk --testcase=multi_disk
 (05/16) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.one_disk_repeat: PASS (113.69 s)
 (06/16) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.max_disk: PASS (1424.49 s)
 (07/16) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.with_virtio_scsi_TMF: PASS (1638.32 s)
 (08/16) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.all_drive_format_types: PASS (86.06 s)
 (09/16) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.one_disk_repeat: PASS (111.30 s)
 (10/16) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.max_disk: PASS (1335.14 s)
 (11/16) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.all_drive_format_types: PASS (85.95 s)
 (12/16) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block: PASS (151.14 s)
 (13/16) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic: PASS (150.50 s)
 (14/16) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_lun: PASS (1539.31 s)
 (15/16) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_scsiid_lun: PASS (8661.08 s)
 (16/16) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: PASS (708.19 s)

All cases are passed, didn't hit any regression issues.

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
