### PR TITLE
qdevices: Fix the missing of the detect-zeroes

### PR DESCRIPTION
**Pull request by YongxueHong**
There has been a regression issue since the patch https://github.com/avocado-framework/avocado-vt/pull/3710
This path's aim is to keep the original type of value for the `detect-zeroes`, not drop it from the blockdev options.

ID: 1320

### CODE REVIEW

**Comment by YongxueHong** [comment]
Hi @nickzhq @zhencliu @qingwangrh 
Would you like to help me to review it? Thanks a lot.

**Comment by qingwangrh** [comment]
refer to https://issues.redhat.com/browse/KVMAUTOMA-1320
the detect_zeroes only exist on the format node

  -blockdev '{"node-name": "file_stg1", "driver": "file", "auto-read-only": true, "discard": "ignore", "aio": "threads", "filename": "/home/kvm_autotest_root/images/stg1.qcow2", "cache": {"direct": true, "no-flush": false}, "detect-zeroes": "on"}' \
 -blockdev '{"node-name": "drive_stg1", "driver": "qcow2", "read-only": false, "cache": {"direct": true, "no-flush": false}, "file": "file_stg1", "detect-zeroes": "on", "discard": "ignore"}' \

**Comment by nickzhq** [comment]
> Hi @nickzhq @zhencliu @qingwangrh Would you like to help me to review it? Thanks a lot.

Ack.

**Comment by YongxueHong** [comment]
> refer to https://issues.redhat.com/browse/KVMAUTOMA-1320 the detect_zeroes only exist on the format node
> 
> -blockdev '{"node-name": "file_stg1", "driver": "file", "auto-read-only": true, "discard": "ignore", "aio": "threads", "filename": "/home/kvm_autotest_root/images/stg1.qcow2", "cache": {"direct": true, "no-flush": false}, "detect-zeroes": "on"}' -blockdev '{"node-name": "drive_stg1", "driver": "qcow2", "read-only": false, "cache": {"direct": true, "no-flush": false}, "file": "file_stg1", "detect-zeroes": "on", "discard": "ignore"}' \

Hi @qingwangrh 
Thanks for reminding, I added a commit to handle it https://github.com/avocado-framework/avocado-vt/pull/3771/commits/464643c9e34ebca12f4a875dc548656793486f1e
Please help to review it. Thanks a lot.

**Comment by qingwangrh** [comment]
the protocol node the discard always is unmap, it just affects the format node.


-blockdev '{"node-name": "file_stg1", "driver": "file", "auto-read-only": true, "discard": "ignore", "aio": "threads", "filename": "/home/kvm_autotest_root/images/stg1.qcow2", "cache": {"direct": true, "no-flush": false}}' \
-blockdev '{"node-name": "drive_stg1", "driver": "qcow2", "read-only": false, "cache": {"direct": true, "no-flush": false}, "file": "file_stg1", "detect-zeroes": "off", "discard": "ignore"}' \

other part looks good.

**Comment by YongxueHong** [comment]
> the protocol node the discard always is unmap, it just affects the format node.
> 
> -blockdev '{"node-name": "file_stg1", "driver": "file", "auto-read-only": true, "discard": "ignore", "aio": "threads", "filename": "/home/kvm_autotest_root/images/stg1.qcow2", "cache": {"direct": true, "no-flush": false}}' -blockdev '{"node-name": "drive_stg1", "driver": "qcow2", "read-only": false, "cache": {"direct": true, "no-flush": false}, "file": "file_stg1", "detect-zeroes": "off", "discard": "ignore"}' \
> 
> other part looks good.

Hi @qingwangrh 
Got it, I think that is a new requirement and I plan to create another PR to handle it.
Let's merge this PR ASAP since it results in the regression error.
Please let me know your opinion. Thanks.

**Review by zhencliu — APPROVED** [review]

**Comment by qingwangrh** [comment]
> > the protocol node the discard always is unmap, it just affects the format node.
> > -blockdev '{"node-name": "file_stg1", "driver": "file", "auto-read-only": true, "discard": "ignore", "aio": "threads", "filename": "/home/kvm_autotest_root/images/stg1.qcow2", "cache": {"direct": true, "no-flush": false}}' -blockdev '{"node-name": "drive_stg1", "driver": "qcow2", "read-only": false, "cache": {"direct": true, "no-flush": false}, "file": "file_stg1", "detect-zeroes": "off", "discard": "ignore"}' \
> > other part looks good.
> 
> Hi @qingwangrh Got it, I think that is a new requirement and I plan to create another PR to handle it. Let's merge this PR ASAP since it results in the regression error. Please let me know your opinion. Thanks.

OK， LGTM. thanks.

**Comment by YongxueHong** [comment]
Thanks all, let's merge it.

**Pull request merged**
