### PR TITLE
Fix usage of grep cmd argument

### PR DESCRIPTION
**Pull request by liang-cong-red-hat**

### CODE REVIEW

**Comment by dzhengfy** [comment]
Please paste what is the error without your fix and test result with your fix. Thanks.

**Comment by liang-cong-red-hat** [comment]
previous way would cause cmd failure like below：
# dmesg -T -l 1,2,3|grep . --color never
grep: never: No such file or directory

After fix:
# dmesg -T -l 1,2,3|grep . --color=never
[Wed Mar 13 01:05:20 2024] Warning: Unmaintained driver is detected: ip_set
[Wed Mar 13 01:05:20 2024] Warning: Unmaintained driver is detected: ip_set_init
[Wed Mar 13 01:25:30 2024] Warning: Unmaintained driver is detected: nft_compat
[Wed Mar 13 01:25:30 2024] Warning: Unmaintained driver is detected: nft_compat_module_init

**Review by cliping — APPROVED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
