### PR TITLE
utils_misc: ignore field deprecated when getting machine type

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 1989421

### CODE REVIEW

**Comment by XueqiangWei** [comment]
Tested on slow train and fast train, all passed.
(1/4) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.smbios_table.type0: PASS (79.81)
(2/4) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.smbios_table.type1: PASS (76.64)
(3/4) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.smbios_table.type0and1: PASS (76.52)
(4/4) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.smbios_table.machine_type: PASS (779.37)

**Comment by XueqiangWei** [comment]
@zhencliu Pleaes help review it. Many thanks.

**Comment by zhencliu** [comment]
LGTM
@YongxueHong , can you please make a double check and merge it ? Thanks.

**Comment by YongxueHong** [comment]
Please add the reason why to ignore filed deprecated in the commit message.
Thanks.

**Comment by XueqiangWei** [comment]
@YongxueHong Updated, please help review it again. Many thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
