### PR TITLE
utils_misc: small enhancement for normalize_data_size function

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
@suqinhuang  and @CongSmile 
Pass  unit test.  if no any comments, I will merge this patch.

**Comment by xutian** [comment]
ID: 1315152

**Comment by spcui** [comment]
PASSED with this patch for physical_resources_check,
so Acked-by: scui@redhat.com

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Pull request merged**
