### PR TITLE
Fix parent_bus for virtio-gpu device

### PR DESCRIPTION
**Pull request by JinLiul**
ID: 2214521
Signed-off-by: Jin Liu jinl@redhat.com

### CODE REVIEW

**Comment by JinLiul** [comment]
@XueqiangWei @PaulYuuu Could you please help to review? Thanks.

**Comment by JinLiul** [comment]
(1/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.intel_iommu.q35: STARTED
 (1/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.intel_iommu.q35: PASS (77.01 s)
 (2/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.virtio_iommu.q35: STARTED
 (2/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.virtio_iommu.q35: PASS (75.71 s)

**Comment by PaulYuuu** [comment]
Commit message too long per line, limit to 72 chars.

**Review by PaulYuuu — APPROVED** [review]

**Comment by PaulYuuu** [comment]
Hello @YongxueHong, can you also help to review?

**Comment by XueqiangWei** [comment]
(1/4) Host_RHEL.m9.u3.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.intel_iommu.q35: STARTED
 (1/4) Host_RHEL.m9.u3.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.intel_iommu.q35: PASS (37.53 s)
 (2/4) Host_RHEL.m9.u3.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.virtio_iommu.q35: STARTED
 (2/4) Host_RHEL.m9.u3.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.virtio_iommu.q35: PASS (93.06 s)
 (3/4) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.intel_iommu.q35: STARTED
 (3/4) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.intel_iommu.q35: PASS (37.14 s)
 (4/4) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.virtio_iommu.q35: STARTED
 (4/4) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.virtio_iommu.q35: PASS (94.04 s)

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by: xuwei@redhat.com

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
