### PR TITLE
drive: New API to get disk drive value of porperties by serial number

### PR DESCRIPTION
**Pull request by YongxueHong**
New API get_disk_props_by_serial_number to get disk drive value
of properties by serial number in windows guest.

ID: 1868329

Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
Hi, @qingwangrh 
Please help me to review it, thanks.

**Comment by qingwangrh** [comment]
a = get_disk_props_by_serial_number(session, "TARGET_DISK1", ['name'])
    print(a)
    a = get_disk_props_by_serial_number(session, "TARGET_DISK1",
                                        ["name", "index"])
    print(a)
    try:
        a = get_disk_props_by_serial_number(session, "TARGET_DISK1", ["name","index","tbd"])
        print(a)
    except:
        pass
    try:
        #wrong SerialNumber
        a = get_disk_props_by_serial_number(session, "TARGET_DISK2", ['name'])
        print(a)
    except:
        pass


2020-12-14 02:02:36,460 ip_sniffing      L0053 DEBUG| Updated HWADDR (9a:a3:1f:ce:cd:f2)<->(10.73.197.144) IP pair into address cache
2020-12-14 02:02:36,815 virt_vm          L0921 DEBUG| Found/Verified IP 10.73.197.144 for VM avocado-vt-vm1 NIC 0
2020-12-14 02:02:37,634 client           L1144 DEBUG| Sending command: wmic diskdrive where (SerialNumber like 'TARGET_DISK1') get name /format:list
2020-12-14 02:02:37,894 client           L1144 DEBUG| Sending command: echo %errorlevel%
2020-12-14 02:02:38,003 output           L0696 DEBUG| [stdout] {'name': '\\\\.\\PHYSICALDRIVE1'}
2020-12-14 02:02:38,003 output           L0696 DEBUG| [stdout] 

2020-12-14 02:02:38,003 client           L1144 DEBUG| Sending command: wmic diskdrive where (SerialNumber like 'TARGET_DISK1') get name,index /format:list
2020-12-14 02:02:38,193 client           L1144 DEBUG| Sending command: echo %errorlevel%
2020-12-14 02:02:38,301 output           L0696 DEBUG| [stdout] {'Index': '1', 'Name': '\\\\.\\PHYSICALDRIVE1'}
2020-12-14 02:02:38,301 output           L0696 DEBUG| [stdout] 

2020-12-14 02:02:38,301 client           L1144 DEBUG| Sending command: wmic diskdrive where (SerialNumber like 'TARGET_DISK1') get name,index,tbd /format:list
2020-12-14 02:02:38,502 client           L1144 DEBUG| Sending command: echo %errorlevel%
2020-12-14 02:02:38,609 client           L1144 DEBUG| Sending command: wmic diskdrive where (SerialNumber like 'TARGET_DISK2') get name /format:list
2020-12-14 02:02:38,792 client           L1144 DEBUG| Sending command: echo %errorlevel%


For the wrong option , it  is acceptable for raising exception.
For the wrong SerialNumber what is the expected result ?

exception or empty dict?

**Comment by YongxueHong** [comment]
Hi, I think we should not check whether the arguments which the caller passed, BTW, for windows command `wmic diskdrive where` that supports the wrong option and serial number, just it returns empty.

So we could raise an exception, but I prefer to let it return empty dict then the caller could execute the following steps by its return value.

**Comment by YongxueHong** [comment]
Hi @qingwangrh 
I have updated the codes, pls help me to review it, thanks,

**Comment by qingwangrh** [comment]
2020-12-14 20:23:22,034 client           L1144 DEBUG| Sending command: wmic diskdrive where (SerialNumber like 'TARGET_DISK1') get name /format:list
2020-12-14 20:23:22,291 client           L1144 DEBUG| Sending command: echo %errorlevel%
2020-12-14 20:23:22,398 output           L0696 DEBUG| [stdout] {'name': '\\\\.\\PHYSICALDRIVE1'}
2020-12-14 20:23:22,399 output           L0696 DEBUG| [stdout] 

2020-12-14 20:23:22,399 client           L1144 DEBUG| Sending command: wmic diskdrive where (SerialNumber like 'TARGET_DISK1') get name,index /format:list
2020-12-14 20:23:22,583 client           L1144 DEBUG| Sending command: echo %errorlevel%
2020-12-14 20:23:22,690 output           L0696 DEBUG| [stdout] {'Index': '1', 'Name': '\\\\.\\PHYSICALDRIVE1'}
2020-12-14 20:23:22,691 output           L0696 DEBUG| [stdout] 

2020-12-14 20:23:22,691 client           L1144 DEBUG| Sending command: wmic diskdrive where (SerialNumber like 'TARGET_DISK1') get name,index,tbd /format:list
2020-12-14 20:23:22,888 client           L1144 DEBUG| Sending command: echo %errorlevel%
2020-12-14 20:23:22,995 output           L0696 DEBUG| [stdout] Shell command failed: "wmic diskdrive where (SerialNumber like 'TARGET_DISK1') get name,index,tbd /format:list"    (status: -2147217385,    output: 'Node - WIN-SVVMKSD7S3L\nERROR:\nDescription = Invalid query\n\n\n\n\n')
2020-12-14 20:23:22,996 output           L0696 DEBUG| [stdout] 

2020-12-14 20:23:22,996 output           L0696 DEBUG| [stderr] Traceback (most recent call last):

2020-12-14 20:23:22,996 output           L0696 DEBUG| [stderr]   File "/home/workdir/kar/workspace/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/hello_world.py", line 57, in run

2020-12-14 20:23:22,996 output           L0696 DEBUG| [stderr]     a = get_disk_props_by_serial_number(session, "TARGET_DISK1", ["name","index","tbd"])

2020-12-14 20:23:22,996 output           L0696 DEBUG| [stderr]   File "/home/workdir/kar/workspace/avocado-vt/virttest/utils_windows/drive.py", line 107, in get_disk_props_by_serial_number

2020-12-14 20:23:22,997 output           L0696 DEBUG| [stderr]     out = wmic.parse_list(session.cmd(cmd, timeout=120))

2020-12-14 20:23:22,997 output           L0696 DEBUG| [stderr]   File "/home/workdir/kar/workspace/lib/python3.6/site-packages/aexpect-1.6.0-py3.6.egg/aexpect/client.py", line 1310, in cmd

2020-12-14 20:23:22,997 output           L0696 DEBUG| [stderr]     raise ShellCmdError(cmd, status, output)

2020-12-14 20:23:22,997 output           L0696 DEBUG| [stderr] aexpect.exceptions.ShellCmdError: Shell command failed: "wmic diskdrive where (SerialNumber like 'TARGET_DISK1') get name,index,tbd /format:list"    (status: -2147217385,    output: 'Node - WIN-SVVMKSD7S3L\nERROR:\nDescription = Invalid query\n\n\n\n\n')

2020-12-14 20:23:22,997 client           L1144 DEBUG| Sending command: wmic diskdrive where (SerialNumber like 'TARGET_DISK2') get name /format:list
2020-12-14 20:23:23,181 client           L1144 DEBUG| Sending command: echo %errorlevel%
2020-12-14 20:23:23,288 output           L0696 DEBUG| [stdout] {}
2020-12-14 20:23:23,288 output           L0696 DEBUG| [stdout] 

Exception is expected.

LGTM.

**Pull request merged**
