### PR TITLE
block_hotplug.block_scsi: it's supported from Host_RHEL6.6

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 1481104

### CODE REVIEW

**Comment by suqinhuang** [comment]
need to update the summary,
should be "it's supported from rhel6.6"

**Comment by aliang123** [comment]
Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by suqinhuang** [comment]
acked-by: Suqin huang

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
