### PR TITLE
utils_netperf: Make safe mode configurable when execute cmd 

### PR DESCRIPTION
**Pull request by huangyum**
Signed-off-by: Yumei Huang <yuhuang@redhat.com>
ID: 1969384

### CODE REVIEW

**Comment by huangyum** [comment]
Test passed. 
@yanglei-rh @yanan-fu Pls help review, thanks.

**Comment by yanan-fu** [comment]
The code change LGTM.

Just for the title, how do you think about `make safe mode configurable when execute cmd` ?  And explain the reason for this change, as safe mode does not work in some situation.

**Comment by yanglei-rh** [comment]
LGTM

The current changes are friendly to my feature,test pass.

**Comment by huangyum** [comment]
> The code change LGTM.
> 
> Just for the title, how do you think about `make safe mode configurable when execute cmd` ? And explain the reason for this change, as safe mode does not work in some situation.

Updated, thanks.

**Review by yanan-fu — APPROVED** [review]
Acked-by: Yanan Fu <yfu@redhat.com>

**Review by yanglei-rh — APPROVED** [review]

**Comment by yanan-fu** [comment]
@luckyh  Could you help review ?  Thanks!

**Pull request closed without merging**
