### PR TITLE
utils_package: support groupinstall/groupremove for Yum package manager

### PR DESCRIPTION
**Pull request by balamuruhans**
This patch enables support to groupinstall/groupremove of packages
with Yum package manager in Host/Guest/RemoteHost RHEL based systems.

Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by balamuruhans** [comment]
depends on https://github.com/avocado-framework/avocado/pull/2700

**Comment by balamuruhans** [comment]
@ldoktor @luckyh request for your review.

**Comment by ldoktor** [comment]
@balamuruhans I think we discussed this in https://github.com/avocado-framework/avocado/pull/2700 and the resolution was to modify the tests to prefix `@` instead of adding arguments that only make sense for limited amount of providers. Have you found any issues with that?

**Comment by balamuruhans** [comment]
@ldoktor I have used your suggestion in the utils_package for the APIs to handle with prefix @. It is better to have framework to handle it instead from each testcase. Also I am working on handling dependency packages to be installed as configurable param for the stress-ng or any tool to be used, so this way would make the code and framework cleaner.

**Comment by ldoktor** [comment]
(I mean it's better to use `@text-internet` than `@Text-based Internet`. Bot work, but the later requires quotation)

**Comment by balamuruhans** [comment]
@ldoktor Okay, let me close this PR. let us take care from testcase. Thanks!

**Pull request closed without merging**
