### PR TITLE
virttest/cpu: add switch to turn off numa check

### PR DESCRIPTION
**Pull request by smitterl**
Architectures might not have NUMA, e.g. s390x. Add variable to skip numa check when checking vcpus, default to True to maintain existing behavior.

Also, add logs to determine more easily which checks failed if the global result is a failure.

Signed-off-by: Sebastian Mitterle <smitterl@redhat.com>

### CODE REVIEW

**Comment by smitterl** [comment]
Failed check will be fixed by https://github.com/avocado-framework/avocado-vt/pull/3612

**Comment by smitterl** [comment]
Needed for https://github.com/autotest/tp-libvirt/pull/4730

**Review by chunfuwen — APPROVED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
