### PR TITLE
shared/cfg/guest-os: Remove case multi_disk from guest-os

### PR DESCRIPTION
**Pull request by ngu-niny**
Remove case multi_disk in files Linux.cfg and Windows.cfg

ID: 1412576

Signed-off-by: Nini Gu <ngu@redhat.com>

### CODE REVIEW

**Comment by ngu-niny** [comment]
Test PASS:

'1-smp_8.16384m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.multi_disk.one_disk_repeat' Finshed 2017-01-12 05:38:56 2017-01-12 05:41:28 PASS 152.657615
'2-smp_8.16384m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.multi_disk.max_disk' Finshed 2017-01-12 05:41:29 2017-01-12 05:43:36 ERROR 127.176926
'3-smp_8.16384m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.multi_disk.one_disk_repeat' Finshed 2017-01-12 05:43:36 2017-01-12 05:48:11 PASS 274.846485
'4-smp_8.16384m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.multi_disk.max_disk' Finshed 2017-01-12 05:48:11 2017-01-12 05:56:54 PASS 523.497565

**Comment by CongLi** [comment]
Why remove it?

**Comment by ngu-niny** [comment]
@CongLi This is to coordinate shuang's job of removing case configuration from guest-os to tp-qemu case cfg

**Comment by xutian** [comment]
@ngu-niny  deps on @suqinhuang pull so delay to review this PR.

**Comment by xutian** [comment]
deps on https://github.com/avocado-framework/avocado-vt/pull/842

**Comment by ngu-niny** [comment]
Close the patch since patch https://github.com/avocado-framework/avocado-vt/pull/842 is still in discussion.

**Pull request closed without merging**
