### PR TITLE
utils_disk: Tweak creating and deleting partition

### PR DESCRIPTION
**Pull request by YongxueHong**
1.Support the function "get_linux_disks" in RHEL6 guest,  since command lsblk does not support them in RHEL6.
2. For function create_partition_linux, add a step to check if the partition is created completely and return the kanme of partition created.
3. For function create_partition_windows, return the index of partition created.
4. For function create_partition, return the kanme of partition created in linux, the index of  partition in windows.
5. Add a mechanism to check the partition is deleted completely.

ID: 1699169, 1719589, 1748158, 1776109
Signed-off-by: Yongxue Hong yhong@redhat.com

### CODE REVIEW

**Comment by YongxueHong** [comment]
Hi @qingwangrh 
Please help me to review, thanks.

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun --guestname=Win2019,RHEL.8.4.0 --clone=no
 (1/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: PASS (319.79 s)
 (2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: ERROR: Shell command failed: 'echo list disk > disk_ciLW && echo select disk 14 >> disk_ciLW &&  echo create partition primary size=45 >> disk_ciLW &&  echo list partition >> disk_ciLW &&  echo exit >> disk_ciLW && diskpart /s disk_ciLW && del /f disk_ciLW'    (... (284.34 s)

failed case log:
http://fileshare.englab.nay.redhat.com/pub/section2/images_backup/qbugs/code2864/2020-12-17-0307/

**Comment by YongxueHong** [comment]
Hi @qingwangrh 
Sorry, I forgot to test it in Windows. will check it right now.

**Comment by YongxueHong** [comment]
Hi @qingwangrh 
Have fixed, please help me to review it again, thanks

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun --guestname=Win2019,RHEL.8.4.0 --clone=no --nrepeat=3

(1/6) repeat1.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: PASS (318.88 s)
 (2/6) repeat1.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: PASS (824.67 s)
 (3/6) repeat2.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: PASS (315.64 s)
 (4/6) repeat2.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: PASS (785.94 s)
 (5/6) repeat3.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: PASS (315.73 s)
 (6/6) repeat3.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: PASS (781.25 s)


LGTM

**Pull request merged**
