### PR TITLE
utils_virtio_port: Align to new chardev definition rules

### PR DESCRIPTION
**Pull request by vivianQizhu**
id: 1734212
Signed-off-by: Qianqian Zhu <qizhu@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@nanliu-r Request for your ack, thanks.

**Comment by nanliu-r** [comment]
> @nanliu-r Request for your ack, thanks.

commit  -- "utils_virtio_port: Keep the configuration only when they all equal " this can be controlled by parameter 'strict'.

**Comment by vivianQizhu** [comment]
@nanliu-r Good catch, thanks and updated.

**Comment by nanliu-r** [comment]
ACK.

**Pull request merged**
