### PR TITLE
guest-os: Add support for SLES12 sp3 guest(x86_64)

### PR DESCRIPTION
**Pull request by yanan-fu**
id: 1540046
Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
(1/1) smp_8.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_blk.up.virtio_net.SLES.12.3.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (674.10 s)

**Comment by yanan-fu** [comment]
@vivianQizhu could you help review this PR ?

**Comment by vivianQizhu** [comment]
Verified guest boot up success with correct command line.
Acked-by: Qianqian Zhu <qizhu@redhat.com>

**Comment by vivianQizhu** [comment]
(1/1) smp_4.2048m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.SLES.12.3.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (768.19 s)

**Pull request merged**
