### PR TITLE
Fixup: handle failures for avocado 69lts

### PR DESCRIPTION
**Pull request by sathnaga**
Handle failures for avocado 69lts version.

Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by sathnaga** [comment]
@chunfuwen @chloerh ping

**Comment by dzhengfy** [comment]
> @chunfuwen @chloerh ping

@sathnaga thanks for your quick fix. We will test it in few minutes.

**Comment by dzhengfy** [comment]
@sathnaga but could you help fix the travis failure?

**Comment by sathnaga** [comment]
> @sathnaga but could you help fix the travis failure?

@dzhengfy my bad, fixed it now, Tnx!

**Comment by chloerh** [comment]
PASS 1-type_specific.local.virtual_network.mtu.negative_test.invalid_val.str

**Review by chloerh — APPROVED** [review]

**Review by dzhengfy — COMMENTED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]

**Comment by pevogam** [comment]
Did the CI checks on this PR succeed?

It is causing

```
2020-09-11 15:56:22,744 stacktrace       L0041 ERROR| Reproduced traceback from: /usr/lib/python3.8/site-packages/avocado_vt/test.py:442
2020-09-11 15:56:22,745 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-09-11 15:56:22,745 stacktrace       L0045 ERROR|   File "/usr/lib/python3.8/site-packages/virttest/error_context.py", line 135, in new_fn
2020-09-11 15:56:22,745 stacktrace       L0045 ERROR|     return fn(*args, **kwargs)
2020-09-11 15:56:22,745 stacktrace       L0045 ERROR|   File "/usr/lib/python3.8/site-packages/virttest/env_process.py", line 932, in preprocess
2020-09-11 15:56:22,745 stacktrace       L0045 ERROR|     cpu_family = cpu_utils.get_family() if hasattr(cpu_utils, 'get_family') else cpu_utils.get_cpu_arch()
2020-09-11 15:56:22,745 stacktrace       L0045 ERROR|   File "/usr/lib/python3.8/site-packages/avocado/utils/cpu.py", line 188, in get_family
2020-09-11 15:56:22,745 stacktrace       L0045 ERROR|     raise NotImplementedError
2020-09-11 15:56:22,745 stacktrace       L0045 ERROR| NotImplementedError
2020-09-11 15:56:22,745 stacktrace       L0046 ERROR| 
2020-09-11 15:56:22,859 stacktrace       L0039 ERROR| 
2020-09-11 15:56:22,859 stacktrace       L0041 ERROR| Reproduced traceback from: /usr/lib/python3.8/site-packages/avocado_vt/test.py:461
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR|   File "/usr/lib/python3.8/site-packages/avocado_vt/test.py", line 421, in _runTest
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR|     params = env_process.preprocess(self, params, env)
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR|   File "/usr/lib/python3.8/site-packages/virttest/error_context.py", line 135, in new_fn
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR|     return fn(*args, **kwargs)
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR|   File "/usr/lib/python3.8/site-packages/virttest/env_process.py", line 932, in preprocess
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR|     cpu_family = cpu_utils.get_family() if hasattr(cpu_utils, 'get_family') else cpu_utils.get_cpu_arch()
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR|   File "/usr/lib/python3.8/site-packages/avocado/utils/cpu.py", line 188, in get_family
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR|     raise NotImplementedError
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR| NotImplementedError
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR| 
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR| During handling of the above exception, another exception occurred:
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR| 
2020-09-11 15:56:22,860 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-09-11 15:56:22,861 stacktrace       L0045 ERROR|   File "/usr/lib/python3.8/site-packages/virttest/error_context.py", line 135, in new_fn
2020-09-11 15:56:22,861 stacktrace       L0045 ERROR|     return fn(*args, **kwargs)
2020-09-11 15:56:22,861 stacktrace       L0045 ERROR|   File "/usr/lib/python3.8/site-packages/virttest/env_process.py", line 1684, in postprocess
2020-09-11 15:56:22,861 stacktrace       L0045 ERROR|     cpu_family = cpu_utils.get_family() if hasattr(cpu_utils, 'get_family') else cpu_utils.get_cpu_arch()
2020-09-11 15:56:22,861 stacktrace       L0045 ERROR|   File "/usr/lib/python3.8/site-packages/avocado/utils/cpu.py", line 188, in get_family
2020-09-11 15:56:22,861 stacktrace       L0045 ERROR|     raise NotImplementedError
2020-09-11 15:56:22,861 stacktrace       L0045 ERROR| NotImplementedError
2020-09-11 15:56:22,861 stacktrace       L0046 ERROR| 
2020-09-11 15:56:22,861 test             L0465 ERROR| Exception raised during postprocessing: 
2020-09-11 15:56:22,900 test             L0479 INFO | Aborting job ()
2020-09-11 15:56:22,900 test             L0484 INFO | VM 'mis1' is alive.
```

for me.

**Comment by pevogam** [comment]
I can see this commit is fixing c9cc10fb022b3d0008474b664a74af16fbebbf3c but it doesn't seem to be complete. I am using the most recent avocado dependency.

**Comment by clebergnu** [comment]
It looks like this went through CI: https://cirrus-ci.com/build/4811880541716480

But as you mention @pevogam, it does not seem to be complete.  I suggested a `virttest/compat.py` like approach, which would IMO make it harder to miss other uses of those utilities.

**Comment by clebergnu** [comment]
Looks like the `NotImplementedError` is raised depending on the architecture or vendor, so this CI is not as effective, as we don't test on a multitude of hardware (and neither control it).

**Comment by sathnaga** [comment]
> Hmmm, in any case it would be good if Avocado VT doesn't become completely disabled on specific architectures as these detections used to work everywhere before.
> 
> I took a brief look at the CI and from what I can see it is worse - the Travis CI only checks python 2.7 versions without allowing any errors.

@pevogam looks like your environment is either `amd` or `arm` so you are hitting in this issue,

good that we noticed before LTS tagging, `NotImplementedError` is not a good idea to raise there, I will quickly send a PR on avocado cpu utils to just warn the user and return None. 

@pevogam probably if you can help me how to get cpu family details in your environment, we could implement that and enhance the utils, but that can wait ...

**Comment by sathnaga** [comment]
@pevogam @clebergnu fixed it, https://github.com/avocado-framework/avocado/pull/4234

**Comment by sathnaga** [comment]
@pevogam @clebergnu ignore previous fix for avocado, it is better to handle/contain in avocado-vt, https://github.com/avocado-framework/avocado-vt/pull/2759

**Comment by sathnaga** [comment]
@pevogam if you can confirm if this working on your environment, we could merge it...

**Comment by pevogam** [comment]
Hi @sathnaga,

> @pevogam if you can confirm if this working on your environment, we could merge it...

Sure,

```
# lshw -c cpu
  *-cpu                     
       description: CPU
       product: AMD EPYC 7401P 24-Core Processor
       vendor: Advanced Micro Devices [AMD]
       physical id: 50
       bus info: cpu@0
       version: AMD EPYC 7401P 24-Core Processor
       slot: Proc 1
       size: 1197MHz
       capacity: 2400MHz
       width: 64 bits
       clock: 100MHz
       capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca cpufreq
       configuration: cores=24 enabledcores=24 threads=48
```

**Pull request merged**
