### PR TITLE
Qemu blockdev raw format elimination

### PR DESCRIPTION
**Pull request by luckyh**
- qemu_capabilities: introduce BLOCKJOB_BACKING_MASK_PROTOCOL
- qemu_monitor: introduce new argument to block_stream/commit
- qcontainer: eliminate raw format node by default

ID: 2408

### CODE REVIEW

**Comment by qingwangrh** [comment]
`- hello_world:
    only Linux
    type = hello_world
    sleep_time = 5
    images =+ "stg0 stg1 stg2 stg3"
    variants:
        - with_raw:
            fmt=raw
        - with_qcow2:
            fmt=qcow2

    image_format_stg0 = ${fmt}
    image_format_stg1 = ${fmt}
    image_format_stg2 = ${fmt}
    image_format_stg3 = ${fmt}
      
    blk_extra_params_stg0 = "serial=stg0"
    blk_extra_params_stg1 = "serial=stg1"
    blk_extra_params_stg2 = "serial=stg2"
    blk_extra_params_stg3 = "serial=stg3"
    
    image_size_stg0 = 1G
    image_size_stg1 = 1G
    image_size_stg2 = 1G
    image_size_stg3 = 1G
    image_name_stg0 = images/stg0
    image_name_stg1 = images/stg1
    image_name_stg2 = images/stg2
    image_name_stg3 = images/stg3
    image_readonly_stg1=yes
    drv_extra_params_stg2 += ",discard=on,detect-zeroes=on"
    drv_extra_params_stg3 += ",discard=off,detect-zeroes=off"



`

**Comment by qingwangrh** [comment]
> - hello_world:
    only Linux
    type = hello_world
    sleep_time = 5
    images =+ "stg0 stg1 stg2 stg3"
    variants:
        - with_raw:
            fmt=raw
        - with_qcow2:
            fmt=qcow2

    image_format_stg0 = ${fmt}
    image_format_stg1 = ${fmt}
    image_format_stg2 = ${fmt}
    image_format_stg3 = ${fmt}
      
    blk_extra_params_stg0 = "serial=stg0"
    blk_extra_params_stg1 = "serial=stg1"
    blk_extra_params_stg2 = "serial=stg2"
    blk_extra_params_stg3 = "serial=stg3"
    
    image_size_stg0 = 1G
    image_size_stg1 = 1G
    image_size_stg2 = 1G
    image_size_stg3 = 1G
    image_name_stg0 = images/stg0
    image_name_stg1 = images/stg1
    image_name_stg2 = images/stg2
    image_name_stg3 = images/stg3
    image_readonly_stg1=yes
    drv_extra_params_stg2 += ",discard=on,detect-zeroes=on"
    drv_extra_params_stg3 += ",discard=off,detect-zeroes=off"

**Comment by qingwangrh** [comment]
hit Error occurred while executing make_create_command()
@luckyh Please check comment in 2408

**Comment by luckyh** [comment]
@qingwangrh good catch, have modified the code accordingly, thanks!

**Comment by luckyh** [comment]
@aliang123 @qingwangrh @YongxueHong would you mind to help review this PR? thanks in advance!

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m9.ux.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.x.0.x86_64.io-github-autotest-qemu.blockdev_snapshot.q35: ERROR: QMP command 'blockdev-add' failed    (arguments: {'node-name': 'drive_sn1', 'driver': 'qcow2', 'file': 'drive_sn1', 'read-only': False},    error message: {'class': 'GenericError', 'desc': "Duplicate nodes with node-name='drive_sn1'"}) (57.94 s)

When adding qcow2 image with blockdev-add, failed to add the format node, as **same node-name assigned to both protocol node and format node.**
{"execute": "blockdev-add", "arguments": {"node-name": "drive_sn1", "driver": "file", "filename": "/root/avocado/data/avocado-vt/sn1.qcow2", "aio": "threads", "auto-read-only": true, "discard": "unmap"}, "id": "RnkXjzdy"}
{"execute": "blockdev-add", "arguments": {"node-name": "drive_sn1", "driver": "qcow2", "file": "drive_sn1", "read-only": false}, "id": "96qDODUP"}
virttest.qemu_monitor.QMPCmdError: QMP command 'blockdev-add' failed    (arguments: {'node-name': 'drive_sn1', 'driver': 'qcow2', 'file': 'drive_sn1', 'read-only': False},    error message: {'class': 'GenericError', 'desc': "Duplicate nodes with node-name='drive_sn1'"})


correct qmp cmd for adding a qcow2 target:
{"execute": "blockdev-add", "arguments": {"node-name": "file_sn1", "driver": "file", "filename": "/root/avocado/data/avocado-vt/sn1.qcow2", "aio": "threads", "auto-read-only": true, "discard": "unmap"}, "id": "ktTo6xjQ"}
{"execute": "blockdev-add", "arguments": {"node-name": "drive_sn1", "driver": "qcow2", "file": "file_sn1", "read-only": false}, "id": "AFpzKVRh"}

**Comment by luckyh** [comment]
Hi @aliang123 , it seems to be a bug on the test script side, so let's fix it there.

**Comment by luckyh** [comment]
> qcow2 protocol discard=unmap even if discard=ignore in xml

@qingwangrh yeah, it's a expected behavior performed libvirt (see [`libvirt/src/qemu/qemu_block.c@qemuBlockStorageSourceAddBlockdevCommonProps`](https://gitlab.com/libvirt/libvirt/-/blob/master/src/qemu/qemu_block.c?ref_type=heads#L956)). In short, the `discard` option of the protocol node will always be set to `unmap` if the format node presents.

However, it seems that it has already been implemented as so even before the raw format elimination been applied. Therefore, I'd suggest filing a separated issue to track it, and we could investigate and discuss there, thanks.

```c
    if (effective) {
        virDomainDiskDetectZeroes dz = virDomainDiskGetDetectZeroesMode(src->discard,
                                                                        src->detect_zeroes);

        if (src->discard != VIR_DOMAIN_DISK_DISCARD_DEFAULT)
            discard = virDomainDiskDiscardTypeToString(src->discard);

        if (dz != VIR_DOMAIN_DISK_DETECT_ZEROES_DEFAULT)
            detectZeroes = virDomainDiskDetectZeroesTypeToString(dz);

        autoReadOnly = VIR_TRISTATE_BOOL_ABSENT;
        readOnly = virTristateBoolFromBool(src->readonly);
    } else {
        /* when passing a FD to qemu via the /dev/fdset mechanism qemu
         * fetches the appropriate FD from the fdset by checking that it has
         * the correct accessmode. Now with 'auto-read-only' in effect qemu
         * wants to use a read-only FD first. If the user didn't pass multiple
         * FDs the feature will not work regardless, so we'll not enable it. */
        if ((actualType == VIR_STORAGE_TYPE_FILE || actualType == VIR_STORAGE_TYPE_BLOCK) &&
            src->fdtuple && src->fdtuple->nfds == 1) {
            autoReadOnly = VIR_TRISTATE_BOOL_ABSENT;

            /* now we setup the normal readonly flag. If user requested write access honour it */
            if (src->fdtuple->writable)
                readOnly = VIR_TRISTATE_BOOL_NO;
            else
                readOnly = virTristateBoolFromBool(src->readonly);
        } else {
            autoReadOnly = VIR_TRISTATE_BOOL_YES;
        }

        discard = "unmap";  // <--- HERE
    }
```

**Comment by aliang123** [comment]
- Ack for file+qcow2:
 -blockdev '{"node-name": "file_data1", "driver": "file", "auto-read-only": true, "discard": "unmap", "aio": "threads", "filename": "/home/kvm_autotest_root/images/data1.qcow2", "cache": {"direct": true, "no-flush": false}}' \
 -blockdev '{"node-name": "drive_data1", "driver": "qcow2", "read-only": true, "cache": {"direct": true, "no-flush": false}, "file": "file_data1"}' \

- Ack for the file+raw:
-blockdev '{"node-name": "drive_data1", "driver": "file", "read-only": true, "discard": "unmap", "aio": "threads", "filename": "/home/kvm_autotest_root/images/data1.raw", "cache": {"direct": true, "no-flush": false}}' \
-device '{"driver": "scsi-hd", "id": "data1", "drive": "drive_data1", "write-cache": "on"}' \

- Ack for NBD+raw:
-blockdev '{"node-name": "drive_data", "driver": "nbd", "read-only": false, "discard": "unmap", "server": {"type": "inet", "host": "10.72.140.40", "port": "10831"}, "cache": {"direct": true, "no-flush": false}}' \
-device '{"driver": "scsi-hd", "id": "data", "drive": "drive_data", "write-cache": "on", "serial": "DATA_DISK1"}' \

- Ack for Ceph+raw:
-blockdev '{"node-name": "drive_src1", "driver": "rbd", "read-only": false, "discard": "unmap", "pool": "rbd", "image": "sr1.raw", "cache": {"direct": true, "no-flush": false}}' \
-device '{"driver": "scsi-hd", "id": "src1", "drive": "drive_src1", "write-cache": "on"}' \

- Ack for copy-on-read:
-blockdev '{"node-name": "file_data", "driver": "file", "read-only": false, "discard": "unmap", "aio": "threads", "filename": "/root/avocado/data/avocado-vt/data.raw", "cache": {"direct": true, "no-flush": false}}' \
-blockdev '{"node-name": "drive_data", "driver": "copy-on-read", "file": "file_data"}' \
-device '{"driver": "scsi-hd", "id": "data", "drive": "drive_data", "write-cache": "on"}' \

- Ack for read-only:
-blockdev '{"node-name": "drive_data1", "driver": "file", "read-only": true, "discard": "unmap", "aio": "threads", "filename": "/home/kvm_autotest_root/images/data1.raw", "cache": {"direct": true, "no-flush": false}}' \
-device '{"driver": "scsi-hd", "id": "data1", "drive": "drive_data1", "write-cache": "on"}'

- Auto-read-only:
Need to confirm the product behavior firstly.

**Comment by qingwangrh** [comment]
Pass
python ConfigTest.py --testcase=insert_media,multi_disk.virtio_scsi_variants.passthrough.generic.with_cache_writethrough --guestname=RHEL.9.4.0 --driveformat=virtio_blk,virtio_scsi --imageformat=qcow2,raw --firmware=default_bios --customsparams="no prepare\nvm_mem_limit = 12G\n" --clone=no

LGTM

**Review by qingwangrh — APPROVED** [review]

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Review by aliang123 — APPROVED** [review]
LGTM

**Pull request merged**
