### PR TITLE
 Additional log files for vt-runner

### PR DESCRIPTION
**Pull request by richtja**
This commit copies content from the temporary vt logdir to the avocado
test-results. This will bring more useful debug files about test
runtime, which are available on legacy runner.

Reference: #3213
Signed-off-by: Jan Richter <jarichte@redhat.com>

### CODE REVIEW

**Review by willianrampazzo — APPROVED** [review]

**Comment by richtja** [comment]
Hi @pevogam this is a fix for your issue #3213

**Comment by pevogam** [comment]
Interesting that I didn't spot this before pushing my PR for the unattended install. Will look into this right away.

**Comment by pevogam** [comment]
Is there a reason for the files to be copied right in the end? This breaks some behavior where tests dump additional files and simply use the test folder for the purpose and prevents early inspection while the test is running.

Also while some folders are indeed there at the end of the test. You can see I describe many more missing files in #3213.

**Comment by richtja** [comment]
> Is there a reason for the files to be copied right in the end? This breaks some behavior where tests dump additional files and simply use the test folder for the purpose and prevents early inspection while the test is running.
  
Hi @pevogam unfortunately I don't understand how this breaks  prevention of early inspection while the test is running. The files are copied after the testing is finished.

> 
> Also while some folders are indeed there at the end of the test. You can see I describe many more missing files in #3213.

Yes you are right, I found more problems with this solution. So for now I converted to the draft.

**Comment by pevogam** [comment]
> > Is there a reason for the files to be copied right in the end? This breaks some behavior where tests dump additional files and simply use the test folder for the purpose and prevents early inspection while the test is running.
> 
> Hi @pevogam unfortunately I don't understand how this breaks prevention of early inspection while the test is running. The files are copied after the testing is finished.

Yes, maybe not completely preventing because technically one should still be able to check a custom log-searched tmp path where the results are stored before they are copied. My problem with this approach is that one has to dig into a particular temporary path and thus deal with temporary and less accessible storage internals instead of the already well established test result folders.

**Comment by richtja** [comment]
> > > Is there a reason for the files to be copied right in the end? This breaks some behavior where tests dump additional files and simply use the test folder for the purpose and prevents early inspection while the test is running.
> > 
> > 
> > Hi @pevogam unfortunately I don't understand how this breaks prevention of early inspection while the test is running. The files are copied after the testing is finished.
> 
> Yes, maybe not completely preventing because technically one should still be able to check a custom log-searched tmp path where the results are stored before they are copied. My problem with this approach is that one has to dig into a particular temporary path and thus deal with temporary and less accessible storage internals instead of the already well established test result folders.

I am not sure if I understand, you need the easy access to those files during the test runtime? Such solution mid be quite tricky, there is so many possible channels for saving to the output directory and vt-runner can't have any control of them. So it will be difficult to track the changes and send them to avocado results' directory.

**Comment by pevogam** [comment]
> > > > Is there a reason for the files to be copied right in the end? This breaks some behavior where tests dump additional files and simply use the test folder for the purpose and prevents early inspection while the test is running.
> > > 
> > > 
> > > Hi @pevogam unfortunately I don't understand how this breaks prevention of early inspection while the test is running. The files are copied after the testing is finished.
> > 
> > 
> > Yes, maybe not completely preventing because technically one should still be able to check a custom log-searched tmp path where the results are stored before they are copied. My problem with this approach is that one has to dig into a particular temporary path and thus deal with temporary and less accessible storage internals instead of the already well established test result folders.
> 
> I am not sure if I understand, you need the easy access to those files during the test runtime? Such solution mid be quite tricky, there is so many possible channels for saving to the output directory and vt-runner can't have any control of them. So it will be difficult to track the changes and send them to avocado results' directory.

Hmmm, maybe I am missing something but with the serial runner before this was fairly straightforward and all files were not copied as diffs but directly written to the test results directory. What are the limitations of the VT runner that make it impossible for it to just directly create the files in the test logdir? Could this be a general Avocado limitation instead but one that relates in some way to the next runner?

**Comment by richtja** [comment]
> > > > > Is there a reason for the files to be copied right in the end? This breaks some behavior where tests dump additional files and simply use the test folder for the purpose and prevents early inspection while the test is running.
> > > > 
> > > > 
> > > > Hi @pevogam unfortunately I don't understand how this breaks prevention of early inspection while the test is running. The files are copied after the testing is finished.
> > > 
> > > 
> > > Yes, maybe not completely preventing because technically one should still be able to check a custom log-searched tmp path where the results are stored before they are copied. My problem with this approach is that one has to dig into a particular temporary path and thus deal with temporary and less accessible storage internals instead of the already well established test result folders.
> > 
> > 
> > I am not sure if I understand, you need the easy access to those files during the test runtime? Such solution mid be quite tricky, there is so many possible channels for saving to the output directory and vt-runner can't have any control of them. So it will be difficult to track the changes and send them to avocado results' directory.
> 
> Hmmm, maybe I am missing something but with the serial runner before this was fairly straightforward and all files were not copied as diffs but directly written to the test results directory. What are the limitations of the VT runner that make it impossible for it to just directly create the files in the test logdir? Could this be a general Avocado limitation instead but one that relates in some way to the next runner?

Unfortunately this can't be done same as in legacy runner, because the new runner architecture is modular, which means that every nrunner like vr-runner is standalone task and might be run even on different machine then avocado itself. So the vr-runner outputdir and avocado test resultdir don't have to be in the same file system.

**Comment by pevogam** [comment]
> > > > > > Is there a reason for the files to be copied right in the end? This breaks some behavior where tests dump additional files and simply use the test folder for the purpose and prevents early inspection while the test is running.
> > > > > 
> > > > > 
> > > > > Hi @pevogam unfortunately I don't understand how this breaks prevention of early inspection while the test is running. The files are copied after the testing is finished.
> > > > 
> > > > 
> > > > Yes, maybe not completely preventing because technically one should still be able to check a custom log-searched tmp path where the results are stored before they are copied. My problem with this approach is that one has to dig into a particular temporary path and thus deal with temporary and less accessible storage internals instead of the already well established test result folders.
> > > 
> > > 
> > > I am not sure if I understand, you need the easy access to those files during the test runtime? Such solution mid be quite tricky, there is so many possible channels for saving to the output directory and vt-runner can't have any control of them. So it will be difficult to track the changes and send them to avocado results' directory.
> > 
> > 
> > Hmmm, maybe I am missing something but with the serial runner before this was fairly straightforward and all files were not copied as diffs but directly written to the test results directory. What are the limitations of the VT runner that make it impossible for it to just directly create the files in the test logdir? Could this be a general Avocado limitation instead but one that relates in some way to the next runner?
> 
> Unfortunately this can't be done same as in legacy runner, because the new runner architecture is modular, which means that every nrunner like vr-runner is standalone task and might be run even on different machine then avocado itself. So the vr-runner outputdir and avocado test resultdir don't have to be in the same file system.

I see. While this might work well for unit tests or small tests I am not that confident it won't create lots of headaches with VT tests where some of them might take tens of minutes to half an hour. Take unattended install tests for instance - the new runner practically makes it if not impossible then very difficult to know how the installation process goes until the very end. In case where some VT tests could hang on boot or get stuck at other large timeout checks, it could take an hour before seeing any progress. But I guess this is beyond the scope of this issue which is just about the additional log files. We could perhaps discuss this problem elsewhere later on.

**Comment by pevogam** [comment]
@richtja Just to clarify something on my side - I don't consider pushes a ping (not sure if you do) so if you need me to test and check this again, just let me know.

**Comment by richtja** [comment]
> > > > > > > Is there a reason for the files to be copied right in the end? This breaks some behavior where tests dump additional files and simply use the test folder for the purpose and prevents early inspection while the test is running.
> > > > > > 
> > > > > > 
> > > > > > Hi @pevogam unfortunately I don't understand how this breaks prevention of early inspection while the test is running. The files are copied after the testing is finished.
> > > > > 
> > > > > 
> > > > > Yes, maybe not completely preventing because technically one should still be able to check a custom log-searched tmp path where the results are stored before they are copied. My problem with this approach is that one has to dig into a particular temporary path and thus deal with temporary and less accessible storage internals instead of the already well established test result folders.
> > > > 
> > > > 
> > > > I am not sure if I understand, you need the easy access to those files during the test runtime? Such solution mid be quite tricky, there is so many possible channels for saving to the output directory and vt-runner can't have any control of them. So it will be difficult to track the changes and send them to avocado results' directory.
> > > 
> > > 
> > > Hmmm, maybe I am missing something but with the serial runner before this was fairly straightforward and all files were not copied as diffs but directly written to the test results directory. What are the limitations of the VT runner that make it impossible for it to just directly create the files in the test logdir? Could this be a general Avocado limitation instead but one that relates in some way to the next runner?
> > 
> > 
> > Unfortunately this can't be done same as in legacy runner, because the new runner architecture is modular, which means that every nrunner like vr-runner is standalone task and might be run even on different machine then avocado itself. So the vr-runner outputdir and avocado test resultdir don't have to be in the same file system.
> 
> I see. While this might work well for unit tests or small tests I am not that confident it won't create lots of headaches with VT tests where some of them might take tens of minutes to half an hour. Take unattended install tests for instance - the new runner practically makes it if not impossible then very difficult to know how the installation process goes until the very end. In case where some VT tests could hang on boot or get stuck at other large timeout checks, it could take an hour before seeing any progress. But I guess this is beyond the scope of this issue which is just about the additional log files. We could perhaps discuss this problem elsewhere later on.

Now I see, and I understand how this can be useful, but first of all I would like to make those files visible for users at least after the test, and then we can discuss how to make it better.

**Comment by richtja** [comment]
Closing this because, because the issue #3213 is better solved in #3226.

**Pull request closed without merging**
