### PR TITLE
Restart multipathd to make sure mpath devs synced

### PR DESCRIPTION
**Pull request by lento-sun**
Sometimes after 'nodedev-destroy' or 'nodedev-create' the mpath
devices not synced with scsi luns.
And this may produce device not found or device not unique issues.
This fix is to make sure the multipath devices synced with scsi
luns.

Signed-off-by: Yi Sun <yisun@redhat.com>

### CODE REVIEW

**Comment by lento-sun** [comment]
Have executed some test rounds within our CI and previous failures not happened again.
https://<URI_OF_OUR_CI>/job/libvirt-RHEL-9.1-runtest-x86_64-function-npiv/43/testReport/
https://<URI_OF_OUR_CI>/job/libvirt-RHEL-9.1-runtest-x86_64-function-npiv/44/testReport/
https://<URI_OF_OUR_CI>/job/libvirt-RHEL-9.1-runtest-x86_64-function-npiv/45/testReport/
There is still one case failed, but not related to this patch.

**Comment by lento-sun** [comment]
@chloerh @chunfuwen could you pls help to review this PR, thx

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by chunfuwen** [comment]
CI/static checks failed with below message, but not related to this PR's change.
```
0s
Run ./selftests/signedoff-check.sh
  ./selftests/signedoff-check.sh
  shell: /usr/bin/bash -e {0}
** Running signedoff-check...
Error: Process completed with exit code [1](https://github.com/avocado-framework/avocado-vt/actions/runs/2991267223/jobs/4812085334#step:3:1).
```

**Pull request merged**
