### PR TITLE
Remove SpiceQA answer files for unattended_install

### PR DESCRIPTION
**Pull request by Andrei-Stepanov**
Remove kickstart files for unattended_install used by SpiceQA.
This files now are part of tp-spice.

Signed-off-by: Andrei Stepanov <astepano@redhat.com>

### CODE REVIEW

**Comment by lmr** [comment]
@Andrei-Stepanov, how's the current status of `tp-spice`? I'd rather remove all the spice tests and spice related files from `virt-test` and `tp-qemu` all at once, in a coordinated fashion. So for now, I'd like to NACK this.

**Comment by Andrei-Stepanov** [comment]
This is part of avocado-vt.

This commit to avocado-vt

Swapna Krishnan  uses autotest + virttest  + qemu-tp

We can safely remove this files from avocado-vt

**Comment by lmr** [comment]
@swapnakrishnan2k is trying out avocado-vt and asked me why the tests were not working. I've sent fixes to `tp-qemu`, and returned `virttest.utils_spice` for now. I agree with the files being removed, but it's better to do it all at once.

**Comment by lmr** [comment]
I'm closing this one until @Andrei-Stepanov tells me `tp-spice` is in good shape and production-ready (in a very liberal and relaxed sense of the expression).

**Pull request closed without merging**
