### PR TITLE
Add 2 more method into modify_vm_iface()

### PR DESCRIPTION
**Pull request by yalzhang**
Add "del_target" and "del_alias" into the modify_vm_iface().

Signed-off-by: Yalan <yalzhang@redhat.com>

### CODE REVIEW

**Comment by yalzhang** [comment]
test result refer to  https://github.com/autotest/tp-libvirt/pull/3651#issuecomment-881218826

**Review by dzhengfy — APPROVED** [review]
LGTM

**Review by Yingshun — APPROVED** [review]
LGTM

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
