### PR TITLE
Two issue about param shell

### PR DESCRIPTION
**Pull request by PandaWei**
commit a3657b85533cd5886594ece953622c7f02ca5c04
Author: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
Date:   Fri May 27 11:06:00 2016 +0800

    Fix CmdError caused by omitting shell=True
    
    Signed-off-by: Wei Jiangang <weijg.fnst@cn.fujitsu.com>

commit 00fa76bbeae2643dfbe5286fa2a88ea1397c1e04
Author: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
Date:   Fri May 27 10:36:40 2016 +0800

    virttest.qemu_vm: fix output of system_ouput()
    
    If 'shell=True' is ommitted,
    The output of process.system_ouput() will be None.
    
    Signed-off-by: Wei Jiangang <weijg.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by PandaWei** [comment]
FYI,  Just example for commit 00fa76b,
Run **`'%s -device %s,\? 2>&1" % ("/usr/bin/qemu-kvm", "vfio-pci")'`** without "shell=True" won't trigger any Error, 
But the output  is None and isn't expected.

2016-05-27 11:12:14,752 output           L0632 DEBUG| output without shell=True:
2016-05-27 11:12:14,790 output           L0632 DEBUG| output with shell=True: vfio-pci.host=pci-host-devaddr
2016-05-27 11:12:14,790 output           L0632 DEBUG| vfio-pci.x-intx-mmap-timeout-ms=uint32
2016-05-27 11:12:14,791 output           L0632 DEBUG| vfio-pci.x-vga=on/off
2016-05-27 11:12:14,791 output           L0632 DEBUG| vfio-pci.bootindex=int32
2016-05-27 11:12:14,791 output           L0632 DEBUG| vfio-pci.addr=pci-devfn
2016-05-27 11:12:14,791 output           L0632 DEBUG| vfio-pci.romfile=string
2016-05-27 11:12:14,791 output           L0632 DEBUG| vfio-pci.rombar=uint32
2016-05-27 11:12:14,791 output           L0632 DEBUG| vfio-pci.multifunction=on/off
2016-05-27 11:12:14,791 output           L0632 DEBUG| vfio-pci.command_serr_enable=on/off

**Comment by xutian** [comment]
thanks @PandaWei  quick fix.

**Comment by xutian** [comment]
Acked

**Comment by will-Do** [comment]
ACK

**Pull request merged**
