### PR TITLE
Add metadata_cache xml support

### PR DESCRIPTION
**Pull request by chunfuwen**
This is newly introduced xml element,something like:
<driver name='qemu' type='qcow2'>
<metadata_cache>
  <max_size unit='bytes'>10</max_size>
</metadata_cache>
</driver>

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
feature_test) [root@hp-dl360g9-16 virttest]# python
Python 3.6.8 (default, Jan 22 2021, 06:08:55) 
[GCC 8.4.1 20200928 (Red Hat 8.4.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from virttest import virsh
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
>>> from virttest.libvirt_xml.devices.disk import Disk
>>> 
>>> 
>>> custom_disk = Disk(type_name='disk')
>>> driver_dict = {"name": "qemu","type": "qcow2"}
>>> new_one = custom_disk.new_drivermetadata(**{"attrs": driver_dict})
>>> 
>>> metadata_cache_dict = {"max_size": "10", "max_size_unit": "bytes"}
>>> 
>>> new_one.metadata_cache = custom_disk.DriverMetadata().new_metadatacache(**metadata_cache_dict)
>>> 
>>> custom_disk.drivermetadata = new_one
>>> print(custom_disk)
<?xml version='1.0' encoding='UTF-8'?>
<disk type="disk"><driver name="qemu" type="qcow2"><metadata_cache><max_size unit="bytes">10</max_size></metadata_cache></driver></disk>

**Comment by chunfuwen** [comment]
@lento-sun 
@qiankehan 

please help take a look

**Comment by qiankehan** [comment]
@chunfuwen LGTM

**Review by lento-sun — APPROVED** [review]
LGTM

**Comment by Yingshun** [comment]
@chunfuwen It looks like this commit broken some existing scripts, could you please have a look?
`  (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.set_get_maxdowntime_during_migrate.with_postcopy: ERROR: name 'DriverMetadata' is not defined (68.63 s)`

**Traceback:**
```

2021-03-07 23:54:43,170 test             L0915 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/migration/migrate_options_shared.py", line 1259, in run
    libvirt.set_vm_disk(vm, params)

2021-03-07 23:54:43,170 test             L0915 ERROR|   File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/utils_test/libvirt.py", line 2636, in set_vm_disk
    vmxml.del_device(disk_)

2021-03-07 23:54:43,170 test             L0915 ERROR|   File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/libvirt_xml/vm_xml.py", line 1504, in del_device
    if device_value == value:

2021-03-07 23:54:43,170 test             L0915 ERROR|   File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/libvirt_xml/base.py", line 82, in __eq__
    return dict_1 == dict_2

2021-03-07 23:54:43,170 test             L0915 ERROR|   File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/libvirt_xml/devices/disk.py", line 639, in __eq__
    return super(DriverMetadata, obj).__eq__(other)

2021-03-07 23:54:43,170 test             L0915 ERROR| NameError: name 'DriverMetadata' is not defined

```

**Pull request merged**
