### PR TITLE
qcontainer: Correct AAVMF_VARS if image has backing file

### PR DESCRIPTION
**Pull request by PaulYuuu**
When the bootable image has a backing file, the current code could not
boot up the guest with the correct AAVMF_VARS.fd, this may lead to
the risk that guest will not start.

ID: 1854032
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
```bash
$ qemu-img info -U /home/kvm_autotest_root/images/sn1.qcow2  --output=json
{
    "backing-filename-format": "qcow2",
    "virtual-size": 21474836480,
    "filename": "/home/kvm_autotest_root/images/sn1.qcow2",
    "cluster-size": 65536,
    "format": "qcow2",
    "actual-size": 213520384,
    "format-specific": {
        "type": "qcow2",
        "data": {
            "compat": "1.1",
            "lazy-refcounts": false,
            "refcount-bits": 16,
            "corrupt": false
        }
    },
    "full-backing-filename": "/home/kvm_autotest_root/images/rhel830-aarch64-virtio-scsi.qcow2",
    "backing-filename": "/home/kvm_autotest_root/images/rhel830-aarch64-virtio-scsi.qcow2",
    "dirty-flag": false
}

$ ls /home/kvm_autotest_root/images/ | grep -E "sn|rhel830-aarch64-virtio-scsi"
rhel830-aarch64-virtio-scsi_AAVMF_VARS.fd
rhel830-aarch64-virtio-scsi.qcow2
rhel830-aarch64-virtio-scsi.qcow2.backup
sn1_AAVMF_VARS.fd
sn1.qcow2
```

Test result before patching:
qemu command:
```
/usr/libexec/qemu-kvm \
    -name 'avocado-vt-vm1'  \
    -drive file=/usr/share/AAVMF/AAVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on \
    -drive file=/var/lib/avocado/data/avocado-vt/images/sn1_AAVMF_VARS.fd,if=pflash,format=raw,unit=1 \
    -machine virt,gic-version=host \
    -nodefaults \
    -device pcie-root-port,id=pcie-root-port-1,port=0x1,addr=0x1.0x1,bus=pcie.0,chassis=2 \
    -device virtio-gpu-pci,bus=pcie-root-port-1,addr=0x0 \
    -m 43008  \
    -smp 22,maxcpus=22,cores=11,threads=1,sockets=2  \
    -cpu 'host' \
    -serial unix:'/var/tmp/avocado_894o9rcq/serial-serial0-20200628-055153-AW87zf2L',server,nowait \
    -device pcie-root-port,id=pcie-root-port-2,port=0x2,addr=0x1.0x2,bus=pcie.0,chassis=3 \
    -blockdev node-name=file_image1,driver=file,aio=threads,filename=/home/kvm_autotest_root/images/sn1.qcow2,cache.direct=on,cache.no-flush=off \
    -blockdev node-name=drive_image1,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_image1 \
    -device pcie-root-port,id=pcie-root-port-3,port=0x3,addr=0x1.0x3,bus=pcie.0,chassis=4 \
    -device virtio-blk-pci,id=image1,drive=drive_image1,bootindex=0,write-cache=on,bus=pcie-root-port-3,addr=0x0 \
```

Patched:
qemu command:
```
/usr/libexec/qemu-kvm \
    -name 'avocado-vt-vm1'  \
    -drive file=/usr/share/AAVMF/AAVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on \
    -drive file=/home/kvm_autotest_root/images/rhel830-aarch64-virtio-scsi_AAVMF_VARS.fd,if=pflash,format=raw,unit=1 \
    -machine virt,gic-version=host \
    -nodefaults \
    -device pcie-root-port,id=pcie-root-port-1,port=0x1,addr=0x1.0x1,bus=pcie.0,chassis=2 \
    -device virtio-gpu-pci,bus=pcie-root-port-1,addr=0x0 \
    -m 26624  \
    -smp 16,maxcpus=16,cores=8,threads=1,sockets=2  \
    -cpu 'host' \
    -serial unix:'/var/tmp/avocado__4014g3r/serial-serial0-20200706-035127-4PldDTMT',server,nowait \
    -device pcie-root-port,id=pcie-root-port-2,port=0x2,addr=0x1.0x2,bus=pcie.0,chassis=3 \
    -device qemu-xhci,id=usb1,bus=pcie-root-port-2,addr=0x0 \
    -device usb-tablet,id=usb-tablet1,bus=usb1.0,port=1 \
    -device pcie-root-port,id=pcie-root-port-3,port=0x3,addr=0x1.0x3,bus=pcie.0,chassis=4 \
    -device virtio-scsi-pci,id=virtio_scsi_pci0,bus=pcie-root-port-3,addr=0x0 \
    -blockdev node-name=file_image1,driver=file,aio=threads,filename=/home/kvm_autotest_root/images/sn1.qcow2,cache.direct=on,cache.no-flush=off \
    -blockdev node-name=drive_image1,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_image1 \
    -device scsi-hd,id=image1,drive=drive_image1,write-cache=on \
```

**Comment by PaulYuuu** [comment]
Hello @ldoktor 
I don't know much about aarch64, can you help to review this patch? Thanks.

cc @luckyh

**Comment by ldoktor** [comment]
I haven't tested it, but overall makes sense to me. @ovoshchana would you please take a look at this? (For future references Oksana took over my assignments related to arm, s390x and ppc64, you can ping her directly)

**Comment by PaulYuuu** [comment]
@ovoshchana Can you please help to review? Thank you.

**Comment by PaulYuuu** [comment]
@luckyh test results on different qemu versions.
qemu-img-rhev-2.12.0-33.el7_7.5.x86_64:
```json
qemu-img info --output=json sn.qcow2 
{
    "virtual-size": 10737418240,
    "filename": "sn.qcow2",
    "cluster-size": 65536,
    "format": "qcow2",
    "actual-size": 200704,
    "format-specific": {
        "type": "qcow2",
        "data": {
            "compat": "1.1",
            "lazy-refcounts": false,
            "refcount-bits": 16,
            "corrupt": false
        }
    },
    "full-backing-filename": "test.qcow2",
    "backing-filename": "test.qcow2",
    "dirty-flag": false
}
```

qemu-img-2.12.0-99.module+el8.2.0+5827+8c39933c.aarch64:
```json
qemu-img info --output=json sn.qcow2 
{
    "virtual-size": 21474836480,
    "filename": "sn.qcow2",
    "cluster-size": 65536,
    "format": "qcow2",
    "actual-size": 200704,
    "format-specific": {
        "type": "qcow2",
        "data": {
            "compat": "1.1",
            "lazy-refcounts": false,
            "refcount-bits": 16,
            "corrupt": false
        }
    },
    "full-backing-filename": "/home/kvm_autotest_root/images/rhel820-aarch64-virtio-scsi.qcow2",
    "backing-filename": "/home/kvm_autotest_root/images/rhel820-aarch64-virtio-scsi.qcow2",
    "dirty-flag": false
}
```

qemu-img-5.1.0-0.scrmod+el8.3.0+7384+2e5aeafb.wrb200716.aarch64:
```json
qemu-img info --output=json sn.qcow2 
{
    "virtual-size": 21474836480,
    "filename": "sn.qcow2",
    "cluster-size": 65536,
    "format": "qcow2",
    "actual-size": 200704,
    "format-specific": {
        "type": "qcow2",
        "data": {
            "compat": "1.1",
            "compression-type": "zlib",
            "lazy-refcounts": false,
            "refcount-bits": 16,
            "corrupt": false
        }
    },
    "full-backing-filename": "/home/kvm_autotest_root/images/rhel820-aarch64-virtio-scsi.qcow2",
    "backing-filename": "/home/kvm_autotest_root/images/rhel820-aarch64-virtio-scsi.qcow2",
    "dirty-flag": false
}
```

**Comment by PaulYuuu** [comment]
Full qemu command:
```
/usr/libexec/qemu-kvm \
    -S  \
    -name 'avocado-vt-vm1'  \
    -sandbox on  \
    -drive file=/usr/share/AAVMF/AAVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on \
    -drive file=/var/lib/avocado/data/avocado-vt/images/rhel820-aarch64-virtio-scsi_AAVMF_VARS.fd,if=pflash,format=raw,unit=1 \
    -machine virt,gic-version=host \
    -device pcie-root-port,id=pcie-root-port-0,multifunction=on,bus=pcie.0,addr=0x1,chassis=1 \
    -device pcie-pci-bridge,id=pcie-pci-bridge-0,addr=0x0,bus=pcie-root-port-0  \
    -nodefaults \
    -device pcie-root-port,id=pcie-root-port-1,port=0x1,addr=0x1.0x1,bus=pcie.0,chassis=2 \
    -device virtio-gpu-pci,bus=pcie-root-port-1,addr=0x0 \
    -m 5120  \
    -smp 4,maxcpus=4,cores=2,threads=1,sockets=2  \
    -cpu 'host' \
    -chardev socket,id=qmp_id_qmpmonitor1,path=/var/tmp/avocado_erh_qo9f/monitor-qmpmonitor1-20200723-021113-39Iv9lZH,server,nowait  \
    -mon chardev=qmp_id_qmpmonitor1,mode=control \
    -chardev socket,id=qmp_id_catch_monitor,path=/var/tmp/avocado_erh_qo9f/monitor-catch_monitor-20200723-021113-39Iv9lZH,server,nowait  \
    -mon chardev=qmp_id_catch_monitor,mode=control  \
    -serial unix:'/var/tmp/avocado_erh_qo9f/serial-serial0-20200723-021113-39Iv9lZH',server,nowait \
    -device pcie-root-port,id=pcie-root-port-2,port=0x2,addr=0x1.0x2,bus=pcie.0,chassis=3 \
    -device qemu-xhci,id=usb1,bus=pcie-root-port-2,addr=0x0 \
    -device usb-tablet,id=usb-tablet1,bus=usb1.0,port=1 \
    -device pcie-root-port,id=pcie-root-port-3,port=0x3,addr=0x1.0x3,bus=pcie.0,chassis=4 \
    -device virtio-scsi-pci,id=virtio_scsi_pci0,bus=pcie-root-port-3,addr=0x0 \
    -drive id=drive_image1,if=none,snapshot=off,aio=threads,cache=none,format=qcow2,file=/home/kvm_autotest_root/images/sn1.qcow2 \
    -device scsi-hd,id=image1,drive=drive_image1 \
    -device pcie-root-port,id=pcie-root-port-4,port=0x4,addr=0x1.0x4,bus=pcie.0,chassis=5 \
    -device virtio-net-pci,mac=9a:ab:1f:08:54:2a,rombar=0,id=idJWXTTK,netdev=idgwmw8m,bus=pcie-root-port-4,addr=0x0  \
    -netdev tap,id=idgwmw8m,vhost=on,vhostfd=20,fd=16  \
    -vnc :0  \
    -rtc base=utc,clock=host,driftfix=slew \
    -enable-kvm \
    -device pcie-root-port,id=pcie_extra_root_port_0,multifunction=on,bus=pcie.0,addr=0x2,chassis=6 \
    -device pcie-root-port,id=pcie_extra_root_port_1,addr=0x2.0x1,bus=pcie.0,chassis=7
```

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
