### PR TITLE
avocado-vt: add coding style file

### PR DESCRIPTION
**Pull request by xutian**
HI All,

Copied coding style file from auotest project to here and some small update,  please help to review. And any comments on it are welcome.

Thanks,
Xu

### CODE REVIEW

**Comment by PandaWei** [comment]
Importing the coding style spec is needed.
But we need update the example, which includes some old and discarded modules or class. such as AutoservError declared in Autotest.

**Comment by xutian** [comment]
@PandaWei  thanks your comments,  commit updated, would you like to help review it, thanks.

**Comment by xutian** [comment]
close it to re-trigger CI checking

**Comment by will-Do** [comment]
Good to see this

**Pull request merged**
