### PR TITLE
Add OpenSUSE Leap 42.3 guest and OpenSUSE-Leap-42.3.xml

### PR DESCRIPTION
**Pull request by morecache**
Signed-off-by: Lin Ma <lma@suse.com>

### CODE REVIEW

**Comment by morecache** [comment]
Directly copied OpenSUSE-Leap-42.2.xml to OpenSUSE-Leap-42.3.xml

avocado run --vt-type qemu --vt-guest-os Linux.OpenSUSE.42.3.x86_64.i440fx io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native                                                               
JOB ID     : fd07ff1724a2511237b80b6bfb3e3ee920d75e09
JOB LOG    : /root/avocado/job-results/job-2017-07-28T15.53-fd07ff1/job.log
 (1/1) io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native: PASS (836.84 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 839.34 s

**Comment by luckyh** [comment]
@morecache looks like the content of `OpenSUSE-Leap-42.3.xml` is same as `OpenSUSE-Leap-42.2.xml`, so my question is can all `OpenSUSE-Leap-42` share a same autoyast file?

**Comment by morecache** [comment]
@luckyh Indeed, They are same. So I think a OpenSUSE-Leap-42 autoyast file can serve for all 42.x guests.
So I'll separate original commit to 2 commits, one for adding 42.3 guest cfg, another for using OpenSUSE-Leap-42.xml for all 42.x guests.

**Comment by morecache** [comment]
avocado run --vt-type qemu --vt-guest-os Linux.OpenSUSE.42.1.x86_64.i440fx io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native
JOB ID     : 7083cd639e1b1a6cf4e0816c6586933ed1e24dc1
JOB LOG    : /root/avocado/job-results/job-2017-08-07T10.57-7083cd6/job.log
 (1/1) io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native: PASS (375.61 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 378.00 s


avocado run --vt-type qemu --vt-guest-os Linux.OpenSUSE.42.2.x86_64.i440fx io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native
JOB ID     : 09f9fc10cd2aec301d62c66f6bbd25ee17c41e15
JOB LOG    : /root/avocado/job-results/job-2017-08-07T11.08-09f9fc1/job.log
 (1/1) io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native: PASS (671.95 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 674.45 s


avocado run --vt-type qemu --vt-guest-os Linux.OpenSUSE.42.3.x86_64.i440fx io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native
JOB ID     : 66d5df84d0f69b857d9f49919d8a386092d986dd
JOB LOG    : /root/avocado/job-results/job-2017-08-07T11.30-66d5df8/job.log
 (1/1) io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native: PASS (789.42 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 791.80 s

@luckyh Could you please help to review the 2 new commits? Thanks

**Pull request merged**
