### PR TITLE
virt_vm: Enable the logging of session for VM

### PR DESCRIPTION
**Pull request by YongxueHong**
Signed-off-by: Yongxue Hong <yhong@redhat.com>

ID: 1938643

### CODE REVIEW

**Comment by YongxueHong** [comment]
Hi @zhenyzha @yanan-fu @luckyh @huangyum @lijinlijin 
Please help me to review it, thanks.

**Review by huangyum — APPROVED** [review]
LGTM, 
test works fine.

**Comment by zhenyzha** [comment]
On rhel.8.5.0 aarch64
git am 2983.patch 
Applying: virt_vm: Enable the logging of session

Can get `session-avocado-vt-vm1-06-29-02-45-01-CsTP.log`

On rhel.9.0 aarch64
git am 2983.patch 
Applying: virt_vm: Enable the logging of session

Can get `session-avocado-vt-vm1-06-29-03-15-01-cYD6.log`

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Comment by lijinlijin** [comment]
@leidwang Could you have a review?

**Comment by yanan-fu** [comment]
I prefer remove `log_function` in aexpect, with the setting of `log_filename`,  log can be saved automatically to the file.  However, I am ok with current change too.

My concern is,  `remote_login`  is not used by `virt_vm` only, this change can not fix all the problem.

**Comment by leidwang** [comment]
Tested this patch on my host,can get 
`session-avocado-vt-vm1-06-29-10-54-05-TBve.log  

session-avocado-vt-vm1-06-29-10-54-20-cURs.log`.

Acked-by:Leidong Wang <leidwang@redhat.com>

**Comment by yanan-fu** [comment]
@YongxueHong  If no requirement for other sessions except the wait_for_login session, i am ok with this change.

Ack,  Thanks!

**Review by luckyh — APPROVED** [review]
LGTM

**Comment by luckyh** [comment]
Thanks to all.

**Pull request merged**
