### PR TITLE
Correcting code styling checks.

### PR DESCRIPTION
**Pull request by TasmiyaNalatwad**

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
@TasmiyaNalatwad thanks this PR will address CI issue which is caused by  https://github.com/avocado-framework/avocado-vt/actions/runs/10344914789/job/28631156995

**Review by harihare — APPROVED** [review]
LGTM

**Comment by PraveenPenguin** [comment]
@clebergnu please have look on this PR

**Review by clebergnu — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
