### PR TITLE
base_installer: replace test.srcdir with test.workdir

### PR DESCRIPTION
**Pull request by hereischen**
The test's "srcdir" property is deprecated and is planned to be
removed no later than May 11 2018. So replaced test.srcdir with
test.workdir.
Also changed variable name accordingly.

Please refer to:
avocado-framework/avocado#2509

Signed-off-by: Haotong Chen <hachen@redhat.com>

id: 1568659

### CODE REVIEW

**Comment by chunfuwen** [comment]
see PR #https://github.com/avocado-framework/avocado/pull/2558
test.workdir permission is 0771, but its parent permission 0700, please make sure whether this don't impact your situation.

**Comment by hereischen** [comment]
@chunfuwen  Thanks for your reminder. I have tested it on Python 2.7, it works fine.

**Comment by hereischen** [comment]
Updated commit msg to reference avocado-framework/avocado#2509

**Comment by xutian** [comment]
Looks OK to me

**Pull request merged**
