### PR TITLE
Fix o_direct access deny issue in setup_or_cleanup_iscsi

### PR DESCRIPTION
**Pull request by chunfuwen**
This issue happen when tmp is tmpfs filesystem

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
Just use one cases to validate the minor change will not impact current cases:
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.scsi3_persistent_reservation.reservations_managed.hotplug_disk.disable_auth

**Comment by chunfuwen** [comment]
@kylazhang 
@dzhengfy 
please help take  a look

**Comment by dzhengfy** [comment]
@chunfuwen iscsi issue has already been fixed in https://github.com/avocado-framework/avocado-vt/pull/3011.

**Review by dzhengfy — COMMENTED** [review]
See https://github.com/avocado-framework/avocado-vt/pull/3011

**Comment by chunfuwen** [comment]
close it ,just monitor #3011

**Pull request closed without merging**
