### PR TITLE
Plug 'vfio-pci' into pcie-root-port instead of pcie.0

### PR DESCRIPTION
**Pull request by quanwenli**
id: 1866237

Signed-off-by: Wenli Quan <wquan@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@yanan-fu @jingzhao84 Request for your review, thanks.

**Comment by yanan-fu** [comment]
call for test result, thanks!

**Comment by quanwenli** [comment]
@yanan-fu update results and qemu command in bug.

**Comment by yanan-fu** [comment]
Let me copy it to here from the bz:
```
    -device pcie-root-port,id=pcie-root-port-4,port=0x4,addr=0x1.0x4,bus=pcie.0,chassis=5 \
    -device vfio-pci,host=06:10.2,id=id_06.10.2,bus=pcie-root-port-4,addr=0x0  \
```

**Comment by yanan-fu** [comment]
The change looks good to me.
How about use commit info like: `Make 'vfio-pci' device get correct parrent bus as it's pcie device` ?

**Comment by vivianQizhu** [comment]
> The change looks good to me.
> How about use commit info like: `Make 'vfio-pci' device get correct parrent bus as it's pcie device` ?

Or `Plug  'vfio-pci' into pcie-root-port instead of pcie.0'

**Comment by quanwenli** [comment]
@vivianQizhu @yanan-fu , I have update commit info ,please help review.

**Comment by yanan-fu** [comment]
> @vivianQizhu @yanan-fu , I have update commit info ,please help review.

And the PR title ?

**Comment by vivianQizhu** [comment]
Thanks @quanwenli  @yanan-fu

**Pull request merged**
