### PR TITLE
virttest.qemu_monitor: Avoid circular dependency

### PR DESCRIPTION
**Pull request by ldoktor**
The `Monitor` object is usually part of `VM`, but at the same time it
requires `VM` in order to be created. This brings circular dependency
which breaks pickle makes it impossible to load the state of the running
VM. There are two ways, one is to clean `Monitor` to not contain `VM`,
which would be cleaner, but it'd require changes to all places where
`Monitor` is created and as this would be a very intrusive change
probably breaking many downstream versions, let's simply fake the VM
object and create a dummy class with the important information (the
name) stored there. It's not nice, but it allows keeping the API
unchanged.

This patch is necessary in order to be able to load the env file with a
running VM, eg. for keep_guest_running feature, or when cleaning-up is
disabled and the test fails. For example when `boot.py` test raises
exception and is executed by:

    avocado --show all run boot --vt-extra-params 'kill_vm=no' \
    'kill_vm_on_error=no'

(reported by Andrei Stepanov)

@Andrei-Stepanov could you please verify this works for you?

### CODE REVIEW

**Comment by ldoktor** [comment]
@xutian, @Hao-Liu can you please take a look at this? It's a fix for issue found by @Andrei-Stepanov and @rdkdd.

**Comment by rdkdd** [comment]
Hi @ldoktor unfortunatelly your patch does not work for me. I have got the same Exception as before:
tried:

> avocado --show all run boot --vt-extra-params 'kill_vm=no' 'kill_vm_on_error=no'

raised:
> root: Exception thrown while loading env
> 
> root: (AttributeError("'VM' object has no attribute 'name'",), <class virttest.qemu_monitor.HumanMonitor at 0x3aaa9a8>, (<virttest.qemu_vm.VM object at 0x3ff3e90>, 'hmp1', '/var/tmp/avocado_krcE_b/monitor-hmp1-20170221-111125-4FKjTyG0', False))
> root: Creating new, empty env file
> Exception AttributeError: "HumanMonitor instance has no attribute 'open_log_files'" in <bound method HumanMonitor.__del__ of <virttest.qemu_monitor.HumanMonitor instance at 0x3ebc638>> ignored

**Comment by ldoktor** [comment]
Can you please attach your results? It works for me:

avocado: 7d682b9d0c4c1f1ce27467cfce8432c15bf5045c
avocado-vt: b6bdd4deb805901ecc329bc6bba88420abaf98b3

[results.zip](https://github.com/avocado-framework/avocado-vt/files/790514/results.zip)

**Comment by Andrei-Stepanov** [comment]
@ldoktor 

we cannot use: avocado: 7d682b9d0c4c1f1ce27467cfce8432c15bf5045c
We use Avocado LTS. It is a part of beaker task.

We install avocado LTS using:

pip install avocado-framework==36

for avocado-vt is installed the latest master:

readonly IN_AVOCADO_VT_PIP_REQ="${IN_AVOCADO_VT_PIP_REQ:-https://raw.githubusercontent.com/avocado-fram  ework/avocado-vt/master/requirements.txt}"

readonly IN_AVOCADO_VT_PIP_URL="${IN_AVOCADO_VT_PIP_URL:-git+git://github.com/avocado-framework/avocado  -vt#egg=avocado-plugins-vt}"


pip install -r \"$IN_AVOCADO_VT_PIP_REQ\""
pip install -e \"$IN_AVOCADO_VT_PIP_URL\""

https://www.redhat.com/archives/avocado-devel/2017-February/msg00001.html

**Comment by ldoktor** [comment]
avocado: 4c6f23ed8945c4fbe501f4950a02294fc206f5b8 (latest master on 36lts)
avocado-vt: b6bdd4d

[job-2017-02-22T09.54-32b92bb.zip](https://github.com/avocado-framework/avocado-vt/files/792728/job-2017-02-22T09.54-32b92bb.zip)

Still it's passing on my machine. Are you sure you applied this patch to test it?

**Comment by rdkdd** [comment]
hi @ldoktor  I had to use Avocado version: 36.0lts 
and your pr applied to master:
```
git log --oneline:
f7ddd4a virttest.qemu_monitor: Avoid circular dependency
cb4f970 Merge pull request #891 from Hao-Liu/fix_get_all_node_meminfo
328b898 Merge pull request #878 from suqinhuang/maxmem
8175748 utils_misc: Fix function name scope typos
```
I introduced your error to `boot.py`. But the error I mentioned is there with or without indtroduced error
[results.zip](https://github.com/avocado-framework/avocado-vt/files/793069/results.zip)

**Comment by ldoktor** [comment]
From your job.log I can see that you are not running with the fix applied. Perhaps you combine develop and installed version and the installed version takes precedence?

```
2017-02-22 11:13:37,316 test             L0222 INFO | Avocado-VT '46.0-10-gcb4f', Branch 'master', SHA1 'cb4f970c38482b4cd79094e10c04961235028b8b'
```

**Comment by ldoktor** [comment]
Btw the avocado version should not really matter, the avocado-vt is what matters...

**Comment by rdkdd** [comment]
sorry for confusion @ldoktor. I didn't know that the location of our utilized avocado-vt directory was changed. So now I can confirm that your patch is a remedy. Former error did not occured again.
[results.zip](https://github.com/avocado-framework/avocado-vt/files/793187/results.zip)

**Comment by ldoktor** [comment]
Cool, with this said @xutian, @Hao-Liu, @will-Do would you please take a look at it?

**Comment by will-Do** [comment]
looks good, thanks

**Comment by xutian** [comment]
Looks Ok to me, thanks @ldoktor

**Pull request merged**
