### PR TITLE
Typo fix serial commented out to serials in base.cfg

### PR DESCRIPTION
**Pull request by MiriamDeng**
Modify minor error in base.cfg,which is variant of serial commented out to serials
Signed-off-by: MiramDeng mdeng@redhat.com

### CODE REVIEW

**Comment by MiriamDeng** [comment]
Bug 1336253

**Comment by will-Do** [comment]
Recommend to update the commit  summary, such as: typo fix

**Comment by mazhang** [comment]
Acked-by: Maosheng Zhang mazhang@redhat.com

**Comment by xutian** [comment]
@MiriamDeng  agree with comment#3,  please update your commit summary

**Comment by MiriamDeng** [comment]
@xutian,Update again,please have a look if you are free.

**Comment by PandaWei** [comment]
LGTM

**Comment by xutian** [comment]
thanks @MiriamDeng . Merged

**Pull request merged**
