### PR TITLE
Set value to args timeout

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 1714061

### CODE REVIEW

**Comment by XueqiangWei** [comment]
Test 300 times, both linux and windows guest are all passed.

004-repeat1.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_reboot.during_bg_test.q35
005-repeat1.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_reboot.after_bg_test.q35
006-repeat1.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.data_disk.with_live_migration.before_bg_test.q35
007-repeat1.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_reboot.during_bg_test.q35
008-repeat1.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_reboot.after_bg_test.q35
009-repeat1.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.data_disk.with_live_migration.before_bg_test.q35

**Comment by XueqiangWei** [comment]
@YongxueHong @peixiu @xiagao @kimi1978wy  please help review it. Many thanks.

**Comment by YongxueHong** [comment]
LGTM

**Comment by luckyh** [comment]
LGTM, but I'd like to request a reasonable commit message, thanks.

**Comment by xiagao** [comment]
Looks good to me. 
And test balloon driver for ten times,all pass.
 (01/10) repeat1.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.balloon_hotplug.with_reboot: PASS (388.17 s)
 (02/10) repeat2.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.balloon_hotplug.with_reboot: PASS (380.28 s)
 (03/10) repeat3.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.balloon_hotplug.with_reboot: PASS (408.02 s)
 (04/10) repeat4.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.balloon_hotplug.with_reboot: PASS (390.51 s)
 (05/10) repeat5.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.balloon_hotplug.with_reboot: PASS (383.10 s)
 (06/10) repeat6.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.balloon_hotplug.with_reboot: PASS (386.33 s)
 (07/10) repeat7.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.balloon_hotplug.with_reboot: PASS (381.74 s)
 (08/10) repeat8.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.balloon_hotplug.with_reboot: PASS (396.84 s)
 (09/10) repeat9.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.balloon_hotplug.with_reboot: PASS (376.07 s)
 (10/10) repeat10.Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.balloon_hotplug.with_reboot: PASS (379.48 s)

**Comment by peixiu** [comment]
Looks good to me~
Acked-by: Peixiu Hou phou@redhat.com

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
