### PR TITLE
add function to test device is a virtio pcie device

### PR DESCRIPTION
**Pull request by xutian**
ID: 1810419

Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by peixiu** [comment]
LGTM and tested with code, the device connect as expected, thanks~
    -device pcie-root-port,id=pcie-root-port-4,port=0x4,addr=0x1.0x4,bus=pcie.0,chassis=5 \
    -device virtio-keyboard-pci,id=input_input1,bus=pcie-root-port-4,addr=0x0 \

Acked-By: Peixiu Hou phou@redhat.com

**Comment by yanan-fu** [comment]
I am not confident about all the devices, it is better to test the new added device:
`virtio-input-host-pci`, `virtio-mouse-pci`, `virtio-tablet-pci`, `virtio-vga`, these devices will be add to `pcie-root-port` too. @peixiu  could you help confirm this ?

**Comment by yanan-fu** [comment]
@xutian  will this effect the virtio-bus ?

**Comment by xutian** [comment]
@yanan-fu   all virtio device use virtio-pci and virtio-pci follow PCI spec, so plug it into pcie-root-port is expected.

**Comment by peixiu** [comment]
Hi yfu, I tested  `virtio-input-host-pci`, `virtio-mouse-pci`, `virtio-tablet-pci`, all devices can be default connected to pcie-root-port(multifunction=on) bus as expected, as:
-device pcie-root-port,id=pcie-root-port-4,port=0x4,addr=0x1.0x4,bus=pcie.0,chassis=5 \
-device virtio-input-host-pci,id=input_input1,evdev=/dev/input/by-path/pci-0000:00:14.0-usb-0:2.1:1.0-event-kbd,bus=pcie-root-port-4,addr=0x0 \

-device pcie-root-port,id=pcie-root-port-4,port=0x4,addr=0x1.0x4,bus=pcie.0,chassis=5 \
-device virtio-mouse-pci/virtio-tablet-pci,id=input_input1,bus=pcie-root-port-4,addr=0x0 \

But for your mentioned "virtio-vga", I cannot find any case need test virtio-vga device, I only find a regular VGA device connected to vm(not virtio-vga), could you mean this device?
and for regular VGA device, it connect to pcie.0 default, this code will not impact this device, default command as: -device VGA,bus=pcie.0,addr=0x2 \ 

And Hi xutian,

I have a questions here, as we known, one pcie-root-port with multifunction=on parent bus can connect 8 child pcie-root-port device at most. Will a new parent bus be opened if a parent bus is full? 

Thanks~
Peixiu

**Comment by xutian** [comment]
@peixiu  yes, if no available pcie-root-port when insert device, framework will add a new pcie-root-port with mmulti-function=on, then plug pcie device to the new pcie-root-port.

**Pull request merged**
