### PR TITLE
qemu_vm: Amend the issue of "no attribute monitor"

### PR DESCRIPTION
**Pull request by YongxueHong**
Amend the issue that "AttributeError: module 'qemu_migration'
has no attribute 'monitor'".

Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
Hi @luckyh  @pevogam  @leexiaohui32
Would you like to help me to review it?
Thanks a lot.

**Review by luckyh — APPROVED** [review]

**Review by pevogam — APPROVED** [review]
LGTM

**Comment by YongxueHong** [comment]
Thanks all, let's merge it.

**Comment by pevogam** [comment]
@YongxueHong Is this PR ready to merge or we need more approvals? Sorry once again that I delayed it on my side.

**Comment by YongxueHong** [comment]
> @YongxueHong Is this PR ready to merge or we need more approvals? Sorry once again that I delayed it on my side.

Hi @pevogam 
Yeah, I need one more approval from our side, sorry for that.
Hi @leexiaohui32
Would you like to help to review it?
Thanks.

**Comment by leexiaohui32** [comment]
LGTM

**Comment by pevogam** [comment]
Hi @YongxueHong the project workflow generally requires two reviews and it doesn't mention that the two reviews should be from maintainers. Thanks for merging this.

**Pull request merged**
