### PR TITLE
Style check based on black

### PR DESCRIPTION
**Pull request by clebergnu**
Avocado has been using black to enforce a code style for a long time now, with very good results.  Let's expand the same to Avocado-VT. With a common code style across Avocado and Avocado-VT it'll be easier to move libraries to the common autils repo.

Reference: https://github.com/avocado-framework/autils/issues/3

### CODE REVIEW

**Review by richtja — APPROVED** [review]
Hi @clebergnu it LGTM, but I was able to review only the black enablement related changes, not the style changes itself (I presume they were made by black). Because of this, I think it is necessary to test these changes with some real avocado-vt test suite. @luckyh can you or any of avocado-vt maintainers test this with some bigger avocado-vt test suite?

**Comment by luckyh** [comment]
@YongxueHong @vivianQizhu @chloerh @dzhengfy @chunfuwen adding you to this thread as well for your awareness, thanks.

**Comment by luckyh** [comment]
@yanan-fu would you mind to help trigger a big test loop to verify this? thanks in advance!

**Comment by clebergnu** [comment]
@yanan-fu did you get a chance to test this?

**Comment by clebergnu** [comment]
Hi @luckyh @yanan-fu, let me know if you are able to advance the review of this PR.  Thanks!

**Comment by luckyh** [comment]
> let me know if you are able to advance the review of this PR. Thanks!

Hi @clebergnu , sorry for the late response (just came back from leave). Apart from needing to resolve the conflicts it LGTM. Thanks!

**Comment by yanan-fu** [comment]
> @yanan-fu did you get a chance to test this? Thanks in advance!

Hi @clebergnu , sorry for the late reply as Holiday and PTOs, as patch conflict, it can not be applied successfully.
Could you please resolve the conflict and i can start the test ASAP, thanks a lot!

**Comment by clebergnu** [comment]
> > @yanan-fu did you get a chance to test this? Thanks in advance!
> 
> Hi @clebergnu , sorry for the late reply as Holiday and PTOs, as patch conflict, it can not be applied successfully. Could you please resolve the conflict and i can start the test ASAP, thanks a lot!

Hi @yanan-fu,

Conflicts have been resolved with a rebase.  Please note that new conflicts will most certainly appear as other PRs are merged.

Thanks.

**Comment by yanan-fu** [comment]
> > > @yanan-fu did you get a chance to test this? Thanks in advance!
> > 
> > 
> > Hi @clebergnu , sorry for the late reply as Holiday and PTOs, as patch conflict, it can not be applied successfully. Could you please resolve the conflict and i can start the test ASAP, thanks a lot!
> 
> Hi @yanan-fu,
> 
> Conflicts have been resolved with a rebase. Please note that new conflicts will most certainly appear as other PRs are merged.
> 
> Thanks.

@clebergnu Regression test in on going, result will be  commented soon.

**Comment by yanan-fu** [comment]
Regression test all PASS.

LGTM,  I think it is time to resolve the conflict and merge it now.  Thanks all!

**Comment by clebergnu** [comment]
> Regression test all PASS.
> 
> LGTM, I think it is time to resolve the conflict and merge it now. Thanks all!

Thanks @yanan-fu.  I'm considering your ACK on the regression testing a second positive review, and will expedite the merge of these changes to avoid further conflicts (once CI checks pass).

**Pull request merged**
