### PR TITLE
qcontainer: fix arm64-pci machine bus type

### PR DESCRIPTION
**Pull request by rayx**
I made two changes:

- change machine's bus type to pcie
- remove virtio-mmio-bus. 

While virt machine type on aarch64 always creates some virtio-mmio buses for connecting on-board devices, I don't think they are useful in tests on 'arm64-pci' configuration. So I remove it. Please correct me if I'm wrong.

I verified the patch with a few tests and it worked fine in my experiments.

### CODE REVIEW

**Comment by vivianQizhu** [comment]
It looks okay for me, but I am not quite sure about arm test requirement..

**Comment by ldoktor** [comment]
Hello @rayx, thank you for this. The MMIO is a bit controversial, but I have nothing against and think it's better to remove it. People can still use MMIO in tests directly without the Avocado support, while MMIO won't be used unexpectedly when using the PCI machine.

The pci support, it's not change of type, you just add the root-port type, which was left out on arm when introducing the support for it, so thank you for this fix.

Before my ack I'd like to ask you to split the patches as they tackle 2 different things and in case they break some tests it should be easier to bisect.

**Comment by rayx** [comment]
@luckyh Thanks for your review and suggestion for git cola. I have a question on how to split the changeset into two ones though. My current change is effectively to replace machine device's child bus from MMIO bus object to PCIE bus object. This is a replace operation, so the two changes (removing the MMIO bus and appending PCIE bus) should be made at the same time. How can that be done in two steps in a meaningful way? I mean, it doesn't seem to work if I append the PCIE bus in patch 1 and remove MMIO in patch 2, because appending PCIE bus object in patch1 effectively removes MMIO bus object from the device hierarchy and renders it useless.

**Comment by rayx** [comment]
@luckyh Or maybe I misunderstand it. Can these two lines of code coexist? (I suppose not.)

            devices.append(qdevices.QStringDevice('machine', cmdline=cmd,
                                                  child_bus=bus,
                                                  aobject="virtio-mmio-bus"))

and

            devices.append(qdevices.QStringDevice('machine', cmdline=cmd,
                                                  child_bus=bus,
                                                  aobject="pci.0"))

**Comment by luckyh** [comment]
@rayx ok, I didn't try it, just wanted to help you figure out what @ldoktor suggested, so let's wait for his reply, thanks.

**Comment by rayx** [comment]
@luckyh No problem. I just realized I made a mistake. The above comments were for @ldoktor but I tagged you. I fixed them just now. Sorry for that.

**Comment by luckyh** [comment]
@rayx ok, no problem.

**Comment by ldoktor** [comment]
Hello @rayx, yes, I wanted you to split it exactly as @luckyh mentioned in https://github.com/avocado-framework/avocado-vt/pull/1879#issuecomment-455028559

As for the issue you still need to request the extra root ports:

```diff
diff --git a/shared/cfg/machines.cfg b/shared/cfg/machines.cfg
index 5476ed29..400ffc39 100644
--- a/shared/cfg/machines.cfg
+++ b/shared/cfg/machines.cfg
@@ -63,6 +63,7 @@ variants:
         # Only virtio-gpu-pci supported for now
         vga = virtio
         vir_domain_undefine_nvram = yes
+        pcie_extra_root_port = 3
     - riscv64-mmio:
         only riscv64
         # USB subsystem not available
```

**Comment by ldoktor** [comment]
Btw with this fix applied and the "pcie_extra_root_port=3" set on the command line hotplug wokrs well on my machine:

`avocado --show all run --vt-machine-type aarch64 --vt-arch arm64-pci block_hotplug.default.block_virtio.fmt_qcow2.with_plug.default.one_pci --vt-qemu-bin /usr/local/bin/qemu-system-aarch64 --vt-extra-params enable_kvm=no cpu_model=cortex-a57 cpu_model_extra_params='' sha1sum_vmlinuz=a sha1sum_initrd=a machine_type=arm64-pci:virt machine_type_extra_params='' pcie_extra_root_port=3
`

**Comment by rayx** [comment]
@ldoktor Sorry for the confusion. I tried it again and it worked. I have no idea why it didn't before (I set pcie_extra_root_port). With the patch 1, the code becomes:

     1      bus = qdevices.QNoAddrCustomBus('bus', [['addr'], [32]],
                                            'virtio-mmio-bus', 'virtio-bus',
                                            'virtio-mmio-bus')
     2      devices.append(qdevices.QStringDevice('machine', cmdline=cmd,
                                                  child_bus=bus,
                                                  aobject="virtio-mmio-bus"))
            # And this is the pcie bus
     3      bus = (qdevices.QPCIEBus('pcie.0', 'PCIE', root_port_type, 'pci.0'),
                        qdevices.QStrictCustomBus(None, [['chassis'], [256]],
                                             '_PCI_CHASSIS', first_port=[1]),
                        qdevices.QStrictCustomBus(None, [['chassis_nr'], [256]],
                                             '_PCI_CHASSIS_NR', first_port=[1]))
     4       devices.append(qdevices.QStringDevice('pci.0', child_bus=bus,
                                                  aobject="pci.0"))
     5       devices.append(qdevices.QStringDevice('gpex-root',
                                                  {'addr': 0, 'driver': 'gpex-root'},
                                                  parent_bus={'aobject': 'pci.0'}))

May I ask what's the meaning of line 4? 

Question 1: If I understand it correctly, the line 4 creates a string device whose name is "pci.0", and has child buses, which contains pcie.0. So is 'pci.0' the PCIE root complex? If so, the name is confusing. On the other hand, however, line 5 seems to suggest 'pci.0' is a bus, instead of a device.

Question 2: How come both the 'pcie.0' QPCIEBus device and the 'pci.0' QStringDevice device are associated with a same 'pci.0' aobject?

**Comment by rayx** [comment]
@ldoktor Also, how do you think about adding this line to arm64-pci in machines.cfg by default?

        pcie_extra_root_port = 3

Many hotplug tests don't set this parameter in their config and therefore fail on arm64-pci.

**Comment by ldoktor** [comment]
Hello @rayx, to be honest I haven't read it that carefully before. Anyway the first item of the string device should be device ID, so to be strictly compliant it should be `''`. But historically we used `pci.0` as some old versions of qemu used that by default. Changing it to `machine` should not harm but is not really helping.

As for the code (let's use the final version):

```python
            devices = []
# initialize objects to be returned
            devices.append(qdevices.QStringDevice('AAVMF_VARS',
                                                  cmdline=aavmf_vars))
# creates fake device to represent aavmf vars
            bus = (qdevices.QPCIEBus('pcie.0', 'PCIE', root_port_type, 'pci.0'),
                   qdevices.QStrictCustomBus(None, [['chassis'], [256]],
                                             '_PCI_CHASSIS', first_port=[1]),
                   qdevices.QStrictCustomBus(None, [['chassis_nr'], [256]],
                                             '_PCI_CHASSIS_NR', first_port=[1]))
# creates 3 buses:
#    1. pcie.0 bus of type PCIE, using root_port_type as default root-port and
#        representing it as "pci.0" in avocado representation (basically it means
#        main-pci-bus, but for historical reasons it's called pci.0
#    2. fake, unnamed bus "chassis" that assigns chasis
#    3. fake, unnamed bus "chassis_nr" that assigns "chassis_nr"
# at this point the bus is not connected to any device, therefor does nothing
            devices.append(qdevices.QStringDevice('machine', cmdline=cmd,
                                                  child_bus=bus,
                                                  aobject="pci.0"))
# Here device, that should have id 'machine', is created, is associated with the
# -machine... options and contains the 3 buses. To Avocado-vt it's internally
# called 'pci.0' again, to be able to ask for the device that provides the main
# system bus. (it has nothing to do with the bus type)
            devices.append(qdevices.QStringDevice('gpex-root',
                                                  {'addr': 0, 'driver': 'gpex-root'},
                                                  parent_bus={'aobject': 'pci.0'}))
# Here `gpex-root` is created as this device is always inserted by qemu
return devices
# Returns devices and Avocado injects them into the internal representation
# using the busses to modify properties of the inserted devices (like 'addr' and
# 'bus').
```

Now looking at `qemu-system-aarch64 -cpu cortex-a57 -M virt -nodefaults -monitor stdio -S`

```
...
  dev: gpex-pcihost, id ""
    gpio-out "sysbus-irq" 4
    mmio ffffffffffffffff/0000000020000000
    mmio ffffffffffffffff/ffffffffffffffff
    mmio 000000003eff0000/0000000000010000
    bus: pcie.0
      type PCIE
      dev: gpex-root, id ""
        addr = 00.0
        romfile = ""
        rombar = 1 (0x1)
        multifunction = false
        command_serr_enable = true
        x-pcie-lnksta-dllla = true
        x-pcie-extcap-init = true
        class Host bridge, addr 00:00.0, pci id 1b36:0008 (sub 1af4:1100)
...
```

You can see our representation is not perfect (main PCI bus is called `machine` in avocado-vt's qemu representation and `` in qemu), but apart from that it does posses `pcie.0` bus and does have `gpex-root` on the `addr=0x0`.

**Comment by ldoktor** [comment]
Btw arm does not support the `qtree` comparison, but on x86 there is the functon to compare `info qtree` to our internal representation, where all ids have to match. If we ever want to implement this function for aarch64, everything would have to match including the extra devices. But at this point I don't think it's necessary so I'd simply keep the naming as is and just added the root-port and added the extra root-ports by default.

**Comment by ldoktor** [comment]
@rayx as for the `pcie_extra_root_port` by default, definitely yes, it is already the default for q35 and when https://github.com/avocado-framework/avocado-vt/pull/1878 is accepted it should not negatively affect any tests (2nd review welcome).

**Comment by rayx** [comment]
@ldoktor Thanks much for your detailed explanation. I have split the change as you suggested. Since https://github.com/avocado-framework/avocado-vt/pull/1878 is still being reviewed, I didn't set pcie_extra_root_port (Should I?)

**Comment by ldoktor** [comment]
I'd prefer adding it here to not to forget (note we can have different default for arm and x86). Anyway with or without it it looks good to me and works well:

Without this PR:
```
root: Devices of avocado-vt-vm1: [t'PREFIX',t'qemu',t'-S',t'vmname',t'AAVMF_CODE',t'AAVMF_VARS',t'machine',t'pci.0',t'gpex-root',t'nodefaults',a'virtio-gpu-pci',t'QMP-qmpmonitor1',t'QMP-catch_monitor',t'SER-serial0',t'isa-log',usb1,virtio_scsi_pci0,drive_image1,image1,idHrZTe4,t'NET-user',t'mem',t'smp',t'cpu',usb-tablet1,t'tcp-redir',t'display',t'rtc',t'bootmenu',t'nokvm']
root: Buses of avocado-vt-vm1
  drive_image1(QDrive): {drive:image1}
  virtio_scsi_pci0.0(virtio-scsi-pci): {0-0:image1}
  usb1.0(xhci): {1:usb-tablet1}
  _PCI_CHASSIS_NR(None): {}
  _PCI_CHASSIS(None): {}
  pcie.0(PCIE): {0x0-0x0:t'gpex-root',0x1-0x0:a'virtio-gpu-pci',0x2-0x0:usb1,0x3-0x0:virtio_scsi_pci0,0x4-0x0:idHrZTe4}
  virtio-mmio-bus(virtio-bus): {}




MALLOC_PERTURB_=1  /usr/local/bin/qemu-system-aarch64 \
    -S  \
    -name 'avocado-vt-vm1' \
    -drive file=/usr/share/AAVMF/AAVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on \
    -drive file=/home/medic/avocado/data/avocado-vt/images/jeos-27-aarch64_AAVMF_VARS.fd,if=pflash,format=raw,unit=1 \
    -machine virt  \
    -nodefaults \
    -device virtio-gpu-pci,bus=pcie.0,addr=0x1  \
    -chardev socket,id=qmp_id_qmpmonitor1,path=/var/tmp/avocado_SIRJqF/monitor-qmpmonitor1-20190122-142209-NBTJT0Qm,server,nowait \
    -mon chardev=qmp_id_qmpmonitor1,mode=control  \
    -chardev socket,id=qmp_id_catch_monitor,path=/var/tmp/avocado_SIRJqF/monitor-catch_monitor-20190122-142209-NBTJT0Qm,server,nowait \
    -mon chardev=qmp_id_catch_monitor,mode=control  \
    -serial unix:'/var/tmp/avocado_SIRJqF/serial-serial0-20190122-142209-NBTJT0Qm',server,nowait \
    -device qemu-xhci,id=usb1,bus=pcie.0,addr=0x2 \
    -device virtio-scsi-pci,id=virtio_scsi_pci0,bus=pcie.0,addr=0x3 \
    -drive id=drive_image1,if=none,format=qcow2,file=/home/medic/avocado/data/avocado-vt/images/jeos-27-aarch64.qcow2 \
    -device scsi-hd,id=image1,drive=drive_image1 \
    -device virtio-net-pci,mac=9a:86:87:88:89:8a,rombar=0,id=idHrZTe4,vectors=4,netdev=ider2W6O,bus=pcie.0,addr=0x4  \
    -netdev user,id=ider2W6O,hostfwd=tcp::5001-:22 \
    -m 1024  \
    -smp 2,maxcpus=2,cores=1,threads=1,sockets=2  \
    -cpu 'cortex-a57' \
    -device usb-tablet,id=usb-tablet1,bus=usb1.0,port=1  \
    -vnc :0  \
    -rtc base=utc,clock=host
```


With this PR:
```
root: Devices of avocado-vt-vm1: [t'PREFIX',t'qemu',t'-S',t'vmname',t'AAVMF_CODE',t'AAVMF_VARS',t'machine',t'gpex-root',t'nodefaults',a'virtio-gpu-pci',t'QMP-qmpmonitor1',t'QMP-catch_monitor',t'SER-serial0',t'isa-log',pcie.0-root-port-2,usb1,pcie.0-root-port-3,virtio_scsi_pci0,drive_image1,image1,pcie.0-root-port-4,idXdALjx,t'NET-user',t'mem',t'smp',t'cpu',usb-tablet1,t'tcp-redir',t'display',t'rtc',t'bootmenu',t'nokvm']
root: Buses of avocado-vt-vm1
  pcie.0-root-port-4(PCIE): {0x0-0x0:idXdALjx}
  drive_image1(QDrive): {drive:image1}
  virtio_scsi_pci0.0(virtio-scsi-pci): {0-0:image1}
  pcie.0-root-port-3(PCIE): {0x0-0x0:virtio_scsi_pci0}
  usb1.0(xhci): {1:usb-tablet1}
  pcie.0-root-port-2(PCIE): {0x0-0x0:usb1}
  _PCI_CHASSIS_NR(None): {}
  _PCI_CHASSIS(None): {}
  pcie.0(PCIE): {0x0-0x0:t'gpex-root',0x1-0x0:a'virtio-gpu-pci',0x2-0x0:pcie.0-root-port-2,0x3-0x0:pcie.0-root-port-3,0x4-0x0:pcie.0-root-port-4}


MALLOC_PERTURB_=1  /usr/local/bin/qemu-system-aarch64 \
    -S  \
    -name 'avocado-vt-vm1' \
    -drive file=/usr/share/AAVMF/AAVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on \
    -drive file=/home/medic/avocado/data/avocado-vt/images/jeos-27-aarch64_AAVMF_VARS.fd,if=pflash,format=raw,unit=1 \
    -machine virt  \
    -nodefaults \
    -device virtio-gpu-pci,bus=pcie.0,addr=0x1  \
    -chardev socket,id=qmp_id_qmpmonitor1,path=/var/tmp/avocado_17to2f/monitor-qmpmonitor1-20190122-142008-llfrh46S,server,nowait \
    -mon chardev=qmp_id_qmpmonitor1,mode=control  \
    -chardev socket,id=qmp_id_catch_monitor,path=/var/tmp/avocado_17to2f/monitor-catch_monitor-20190122-142008-llfrh46S,server,nowait \
    -mon chardev=qmp_id_catch_monitor,mode=control  \
    -serial unix:'/var/tmp/avocado_17to2f/serial-serial0-20190122-142008-llfrh46S',server,nowait \
    -device pcie-root-port,id=pcie.0-root-port-2,slot=2,chassis=2,addr=0x2,bus=pcie.0 \
    -device qemu-xhci,id=usb1,bus=pcie.0-root-port-2,addr=0x0 \
    -device pcie-root-port,id=pcie.0-root-port-3,slot=3,chassis=3,addr=0x3,bus=pcie.0 \
    -device virtio-scsi-pci,id=virtio_scsi_pci0,bus=pcie.0-root-port-3,addr=0x0 \
    -drive id=drive_image1,if=none,format=qcow2,file=/home/medic/avocado/data/avocado-vt/images/jeos-27-aarch64.qcow2 \
    -device scsi-hd,id=image1,drive=drive_image1 \
    -device pcie-root-port,id=pcie.0-root-port-4,slot=4,chassis=4,addr=0x4,bus=pcie.0 \
    -device virtio-net-pci,mac=9a:9c:9d:9e:9f:a0,rombar=0,id=idXdALjx,vectors=4,netdev=idFo4fEs,bus=pcie.0-root-port-4,addr=0x0  \
    -netdev user,id=idFo4fEs,hostfwd=tcp::5000-:22 \
    -m 1024  \
    -smp 2,maxcpus=2,cores=1,threads=1,sockets=2  \
    -cpu 'cortex-a57' \
    -device usb-tablet,id=usb-tablet1,bus=usb1.0,port=1  \
    -vnc :0  \
    -rtc base=utc,clock=host
```

So let's wait for second ack and merge it. If you happen to add the `pcie_extra_root_ports`, good, otherwise please open another PR later to not to forget.

**Pull request merged**
