### PR TITLE
guest-os: Add new filter to Win2012 cfg

### PR DESCRIPTION
**Pull request by YongxueHong**
Add the filter "with_installation" to Win2012 cfg.

ID: 1731616
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by peixiu** [comment]
(1/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd.q35: PASS (1001.64 s)
 (2/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_block.q35: PASS (892.95 s)

LGTM~
Acked-by: Peixiu Hou phou@redhat.com

**Comment by YongxueHong** [comment]
@luckyh  pls help me to review when you are free, thanks.

**Comment by luckyh** [comment]
@YongxueHong does other windows guest have this issue too?

**Comment by YongxueHong** [comment]
@luckyh , no, other windows guests are ok , I have tested them.

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
