### PR TITLE
qdevice: change acpi-index type

### PR DESCRIPTION
**Pull request by nickzhq**
ID: 2186368

### CODE REVIEW

**Comment by nickzhq** [comment]
@zhencliu @YongxueHong Please take a look, thanks!

**Comment by YongxueHong** [comment]
Please add the related bug ID in conversation 0.
Thanks.

**Comment by nickzhq** [comment]
@yanglei-rh Please take a look, thanks!

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by yanglei-rh** [comment]
Test Pass: 
(2/3) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.nic_acpi_index.boot_with_acpi: PASS (277.06 s)
 (3/3) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.nic_acpi_index.hotplug_with_acpi: PASS (459.33 s)

**Review by yanglei-rh — APPROVED** [review]

**Review by zhencliu — APPROVED** [review]

**Pull request merged**
