### PR TITLE
update utils_env

### PR DESCRIPTION
**Pull request by lolyu**
1. use with statement to replace try...finally block.
2. use functools.wraps.

Signed-off-by: lolyu <lolyu@redhat.com>

### CODE REVIEW

**Comment by lolyu** [comment]
```
# python  selftests/unit/test_utils_env.py
WARNING:root:Creating new, empty env file
..WARNING:root:Creating new, empty env file
.WARNING:root:Creating new, empty env file
.WARNING:root:Creating new, empty env file
.WARNING:root:Creating new, empty env file
.WARNING:root:Creating new, empty env file
.
----------------------------------------------------------------------
Ran 7 tests in 0.357s

OK
```

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by lolyu** [comment]
updated, thanks.

**Comment by balamuruhans** [comment]
Thanks @lolyu @hereischen.

**Pull request merged**
