### PR TITLE
qemu_vm: removing unecessary arguments inside add_{floopy,uuid,vnc...} [v2].

### PR DESCRIPTION
**Pull request by jcfaracco**
The function make_create_command() has many functions inside with unused
"devices" parameter. This parameter is not being used inside many of
them.

So, this commit clean up the functions.
Referecing the commit number: c3ae587.

This commit introduces an 'else' conditional inside add_sga() to keep the
pattern of other functions.

Signed-off-by: Julio Faracco <jcfaracco@gmail.com>

### CODE REVIEW

**Comment by PandaWei** [comment]
ACK

**Comment by will-Do** [comment]
LGTM

**Comment by PandaWei** [comment]
Thanks @jcfaracco @will-Do

**Comment by jcfaracco** [comment]
Thanks @PandaWei and @will-Do :-)

**Pull request merged**
