### PR TITLE
unattended_install:support to use cdrom metadata during installation 

### PR DESCRIPTION
**Pull request by yanan-fu**
id: 1970022
Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
@luckyh Could you help review ? Thanks!

**Comment by yanan-fu** [comment]
@PaulYuuu Could you help review ? Thanks!

**Comment by yanan-fu** [comment]
Regression test PASS:
```
1-Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads Finshed 2021-07-01 03:16:57 2021-07-01 03:28:34 PASS 697.978639
```

**Review by PaulYuuu — APPROVED** [review]

**Review by luckyh — APPROVED** [review]
LGTM

**Comment by luckyh** [comment]
Thanks to all.

**Pull request merged**
