### PR TITLE
Adding support for ubuntu 24.04 guest-os name and qcow2 image name.

### PR DESCRIPTION
**Pull request by TasmiyaNalatwad**
Creating a cfg file for Ubuntu 24.04, tested basic scenario as importing guest, running one test from lifecycle test bucket and removing guest using --guest-os Ubuntu.24.04.ppc64le  Please find the test results below.

root@localhost:/home/tests# python3 avocado-setup.py --run-suite guest_lifecycle_bck --guest-os Ubuntu.24.04.ppc64le --only-filter 'virtio_scsi virtio_net qcow2' --no-download
11:56:57 WARNING : Overriding user setting and enabling kvm bootstrap as guest tests are requested
11:56:57 INFO    : Check for environment
11:56:58 INFO    : Creating temporary mux dir
11:56:58 INFO    : 
11:56:58 INFO    : Running Guest Tests Suite lifecycle_bck
11:56:58 INFO    : Running: /usr/local/bin/avocado run --vt-type libvirt --vt-config /home/tests/data/avocado-vt/backends/libvirt/cfg/lifecycle_bck.cfg                 --force-job-id 6fd229eb8cfe6d4ebec70f16374230de6f26a226                 --job-results-dir /home/tests/results  --vt-only-filter                                             "virtio_scsi virtio_net qcow2 Ubuntu.24.04.ppc64le" 
JOB ID     : 6fd229eb8cfe6d4ebec70f16374230de6f26a226
JOB LOG    : /home/tests/results/job-2024-06-10T11.57-6fd229e/job.log
 (1/3) io-github-autotest-qemu.unattended_install.import.import.default_install.aio_native: STARTED
 (1/3) io-github-autotest-qemu.unattended_install.import.import.default_install.aio_native: PASS (38.51 s)
 (2/3) type_specific.io-github-autotest-libvirt.virsh.destroy.error_test.hex_id_option: STARTED
 (2/3) type_specific.io-github-autotest-libvirt.virsh.destroy.error_test.hex_id_option: PASS (35.85 s)
 (3/3) io-github-autotest-libvirt.remove_guest.without_disk: STARTED
 (3/3) io-github-autotest-libvirt.remove_guest.without_disk: PASS (5.40 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/tests/results/job-2024-06-10T11.57-6fd229e/results.html
JOB TIME   : 89.18 s
11:58:30 INFO    : 
11:58:30 INFO    : Summary of test results can be found below:
TestSuite                                                                                TestRun    Summary
 
guest_lifecycle_bck                                                                      Run        Successfully executed
/home/tests/results/job-2024-06-10T11.57-6fd229e/job.log
| PASS 3 || CANCEL 0 || ERRORS 0 || FAILURES 0 || SKIP 0 || WARN 0 || INTERRUPT 0 |
11:58:30 INFO    : Removing temporary mux dir

### CODE REVIEW

**Review by bskjois — APPROVED** [review]
I have tried this patch. It is working as expected. LGTM

**Review by harihare — APPROVED** [review]
LGTM

**Review by PraveenPenguin — APPROVED** [review]
LGTM

**Comment by pevogam** [comment]
Hi @TasmiyaNalatwad have you managed to perform unattended installation for Ubuntu 24.04 with this variant? I have reported a related issue https://github.com/avocado-framework/avocado-vt/issues/4069 about the fact that there is a new unattended installation method for this distro version.

**Comment by harihare** [comment]
@pevogam It is not the complete installation we build the qcow2 image and use it. The patch is to enable the naming convention for the Ubuntu build

**Comment by TasmiyaNalatwad** [comment]
@pevogam As mentioned by @harihare the patch helps establish a naming convention as we build the qcow2 image. It is not a complete installation.

**Comment by pevogam** [comment]
I see, thank you both for the clarification!

**Pull request merged**
