### PR TITLE
virsh requires hostname to resolved with IP for migration

### PR DESCRIPTION
**Pull request by balamuruhans**
Adopt migration setup to map hostname and ipaddress of the hosts in
source and target for virsh to resolve and migrate without error.
    
virsh throws error if it fails to resolve the IP during migration
    
```
error: Unable to resolve address 'ltc-fire4' service '49152': Name or service not known`
```
Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by balamuruhans** [comment]
**Issue Observed:**
```
2018-06-18 12:35:01,171 virsh            L0654 DEBUG| Running virsh command: migrate --live --persistent --auto-converge --timeout 1800 --domain vms2 --desturi qemu:///system
2018-06-18 12:35:01,172 process          L0554 INFO | Running '/bin/virsh -c 'qemu+ssh://10.47.70.203/system' migrate --live --persistent --auto-converge --timeout 1800 --domain vms2 --desturi qemu:///system'
2018-06-18 12:35:01,180 process          L0633 INFO | Command /bin/virsh -c 'qemu+ssh://10.47.70.203/system' migrate --live --persistent --auto-converge --timeout 1800 --domain vms2 --desturi qemu:///system running on a thread
2018-06-18 12:35:03,963 process          L0385 DEBUG| [stderr] error: Unable to resolve address 'ltc-fire4' service '49152': Name or service not known
2018-06-18 12:35:04,085 process          L0385 DEBUG| [stdout]
2018-06-18 12:35:04,086 process          L0642 INFO | Command '/bin/virsh -c 'qemu+ssh://10.47.70.203/system' migrate --live --persistent --auto-converge --timeout 1800 --domain vms2 --desturi qemu:///system' finished with 1 after 2.90607905388s
```

**Comment by balamuruhans** [comment]
**debug log**
```
2018-06-22 15:17:05,125 remote           L0395 DEBUG| Attempting to log into 9.47.70.203:22 using ssh (timeout 240s)
2018-06-22 15:17:07,034 client           L1078 DEBUG| Sending command: ppc64_cpu --smt
2018-06-22 15:17:07,208 client           L1078 DEBUG| Sending command: echo $?
2018-06-22 15:17:08,920 utils_net        L3706 INFO | All the hostnames and IPs are mapped in /etc/hosts
2018-06-22 15:17:08,921 remote           L0395 DEBUG| Attempting to log into 9.47.70.203:22 using ssh (timeout 240s)
2018-06-22 15:17:10,997 client           L1078 DEBUG| Sending command: cat /etc/hosts
2018-06-22 15:17:11,151 client           L1078 DEBUG| Sending command: echo $?
2018-06-22 15:17:11,305 client           L1078 DEBUG| Sending command: echo '9.47.70.203 pkvmhab008.pok.stglabs.ibm.com' >> /etc/hosts
2018-06-22 15:17:11,458 client           L1078 DEBUG| Sending command: echo $?
2018-06-22 15:17:11,611 client           L1078 DEBUG| Sending command: cat /etc/hosts
2018-06-22 15:17:11,765 client           L1078 DEBUG| Sending command: echo $?
2018-06-22 15:17:11,918 client           L1078 DEBUG| Sending command: echo '9.40.193.21 ltc-fire4' >> /etc/hosts
2018-06-22 15:17:12,072 client           L1078 DEBUG| Sending command: echo $?
2018-06-22 15:17:12,225 utils_net        L3706 INFO | All the hostnames and IPs are mapped in /etc/hosts
2018-06-22 15:17:12,376 env_process      L0853 DEBUG| KVM version: 4.17.0-1.dev.git5ce3eac.el7.ppc64le

```

**Comment by sathnaga** [comment]
@balamuruhans pls rebase

**Comment by balamuruhans** [comment]
@sathnaga Done.

**Comment by balamuruhans** [comment]
@sathnaga request for your review.

**Pull request merged**
