### PR TITLE
guest-os: Add RHEL.7.8 guest os

### PR DESCRIPTION
**Pull request by yanan-fu**
id: 1823654

Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
@PaulYuuu Could you help reivew ? thanks!

**Comment by PaulYuuu** [comment]
Ack.

**Comment by yanan-fu** [comment]
test result:
```
(1/3) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (970.49 s)
```

**Comment by yanan-fu** [comment]
@luckyh Could you help review ? thanks!

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
