### PR TITLE
Fixup: changed version str to latest released 41.0

### PR DESCRIPTION
**Pull request by sathnaga**
changed version string to latest released 41.0

### CODE REVIEW

**Comment by ldoktor** [comment]
Thanks @sathnaga, we missed this. @clebergnu please update your scripts to include the `setup.py` modification before release.

**Comment by clebergnu** [comment]
@sathnaga good catch... sorry about missing that.  Wrt you commit, you'd need to add a "Signed-off by" line... Oops, too late, @ldoktor merged it.  It's not a big deal though.  Thanks for that!

**Comment by clebergnu** [comment]
@ldoktor @sathnaga somehow the release version 40.0 (during its release) was not recorded in setup.py, and then, I looked at that diff to change the version numbers for version 41.0. That means I also missed updating version 41.0. Sorry about that, I'll implement some measures to not miss them again.

**Comment by ldoktor** [comment]
Well there is the `author` so the signed off is a bit duplicate (I saw many commits without it already. So it's better to include it, but I don't find it particularly important)

**Comment by clebergnu** [comment]
@ldoktor BTW, one of the reasons I missed that, is because we also have the version number in the SPEC file and also in the Makefile.  That means that things like the RPM packages get generated with the "right" versions...

**Comment by sathnaga** [comment]
@ldoktor @clebergnu Sure :+1:

**Comment by ldoktor** [comment]
Sure, I saw the 41.0 commit. Aren't there ways to avoid some of them (at least the `Makefile` could use the `setup.py` value, can't it?)

**Comment by sathnaga** [comment]
@ldoktor @clebergnu yes, I agree, it is easy to miss if in many places, we can think of having a global version string maintained in one place and all others uses it.

**Comment by clebergnu** [comment]
@ldoktor IMHO the best way to avoid would be to have a single place with the version numbers.  The second best way (which is a lot worse) would be to cross check the version numbers on the various places.  Anyway, this needs to be fixed "for good": https://trello.com/c/3HKsnsRU/823-avocado-vt-have-a-single-version-number-definition

**Comment by sathnaga** [comment]
@clebergnu @ldoktor  working on a fix, will send a RFC patch, we can discuss and add if fine

**Comment by ldoktor** [comment]
Well the `rpm` spec file requires the version hardcoded, isn't it? Apart from that it should be just one place...

**Comment by sathnaga** [comment]
@ldoktor yes, looks like it has to be hardcoded for spec, searching if I can manipulate version for rpm spec file aswell, not getting any info around it.

**Comment by sathnaga** [comment]
@clebergnu @ldoktor Fixed in https://github.com/avocado-framework/avocado-vt/pull/697, let me know your comments

**Pull request merged**
