### PR TITLE
Windows:add iso installation lable "check_block_size"

### PR DESCRIPTION
**Pull request by aliang123**
shared.cfg.guest-os:
1.add iso installation label "check_block_size.4096/512_512" in windows.cfg
2.add iso installation label "check_block_size" for win8/10/2012/2016

Signed-off-by:Aihua Liang<aliang@redhat.com>

ID:1134252

### CODE REVIEW

**Comment by balamuruhans** [comment]
@aliang123 please push it again to trigger travis, as fix have went in.

**Comment by aliang123** [comment]
@balamuruhans , have updated it, thanks for reminding.

**Comment by CongLi** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Pull request merged**
