### PR TITLE
Collect usefull information in system report

### PR DESCRIPTION
**Pull request by quanwenli**
Add selinux/watchdog/tuning profile/qdisc/coalescing parameters information in system report.
    
Signed-off-by: Wenli Quan <wquan@redhat.com>

ID: 1502520

### CODE REVIEW

**Comment by clebergnu** [comment]
@quanwenli just an idea: what if we abstracted the sysinfo functionality in core Avocado, and allowed that to work on Virtual Machines?

**Comment by quanwenli** [comment]
＠clebergnu it's a good idea, the sysinfo is not for only for vm, but also for host. could we push the request firstly, then consider more about sysinfo function.

**Comment by clebergnu** [comment]
@quanwenli most definitely yes.  I'm not attempting to block this, it was just an idea that, if you like it and feel like helping us out, we can implement on core Avocado.  If that's the case, please open an issue on the Avocado project, and we can take it from there.

**Comment by quanwenli** [comment]
＠clebergnu I think more about it, the sysinfo here is custom one including host/guest information and test each steps for netperf test case, it's not generic.

**Comment by YanhuiMa** [comment]
pls modify the correct bz ID: 1502520

**Comment by YanhuiMa** [comment]
The netperf.py only calls scripts/rh_perf_log_hostinfo_script.sh now. so I can only test host info collection, can not test guest info collection. And test results are pass. But I will not Ack until you submit another patch of the guest info collection.
(1/1) smp_32.4096m.repeat1.repeat1.Host_RHEL.m7.u3.raw.virtio_blk.up.virtio_net.RHEL.7.4.x86_64.myprovider.netperf.host_guest: PASS

**Comment by quanwenli** [comment]
Post internal patch "[PATCH] Staf-kvm: update performance_net.cfg for rhel7.5", please help a try

**Comment by YanhuiMa** [comment]
PASS 1-smp_16.16384m.repeat1.repeat1.Host_RHEL.m7.u4.raw.virtio_blk.up.virtio_net.RHEL.7.4.x86_64.io-github-autotest-qemu.netperf.jumbo.host_guest

Acked-by: Yanhui Ma yama@redhat.com

**Comment by luckyh** [comment]
@quanwenli can you please rebase this branch? https://github.com/avocado-framework/avocado-vt/pull/1179/commits/44853bbf59304c574afe16dbe3971668a695175a seems useless.

**Comment by quanwenli** [comment]
@luckyh I have done, please check.

**Pull request merged**
