### PR TITLE
serial_host_send_receive: Support pty backend

### PR DESCRIPTION
**Pull request by vivianQizhu**
id: 1588423
Signed-off-by: Qianqian Zhu <qizhu@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@nanliu-r Please help review, together with https://github.com/avocado-framework/avocado-vt/pull/2190 Thanks.

**Comment by vivianQizhu** [comment]
Depends on https://github.com/avocado-framework/avocado-vt/pull/2190

**Comment by nanliu-r** [comment]
> @nanliu-r Please help review, together with [autotest/tp-qemu#1866](https://github.com/autotest/tp-qemu/pull/1866) Thanks.

Test pass both windows and Linux guest:

 (096/100) repeat96.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer.pty.q35:  PASS (105.68 s)
 (097/100) repeat97.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer.pty.q35:  PASS (89.61 s)
 (098/100) repeat98.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer.pty.q35:  PASS (89.60 s)
 (099/100) repeat99.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer.pty.q35:  PASS (90.60 s)
 (100/100) repeat100.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer.pty.q35:  PASS (91.64 s)
RESULTS    : PASS 100 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

 (096/100) repeat96.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer.pty.q35:  PASS (51.79 s)
 (097/100) repeat97.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer.pty.q35:  PASS (57.32 s)
 (098/100) repeat98.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer.pty.q35:  PASS (51.04 s)
 (099/100) repeat99.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer.pty.q35:  PASS (55.18 s)
 (100/100) repeat100.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer.pty.q35:  PASS (52.55 s)
RESULTS    : PASS 100 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by nanliu-r** [comment]
ACK.

**Comment by vivianQizhu** [comment]
Thanks @nanliu-r merging.

**Pull request merged**
