### PR TITLE
Add iscsi and ceph backends support

### PR DESCRIPTION
**Pull request by zhencliu**
1. Support QEMU to access iSCSI resources directly by url:
   iscsi://portal/target/lun
2. Support QEMU to access ceph resources directly by uri:
   rbd:{pool-name}/{image-name}
3. Support vm installation on directly accessed iscsi/ceph image

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1775502,1775506,1775508,1775509

### CODE REVIEW

**Comment by zhencliu** [comment]
1. ceph access with auth
-object secret,id=image1_access_secret,format=base64,data=AQBPxXBdAh7OJRAAC0EEml6+slcYAkZRiWN52w== \
-blockdev node-name=rbd_image1,driver=rbd,pool=rbd,image=rhel78-64-virtio-scsi.raw,key-secret=image1_access_secret,cache.direct=on,cache.no-flush=off \
-blockdev node-name=drive_image1,driver=raw,cache.direct=on,cache.no-flush=off,file=rbd_image1 \

 (1/3) Host_RHEL.m8.u1.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (2787.02 s)
 (3/3) Host_RHEL.m8.u1.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.boot.q35: PASS (173.60 s)


2. ceph access without auth
-object secret,id=image1_encrypt0,data=redhat \
-blockdev node-name=rbd_image1,driver=rbd,pool=rbd,image=rhel811-64-virtio-scsi.luks,cache.direct=on,cache.no-flush=off \
-blockdev node-name=drive_image1,driver=luks,key-secret=image1_encrypt0,cache.direct=on,cache.no-flush=off,file=rbd_image1 \

(1/3) Host_RHEL.m8.u1.ceph.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (2698.95 s)
 (3/3) Host_RHEL.m8.u1.ceph.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.shutdown.q35: PASS (86.82 s)


3. direct iscsi access with auth
-object secret,id=image1_encrypt0,data=redhat \
-object secret,id=image1_access_secret,format=raw,file=/root/project/merge/kar/workspace/var/lib/avocado/data/avocado-vt/images/secrets/image1_access_secret.secret \
-blockdev node-name=iscsi_image1,driver=iscsi,transport=tcp,portal=10.66.10.26,target=iqn.2019-09.com.example:zhencliu,lun=0,user=redhat,password-secret=image1_access_secret,initiator-name=iqn.2008-11.org.linux-kvm,cache.direct=on,cache.no-flush=off \
-blockdev node-name=drive_image1,driver=luks,key-secret=image1_encrypt0,cache.direct=on,cache.no-flush=off,file=iscsi_image1 \

 (1/3) Host_RHEL.m8.u1.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1517.11 s)
 (3/3) Host_RHEL.m8.u1.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.system_reset.q35: PASS (93.67 s)

4. direct iscsi access without auth
-object secret,id=image1_encrypt0,data=redhat \
-blockdev node-name=iscsi_image1,driver=iscsi,transport=tcp,portal=10.66.10.26,target=iqn.2019-09.com.example:zhencliu1,lun=1,cache.direct=on,cache.no-flush=off \
-blockdev node-name=drive_image1,driver=luks,key-secret=image1_encrypt0,cache.direct=on,cache.no-flush=off,file=iscsi_image1 \

 (1/3) Host_RHEL.m8.u1.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1388.71 s)
 (3/3) Host_RHEL.m8.u1.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.boot.q35: PASS (50.00 s)


5. without storage_backend_conf:
-object secret,id=image1_encrypt0,data=redhat \
-blockdev node-name=file_image1,driver=file,aio=threads,filename=/home/kvm_autotest_root/images/rhel811-64-virtio-scsi.luks,cache.direct=on,cache.no-flush=off \
-blockdev node-name=drive_image1,driver=luks,key-secret=image1_encrypt0,cache.direct=on,cache.no-flush=off,file=file_image1 \

 (1/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (2956.73 s)
 (3/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.boot.q35: PASS (79.10 s)

**Comment by hellohellenmao** [comment]
(1/3) Host_RHEL.m7.u8.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (4452.50 s)
 (2/3) Host_RHEL.m7.u8.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.rh_kernel_update: ERROR: 'list' object has no attribute 'splitlines' (355.62 s)
 (3/3) Host_RHEL.m7.u8.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.boot: PASS (76.39 s)

**Comment by hellohellenmao** [comment]
(1/3) Host_RHEL.m7.u8.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1844.48 s)
 (2/3) Host_RHEL.m7.u8.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.rh_kernel_update: ERROR: 'list' object has no attribute 'splitlines' (345.57 s)
 (3/3) Host_RHEL.m7.u8.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.boot: PASS (73.63 s)

**Comment by hellohellenmao** [comment]
Compatibility test - pass!
 (1/3) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (992.87 s)
 (2/3) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.rh_kernel_update: PASS (450.03 s)
 (3/3) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.boot: PASS (42.18 s)

**Comment by hellohellenmao** [comment]
Tested installation over ceph with key-secret. - Pass!

(1/1) Host_RHEL.m7.u8.ceph.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (4707.83 s)

**Comment by zhenyzha** [comment]
Test Results:
Iscsi -blockdev:
 (1/3) Host_RHEL.m8.u0.iscsi_direct.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.ppc64le.io-github-autotest-qemu.unattended_install.cd
rom.extra_cdrom_ks.default_install.aio_threads: PASS (1656.02 s)
 (2/3) Host_RHEL.m8.u0.iscsi_direct.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.ppc64le.io-github-autotest-qemu.rh_kernel_update: CAN
CEL: The snapshot=on is not supported by -blockdev. (9.81 s)
 (3/3) Host_RHEL.m8.u0.iscsi_direct.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.ppc64le.io-github-autotest-qemu.shutdown: PASS (97.15
 s)

Iscsi -drive:
 (1/3) Host_RHEL.m8.u0.iscsi_direct.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1675.36 s)
 (2/3) Host_RHEL.m8.u0.iscsi_direct.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.ppc64le.io-github-autotest-qemu.rh_kernel_update: ERROR: 'list' object has no attribute 'splitlines' (297.45 s)
 (3/3) Host_RHEL.m8.u0.iscsi_direct.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.ppc64le.io-github-autotest-qemu.shutdown: PASS (92.73 s)

**Comment by zhenyzha** [comment]
Test Results:
Ceph -blockdev:
  (1/3) Host_RHEL.m8.u0.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extr
a_cdrom_ks.default_install.aio_threads: /[FAIL: Timeout elapsed while waiting for install to finish (5521.24 s)
 (2/3) Host_RHEL.m8.u0.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.ppc64le.io-github-autotest-qemu.rh_kernel_update: CANCEL: The
 snapshot=on is not supported by -blockdev. (9.81 s)
 (3/3) Host_RHEL.m8.u0.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.ppc64le.io-github-autotest-qemu.shutdown: ERROR: No ipv4 DHCP
 lease for MAC 9a:14:d6:2f:92:ba (790.23 s)

later, I will build a ceph server on Power, test again.

**Comment by zhenyzha** [comment]
Update test results:
By checking the ceph cli, the patch is ok for me.
However, when I git am the patch again on November 25th today, There's display an error:
# git am 2338.patch 
Applying: Add iscsi and ceph backends support
error: patch failed: virttest/qemu_storage.py:178
error: virttest/qemu_storage.py: patch does not apply
Patch failed at 0001 Add iscsi and ceph backends support
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

**Comment by zhenyzha** [comment]
Conflict has been resolved.
git am 2338.patch 
Applying: Add iscsi and ceph backends support

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
