### PR TITLE
libvirt_vmxml: add func to match xml by xpath

### PR DESCRIPTION
**Pull request by dzhengfy**
This patch is to add a new function to enable the checking vmxml
using xpath way.

Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by nanli1** [comment]
@dzhengfy Hi dzheng ,This new function works on my cases. Just one small issue ,We don't check `text`  every time, So could you  please give a judgment before  `  elem_text = xpath_text['text']`

**Comment by dzhengfy** [comment]
> @dzhengfy Hi dzheng ,This new function works on my cases. Just one small issue ,We don't check `text` every time, So could you please give a judgment before ` elem_text = xpath_text['text']`
Updated

**Review by nanli1 — APPROVED** [review]

**Comment by dzhengfy** [comment]
@smitterl Could you help review it?

**Comment by nanli1** [comment]
test by  https://github.com/autotest/tp-libvirt/pull/4825 
```

avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 chardev.file_append
 (1/3) type_specific.io-github-autotest-libvirt.chardev.file_append.serial.append_on: PASS (139.34 s)
 (2/3) type_specific.io-github-autotest-libvirt.chardev.file_append.serial.append_off: PASS (138.87 s)
 (3/3) type_specific.io-github-autotest-libvirt.chardev.file_append.serial.append_default: PASS (139.76 s)

```

**Review by chloerh — APPROVED** [review]

**Pull request merged**
