### PR TITLE
shared/cfg/guest-hw.cfg: Rename Host_RHEL using new rule

### PR DESCRIPTION
**Pull request by spcui**
Signed-off-by: Shuping Cui <scui@redhat.com>

ID: 1161504

### CODE REVIEW

**Comment by ypu** [comment]
related with https://github.com/autotest/tp-qemu/pull/433

**Comment by ypu** [comment]
LGTM

Acked-by: Yiqiao Pu <ypu@redhat.com>

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by suqinhuang** [comment]
@lmr hi, could you merge this patch

**Pull request merged**
