### PR TITLE
guest-hw: add a new image format of vdi

### PR DESCRIPTION
**Pull request by hellohellenmao**
Signed-off-by: Tingting Mao <timao@redhat.com>

ID: 2064158

### CODE REVIEW

**Comment by hellohellenmao** [comment]
1/1) Host_RHEL.m9.u0.vdi.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.vdi_image_create.q35: PASS (2.93 s)

**Comment by XueqiangWei** [comment]
(1/1) Host_RHEL.m9.u0.vdi.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.vdi_image_create.q35: PASS (6.90 s)


LGTM,
Acked-by: xuwei@redhat.com

**Comment by zhencliu** [comment]
LGTM
hi @YongxueHong , would you please help to review this patch? Thanks.

**Comment by YongxueHong** [comment]
Hi @hellohellenmao 
Does it also support the ppc platform?
Thanks.

**Comment by hellohellenmao** [comment]
> Hi @hellohellenmao Does it also support the ppc platform? Thanks.

Hi @YongxueHong , no need for ppc, at least not for now.

**Review by YongxueHong — APPROVED** [review]

**Comment by YongxueHong** [comment]
Hi, @luckyh 
Would you like to help review it?
Thanks.

**Review by YongxueHong — CHANGES_REQUESTED** [review]
Sorry for inconvenience.
Some requirements we need to confirm.

**Comment by hellohellenmao** [comment]
Will implement the new format of vdi in case level. So close this patch now. Thanks all.

**Pull request closed without merging**
