### PR TITLE
usb_device: move adding usb devices logic forward

### PR DESCRIPTION
**Pull request by ybduan**
Move adding usb devices logic at the earlier stage in
make_create_command() before adding images to support
plugging usb-storage under usb-hub automatically.

ID: 1802010
Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by ybduan** [comment]
Please help review this PR, thanks! @XueqiangWei

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by: xuwei@redhat.com

**Comment by ybduan** [comment]
Please help review this PR, thanks! @lolyu

**Comment by ybduan** [comment]
Could you please help review this PR? Thanks! @luckyh

**Comment by luckyh** [comment]
@ybduan looks this change might affect some usb related tests (for example, for port addressing issue), have you done a verification?

**Comment by XueqiangWei** [comment]
Tested usb_device loop, not hit any issue.

Summary: 
Finshed=374, PASS=345, CANCEL=1, SKIP=28

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
