### PR TITLE
libvirt_vm: Interface for qemu monitor using libvirt VM

### PR DESCRIPTION
**Pull request by balamuruhans**
Monitor interface helps to achieve qemu monitor commands to be
executed from libvirt VM object, generic tests from libvirt and
qemu repositories can use it seamlessly.

Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>
Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by balamuruhans** [comment]
**Test run:**
```
# avocado run --vt-type libvirt --vt-config /home/bala/avocado-fvt-wrapper/data/avocado-vt/backends/libvirt/cfg/lifecycle.cfg  --vt-only-filter "virtio_scsi qcow2 Pegas.1.0.ppc64le" --vt-no-filter "user network macvtap"
JOB ID     : 0bfd14fc82bb35c3a0b7c21d6f40ce86814847c6
JOB LOG    : /home/bala/avocado-fvt-wrapper/results/job-2017-11-15T15.53-0bfd14f/job.log
 (1/1) guest_shutdown.qemu.qcow2.virtio_scsi.smp2.virtio_net.Pegas.1.0.ppc64le.powerkvm-qemu.shutdown: PASS (117.74 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 121.59 s
JOB HTML   : /home/bala/avocado-fvt-wrapper/results/job-2017-11-15T15.53-0bfd14f/results.html
```

**Comment by balamuruhans** [comment]
@luckyh added interface for monitor as per your suggestion, please help for review.

**Comment by balamuruhans** [comment]
> Sorry, I'm afraid it is not the solution I suggested in autotest/tp-qemu#1150, so let me clarify it again.

sorry, I have mistaken your suggestion. But I believe it is better solution as explained below,

> I'd suggest introducing the powerdown interface for all the VM classes so that we can perform system_powerdown action to a vm object.

Introducing powerdown interface under VM class will not be generic in my opinion. I believe with this implementation we can still perform system_powerdown using a vm object along with any other qemu monitor operations. Also this will be useful in future enhancement without modification from testcase end.

**Comment by sathnaga** [comment]
Lets merge as all comments are addressed and open for long time.

**Pull request merged**
