### PR TITLE
unattened.xml: workaround win10 network location issue

### PR DESCRIPTION
**Pull request by xutian**
This commit fix win10 unattended_install failed issue. Root cause is that windows network location notification window pop at first login, which blocked post installation script execution.

Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
@suqinhuang 

This is a hotfix, would you like to test and review it.

thanks,
Xu

**Comment by suqinhuang** [comment]
Hi @xutian could you add description to the patch, I'm not sure what you fix

RD,
Suqin

**Comment by xutian** [comment]
@suqinhuang , done.
thanks

**Comment by xutian** [comment]
ID: 1279686

**Comment by suqinhuang** [comment]
Great, it works well

Acked-by: Suqin Huang

**Pull request merged**
