### PR TITLE
avocado-vt: update path for multi_host_migration test

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
ID 1394608

**Comment by CongLi** [comment]
LGTM,
acked-by: Cong Li <coli@redhat.com>

**Comment by aliang123** [comment]
Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by XueqiangWei** [comment]
@xutian as we talked, avoid use "\" as the newline character. Already updated, please help review, thank you.

**Comment by aliang123** [comment]
Have checked, it looks ok.
Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by xutian** [comment]
LGTM

**Pull request merged**
