### PR TITLE
Added Intel TDX support

### PR DESCRIPTION
**Pull request by zhencliu**
1. Removed kvm-type from -machine options
2. Workaround the firmware setting by bios_path

ID: 2368

### CODE REVIEW

**Comment by zhencliu** [comment]
hi @luckyh , would you please have a look? In future, pflash may be used for bios setting IMO, so this is mostly like a workaround, and I didn't do much check, e.g. if bios_path is set

**Review by luckyh — APPROVED** [review]
LGTM

**Review by xhao22 — APPROVED** [review]
It's good to me. and tested pass.

**Comment by luckyh** [comment]
Thanks to all.

**Pull request merged**
