### PR TITLE
shared.unattended: Rename RHEL.7.devel's ks file

### PR DESCRIPTION
**Pull request by ldoktor**
The RHEL.7.devel kickstart is being used both as spice and as normal
kickstart. The big issue is that spice team required some changes and
they sneaked-in a patch which makes kickstarts from "test-providers.d"
taking precedence over the stock ones and later they altered the
"RHEL-7-spice.ks" file in their repo. This is very hard to debug as
without "tp-spice" repo cloned avocado-vt uses the stock RHEL-7-spice.ks
but with "tp-spice" cloned it uses RHEL-7-spice.ks from tp-spice
provider no matter which tp backend is used.

I think this behavior is actually a bug, we should not look for any
config files in backend that are not being used and I want to address
that but in the mean time let's simply rename the RHEL.7.devel's
kicstart to a different name as the current behavior heavily affects
users.

Note the tp-spice is cloned automatically on `avocado vt-bootstrap`
that's what makes this issue pretty hot.

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>

### CODE REVIEW

**Comment by ldoktor** [comment]
Note to reproduce the issue you can:

1. clone avocado-vt
2. avocado vt-bootstrap
3. avocado --show all run unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads --vt-machine-type q35 --vt-guest-os RHEL.7.devel

When you run the vt-bootstrap without this fix you'll have:

```
2017-02-23 10:44:45,087 process          L0368 INFO | Running 'losetup -a'
2017-02-23 10:44:45,098 process          L0478 INFO | Command 'losetup -a' finished with 0 after 0.00311803817749s
2017-02-23 10:44:45,232 unattended_insta L0408 DEBUG| Unattended install contents:
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| #
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| # Next part was generated by system-config-kickstart.
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| #
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| #platform=x86, AMD64, or Intel EM64T
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| #version=DEVEL
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| # Install OS instead of upgrade
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| install
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| # Keyboard layouts
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| keyboard 'us'
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| # Root password
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| rootpw --plaintext 123456
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| # System timezone
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| timezone Europe/Prague
2017-02-23 10:44:45,233 unattended_insta L0410 DEBUG| # System language
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| lang en_US
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| # Firewall configuration
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| firewall --disabled
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| # System authorization information
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| auth  --useshadow  --passalgo=sha512
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| # Use text mode install
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| text
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| # SELinux configuration
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| selinux --enforcing
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| # Network information
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| network  --bootproto=dhcp --device=eth0
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| # System bootloader configuration
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| bootloader --location=mbr
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| # Clear the Master Boot Record
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| zerombr
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| # Partition clearing information
2017-02-23 10:44:45,234 unattended_insta L0410 DEBUG| clearpart --all --initlabel
```

in your job.log. With this PR:

```
2017-02-23 10:45:49,639 process          L0368 INFO | Running 'losetup -a'
2017-02-23 10:45:49,649 process          L0478 INFO | Command 'losetup -a' finished with 0 after 0.00296688079834s
2017-02-23 10:45:49,650 unattended_insta L0408 DEBUG| Unattended install contents:
2017-02-23 10:45:49,650 unattended_insta L0410 DEBUG| install
2017-02-23 10:45:49,650 unattended_insta L0410 DEBUG| cdrom
2017-02-23 10:45:49,650 unattended_insta L0410 DEBUG| graphical
2017-02-23 10:45:49,650 unattended_insta L0410 DEBUG| poweroff
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| lang en_US.UTF-8
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| keyboard us
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| network --onboot yes --device eth0 --bootproto dhcp
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| rootpw --plaintext 123456
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| firstboot --disable
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| user --name=test --password=123456
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| firewall --enabled --ssh
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| selinux --enforcing
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| timezone --utc America/New_York
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| bootloader --location=mbr --append="console=tty0 console=ttyS0,115200"
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| zerombr
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| 
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| clearpart --all --initlabel
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| autopart
2017-02-23 10:45:49,651 unattended_insta L0410 DEBUG| xconfig --startxonboot
2017-02-23 10:45:49,652 unattended_insta L0410 DEBUG| 
2017-02-23 10:45:49,652 unattended_insta L0410 DEBUG| %packages --ignoremissing
2017-02-23 10:45:49,652 unattended_insta L0410 DEBUG| @base

```

**Comment by Andrei-Stepanov** [comment]
I totally agree.
Config `shared/cfg/guest-os/Linux/RHEL/7.devel.cfg` should serve for general purposes. It should use generic KS-file with general filename.

**Comment by xutian** [comment]
ACK

Thanks @ldoktor and @Andrei-Stepanov

**Comment by ldoktor** [comment]
[Rename RHEL.7.devel's kickstart file to avoid clashes and confusions.](https://trello.com/c/jzggsEVw/985-rename-rhel-7-devel-s-kickstart-file-to-avoid-clashes-and-confusions)

**Pull request merged**
