### PR TITLE
boot_options_default: remove default values of boot options

### PR DESCRIPTION
**Pull request by ybduan**
Remove the default values of boot options to add ability to
test each option separately.

ID: 1752360

Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
(1/2) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.seabios_order_once.with_order.q35: PASS (164.87 s)
 (2/2) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.seabios_order_once.with_order.q35: PASS (164.73 s)

**Comment by luckyh** [comment]
@ybduan what are the default values set by qemu? are they the same as what we set these options previously?

**Comment by ybduan** [comment]
The initial values of "boot_menu", "boot_order" and "boot_once" have been set in avocado-all/avocado-vt/shared/cfg/base.cfg, and the default value of 'strict' is 'off' set by qemu.

```
# Set boot order                                                                
boot_order = cdn                                                                
# Use the first hard disk for boot device once                                  
boot_once = c                                                                   
# Enable/Disable boot menu                                                      
boot_menu = off 
```

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
