### PR TITLE
Guest-os: Add RHEL7.4 guest os configuration

### PR DESCRIPTION
**Pull request by yanan-fu**
id: 1497031
Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
@qunfang could you help review ppc part ? thanks!

**Comment by yanan-fu** [comment]
x86 part, test pass:
'1-smp_4.4096m.repeat1.pre_test.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.RHEL.7.4.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native' Finshed 2017-10-11 04:02:59 2017-10-11 04:24:12 PASS 1273.349069
'2-smp_4.4096m.repeat1.pre_test.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.RHEL.7.4.x86_64.io-github-autotest-qemu.rh_kernel_update' Finshed 2017-10-11 04:24:12 2017-10-11 04:40:56 PASS 1004.18172
'3-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.RHEL.7.4.x86_64.io-github-autotest-qemu.boot' Finshed 2017-10-11 04:41:01 2017-10-11 04:41:36 PASS 35.270935

**Comment by qunfang** [comment]
Installation pass on Power8:

'01-smp_4.8192m.repeat1.pre_test.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.RHEL.7.4.ppc64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native' Finshed 2017-10-12 05:05:05 2017-10-12 05:32:50 PASS 1665.452695
'02-smp_4.8192m.repeat1.pre_test.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.RHEL.7.4.ppc64.io-github-autotest-qemu.rh_kernel_update' Finshed 2017-10-12 05:32:51 2017-10-12 05:43:08 FAIL 617.138099
'03-smp_4.8192m.repeat1.pre_test.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.RHEL.7.4.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native' Finshed 2017-10-12 05:43:08 2017-10-12 06:09:33 PASS 1585.201217
'04-smp_4.8192m.repeat1.pre_test.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.RHEL.7.4.ppc64le.io-github-autotest-qemu.rh_kernel_update' Finshed 2017-10-12 06:09:33 2017-10-12 06:20:09 PASS 636.028361

Ack'ed.

**Comment by xutian** [comment]
looks fine, merged thanks @yanan-fu

**Pull request merged**
