### PR TITLE
Update the dhcp/range as the definition changes

### PR DESCRIPTION
**Pull request by yalzhang**
Recently the dhcp/range has added a element expiry time, so the
definition change from dict to a class. Update some network
define functions in libvirt.py file accordingly.

Signed-off-by: Yalan Zhang <yalzhang@redhat.com>

### CODE REVIEW

**Comment by yalzhang** [comment]
@chloerh  Please help to review it, Thank you!

**Comment by chloerh** [comment]
@yalzhang It would be more helpful if some test result is provided.

**Comment by yalzhang** [comment]
> @yalzhang It would be more helpful if some test result is provided.

Yes, I will run a jenkins job and provide the overall test results together with https://github.com/autotest/tp-libvirt/pull/3260 and https://github.com/autotest/tp-libvirt/pull/3255

**Review by chloerh — APPROVED** [review]
Approved, but waiting for more test result

**Comment by yalzhang** [comment]
The test result is pass on jenkins: Virtual networks, build 17

**Comment by yalzhang** [comment]
create_net_xml() is called in iface_network.py, the test is pass:
iface_network.net_forward.net_open.default | 40 sec | Fixed
iface_network.net_forward.net_open.negative_with_dev | 11 sec | Fixed
iface_network.net_forward.net_open.negative_without_ip | 11 sec | Fixed
iface_network.net_forward.net_open.without_bridge | 40 sec | Fixed
iface_network.net_forward.net_open.without_mac | 40 sec | Fixed
iface_network.net_forward.net_route | 50 sec | Fixed
iface_network.net_forward.route_test | 41 sec | Fixed

**Comment by chloerh** [comment]
Great! @Yingshun Could you help review, too?

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
