### PR TITLE
Update netperf package to fix compile issue

### PR DESCRIPTION
**Pull request by cliping**
When run 'make' command to compile netperf, meet following error:
  gcc     -o netperf netperf.o netlib.o netsh.o nettest_bsd.o nettest_dlpi.o nettest_unix.o nettest_xti.o nettest_sctp.o nettest_sdp.o nettest_omni.o net_uuid.o dscp.o netcpu_none.o netrt_none.o netdrv_none.o netslot_none.o netsys_none.o netsec_none.o  -lm
  /usr/bin/ld: nettest_omni.o:(.bss+0x398): multiple definition of `loc_nodelay'; nettest_bsd.o:(.bss+0x20): first defined here
  /usr/bin/ld: nettest_omni.o:(.bss+0x39c): multiple definition of `rem_nodelay'; nettest_bsd.o:(.bss+0x24): first defined here
  /usr/bin/ld: nettest_omni.o:(.bss+0x3a0): multiple definition of `loc_sndavoid'; nettest_bsd.o:(.bss+0x30): first defined here
  /usr/bin/ld: nettest_omni.o:(.bss+0x3a4): multiple definition of `loc_rcvavoid'; nettest_bsd.o:(.bss+0x34): first defined here
  /usr/bin/ld: nettest_omni.o:(.bss+0x3a8): multiple definition of `rem_sndavoid'; nettest_bsd.o:(.bss+0x38): first defined here
  /usr/bin/ld: nettest_omni.o:(.bss+0x3ac): multiple definition of `rem_rcvavoid'; nettest_bsd.o:(.bss+0x3c): first defined here
  collect2: error: ld returned 1 exit status
  make[3]: *** [Makefile:443: netperf] Error 1

One patch [1] is to fix this issue. According to this patch to
update netperf package.

[1] https://github.com/HewlettPackard/netperf/pull/46

Signed-off-by: lcheng <lcheng@redhat.com>

### CODE REVIEW

**Comment by cliping** [comment]
Before fix:

 (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migration.stress.host.netperf_network.without_postcopy: ERROR: Packeage Error: Compile failed: Shell command failed: 'cd /var/tmp/  && tar jxf netperf-2.6.0-1.tar.bz2 && cd /var/tmp/netperf-2.6.0-1  && ./autogen.sh > /dev/null 2>&1 && ./configure --build=x86_64  > /dev/null 2>&1 && make > /dev/null 2>&1 '    (status:... (238.09 s)

After fix:
#avocado run --vt-type libvirt --vt-machine-type q35 virsh.migrate_vm.positive_testing.live_migration.stress.host.netperf_network.without_postcopy --vt-connect-uri qemu:///system
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 0ea733bdfcda0df1dc2a3e75831baf4acdb398b6
JOB LOG    : /root/avocado/job-results/job-2021-07-09T03.48-0ea733b/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migration.stress.host.netperf_network.without_postcopy: PASS (412.31 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 415.74 s

**Comment by chunfuwen** [comment]
@cliping 
Generally, it is not good idea to accommodate one binary package directly under avocado-vt folder.

**Comment by cliping** [comment]
@chunfuwen , yes, we can fix this package error first, and then to consider how to delete this package.

**Review by chunfuwen — APPROVED** [review]
Approve it firstly, then bring it to PR review meeting to discuss whether it is proper to accommodate binary package in avocado-vt directly

**Review by Yingshun — APPROVED** [review]

**Pull request merged**
