### PR TITLE
nfs: add support to configure nfs on remote host/VM

### PR DESCRIPTION
**Pull request by balamuruhans**
nfs: add support to configure nfs on remote host/VM

perform nfs configurations in remote machines and mount it
in test machines with `setup_remote_nfs` set, this patch
adds support to it.

 utils_misc: refactor safe_rmdir() to support remote host/vm

add safe_rmdir() to handle remote session to make use of it by virttest/nfs
package to perform setup_remote_nfs to configure nfs on remote host/guest
and mount it in test machines. add check_isdir() to verify whether a path
is directory or not in remote/VM.

Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by balamuruhans** [comment]
**setup_local_nfs: (configure and set nfs in local host test machine and use it)**
```
storage_type = nfs
setup_local_nfs = "yes"
nfs_mount_dir=/home/bala/sharing
nfs_mount_options="rw"
export_options=rw,sync,no_root_squash
nfs_mount_src=/home/bala/NFS
export_dir=/home/bala/NFS

**Test result:**

JOB ID     : 1294bad9013cfabfa68556584ccfacdb4442e186
JOB LOG    : /home/bala/avocado-fvt-wrapper/results/job-2019-02-19T08.30-1294bad/job.log
 (1/1) guest_boot.qemu.qcow2.virtio_scsi.smp2.virtio_net.Guest.RHEL.8.0.ppc64le.powerkvm-qemu.unattended_install.import.import.default_install.aio_native: PASS (46.85 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 51.46 s
JOB HTML   : /home/bala/avocado-fvt-wrapper/results/job-2019-02-19T08.30-1294bad/results.html
```
**setup_remote_nfs: (configure and set nfs in remote host/VM and use it in test machine)**
```
**params to set:**
storage_type = nfs
setup_remote_nfs = "yes"
nfs_mount_dir=/home/bala/sharing
nfs_mount_options="rw"
export_options=rw,sync,no_root_squash
nfs_mount_src=/home/bala/NFS
export_dir=/home/bala/NFS
nfs_server_ip = "10.10.193.215"
nfs_server_pwd = "123456"
nfs_server_user = "root"

**Test result:**

JOB ID     : 72fcca347c20bab0f3515ddca3f0dacc4ea2d4af
JOB LOG    : /home/bala/avocado-fvt-wrapper/results/job-2019-02-19T08.36-72fcca3/job.log
 (1/1) guest_boot.qemu.qcow2.virtio_scsi.smp2.virtio_net.Guest.RHEL.8.0.ppc64le.powerkvm-qemu.unattended_install.import.import.default_install.aio_native: PASS (163.51 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 168.13 s
JOB HTML   : /home/bala/avocado-fvt-wrapper/results/job-2019-02-19T08.36-72fcca3/results.html
```

**Just mount the remote location:  (without setting up nfs in local or remote but to use already existing nfs configured machine)**
```
**param to set:**
storage_type = nfs
nfs_server_ip = "10.10.193.215"
nfs_mount_dir=/home/bala/sharing
nfs_mount_src=/home/bala/NFS

**Test result:**
JOB ID     : eab042c95a5788880f8fd9688f5ee946d9e0f543
JOB LOG    : /home/bala/avocado-fvt-wrapper/results/job-2019-02-19T08.27-eab042c/job.log
 (1/1) guest_boot.qemu.qcow2.virtio_scsi.smp2.virtio_net.Guest.RHEL.8.0.ppc64le.powerkvm-qemu.unattended_install.import.import.default_install.aio_native: PASS (102.86 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 107.45 s
JOB HTML   : /home/bala/avocado-fvt-wrapper/results/job-2019-02-19T08.27-eab042c/results.html
```

**Comment by balamuruhans** [comment]
@dzhengfy could you help review this PR, I had tested it and it can be used in your migration tests as well. Thanks!

**Comment by chloerh** [comment]
We're getting this error since this pr got merged:
AttributeError: module 'virttest.staging.service' has no attribute 'Service'

**Comment by balamuruhans** [comment]
This is dependency patch - https://github.com/avocado-framework/avocado-vt/pull/1965

**Comment by dzhengfy** [comment]
@balamuruhans , sorry, I missed this PR for reviewing. And it is good to see there is already a patch for this failure.

**Comment by dzhengfy** [comment]
@balamuruhans , sorry, I missed this PR for reviewing. And it is good to see there is already a patch for this failure.

**Comment by dzhengfy** [comment]
And It is good to have the two PRs merged at same time, otherwise we get many failures. Thanks.

**Comment by balamuruhans** [comment]
@dzhengfy @sathnaga  sorry, I missed to mention the dependency PR. actually its been long time, I have been sent these patches. no worries, I have tested it wisely.

**Pull request merged**
