### PR TITLE
qemu_vm: Wait for IO channels setting up completely

### PR DESCRIPTION
**Pull request by YongxueHong**
Wait for connecting socket server completely by sleeping 1 second.

ID: 1654102
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by wangxianxian** [comment]
ACK

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by YongxueHong** [comment]
@sitoliu  help review if you free, thanks.

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
