### PR TITLE
Adopt Avocado cpu library changes

### PR DESCRIPTION
**Pull request by sathnaga**
Cpu library is getting refactored through this
PR https://github.com/avocado-framework/avocado/pull/3350,
This PR modified respective test code to reflect the same.

Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by sathnaga** [comment]
@clebergnu @ldoktor I guess we need to cherry-pick this avocado fix https://github.com/avocado-framework/avocado/pull/3350  to python 2.7 supported branch(i.e. 69lts) too, as we see a travis failure for 2.7 versions, 

excerpt from tavis failure

```
git clone --depth 1 https://github.com/avocado-framework/avocado.git --branch $([ $TRAVIS_PYTHON_VERSION == "2.7" ] && echo 69lts || echo master) avocado-libs
..
...
 File "/home/travis/build/avocado-framework/avocado-vt/avocado-libs/scripts/avocado", line 78, in <module>

    sys.exit(app.run())

  File "/home/travis/build/avocado-framework/avocado-vt/avocado-libs/avocado/core/app.py", line 91, in run

    return method(self.parser.args)

  File "/home/travis/build/avocado-framework/avocado-vt/avocado_vt/plugins/vt_bootstrap.py", line 111, in run

    bootstrap.bootstrap(options=args, interactive=True)

  File "/home/travis/build/avocado-framework/avocado-vt/virttest/bootstrap.py", line 958, in bootstrap

    check_modules = arch.get_kvm_module_list()

  File "/home/travis/build/avocado-framework/avocado-vt/virttest/arch.py", line 89, in get_kvm_module_list

    return ["kvm", "kvm-%s" % cpu.get_vendor()]

AttributeError: 'module' object has no attribute 'get_vendor'
```

**Comment by chloerh** [comment]
> @clebergnu @ldoktor I guess we need to cherry-pick this avocado fix [avocado-framework/avocado#3350](https://github.com/avocado-framework/avocado/pull/3350) to python 2.7 supported branch(i.e. 69lts) too, as we see a travis failure for 2.7 versions,
> 
> excerpt from tavis failure
> 
> ```
> git clone --depth 1 https://github.com/avocado-framework/avocado.git --branch $([ $TRAVIS_PYTHON_VERSION == "2.7" ] && echo 69lts || echo master) avocado-libs
> ..
> ...
>  File "/home/travis/build/avocado-framework/avocado-vt/avocado-libs/scripts/avocado", line 78, in <module>
> 
>     sys.exit(app.run())
> 
>   File "/home/travis/build/avocado-framework/avocado-vt/avocado-libs/avocado/core/app.py", line 91, in run
> 
>     return method(self.parser.args)
> 
>   File "/home/travis/build/avocado-framework/avocado-vt/avocado_vt/plugins/vt_bootstrap.py", line 111, in run
> 
>     bootstrap.bootstrap(options=args, interactive=True)
> 
>   File "/home/travis/build/avocado-framework/avocado-vt/virttest/bootstrap.py", line 958, in bootstrap
> 
>     check_modules = arch.get_kvm_module_list()
> 
>   File "/home/travis/build/avocado-framework/avocado-vt/virttest/arch.py", line 89, in get_kvm_module_list
> 
>     return ["kvm", "kvm-%s" % cpu.get_vendor()]
> 
> AttributeError: 'module' object has no attribute 'get_vendor'
> ```

Agreed. Functions like 'get_family()' and 'get_verder()' are not available on 69lts which we're currently using. This patch will cause error after it got merged.  Cherry-pick should fix this.  :+1: 
I'll also close my pull request after the solution decided.

**Comment by chunfuwen** [comment]
cherry-pick avocado-framework/avocado#3350 back to 69lts is fast-forward solution, actually most of our CI testing still depends on 69lts.

**Comment by ldoktor** [comment]
@clebergnu @beraldoleal: please have a look at this PR. I know you are about to release a new LTS so the question is how fast can we move Avocado-vt to the new LTS and when the 69 LTS will be deprecated, but the reworked cpu library is quite useful especially for VT. Any suggestions how to proceed? I don't think it makes sense to attempt to add 69LTS compatibility on VT side on the other hand we don't really want to add new features to LTS releases (especially if they are dying already).

**Comment by sathnaga** [comment]
@clebergnu @beraldoleal ping

**Comment by beraldoleal** [comment]
Hi @ldoktor and @sathnaga, sorry for the delay here. From the code perspective, this looks good to me. About the LTS question, I will double-check with @clebergnu.

**Comment by sathnaga** [comment]
> Hi @ldoktor and @sathnaga, sorry for the delay here. From the code perspective, this looks good to me. About the LTS question, I will double-check with @clebergnu.

@beraldoleal did you get a chance to double check, this is taking very long time and multiple people dependant on this.

@clebergnu fyi.

**Comment by sathnaga** [comment]
> This is just renaming the methods calls since it was changed on Avocado side. So besides the CI failures, LGTM. @sathnaga can you check the CI failures, please?

@beraldoleal regarding travis failure, I had a comment already, https://github.com/avocado-framework/avocado-vt/pull/2455#issuecomment-666220878, all it needs a cheery-pick of a avocado-framework/avocado#3350 to 69lts, thanks, this helps!

**Comment by beraldoleal** [comment]
@sathnaga Oh I see, so maybe you need to adapt this code to handle both versions of Avocado, like @clebergnu did with settings PR here.

**Comment by clebergnu** [comment]
> @clebergnu @beraldoleal: please have a look at this PR. I know you are about to release a new LTS so the question is how fast can we move Avocado-vt to the new LTS and when the 69 LTS will be deprecated, but the reworked cpu library is quite useful especially for VT. Any suggestions how to proceed? I don't think it makes sense to attempt to add 69LTS compatibility on VT side on the other hand we don't really want to add new features to LTS releases (especially if they are dying already).

@ldoktor hits the nail on the head here... the kind of change in https://github.com/avocado-framework/avocado/pull/3350 is *not* suitable for LTS.  I understand Avocado-VT is a very important user (and most probably the main one), but we can not bend the core principle we've established to everyone.  That core principle is that the LTS releases receive bug fixes only, if we don't stick to it, we will end up making LTS just another non-LTS release.

There's no trivial solution here, but the best one, as @beraldoleal mentioned, is to introduce compatibility code on Avocado-VT, given that (so far) it's intended to work with both 69.x LTS and the latest and greatest Avocado.

And, given that the topic has been brought up, I'd like to notice that I'll be sending an email to the mailing list about a proposal for future Avocado and Avocado-VT interaction, with the goal of eliminating this kind of multiple Avocado version compatibility work.

@sathnaga please let me know if you need help wrt to compatibility code.  My latest experience with that was https://github.com/avocado-framework/avocado-vt/pull/2708, so it may serve as a model.

**Comment by clebergnu** [comment]
> > @clebergnu @beraldoleal: please have a look at this PR. I know you are about to release a new LTS so the question is how fast can we move Avocado-vt to the new LTS and when the 69 LTS will be deprecated, but the reworked cpu library is quite useful especially for VT. Any suggestions how to proceed? I don't think it makes sense to attempt to add 69LTS compatibility on VT side on the other hand we don't really want to add new features to LTS releases (especially if they are dying already).
> 
> @ldoktor hits the nail on the head here... the kind of change in [avocado-framework/avocado#3350](https://github.com/avocado-framework/avocado/pull/3350) is _not_ suitable for LTS. I understand Avocado-VT is a very important user (and most probably the main one), but we can not bend the core principle we've established to everyone. That core principle is that the LTS releases receive bug fixes only, if we don't stick to it, we will end up making LTS just another non-LTS release.
> 
> There's no trivial solution here, but the best one, as @beraldoleal mentioned, is to introduce compatibility code on Avocado-VT, given that (so far) it's intended to work with both 69.x LTS and the latest and greatest Avocado.
> 
> And, given that the topic has been brought up, I'd like to notice that I'll be sending an email to the mailing list about a proposal for future Avocado and Avocado-VT interaction, with the goal of eliminating this kind of multiple Avocado version compatibility work.
> 
> @sathnaga please let me know if you need help wrt to compatibility code. My latest experience with that was #2708, so it may serve as a model.

BTW, if it's not clear what's the idea behind LTS, please refer to:

https://avocado-framework.readthedocs.io/en/80.0/guides/contributor/rfcs/lts.html

**Comment by chloerh** [comment]
This way works for me, too. I guess this pr needs some upgrade of compatibility and I'll check avocado.utils.cpu related usage of tp-libvirt. There shouldn't be a lot, I'll submit code soon.
And looking forward to the greatest Avocado :1st_place_medal:

**Comment by chloerh** [comment]
I'll close my pr of fixing env_process https://github.com/avocado-framework/avocado-vt/pull/2679 since it should be included in this one later.

**Comment by sathnaga** [comment]
> > @clebergnu @beraldoleal: please have a look at this PR. I know you are about to release a new LTS so the question is how fast can we move Avocado-vt to the new LTS and when the 69 LTS will be deprecated, but the reworked cpu library is quite useful especially for VT. Any suggestions how to proceed? I don't think it makes sense to attempt to add 69LTS compatibility on VT side on the other hand we don't really want to add new features to LTS releases (especially if they are dying already).

> 
> @ldoktor hits the nail on the head here... the kind of change in [avocado-framework/avocado#3350](https://github.com/avocado-framework/avocado/pull/3350) is _not_ suitable for LTS. I understand Avocado-VT is a very important user (and most probably the main one), but we can not bend the core principle we've established to everyone. That core principle is that the LTS releases receive bug fixes only, if we don't stick to it, we will end up making LTS just another non-LTS release.
> 
> There's no trivial solution here, but the best one, as @beraldoleal mentioned, is to introduce compatibility code on Avocado-VT, given that (so far) it's intended to work with both 69.x LTS and the latest and greatest Avocado.
> 
> And, given that the topic has been brought up, I'd like to notice that I'll be sending an email to the mailing list about a proposal for future Avocado and Avocado-VT interaction, with the goal of eliminating this kind of multiple Avocado version compatibility work.

@clebergnu Agree, it becomes complex, it would be good to have some spec file to have proper interaction between avocado LTS vs Avocado-VT version to be used.
probably how about the parallel LTS version for Avocado-VT matching Avocado and both should go well, but then it will lock the
newer test changes which would need API changes, which is more often the case, and the issue in this PR aswell.


> 
> @sathnaga please let me know if you need help wrt to compatibility code. My latest experience with that was #2708, so it may serve as a model.

Sure, Thanks for the reference, let me check and come up with compatible one for both version.

**Comment by sathnaga** [comment]
> This way works for me, too. I guess this pr needs some upgrade of compatibility and I'll check avocado.utils.cpu related usage of tp-libvirt. There shouldn't be a lot, I'll submit code soon.
> And looking forward to the greatest Avocado 1st_place_medal

@chloerh Did submit one already for tp-libvirt aswell long back, still in review, https://github.com/autotest/tp-libvirt/pull/2568, probably you help speed up the review/merge.

**Comment by sathnaga** [comment]
> 
> And, given that the topic has been brought up, I'd like to notice that I'll be sending an email to the mailing list about a proposal for future Avocado and Avocado-VT interaction, with the goal of eliminating this kind of multiple Avocado version compatibility work.
> 

Looking forward to it, would like help very much incase needed.

**Comment by chloerh** [comment]
> > This way works for me, too. I guess this pr needs some upgrade of compatibility and I'll check avocado.utils.cpu related usage of tp-libvirt. There shouldn't be a lot, I'll submit code soon.
> > And looking forward to the greatest Avocado 1st_place_medal
> 
> @chloerh Did submit one already for tp-libvirt aswell long back, still in review, [autotest/tp-libvirt#2568](https://github.com/autotest/tp-libvirt/pull/2568), probably you could help speed up the review/merge.

@sathnaga Great! Already self-requested review. Thank you~

**Comment by sathnaga** [comment]
@ldoktor @beraldoleal @clebergnu I fixed the CI failures, now that we are in tagging LTS release this is good to go with 82 LTS.

**Comment by sathnaga** [comment]
now that we have less for tagging LTS and this got approved earlier and only concern was the CI failure, which is fixed now. merging this now.

will takeup incase any hotfix needed later.

**Comment by qcheng-redhat** [comment]
Hi @sathnaga,

When this patch merged, nested test case is broken. 

In guest L1 VM get error:

14:41:45 WARNI| Could not find micro-architecture/family, Error: [Errno 2] No such file or directory: '/sys/devices/cpu/caps/pmu_name'
14:41:45 ERROR|
14:41:45 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-82.0-py3.6.egg/avocado_vt/test.py:462
14:41:45 ERROR| Traceback (most recent call last):
14:41:45 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-82.0-py3.6.egg/avocado_vt/test.py", line 421, in _runTest
14:41:45 ERROR|     params = env_process.preprocess(self, params, env)
14:41:45 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-82.0-py3.6.egg/virttest/error_context.py", line 135, in new_fn
14:41:45 ERROR|     return fn(*args, **kwargs)
14:41:45 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-82.0-py3.6.egg/virttest/env_process.py", line 936, in preprocess
14:41:45 ERROR|     if "power" in cpu_family:
14:41:45 ERROR| TypeError: argument of type 'NoneType' is not iterable
14:41:45 ERROR|
14:41:45 ERROR| During handling of the above exception, another exception occurred:
14:41:45 ERROR|
14:41:45 ERROR| Traceback (most recent call last):
14:41:45 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-82.0-py3.6.egg/virttest/error_context.py", line 135, in new_fn
14:41:45 ERROR|     return fn(*args, **kwargs)
14:41:45 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-82.0-py3.6.egg/virttest/env_process.py", line 1689, in postprocess
14:41:45 ERROR|     if "power" in cpu_family:
14:41:45 ERROR| TypeError: argument of type 'NoneType' is not iterable
14:41:45 ERROR|

Could you help fix this issue ?

Thanks,
Qinghua Cheng

**Comment by sathnaga** [comment]
> Hi @sathnaga,
> 
> When this patch merged, nested test case is broken.
> 
> In guest L1 VM get error:
> 
> 14:41:45 WARNI| Could not find micro-architecture/family, Error: [Errno 2] No such file or directory: '/sys/devices/cpu/caps/pmu_name'
> 14:41:45 ERROR|
> 14:41:45 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-82.0-py3.6.egg/avocado_vt/test.py:462
> 14:41:45 ERROR| Traceback (most recent call last):
> 14:41:45 ERROR| File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-82.0-py3.6.egg/avocado_vt/test.py", line 421, in _runTest
> 14:41:45 ERROR| params = env_process.preprocess(self, params, env)
> 14:41:45 ERROR| File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-82.0-py3.6.egg/virttest/error_context.py", line 135, in new_fn
> 14:41:45 ERROR| return fn(*args, **kwargs)
> 14:41:45 ERROR| File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-82.0-py3.6.egg/virttest/env_process.py", line 936, in preprocess
> 14:41:45 ERROR| if "power" in cpu_family:
> 14:41:45 ERROR| TypeError: argument of type 'NoneType' is not iterable
> 14:41:45 ERROR|
> 14:41:45 ERROR| During handling of the above exception, another exception occurred:
> 14:41:45 ERROR|
> 14:41:45 ERROR| Traceback (most recent call last):
> 14:41:45 ERROR| File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-82.0-py3.6.egg/virttest/error_context.py", line 135, in new_fn
> 14:41:45 ERROR| return fn(*args, **kwargs)
> 14:41:45 ERROR| File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-82.0-py3.6.egg/virttest/env_process.py", line 1689, in postprocess
> 14:41:45 ERROR| if "power" in cpu_family:
> 14:41:45 ERROR| TypeError: argument of type 'NoneType' is not iterable
> 14:41:45 ERROR|
> 
> Could you help fix this issue ?
> 
> Thanks,
> Qinghua Cheng

@qcheng-redhat could you please help me with `cat /proc/cpuinfo` and `lscpu` of your environment, where it is failing...

**Comment by ldoktor** [comment]
> 
> @qcheng-redhat could you please help me with `cat /proc/cpuinfo` and `lscpu` of your environment, where it is failing...

Slightly related note, perhaps it'd make sense to get `/proc/cpuinfo` in case we fail to get `cpu_family` so we don't need to ask users for additional input.

**Comment by qcheng-redhat** [comment]
@sathnaga

On the host:
# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              20
On-line CPU(s) list: 0-19
Thread(s) per core:  2
Core(s) per socket:  10
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
Stepping:            7
CPU MHz:             2589.004
CPU max MHz:         3200.0000
CPU min MHz:         1000.0000
BogoMIPS:            4400.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            14080K
NUMA node0 CPU(s):   0-19
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
stepping        : 7
microcode       : 0x5002f01
cpu MHz         : 1405.818
cache size      : 14080 KB
physical id     : 0
siblings        : 20
core id         : 0
cpu cores       : 10
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs taa itlb_multihit
bogomips        : 4400.00
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
stepping        : 7
microcode       : 0x5002f01
cpu MHz         : 1405.818
cache size      : 14080 KB
physical id     : 0
siblings        : 20
core id         : 0
cpu cores       : 10
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs taa itlb_multihit
bogomips        : 4400.00
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
...
processor       : 19
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
stepping        : 7
microcode       : 0x5002f01
cpu MHz         : 2012.086
cache size      : 14080 KB
physical id     : 0
siblings        : 20
core id         : 10
cpu cores       : 10
apicid          : 21
initial apicid  : 21
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs taa itlb_multihit
bogomips        : 4400.00
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

**Comment by sathnaga** [comment]
@qcheng-redhat thanks for the output, looks like we do not have `/sys/devices/cpu/caps/pmu_name` on guest environment and we fail, have handled None values now, https://github.com/avocado-framework/avocado-vt/pull/2762, could you check if this fixes your issue, Thanks.

**Pull request merged**
