### PR TITLE
WinNext: Introduce a new guest name to test vnext version

### PR DESCRIPTION
**Pull request by leidwang**
Introduce a new varaint WinNext to test Windows desktop vNext edtion.

ID:2103

### CODE REVIEW

**Comment by leidwang** [comment]
Hi @vivianQizhu 
Would you please help review this patch when you free?Thanks.

**Comment by xiagao** [comment]
Run an acceptance test loop, it looks good.
ACK.

**Review by vivianQizhu — APPROVED** [review]

**Comment by vivianQizhu** [comment]
@yanan-fu @lkotek Would you please help review? Thanks.

**Comment by yanan-fu** [comment]
> @yanan-fu @lkotek Would you please help review? Thanks.

IMO, acceptance from xigao is enough, no more comments, thanks!

**Comment by lkotek** [comment]
> > @yanan-fu @lkotek Would you please help review? Thanks.
> 
> IMO, acceptance from xigao is enough, no more comments, thanks!

Same here. I have no objections :+1:

**Pull request merged**
