### PR TITLE
Support virtio-fs filesystem

### PR DESCRIPTION
**Pull request by YongxueHong**
ID: 1809579

Signed-off-by: Xu Han <xuhan@redhat.com>
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
The part of log about virtiofs by running my custom test code:
For single virtiofs daemon:
```
02:30:57 INFO | Create filesystem source /home/yhong/for-support-virtio-fs/kar/workspace/var/lib/avocado/data/avocado-vt/virtio_fs_test/.
...
02:31:00 INFO | Running virtiofs daemon command /usr/libexec/virtiofsd --socket-path=/var/tmp/avocado_3sejsr0l/avocado-vt-vm1-fs-virtiofsd.sock -o source=/home/yhong/for-support-virtio-fs/kar/workspace/var/lib/avocado/data/avocado-vt/virtio_fs_test/ -d -o cache=auto.
02:31:01 INFO | Created virtiofs daemon process with parent PID 331141.
02:31:01 INFO | Running qemu command (reformatted):
MALLOC_PERTURB_=1  /usr/libexec/qemu-kvm \
    -S  \
    -name 'avocado-vt-vm1'  \
    -sandbox on  \
    -machine q35 \
    -device pcie-root-port,id=pcie-root-port-0,multifunction=on,bus=pcie.0,addr=0x1,chassis=1 \
    -device pcie-pci-bridge,id=pcie-pci-bridge-0,addr=0x0,bus=pcie-root-port-0  \
    -nodefaults \
    -device VGA,bus=pcie.0,addr=0x2 \
    -m 4096 \
    -object memory-backend-file,size=4G,mem-path=/dev/shm,share=yes,id=mem-mem1  \
    -smp 12,maxcpus=12,cores=6,threads=1,dies=1,sockets=2  \
    -numa node,memdev=mem-mem1,nodeid=0  \
    -cpu 'SandyBridge',+kvm_pv_unhalt \
    -chardev socket,id=qmp_id_qmpmonitor1,server,path=/var/tmp/avocado_3sejsr0l/monitor-qmpmonitor1-20200509-023058-3mu4ZoP7,nowait  \
    -mon chardev=qmp_id_qmpmonitor1,mode=control \
    -chardev socket,id=qmp_id_catch_monitor,server,path=/var/tmp/avocado_3sejsr0l/monitor-catch_monitor-20200509-023058-3mu4ZoP7,nowait  \
    -mon chardev=qmp_id_catch_monitor,mode=control \
    -device pvpanic,ioport=0x505,id=id3DXJCg \
    -chardev socket,id=chardev_serial0,server,path=/var/tmp/avocado_3sejsr0l/serial-serial0-20200509-023058-3mu4ZoP7,nowait \
    -device isa-serial,id=serial0,chardev=chardev_serial0  \
    -chardev socket,id=seabioslog_id_20200509-023058-3mu4ZoP7,path=/var/tmp/avocado_3sejsr0l/seabios-20200509-023058-3mu4ZoP7,server,nowait \
    -device isa-debugcon,chardev=seabioslog_id_20200509-023058-3mu4ZoP7,iobase=0x402 \
    -device pcie-root-port,id=pcie-root-port-1,port=0x1,addr=0x1.0x1,bus=pcie.0,chassis=2 \
    -device qemu-xhci,id=usb1,bus=pcie-root-port-1,addr=0x0 \
    -device usb-tablet,id=usb-tablet1,bus=usb1.0,port=1 \
    -device pcie-root-port,id=pcie-root-port-2,port=0x2,addr=0x1.0x2,bus=pcie.0,chassis=3 \
    -device virtio-scsi-pci,id=virtio_scsi_pci0,bus=pcie-root-port-2,addr=0x0 \
    -blockdev node-name=file_image1,driver=file,aio=threads,filename=/home/kvm_autotest_root/images/rhel820-64-virtio-scsi.qcow2,cache.direct=on,cache.no-flush=off \
    -blockdev node-name=drive_image1,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_image1 \
    -device scsi-hd,id=image1,drive=drive_image1,write-cache=on \
    -chardev socket,id=char_virtiofs_fs,path=/var/tmp/avocado_3sejsr0l/avocado-vt-vm1-fs-virtiofsd.sock \
    -device vhost-user-fs-pci,id=vufs_virtiofs_fs,chardev=char_virtiofs_fs,tag=myfs,queue-size=1024,bus=pcie.0,addr=0x3 \
    -device pcie-root-port,id=pcie-root-port-3,port=0x3,addr=0x1.0x3,bus=pcie.0,chassis=4 \
    -device virtio-net-pci,mac=9a:dd:f3:b5:b4:78,id=idV1unbO,netdev=idwK3RZZ,bus=pcie-root-port-3,addr=0x0  \
    -netdev tap,id=idwK3RZZ,vhost=on,vhostfd=22,fd=14  \
    -vnc :0  \
    -rtc base=utc,clock=host,driftfix=slew  \
    -boot menu=off,order=cdn,once=c,strict=off \
    -enable-kvm \
    -device pcie-root-port,id=pcie_extra_root_port_0,multifunction=on,bus=pcie.0,addr=0x4,chassis=5
...
02:32:46 INFO | Remove filesystem source /home/yhong/for-support-virtio-fs/kar/workspace/var/lib/avocado/data/avocado-vt/virtio_fs_test/.
```
For multiple virtiofs daemons:
```
02:47:29 INFO | Create filesystem source /tmp/virtio_fs1_test.
02:47:29 INFO | Create filesystem source /tmp/virtio_fs2_test.
02:47:29 INFO | Create filesystem source /tmp/virtio_fs3_test.
02:47:29 INFO | Create filesystem source /tmp/virtio_fs4_test.
02:47:29 INFO | Create filesystem source /tmp/virtio_fs5_test.
...
02:47:31 INFO | Running virtiofs daemon command /usr/libexec/virtiofsd --socket-path=/var/tmp/avocado_js3o9f05/avocado-vt-vm1-fs1-virtiofsd.sock -o source=/tmp/virtio_fs1_test -d -o cache=auto.
02:47:32 INFO | Created virtiofs daemon process with parent PID 336555.
02:47:32 INFO | Running virtiofs daemon command /usr/libexec/virtiofsd --socket-path=/var/tmp/avocado_js3o9f05/avocado-vt-vm1-fs2-virtiofsd.sock -o source=/tmp/virtio_fs2_test -d -o cache=auto.
02:47:34 INFO | Created virtiofs daemon process with parent PID 336559.
02:47:34 INFO | Running virtiofs daemon command /usr/libexec/virtiofsd --socket-path=/var/tmp/avocado_js3o9f05/avocado-vt-vm1-fs3-virtiofsd.sock -o source=/tmp/virtio_fs3_test -d -o cache=auto.
02:47:35 INFO | Created virtiofs daemon process with parent PID 336563.
02:47:35 INFO | Running virtiofs daemon command /usr/libexec/virtiofsd --socket-path=/var/tmp/avocado_js3o9f05/avocado-vt-vm1-fs4-virtiofsd.sock -o source=/tmp/virtio_fs4_test -d -o cache=auto.
02:47:37 INFO | Created virtiofs daemon process with parent PID 336569.
02:47:37 INFO | Running virtiofs daemon command /usr/libexec/virtiofsd --socket-path=/var/tmp/avocado_js3o9f05/avocado-vt-vm1-fs5-virtiofsd.sock -o source=/tmp/virtio_fs5_test -d -o cache=auto.
02:47:38 INFO | Created virtiofs daemon process with parent PID 336573.
02:47:38 INFO | Running qemu command (reformatted):
MALLOC_PERTURB_=1  /usr/libexec/qemu-kvm \
    -S  \
    -name 'avocado-vt-vm1'  \
    -sandbox on  \
    -machine q35 \
    -device pcie-root-port,id=pcie-root-port-0,multifunction=on,bus=pcie.0,addr=0x1,chassis=1 \
    -device pcie-pci-bridge,id=pcie-pci-bridge-0,addr=0x0,bus=pcie-root-port-0  \
    -nodefaults \
    -device VGA,bus=pcie.0,addr=0x2 \
    -m 4096 \
    -object memory-backend-file,size=4G,mem-path=/dev/shm,share=yes,id=mem-mem1  \
    -smp 12,maxcpus=12,cores=6,threads=1,dies=1,sockets=2  \
    -numa node,memdev=mem-mem1,nodeid=0  \
    -cpu 'SandyBridge',+kvm_pv_unhalt \
    -chardev socket,server,path=/var/tmp/avocado_js3o9f05/monitor-qmpmonitor1-20200509-024729-WH1tga9K,nowait,id=qmp_id_qmpmonitor1  \
    -mon chardev=qmp_id_qmpmonitor1,mode=control \
    -chardev socket,server,path=/var/tmp/avocado_js3o9f05/monitor-catch_monitor-20200509-024729-WH1tga9K,nowait,id=qmp_id_catch_monitor  \
    -mon chardev=qmp_id_catch_monitor,mode=control \
    -device pvpanic,ioport=0x505,id=idGcac4m \
    -chardev socket,server,path=/var/tmp/avocado_js3o9f05/serial-serial0-20200509-024729-WH1tga9K,nowait,id=chardev_serial0 \
    -device isa-serial,id=serial0,chardev=chardev_serial0  \
    -chardev socket,id=seabioslog_id_20200509-024729-WH1tga9K,path=/var/tmp/avocado_js3o9f05/seabios-20200509-024729-WH1tga9K,server,nowait \
    -device isa-debugcon,chardev=seabioslog_id_20200509-024729-WH1tga9K,iobase=0x402 \
    -device pcie-root-port,id=pcie-root-port-1,port=0x1,addr=0x1.0x1,bus=pcie.0,chassis=2 \
    -device qemu-xhci,id=usb1,bus=pcie-root-port-1,addr=0x0 \
    -device usb-tablet,id=usb-tablet1,bus=usb1.0,port=1 \
    -device pcie-root-port,id=pcie-root-port-2,port=0x2,addr=0x1.0x2,bus=pcie.0,chassis=3 \
    -device virtio-scsi-pci,id=virtio_scsi_pci0,bus=pcie-root-port-2,addr=0x0 \
    -blockdev node-name=file_image1,driver=file,aio=threads,filename=/home/kvm_autotest_root/images/rhel820-64-virtio-scsi.qcow2,cache.direct=on,cache.no-flush=off \
    -blockdev node-name=drive_image1,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_image1 \
    -device scsi-hd,id=image1,drive=drive_image1,write-cache=on \
    -chardev socket,id=char_virtiofs_fs1,path=/var/tmp/avocado_js3o9f05/avocado-vt-vm1-fs1-virtiofsd.sock \
    -device vhost-user-fs-pci,id=vufs_virtiofs_fs1,chardev=char_virtiofs_fs1,tag=myfs1,queue-size=1024,bus=pcie.0,addr=0x3 \
    -chardev socket,id=char_virtiofs_fs2,path=/var/tmp/avocado_js3o9f05/avocado-vt-vm1-fs2-virtiofsd.sock \
    -device vhost-user-fs-pci,id=vufs_virtiofs_fs2,chardev=char_virtiofs_fs2,tag=myfs2,queue-size=1024,bus=pcie.0,addr=0x4 \
    -chardev socket,id=char_virtiofs_fs3,path=/var/tmp/avocado_js3o9f05/avocado-vt-vm1-fs3-virtiofsd.sock \
    -device vhost-user-fs-pci,id=vufs_virtiofs_fs3,chardev=char_virtiofs_fs3,tag=myfs3,queue-size=1024,bus=pcie.0,addr=0x5 \
    -chardev socket,id=char_virtiofs_fs4,path=/var/tmp/avocado_js3o9f05/avocado-vt-vm1-fs4-virtiofsd.sock \
    -device vhost-user-fs-pci,id=vufs_virtiofs_fs4,chardev=char_virtiofs_fs4,tag=myfs4,queue-size=1024,bus=pcie.0,addr=0x6 \
    -chardev socket,id=char_virtiofs_fs5,path=/var/tmp/avocado_js3o9f05/avocado-vt-vm1-fs5-virtiofsd.sock \
    -device vhost-user-fs-pci,id=vufs_virtiofs_fs5,chardev=char_virtiofs_fs5,tag=myfs5,queue-size=1024,bus=pcie.0,addr=0x7 \
    -device pcie-root-port,id=pcie-root-port-3,port=0x3,addr=0x1.0x3,bus=pcie.0,chassis=4 \
    -device virtio-net-pci,mac=9a:ad:57:4c:88:c0,id=idvDHoEd,netdev=idVNv7xj,bus=pcie-root-port-3,addr=0x0  \
    -netdev tap,id=idVNv7xj,vhost=on,vhostfd=22,fd=14  \
    -vnc :0  \
    -rtc base=utc,clock=host,driftfix=slew  \
    -boot menu=off,order=cdn,once=c,strict=off \
    -enable-kvm \
    -device pcie-root-port,id=pcie_extra_root_port_0,multifunction=on,bus=pcie.0,addr=0x8,chassis=5
02:47:40 INFO | Created qemu process with parent PID 336577
...
02:52:57 INFO | Remove filesystem source /tmp/virtio_fs1_test.
02:52:57 INFO | Remove filesystem source /tmp/virtio_fs2_test.
02:52:58 INFO | Remove filesystem source /tmp/virtio_fs3_test.
02:52:58 INFO | Remove filesystem source /tmp/virtio_fs4_test.
02:52:59 INFO | Remove filesystem source /tmp/virtio_fs5_test.
```

**Comment by YongxueHong** [comment]
Regression test:
python3 ConfigTest.py --clone=no --nrepeat=1 --platform=x86_64 --guestname=RHEL.8.2.0 --testcase=boot --driveformat=virtio_scsi --machine=q35
` (1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.boot.q35: PASS (56.72 s)`

**Comment by yanan-fu** [comment]
@YongxueHong @luckyh  gating test pass, no regression issue with this patch, thanks!

**Comment by YongxueHong** [comment]
> @YongxueHong @luckyh gating test pass, no regression issue with this patch, thanks!

@yanan-fu Thanks a lot.

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
