### PR TITLE
Revert the workaround for smbios configuration

### PR DESCRIPTION
**Pull request by leidwang**
The related problem no longer exists, so revert the previous temporary workaround commits.

ID:2109

### CODE REVIEW

**Comment by leidwang** [comment]
Hi @XueqiangWei 

As we discussed, I will remove this workaround in this PR.

Would you please help to review it? Thanks a lot!

**Review by XueqiangWei — APPROVED** [review]
(1/1) Host_RHEL.m9.u3.v0.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.boot.q35: PASS (125.85 s)

LGTM,
Acked-by: xuwei@redhat.com

**Comment by leidwang** [comment]
Hi @yanan-fu @ldoktor 

Would you please help to review or testing this PR?Thanks a lot!

**Comment by ldoktor** [comment]
I'm not really familiar with windows but looking at https://gitlab.com/mstredhat/qemu/-/commit/2c7c45b3d0ba097ac99bf4b9a13c6de1d7724032 I get the impression qemu 8.1 - 8.2 would still be affected. Wouldn't it be wise to wait for a few months before removing this workaround to avoid breakages? (again, I won't be affected so it's just an inquiry. Feel free to merge this if you thing it's safe)

**Comment by leidwang** [comment]
> I'm not really familiar with windows but looking at https://gitlab.com/mstredhat/qemu/-/commit/2c7c45b3d0ba097ac99bf4b9a13c6de1d7724032 I get the impression qemu 8.1 - 8.2 would still be affected. Wouldn't it be wise to wait for a few months before removing this workaround to avoid breakages? (again, I won't be affected so it's just an inquiry. Feel free to merge this if you thing it's safe)

Thanks a lot @ldoktor , sorry to bother you. I was originally going to @ another Lucas. Thanks again!

Hi @lkotek  Would you please help to review this PR?Thanks!

**Comment by lkotek** [comment]
Hi @leidwang, thanks for letting me know! Please, correct me if I am wrong, but wouldn't this mean e.g. RHEL 8.* systems using `qemu-kvm-6.2` are still affected by the problem, right?

**Comment by yanan-fu** [comment]
I will hold on until the product behaviours are clear from feature owner side,

Note, we have change the strategy multiple times,  i would like suggest take the ZStreams in mind, do not focus on the latest version only.

Thanks!

**Comment by XueqiangWei** [comment]
> Hi @leidwang, thanks for letting me know! Please, correct me if I am wrong, but wouldn't this mean e.g. RHEL 8.* systems using `qemu-kvm-6.2` are still affected by the problem, right?

on rhel8, the default value of smbios version is 2.8, no need add parameter "smbios-entry-point-type=32"

**Comment by leidwang** [comment]
> Hi @leidwang, thanks for letting me know! Please, correct me if I am wrong, but wouldn't this mean e.g. RHEL 8.* systems using `qemu-kvm-6.2` are still affected by the problem, right?

Actually, qemu6.2 will not be affected by this problem. That's why we need disable this configuration for RHEL8 before.

**Comment by lkotek** [comment]
> > Hi @leidwang, thanks for letting me know! Please, correct me if I am wrong, but wouldn't this mean e.g. RHEL 8.* systems using `qemu-kvm-6.2` are still affected by the problem, right?
> 
> Actually, qemu6.2 will not be affected by this problem. That's why we need disable this configuration for RHEL8 before.

Or course, you're right! Sure, now we remove this at all. Sorry, something confused me yesterday :slightly_smiling_face: 

In that case, LGTM. Thanks!

**Comment by yanan-fu** [comment]
cc @vivianQizhu  thanks~

**Comment by vivianQizhu** [comment]
Thank you all, I would say that this is a product issue, so if some elder version fail on it, it should fail as it is. Now the solution from qemu side are clear enough, I suppose we could revert the change now. @yanan-fu WDYT?

**Comment by vivianQizhu** [comment]
@leidwang Could you help revert the commit instead of creating a new one, that would be clearer for commit logs.

**Comment by leidwang** [comment]
> @leidwang Could you help revert the commit instead of creating a new one, that would be clearer for commit logs.

Okay, I will update this PR later.Thanks!

**Comment by leidwang** [comment]
Hi @vivianQizhu  I Updated the PR to revert previous commits, would you please help review this PR again?Thanks.

**Pull request merged**
