### PR TITLE
Live commit: Add with_stress (heavyload) to Windows.cfg 

### PR DESCRIPTION
**Pull request by xiywang**
ID: 1380234

Signed-off-by: xiywang <xiywang@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
@xiywang  can you show me your test results.

**Comment by xiywang** [comment]
@xutian Test results are pasted in https://github.com/autotest/tp-qemu/pull/762.
I'll copy it here also.

smp_8.8192m.repeat1.pre_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.disable_win_update: PASS (150.96 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.block_commit.with_stress: PASS (144.49 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.block_stream.with_stress: PASS (280.78 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.block_stream.with_stress.data_plane: PASS (294.18 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.block_stream.with_stress.cancel_async: PASS (337.12 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.drive_mirror.with_stress.heavyload.stress.2qcow2: PASS (323.90 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.drive_mirror.with_stress.heavyload.stress.2raw: PASS (304.57 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.drive_mirror.with_stress.heavyload.stress.on_nfs.2qcow2: PASS (302.56 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.drive_mirror.with_stress.heavyload.stress.on_nfs.2raw: PASS (294.61 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.drive_mirror.with_stress.heavyload.stop.2qcow2: PASS (286.49 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.drive_mirror.with_stress.heavyload.stop.2raw: PASS (278.59 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.drive_mirror.with_stress.heavyload.stop.on_nfs.2qcow2: PASS (293.80 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.drive_mirror.with_stress.heavyload.stop.on_nfs.2raw: PASS (328.10 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.drive_mirror.with_stress.heavyload.check_steady.2qcow2: PASS (622.60 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.drive_mirror.with_stress.heavyload.check_steady.2raw: PASS (564.61 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.drive_mirror.with_stress.heavyload.check_steady.on_nfs.2qcow2: PASS (605.34 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.myprovider.drive_mirror.with_stress.heavyload.check_steady.on_nfs.2raw: PASS (409.94 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.block_commit.with_stress: PASS (190.21 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.block_stream.with_stress: PASS (418.86 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.block_stream.with_stress.data_plane: PASS (421.67 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.block_stream.with_stress.cancel_async: PASS (418.79 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.drive_mirror.with_stress.heavyload.stress.2qcow2: PASS (591.18 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.drive_mirror.with_stress.heavyload.stress.2raw: PASS (457.38 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.drive_mirror.with_stress.heavyload.stress.on_nfs.2qcow2: PASS (432.17 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.drive_mirror.with_stress.heavyload.stress.on_nfs.2raw: PASS (442.30 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.drive_mirror.with_stress.heavyload.stop.2qcow2: PASS (408.95 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.drive_mirror.with_stress.heavyload.stop.2raw: PASS (409.39 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.drive_mirror.with_stress.heavyload.stop.on_nfs.2qcow2: PASS (565.60 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.drive_mirror.with_stress.heavyload.stop.on_nfs.2raw: PASS (398.59 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.drive_mirror.with_stress.heavyload.check_steady.2qcow2: PASS (764.06 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.drive_mirror.with_stress.heavyload.check_steady.2raw: PASS (744.19 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.drive_mirror.with_stress.heavyload.check_steady.on_nfs.2qcow2: PASS (757.44 s)
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.myprovider.drive_mirror.with_stress.heavyload.check_steady.on_nfs.2raw: PASS (746.99 s)

**Comment by xutian** [comment]
looks good, please provider ID in comment#0 please

**Comment by xiywang** [comment]
@xutian Updated!

**Comment by huangyum** [comment]
LGTM
Acked-by: Yumei Huang yuhuang@redhat.com

**Comment by xutian** [comment]
looks good to me

**Pull request merged**
