### PR TITLE
Add a new utils_pyvmomi module for vmware pyvmomi

### PR DESCRIPTION
**Pull request by xiaodwan**
Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>

### CODE REVIEW

**Comment by xiaodwan** [comment]
```python
>>> import logging
>>> from utils_pyvmomi import *
>>> from pyVmomi import vim
>>> connect_args = {'host': "x.x.x.x", 'user': 'root', 'password': 'xxxx'}
>>> logging.root.setLevel(logging.NOTSET)
>>> conn = VSphere(**connect_args)
>>> conn.target_vm = 'pyvmomi-rhel8.1'
DEBUG:root:New vsphere connection established: 'vim.ServiceInstance:ServiceInstance' (140472838077576)
DEBUG:root:Current target VM is pyvmomi-rhel8.1
>>> conn.query_changed_disk_areas(snapshot_id='snapshot-1479', disk_key=2000)
DEBUG:root:Found device: label(Hard disk 1) key(2000) summary(16,777,216 KB)
(vim.VirtualMachine.DiskChangeInfo) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   startOffset = 0,
   length = 17179869184,
   changedArea = (vim.VirtualMachine.DiskChangeInfo.DiskChangeExtent) []
}
>>> 
>>> conn.query_changed_disk_areas(snapshot_id='snapshot-1479', disk_key=2000)
DEBUG:root:Found device: label(Hard disk 1) key(2000) summary(16,777,216 KB)
(vim.VirtualMachine.DiskChangeInfo) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   startOffset = 0,
   length = 17179869184,
   changedArea = (vim.VirtualMachine.DiskChangeInfo.DiskChangeExtent) []
}
>>> 
>>> 
>>> conn.power_off()
DEBUG:root:VM pyvmomi-rhel8.1 was powered off
>>> conn.remove_current_snapshot()
DEBUG:root:Remove current snapshot for VM pyvmomi-rhel8.1
>>> conn.create_snapshot()
>>> conn.target_vm.snapshot
(vim.vm.SnapshotInfo) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   currentSnapshot = 'vim.vm.Snapshot:snapshot-1481',
   rootSnapshotList = (vim.vm.SnapshotTree) [
      (vim.vm.SnapshotTree) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         snapshot = 'vim.vm.Snapshot:snapshot-1479',
         vm = 'vim.VirtualMachine:vm-1463',
         name = 'VM Snapshot 4%252f14%252f2020, 11:02:05 PM',
         description = '',
         id = 12,
         createTime = 2020-04-14T15:01:03.454338Z,
         state = 'poweredOff',
         quiesced = false,
         backupManifest = <unset>,
         childSnapshotList = (vim.vm.SnapshotTree) [
            (vim.vm.SnapshotTree) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               snapshot = 'vim.vm.Snapshot:snapshot-1481',
               vm = 'vim.VirtualMachine:vm-1463',
               name = 'Testing Snapshot CBT',
               description = 'Created at 2020-04-22 08:41:24.661441 by Avocado-VT on testing host',
               id = 14,
               createTime = 2020-04-22T12:40:19.81676Z,
               state = 'poweredOff',
               quiesced = false,
               backupManifest = <unset>,
               childSnapshotList = (vim.vm.SnapshotTree) [],
               replaySupported = false
            }
         ],
         replaySupported = false
      }
   ]
}
>>> conn.remove_snapshot_by_id('snapshot-1479', remove_children=False)
DEBUG:root:Remove snapshot 'vim.vm.Snapshot:snapshot-1479' for VM pyvmomi-rhel8.1
>>> conn.target_vm.snapshot
(vim.vm.SnapshotInfo) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   currentSnapshot = 'vim.vm.Snapshot:snapshot-1481',
   rootSnapshotList = (vim.vm.SnapshotTree) [
      (vim.vm.SnapshotTree) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         snapshot = 'vim.vm.Snapshot:snapshot-1481',
         vm = 'vim.VirtualMachine:vm-1463',
         name = 'Testing Snapshot CBT',
         description = 'Created at 2020-04-22 08:41:24.661441 by Avocado-VT on testing host',
         id = 14,
         createTime = 2020-04-22T12:40:19.81676Z,
         state = 'poweredOff',
         quiesced = false,
         backupManifest = <unset>,
         childSnapshotList = (vim.vm.SnapshotTree) [],
         replaySupported = false
      }
   ]
}
>>> 
>>> 
>>> conn.remove_snapshot_by_id('snapshot-1479', remove_children=False)
DEBUG:root:Not found snapshot_id snapshot-1479 for VM pyvmomi-rhel8.1
>>> conn.remove_snapshot_by_id('snapshot-1479', remove_children=True)
DEBUG:root:Not found snapshot_id snapshot-1479 for VM pyvmomi-rhel8.1
>>> conn.remove_snapshot_by_id('snapshot-1479', raise_not_found=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/utils_pyvmomi.py", line 338, in wraper
    return f(self, *args, **kwargs)
  File "/root/utils_pyvmomi.py", line 555, in remove_snapshot_by_id
    raise VSphereSnapNotFound(vm_obj.name, snapshot_id)
utils_pyvmomi.VSphereSnapNotFound: snapshot not Found for VM pyvmomi-rhel8.1: snapshot-1479
>>> conn.remove_all_snapshots()
DEBUG:root:Remove all snapshots for VM pyvmomi-rhel8.1
>>> conn.target_vm.snapshot
```

**Comment by xiaodwan** [comment]
```python
>>> with VSphereConnection(**connect_args) as conn:
...     conn.target_vm = 'pyvmomi-rhel8.1'
...     print(conn.get_vm_summary()['mac_address'])
... 
DEBUG:root:New vsphere connection established: 'vim.ServiceInstance:ServiceInstance' (140472834954464)
DEBUG:root:Current target VM is pyvmomi-rhel8.1
['00:50:56:ac:09:3e']
DEBUG:root:vsphere connection closed: 'vim.ServiceInstance:ServiceInstance' (140472834954464)
```

**Comment by xiaodwan** [comment]
@chunfuwen @chloerh Please help to review this PR, thanks.

**Comment by xiaodwan** [comment]
Updated the initialization parameters, keep same as the API in pyvmomi.

```python
>>> import logging
>>> from utils_pyvmomi import *
>>> connect_args = {'host': "10.73.73.141", 'user': 'root', 'pwd': 'VCENTER@redhat2016'}
>>> ogging.root.setLevel(logging.NOTSET)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ogging' is not defined
>>> logging.root.setLevel(logging.NOTSET)
>>> conn = VSphere(**connect_args)
>>> conn.target_vm = 'pyvmomi-rhel8.1'
DEBUG:root:New vsphere connection established: 'vim.ServiceInstance:ServiceInstance' (139764656344200)
DEBUG:root:Current target VM is pyvmomi-rhel8.1
>>> conn.close()
DEBUG:root:vsphere connection closed: 'vim.ServiceInstance:ServiceInstance' (139764656344200)
>>> with VSphereConnection(**connect_args) as conn:
...     conn.target_vm = 'pyvmomi-rhel8.1'
...     print(conn.get_vm_summary()['mac_address'])
... 
DEBUG:root:New vsphere connection established: 'vim.ServiceInstance:ServiceInstance' (139764653731912)
DEBUG:root:Current target VM is pyvmomi-rhel8.1
['00:50:56:ac:09:3e']
DEBUG:root:vsphere connection closed: 'vim.ServiceInstance:ServiceInstance' (139764653731912)
>>> 
```

**Comment by xiaodwan** [comment]
Update description of the commit, fix auto reconnection problem.
```python
>>> conn.is_conn_dead()
True
>>> conn.get_vm_summary()['ip_address']
DEBUG:root:vsphere connection closed: 'vim.ServiceInstance:ServiceInstance' (140410100703528)
DEBUG:root:New vsphere connection established: 'vim.ServiceInstance:ServiceInstance' (140410099649672)
DEBUG:root:Current target VM is pyvmomi-rhel8.1
'10.73.73.163'
```

**Comment by chunfuwen** [comment]
Suggest change python file name to utils_v2v_pyvmomi.py since this is v2v specific

**Comment by xiaodwan** [comment]
> Suggest change python file name to utils_v2v_pyvmomi.py since this is v2v specific

This module is not v2v specific, this is an public module which can be used by any other modules if they want to do interactive operations with vshpere. so bind v2v to it's name will be weird.

**Pull request merged**
