### PR TITLE
virttest/utils_net.py: Update setup() and cleanup() for IPv6 address

### PR DESCRIPTION
**Pull request by dzhengfy**
When IPv6Manager sets up IPv6 environment, the setup() does not check if the specified address exists already on the host which sometimes may cause IfChangeAddrError exception.
When IPv6Manager cleans up IPv6 environment, the cleanup() does not check if the specified address is added by avocado-vt which also may cause IfChangeAddrError.

### CODE REVIEW

**Comment by will-Do** [comment]
The codes are LGTM, just two suggestions:
1) It's better to update your commit summary, an example:
```
utils_net: Check IPv6 address before add it

Before add a specific address, it's necessary to check if it exist to
avoid IfChangeAddrError exception.
```

2) For the two flags you added, I suggest to name them consistent(server/client vs src/dest)

**Comment by dzhengfy** [comment]
Running 'inspekt lint'

Pylint disabled: C,E,R,W,F0401,I0011

Pylint enabled : W0611

************* Module avocado-vt.virttest.qemu_devices.qcontainer

W0611: 21,0: : Unused import utils_misc

Pylint check fail: /home/travis/build/avocado-framework/avocado-vt/virttest/qemu_devices/qcontainer.py

Syntax check FAIL

**Comment by will-Do** [comment]
@dzhengfy 
https://github.com/avocado-framework/avocado-vt/pull/292 fix this issue and already merged, you can rebase your patch

**Comment by will-Do** [comment]
ACK and merge this fix

**Pull request merged**
