### PR TITLE
utils_qemu: Get "cpu-max" with QMP return value

### PR DESCRIPTION
**Pull request by PaulYuuu**
It is unreliable to grab the "cpu-max" through the error message of
qemu, modify the method to use the return value of qmp.

ID: 1901796
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
Hello @vivianQizhu @huangyum, please help review, thanks. `cpu_device_hotplug_maximum` and `cpu_model_negative`  will invoke it.

**Review by vivianQizhu — APPROVED** [review]
LGTM, thanks @PaulYuuu for the improvement.

**Review by huangyum — APPROVED** [review]
(1/1) type_specific.io-github-autotest-qemu.cpu_device_hotplug_maximum.default.max_socket: PASS (110.81 s)

**Comment by vivianQizhu** [comment]
Thanks @PaulYuuu @huangyum

**Pull request merged**
