### PR TITLE
virttest/utils_misc: Add rescan_windows_disk() and extend_shrink_windows_disk()

### PR DESCRIPTION
**Pull request by peixiu**
Define new functions to complete the windows disk extend and shrink.
For disk shrink, need to query maximum shrunk value, then to do shrink.
Define rescan_windows_disk() due to many process need to run these steps,
so write them on one function().

id: 1411207 1390485
Signed-off-by: Peixiu Hou <phou@redhat.com>

### CODE REVIEW

**Comment by peixiu** [comment]
@hereischen @aliang123 could you help review this patch?
thanks a lot~

**Comment by luckyh** [comment]
@peixiu suggest to move these functions to `virttest.utils_windows.drive`.

**Comment by peixiu** [comment]
@luckyh that's ok, thanks for your advise.

**Comment by peixiu** [comment]
NACK, will move them to virttest.utils_windows.drive.

**Comment by peixiu** [comment]
Moved these code to utils_windows/drive.py, so closed this patch.
https://github.com/avocado-framework/avocado-vt/pull/1459

**Pull request closed without merging**
