### PR TITLE
Add windows server 2022 support

### PR DESCRIPTION
**Pull request by lijinlijin**
1. Add guest os config files for win2022;
2. Add answer files(seabios & ovmf) for win2022.

ID: 1966588

Signed-off-by: Li Jin <lijin@redhat.com>

### CODE REVIEW

**Comment by lijinlijin** [comment]
seabios result:
(1/2) Host_RHEL.m8.u5.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: /
PASS (1045.18 s)
 (2/2) Host_RHEL.m8.u5.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.boot: PASS (118.93 s)

ovmf result:
 (1/2) Host_RHEL.m8.u5.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (792.68 s)
 (2/2) Host_RHEL.m8.u5.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.boot.q35: PASS (123.09 s)

**Comment by lijinlijin** [comment]
@luckyh 
Could you help to review this PR?

Thanks

**Comment by lijinlijin** [comment]
@yanan-fu 

Could you take a look as well?

Thanks

**Comment by yanan-fu** [comment]
LGTM

Acked-by: Yanan Fu <yfu@redhat.com>

**Review by luckyh — APPROVED** [review]

**Pull request merged**
