### PR TITLE
Restrict set of seclabels to be removed

### PR DESCRIPTION
**Pull request by smitterl**
1. del_seclabel:
 a. The function originally deleted all seclabels.
 b. Added new parameter maintaining legacy behavior.
 c. New parameter let's restrict the set of seclables
    to be removed (see docstring).

2. virttest/unittests:
 a. Created new package for unit tests and subpackage to have
    consistent paths in unittests.

3. test_vm_xml.py:
 a. Added test cases to cover previous/default and new behavior.

### CODE REVIEW

**Comment by smitterl** [comment]
@dzhengfy

**Comment by dzhengfy** [comment]
@smitterl please help correct the checking failure.

**Comment by smitterl** [comment]
@dzhengfy I do not understand how the fedora_30 and rhel_8 failures are related to my changes. There seem to be problems with vt-bootstrap on the CI but I can't reproduce the issue. LGTM.com and travis-ci have passed, also, the other avocado bootstraps did pass. Do you happen to know what the failing checks are about, e.g. https://github.com/avocado-framework/avocado-vt/pull/2323/checks?check_run_id=297190493 ?

**Comment by smitterl** [comment]
@dzhengfy https://github.com/avocado-framework/avocado-vt/pull/2325

**Comment by smitterl** [comment]
@dzhengfy accidentally closed this one, re-opened here: https://github.com/avocado-framework/avocado-vt/pull/2329

**Pull request closed without merging**
