### PR TITLE
Add options for qemu-img

### PR DESCRIPTION
**Pull request by pingl2016**
1. Add option for subcommand convert of qemu-img
2. Add option for image infomation

Signed-off-by: Ping Li pingl@redhat.com

### CODE REVIEW

**Comment by pingl2016** [comment]
ID: 1360544, 1361861, 1362009, 1362614

**Comment by CongLi** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by XueqiangWei <xuwei@redhat.com>

**Comment by xutian** [comment]
Thanks  @pingl2016 , @CongLi  and @XueqiangWei.  LGTM, Merged.

**Pull request merged**
