### PR TITLE
Check the modular daemon environment only the first time you use it

### PR DESCRIPTION
**Pull request by Yingshun**
It prints too much output when checking if it's modular daemon
environment, so update to check it when the function is first
called.

Signed-off-by: Yingshun Cui <yicui@redhat.com>

### CODE REVIEW

**Comment by Yingshun** [comment]
**Test result:**  Please ignore "ERROR:xxxx", these are debug information,  I've removed them already.
```
>>> a=utils_split_daemons.is_modular_daemon()
ERROR:root:before run: {'local': None}
ERROR:root:after run: {'local': False}

>>> a=utils_split_daemons.is_modular_daemon(remote_session2)
ERROR:root:before run: {'local': False}
ERROR:root:after run: {'local': False, 'hp-moonshot-01-c29.ml3.eng.bos.redhat.com': False}
>>> a=utils_split_daemons.is_modular_daemon(remote_session2)
ERROR:root:before run: {'local': False, 'hp-moonshot-01-c29.ml3.eng.bos.redhat.com': False}
ERROR:root:after run: {'local': False, 'hp-moonshot-01-c29.ml3.eng.bos.redhat.com': False}
>>> a
False
>>> a=utils_split_daemons.is_modular_daemon(remote_session2)
ERROR:root:before run: {'local': False, 'hp-moonshot-01-c29.ml3.eng.bos.redhat.com': False, 'dell-per730-59.lab.eng.pek2.redhat.com': True}
ERROR:root:after run: {'local': False, 'hp-moonshot-01-c29.ml3.eng.bos.redhat.com': False, 'dell-per730-59.lab.eng.pek2.redhat.com': True}
>>> a
True
```

**Comment by Yingshun** [comment]
@dzhengfy  @chloerh  Could you please help review it?

**Comment by Yingshun** [comment]
```
# avocado run --vt-type libvirt virsh.nodecpustats.unexpect_option.invalid_cpuNum

JOB ID     : c118cd80c5d35fb3a5737bbc9cf4d44677265a26
JOB LOG    : /root/avocado/job-results/job-2020-08-19T22.48-c118cd8/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.nodecpustats.unexpect_option.invalid_cpuNum: PASS (5.72 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Review by chloerh — APPROVED** [review]

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
