### PR TITLE
refactor(qemu_vm): Use QNetdev to hot plug/unplug netdev devices

### PR DESCRIPTION
**Pull request by PaulYuuu**
1. Use QNetdev to create a netdev device, and then hot-plug/unplug it
via simple_hotplug/unplug, this method will also verify if the plug
operation is completed.
2. Close origin file descriptors after getfd and close tap file
descriptors after netdev_add because qemu process retains access via
open fd, so we don't need to keep fds always open, otherwise, this will
cause fd to leak, and the qemu process takes a lot of fds.
3. Delete the tap device after netdev_del.

ID: 1400
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
Before this fix:

fds created after utils_net.open_tap() and getfd each time
```
# python_fds qemu_fds
9:33:34:35 ['155', '156', '157', '154']
23:36:38:39 ['166', '164', '163', '165']
37:40:42:43 ['166', '164', '163', '165']
41:44:46:47 ['166', '164', '163', '165']
```

After fix:
```
# python_fds qemu_fds
12:33:34:35 ['156', '157', '154', '155']
20:33:34:35 ['163', '164', '165', '166']
20:33:34:35 ['163', '164', '165', '166']
```

**Comment by PaulYuuu** [comment]
Hello @YongxueHong @yanglei-rh Could you help to review this one?

Also @yanglei-rh @heywji @maxujun @fbq815, functional testing is best to check if this causing regression issues.

**Comment by yanglei-rh** [comment]
LGTM
I will provide a test result ASAP.

**Comment by yanglei-rh** [comment]
Tested hotplug/unplug multi queues nic 500 times, it can works well.

**Comment by fbq815** [comment]
(1/4) virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.s390x.io-github-autotest-qemu.multi_nics_hotplug.nic_virtio.s390-virtio: PASS (451.53 s)
 (2/4) virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.s390x.io-github-autotest-qemu.multi_nics_hotplug.sameid.s390-virtio: PASS (127.78 s)
 (3/4) virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.s390x.io-github-autotest-qemu.nic_hotplug.used_netdev.nic_virtio.s390-virtio: PASS (28.03 s)
 (4/4)virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.s390x.io-github-autotest-qemu.multi_queues_test.with_netperf.smp1.s390-virtio: PASS (254.54 s)

LGTM

**Comment by maxujun** [comment]
(1/4) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.nic_hotplug.used_netdev.nic_virtio: STARTED
 (1/4) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.nic_hotplug.used_netdev.nic_virtio: PASS (118.26 s)
 (2/4) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.multi_nics_hotplug.nic_virtio: STARTED
 (2/4) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.multi_nics_hotplug.nic_virtio: PASS (1298.55 s)
 (3/4) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.multi_nics_hotplug.sameid: STARTED
 (3/4) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.multi_nics_hotplug.sameid: PASS (220.66 s)
 (4/4) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.multi_queues_test.with_netperf.smp1: STARTED
 (4/4) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.multi_queues_test.with_netperf.smp1: PASS (334.03 s)

LGTM

**Comment by PaulYuuu** [comment]
Hello @YongxueHong, just a reminder for this patch review, thanks.

**Comment by heywji** [comment]
LGTM

```
CaseName                                 Status          StartTime       EndTime         Result     TimeElapsed
1-Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35 Finshed 2024-01-17 16:04:46 2024-01-17 16:26:08 PASS 1281.750061
2-Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.nic_hotplug.used_netdev.nic_virtio.q35 Finshed 2024-01-17 16:26:08 2024-01-17 16:28:21 PASS 132.159368
3-Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.multi_nics_hotplug.nic_virtio.q35 Finshed 2024-01-17 16:28:21 2024-01-17 16:39:42 PASS 681.520527
4-Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.multi_nics_hotplug.sameid.q35 Finshed 2024-01-17 16:39:43 2024-01-17 16:46:21 PASS 398.073753
Summary: 
Finshed=4, PASS=4
CaseName                                 Status          StartTime       EndTime         Result     TimeElapsed
01-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.multi_nics_hotplug.nic_virtio.q35 Finshed 2024-01-17 13:41:16 2024-01-17 13:52:32 PASS 676.41462
02-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.multi_nics_hotplug.sameid.q35 Finshed 2024-01-17 13:52:32 2024-01-17 13:57:11 PASS 278.278453
03-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.nic_hotplug.used_netdev.nic_virtio.q35 Finshed 2024-01-17 13:57:11 2024-01-17 14:00:47 PASS 215.717209
04-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.multi_nics_hotplug.nic_virtio.q35 Finshed 2024-01-17 14:00:47 2024-01-17 14:12:07 PASS 679.423193
05-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.multi_nics_hotplug.sameid.q35 Finshed 2024-01-17 14:12:07 2024-01-17 14:16:33 PASS 265.753359
06-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.nic_hotplug.used_netdev.nic_virtio.q35 Finshed 2024-01-17 14:16:33 2024-01-17 14:20:23 PASS 230.350723
07-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.multi_nics_hotplug.nic_virtio.q35 Finshed 2024-01-17 14:20:24 2024-01-17 14:30:47 PASS 623.776739
08-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.multi_nics_hotplug.sameid.q35 Finshed 2024-01-17 14:30:48 2024-01-17 14:34:44 PASS 236.145741
09-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.nic_hotplug.used_netdev.nic_virtio.q35 Finshed 2024-01-17 14:34:44 2024-01-17 14:37:19 PASS 155.039348
10-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_nics_hotplug.nic_virtio.q35 Finshed 2024-01-17 14:37:20 2024-01-17 14:48:17 PASS 657.418686
11-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_nics_hotplug.sameid.q35 Finshed 2024-01-17 14:48:18 2024-01-17 14:54:43 PASS 385.475137
12-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.nic_hotplug.used_netdev.nic_virtio.q35 Finshed 2024-01-17 14:54:43 2024-01-17 14:57:57 PASS 193.359618
13-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.multi_nics_hotplug.nic_virtio.q35 Finshed 2024-01-17 14:57:57 2024-01-17 15:08:56 PASS 658.624501
14-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.multi_nics_hotplug.sameid.q35 Finshed 2024-01-17 15:08:56 2024-01-17 15:12:08 PASS 191.75399
15-Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.nic_hotplug.used_netdev.nic_virtio.q35 Finshed 2024-01-17 15:12:08 2024-01-17 15:15:11 PASS 182.578308
Summary: 
Finshed=15, PASS=15
```

**Comment by PaulYuuu** [comment]
Hello @yanglei-rh @heywji, I did a small modification, no big updates, could you help to run a sanity test with the current code? Thanks.

**Review by YongxueHong — APPROVED** [review]

**Comment by yanglei-rh** [comment]
> Hello @yanglei-rh @heywji, I did a small modification, no big updates, could you help to run a sanity test with the current code? Thanks.

It can test pass from my side.

**Review by yanglei-rh — APPROVED** [review]

**Comment by YongxueHong** [comment]
> Hello @yanglei-rh @heywji, I did a small modification, no big updates, could you help to run a sanity test with the current code? Thanks.

Hi @heywji 
Would you like to help to run test with the latest code? Thanks in advance.

**Comment by heywji** [comment]
Hi @YongxueHong

Sorry, I ignored it. I am running now.

Thanks Lei for the private reminder.

**Comment by heywji** [comment]
It can also test pass from my side, including Win2022 Win2019 Win11 Win10.i386, and Win10.x86_64.

**Review by heywji — APPROVED** [review]

**Comment by YongxueHong** [comment]
Thanks all, let's merge it.

**Pull request merged**
