### PR TITLE
Add_pcidevice: format cmd line to json

### PR DESCRIPTION
**Pull request by quanwenli**
ID: 1552
Signed-off-by: Wenli Quan [wquan@redhat.com](mailto:wquan@redhat.com)

### CODE REVIEW

**Comment by quanwenli** [comment]
JOB LOG    : /root/avocado/job-results/job-2023-11-21T16.51-9239321/job.log
 (1/1) BF3.vfio_test.1q.acceptance.repeat1.Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.netperf.with_jumbo.host_guest.q35: STARTED
 (1/1) BF3.vfio_test.1q.acceptance.repeat1.Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.netperf.with_jumbo.host_guest.q35: PASS (311.95 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-11-21T16.51-9239321/results.html

**Comment by quanwenli** [comment]
@nickzhq could you help review this ? Thanks

**Comment by nickzhq** [comment]
> @nickzhq could you help review this ? Thanks

Ack.

@YongxueHong @zhencliu  Please give a feedback, thanks!

**Review by YongxueHong — APPROVED** [review]

**Comment by nickzhq** [comment]
Hello @quanwenli , based on your commit, do you want to cover the line `dev = qdevices.QCustomDevice('pcidevice', parent_bus=pci_bus)` ?
If Not, your code is okay to me.
If yes, the device can NOT be present in json format.

**Comment by quanwenli** [comment]
> Hello @quanwenli , based on your commit, do you want to cover the line `dev = qdevices.QCustomDevice('pcidevice', parent_bus=pci_bus)` ? If Not, your code is okay to me.

I do not have this requirement.   

If yes, the device can NOT be present in json format.

**Comment by nickzhq** [comment]
> > Hello @quanwenli , based on your commit, do you want to cover the line `dev = qdevices.QCustomDevice('pcidevice', parent_bus=pci_bus)` ? If Not, your code is okay to me.
> 
> I do not have this requirement.
> 
> If yes, the device can NOT be present in json format.

FYI, cc @YongxueHong @zhencliu

**Comment by zhencliu** [comment]
> > If yes, the device can NOT be present in json format.

> > > Hello @quanwenli , based on your commit, do you want to cover the line `dev = qdevices.QCustomDevice('pcidevice', parent_bus=pci_bus)` ? If Not, your code is okay to me.
> > 
> > 
> > I do not have this requirement.
Then we may put the format setting line under line 938, it's not a good idea to put it here for it also handles qdevices.QCustomDevice even we don't use it any more, cc @YongxueHong 

> > If yes, the device can NOT be present in json format.
> 
> FYI, cc @YongxueHong @zhencliu

**Comment by quanwenli** [comment]
> > > If yes, the device can NOT be present in json format.
> 
> > > > Hello @quanwenli , based on your commit, do you want to cover the line `dev = qdevices.QCustomDevice('pcidevice', parent_bus=pci_bus)` ? If Not, your code is okay to me.
> > > 
> > > 
> > > I do not have this requirement.
> 
> Then we may put the format setting line under line 938, it's not a good idea to put it here for it also handles qdevices.QCustomDevice even we don't use it any more, cc @YongxueHong

I have updated it under the line 938. 
> 
> > > If yes, the device can NOT be present in json format.
> > 
> > 
> > FYI, cc @YongxueHong @zhencliu

**Comment by quanwenli** [comment]
JOB LOG    : /root/avocado/job-results/job-2023-12-05T17.04-4c794e0/job.log
 (1/1) BF3.vfio_test.1q.acceptance.repeat1.Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.netperf.with_jumbo.host_guest.q35: STARTED
BF3.vfio_test.1q.acceptance.repeat1.Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.netperf.with_jumbo.host_guest.q35: PASS (378.49 s)

**Review by YongxueHong — APPROVED** [review]

**Review by zhencliu — APPROVED** [review]

**Pull request merged**
