### PR TITLE
Fix argument passing in wait_for_ssh_login_to_migrate

### PR DESCRIPTION
**Pull request by xiaodwan**
Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>

### CODE REVIEW

**Comment by xiaodwan** [comment]
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.without_default_net.esx_70.rhev.rhv_upload.it_vddk.esx_uri: PASS (459.00 s)

**Comment by xiaodwan** [comment]
> This pull request **introduces 1 alert** when merging [305fc55](https://github.com/avocado-framework/avocado-vt/commit/305fc552657d6ca8e4569a2641086af956469fce) into [d7073f4](https://github.com/avocado-framework/avocado-vt/commit/d7073f4718b20e98147866f9e92091f66d2a4a46) - [view on LGTM.com](https://lgtm.com/projects/g/avocado-framework/avocado-vt/rev/pr-b0e5206596d7fc20fef809720972e4fd1e906e36)
> 
> **new alerts:**
> 
>     * 1 for Wrong name for an argument in a call

Is it because aexpect 1.6.0 in python2.7? The new argument is introduced in aexpect 1.6.1.

**Review by pevogam — COMMENTED** [review]
Hi @xiaodwan, good that we added the extra argument here too. However, if aexpect 1.6.1 is rolled out perhaps we could deprecate both `*_to_migrate` functions for the sake of the enhanced ones provided by aexpect?

**Comment by xiaodwan** [comment]
> Hi @xiaodwan, good that we added the extra argument here too. However, if aexpect 1.6.1 is rolled out perhaps we could deprecate both `*_to_migrate` functions for the sake of the enhanced ones provided by aexpect?

The problem is avocado-vt doesn't support any aexpect>=1.6.1 in python2.7 because of python2 compatibility issue. 
so any fixes after aexpect 1.6.1 cannot work in python2.7, that means if you need to fix something in aexpect, the fix
will not work in python2.7 and always fail the travis CI.
I've no idea how to solve this problem.  
@pevogam @lmr @ldoktor @chunfuwen Do you have any idea about aexpect>=1.6.1 doesn't support python2 and if some fixes in avocado-vt depends on aexpect>=1.6.1 will not pass travis CI in python2.7?

**Comment by pevogam** [comment]
> > Hi @xiaodwan, good that we added the extra argument here too. However, if aexpect 1.6.1 is rolled out perhaps we could deprecate both `*_to_migrate` functions for the sake of the enhanced ones provided by aexpect?
> 
> The problem is avocado-vt doesn't support any aexpect>=1.6.1 in python2.7 because of python2 compatibility issue.
> so any fixes after aexpect 1.6.1 cannot work in python2.7, that means if you need to fix something in aexpect, the fix
> will not work in python2.7 and always fail the travis CI.

Ah, python 2 again, good point... I am wondering if we could add a tag, comment or something in the docstring of each of these two functions to clarify that the only reason we are not dropping them is python 2. This could be useful if other people look at them and raise the same questions.

> I've no idea how to solve this problem.

Perhaps we could disable the specific unit tests or checks on the python 2 side of the CI and localize such disabling process as much as possible.

> @pevogam @lmr @ldoktor @chunfuwen Do you have any idea about aexpect>=1.6.1 doesn't support python2 and if some fixes in avocado-vt depends on aexpect>=1.6.1 will not pass travis CI in python2.7?

Yes, we have lots of newer code which makes it impossible to keep supporting python 2. The only reason why we still keep such support in Avocado VT is because in @ldoktor's words we could keep it for as long as we get it for free and are not forced to drop it. I do get increasingly concerned however that it keeps contributing to a bogged decision process where we cannot make steps forward.

Anyway, perhaps we could just tag the two functions as "undroppable" due to python 2 and try to localize the CI failure through some additional magic.

**Comment by xiaodwan** [comment]
@pevogam How do you like the change? It's better to disable E1123 for python3 function, meanwhile it will not break the python2 execution.

**Review by pevogam — APPROVED** [review]
Hi @xiagao I think it is a good change since these two functions are deprecated code anyway. Thanks for the fix!

**Comment by xiaodwan** [comment]
@chunfuwen @chloerh Please help to review this PR, thanks.

**Comment by chloerh** [comment]
@Yingshun Would you like to review?

**Review by Yingshun — APPROVED** [review]

**Comment by pevogam** [comment]
@Yingshun since the PR has two approvals we can also merge.

**Pull request merged**
