### PR TITLE
guest-os.cfg: update netperf params for ppc guest

### PR DESCRIPTION
**Pull request by xutian**
ID: 1304314

Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by CongSmile** [comment]
@luckyh

**Comment by mazhang** [comment]
I think add the build type for each platform in config file of the case is more reasonable.
Plus, the time of parse by cartesion script with two ways was pretty much equal.

example:
`    ppc64:
        netperf_build_type = "--build=ppc64"
    ppc64le:
        netperf_build_type = "--build=ppc64le"
    setup_cmd = "cd /tmp && rm -rf netperf-2.6.0 && tar xvfj netperf-2.6.0.tar.bz2 && cd netperf-2.6.0 && ./configure ${netperf_build_type} --enable-burst --enable-demo=yes && make"`

**Comment by Zhengtong** [comment]
I also suggest to add the params to sub-cases configure files. Seems these configurations have more relations with netperf test case itself, though have to specify the difference b/w architecture.

**Comment by xutian** [comment]
Ok.  close this one, please refer fix @https://github.com/autotest/tp-qemu/pull/557

**Pull request closed without merging**
