### PR TITLE
fix python3 compatibility issue

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 1654097

### CODE REVIEW

**Comment by XueqiangWei** [comment]
Tested with python3, the result is passed.

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by XueqiangWei** [comment]
@hereischen @luckyh updated, please help review it. Many thanks.

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
