### PR TITLE
Updates to setup.py, Makefile and CI

### PR DESCRIPTION
**Pull request by ana**
* ` Makefile`:
  *  fix default target
  * update check target to include the spellchecker
  
* `setup.py`: add custom command `clean`

* CI
   *  Add job to build package (egg)
   * Check signed-off-by to make sure new commits are signed by the author.
   * Add spellchecker together with its requirements on pyenchant to `requirements-travis.txt`
After the update, the CI will look like this https://github.com/ana/avocado-vt/actions/runs/1115976569
  
And last, but not least, many many typo fixes and a big update to `spell.ignore`

### CODE REVIEW

**Comment by chunfuwen** [comment]
@ana  Do you want to squash six commits as one commit?

**Comment by ana** [comment]
> @ana Do you want to separate this PR into a few ones, for example, typo fixing can be independent one?

@chunfuwen Ok, I have started with a first PR addressing the typo and the spell.ignore update. Please see https://github.com/avocado-framework/avocado-vt/pull/3183

**Comment by ana** [comment]
And a second PR at https://github.com/avocado-framework/avocado-vt/pull/3184
I left for a 3rd and last PR the most disruptive changes (github actions and `make check` behavior)

**Comment by ana** [comment]
Third, and last PR, from here is at https://github.com/avocado-framework/avocado-vt/pull/3186

**Pull request closed without merging**
