### PR TITLE
qemu_vm.activate_netdev: Change "vnet_hdr=Flase" to "vnet_hdr=True"

### PR DESCRIPTION
**Pull request by yanglei-rh**
Keep the same usage with libvirt

ID:2174625
Signed-off-by: Lei Yang leiyang@redhat.com

### CODE REVIEW

**Comment by yanglei-rh** [comment]
Hello @luckyh @PaulYuuu Please help me review it, thanks a lot.

**Comment by yanglei-rh** [comment]
Hello @leidwang @zhenyzha Please help review it, thanks a lot.

**Comment by luckyh** [comment]
@xiangchunfu would you please help check if this change works for kata scenarios as well?

**Comment by xiangchunfu** [comment]
For kata scenario,  vnet_hdr option is enabled by default.  This change won't affect kata scenario.
1) on worker node
#ip -d tuntap
...
tap: tap multi_queue vnet_hdr persist
	Attached to processes:
...
2) It is enabled from kata source code by default(Thanks Xu for helping kata code) 

Acked by: xfu@redhat.com

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
