### PR TITLE
Add Win2025 support

### PR DESCRIPTION
**Pull request by leidwang**
Microsoft released a new windows server version, add related configuration to support Win2025 in avocado-vt.

ID:1936

### CODE REVIEW

**Comment by leidwang** [comment]
Hi @vivianQizhu 

Would you please review this PR?Thanks!

**Comment by vivianQizhu** [comment]
@xiagao @menli820 Request for your review, thank you.

**Comment by menli820** [comment]
I am running some sanity testing，need some time, will update the result once finish.

**Comment by menli820** [comment]
> I am running some sanity testing，need some time, will update the result once finish.

LGTM.
sanity testing pass

**Review by menli820 — APPROVED** [review]

**Review by vivianQizhu — APPROVED** [review]

**Pull request merged**
