### PR TITLE
Fix outdated usage of numa_cell

### PR DESCRIPTION
**Pull request by chloerh**
Usage of numa_cell is changed now.

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

### CODE REVIEW

**Comment by chloerh** [comment]
PASS 1-type_specific.local.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_on.lock_posix_off.cache_mode_always.one_fs.one_guest

**Review by dzhengfy — APPROVED** [review]
LGTM

**Comment by dzhengfy** [comment]
@kylazhang Could you help double review?

**Comment by dzhengfy** [comment]
If other cases' failures are found, we will file new PR to fix.

**Comment by sathnaga** [comment]
@chloerh @dzhengfy fyi https://github.com/avocado-framework/avocado-vt/pull/2895

**Pull request merged**
