### PR TITLE
Virt_vm: add macvtap device check for verify_dmesg.

### PR DESCRIPTION
**Pull request by quanwenli**
Signed-off-by: Wenli Quan <wquan@redhat.com>

ID: 1528569

### CODE REVIEW

**Comment by quanwenli** [comment]
JOB LOG    : /root/avocado/job-results/job-2017-12-22T04.27-2bd9f9d/job.log
 (1/1) smp_8.4096m.repeat1.repeat1.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.RHEL.7.4.x86_64.io-github-autotest-qemu.netperf.jumbo.host_guest: PASS (623.42 s)

**Comment by quanwenli** [comment]
@hereischen , I have removed "." in my commit log.

**Comment by balamuruhans** [comment]
@sathnaga can you help to review this PR

**Comment by quanwenli** [comment]
JOB LOG    : /root/avocado/job-results/job-2018-03-15T01.53-33f874c/job.log
 (1/2) smp_8.8192m.repeat1.repeat1.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.netperf.jumbo.host_guest: PASS (239.52 s)
 (2/2) smp_8.8192m.repeat1.repeat1.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.netperf.default.host_guest: PASS (312.21 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by luckyh** [comment]
Please add the signed-off signature into commit message.

**Pull request merged**
