### PR TITLE
add  set static IP address in guest support

### PR DESCRIPTION
**Pull request by xutian**

### CODE REVIEW

**Comment by xutian** [comment]
@CongSmile   would you like to help review this PR,  thanks.

**Comment by suqinhuang** [comment]
hi @xutian 
could you provide id

**Comment by xutian** [comment]
Hi @suqinhuang ,

It's very old fix to virt_test, I just do some enhancement, so I can't find a id for it.

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Pull request merged**
