### PR TITLE
[V1] Merge with virt-test

### PR DESCRIPTION
**Pull request by lmr**
Merge virt-test inside avocado-vt. This involves picking up virt-test's entire history and bringing it to avocado-vt.

Changes from V0:
* Consolidated the last commits, making them more cohesive and easy to follow.

### CODE REVIEW

**Comment by adereis** [comment]
Cool. Can you please provide test instructions? A couple of high level issues:

 - README needs to be updated
 - the concept of "dropin" tests should be removed, as avocado has native support for it
 - virt-test/ content should be merged into other directories and files, being updated in the process.

**Comment by lmr** [comment]
@adereis, sure, I'll be working on everything you mentioned.

**Comment by lmr** [comment]
@adereis now I think I got things mostly right. Things are functional either through RPM install and doing 'make link' on the avocado repo, provided that avocado is in the branch of PR https://github.com/avocado-framework/avocado/pull/708. As for instructions, you can find them here:

https://github.com/avocado-framework/avocado-vt/blob/0a7aedc34ee84157206b4a56f255a0827744166f/README.rst

I believe I have addressed your concerns, but of course, this is quite the tricky work, so I'm expecting that you, @clebergnu and @ldoktor will find plenty of problems.

**Comment by lmr** [comment]
Closing in favor of #31

**Pull request closed without merging**
