### PR TITLE
env_process: Refactor firewalld setup/cleanup into a Setuper

### PR DESCRIPTION
**Pull request by bgartzi**
Move the setup step of the firewalld service from the env_process.{pre,post}process into a Setuper subclass. The env_process setup_manager will call the setup/cleanup methods when appropriate.

ID: 2276

### CODE REVIEW

**Comment by bgartzi** [comment]
Hi @YongxueHong, could you review this please?

@yanglei-rh some networking tests rely on disabling firewalld during the test setup step. This change might affect that. To cover it, I ran the `iperf_test` test variants and all passed. I also confirmed that `firewalld` was active before running the tests but inactive after that. Other tests that need to disable firewalld should also be okay after this change.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by YongxueHong** [comment]
Hi @yanglei-rh 
Could you help to review it?
Thanks in advance.

**Comment by yanglei-rh** [comment]
> Hi @yanglei-rh Could you help to review it? Thanks in advance.

The code are LGTM, but in order to code stable, let me apply this patch and test it with all the network cases. I will update test result ASAP.

**Comment by bgartzi** [comment]
Thanks @YongxueHong, @yanglei-rh!

**Review by yanglei-rh — APPROVED** [review]
Test pass with virtual network regression tests.

**Comment by YongxueHong** [comment]
Thanks all. Let's merge it.

**Pull request merged**
