### PR TITLE
update for further usage in bandwidth value get

### PR DESCRIPTION
**Pull request by kylazhang**
it also affect 1 usage in tp-libvirt so need to merge them all at the same time

### CODE REVIEW

**Comment by kylazhang** [comment]
@sathnaga could you please help to check it? As one related tp-libvirt patch already merged and the running will have some problem

**Comment by kylazhang** [comment]
@sathnaga @balamuruhans could you please help to review it? Thanks

**Comment by sathnaga** [comment]
@kylazhang next time pls explain reason better in commit message, Thanks :-)

**Comment by kylazhang** [comment]
@sathnaga, ok, thanks for remind.

**Pull request merged**
