### PR TITLE
unattended_install: Load viomem driver

### PR DESCRIPTION
**Pull request by menli820**
Install viomem driver during guest installation

ID: 1946

Signed-off-by: menli <menli@redhat.com>

### CODE REVIEW

**Comment by menli820** [comment]
No available package to test, so change it to draft first.

**Comment by menli820** [comment]
This patch depends on:
https://gitlab.cee.redhat.com/kvm-qe/kar/-/merge_requests/1272

**Comment by menli820** [comment]
@leidwang  please help to review it when you free, thanks

**Comment by menli820** [comment]
paste partly log here:

[stdlog] 2024-06-04 14:00:14,336 avocado.unattended_install unattended_insta L0689 DEBUG|                                 <PathAndCredentials wcm:keyValue="11" wcm:action="add">
[stdlog] 2024-06-04 14:00:14,336 avocado.unattended_install unattended_insta L0689 DEBUG|                                         <Path>**F:\viomem\w10\x86**</Path>
[stdlog] 2024-06-04 14:00:14,336 avocado.unattended_install unattended_insta L0689 DEBUG|                                 </PathAndCredentials>
[stdlog] 2024-06-04 14:00:14,336 avocado.unattended_install unattended_insta L0689 DEBUG| 			</DriverPaths>
[stdlog] 2024-06-04 14:00:14,336 avocado.unattended_install unattended_insta L0689 DEBUG| 		</component>

**Review by leidwang — APPROVED** [review]
LGTM

**Comment by menli820** [comment]
@PaulYuuu  please help to review it when you free, thanks

**Comment by PaulYuuu** [comment]
> This patch depends on: [gitlab.cee.redhat.com/kvm-qe/kar/-/merge_requests/1272](https://gitlab.cee.redhat.com/kvm-qe/kar/-/merge_requests/1272)

@YongxueHong please help to delete this comment.

**Review by PaulYuuu — APPROVED** [review]

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
