### PR TITLE
Added support for Fedora24 ppc64le guest

### PR DESCRIPTION
**Pull request by sathnaga**
Added config and kickstart file for Fedora24 ppc64le
guest support

### CODE REVIEW

**Comment by sathnaga** [comment]
JOB ID     : 2264e0af03ac15aac359d19287987dfb89351f67
JOB LOG    : /var/lib/libvirt/images/workspace/runAvocadoTest/avocado-wrapper/results/job-2016-08-19T01.19-2264e0a/job.log
TESTS      : 2
 (1/2) guest_install.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.http_ks.default_install.aio_native: PASS (472.76 s)
 (2/2) guest_install.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-libvirt.remove_guest.without_disk: PASS (1.20 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /var/lib/libvirt/images/workspace/runAvocadoTest/avocado-wrapper/results/job-2016-08-19T01.19-2264e0a/html/results.html
TESTS TIME : 473.96 s

**Comment by bssrikanth** [comment]
ACKed

**Comment by sathnaga** [comment]
@ldoktor can this be merged, if no comments, Thanks in advance :-)

**Comment by lmr** [comment]
Merged, thanks!

**Comment by ldoktor** [comment]
Well actually there is no difference between F23 and F24 kickstart, so I don't see a reason for calling the kickstart file `Fedora-24-ppc64le.ks`. Apart from that it looks good.

**Comment by sathnaga** [comment]
@ldoktor reason behind kept them separate incase of any power specific package inclusion, changes in future needed.

**Pull request merged**
