### PR TITLE
utils_env:register iscsidev to env

### PR DESCRIPTION
**Pull request by aliang123**
register iscsidev to env
    
    Signed-off-by: Aihua Liang <aliang@redhat.com>
    id:2100690

### CODE REVIEW

**Comment by aliang123** [comment]
@zhencliu @YongxueHong, please help to review, thanks.

**Comment by YongxueHong** [comment]
Hi @aliang123 
Would you like to explain the reason why register the iscsidev to env?
Thanks.

**Comment by aliang123** [comment]
> Hi @aliang123 Would you like to explain the reason why register the iscsidev to env? Thanks.
In original code,
  In pre stage, we define an iscsidev instance to do some setup steps, then in post stage, we re-define an iscsidev instance to do some cleanup steps, that's not reasonable, and we should operate the same iscsidev instance in pre and post stage.
 
So after discussion with zhenchao, I update code as it is now:
   In pre stage, we define an iscsidev instance to do some setup steps, then we store it in the env, and get it in the post stage to do some cleanup steps.

**Comment by zhencliu** [comment]
> > Hi @aliang123 Would you like to explain the reason why register the iscsidev to env? Thanks.
> > In original code,
> > In pre stage, we define an iscsidev instance to do some setup steps, then in post stage, we re-define an iscsidev instance to do some cleanup steps, that's not reasonable, and we should operate the same iscsidev instance in pre and post stage.
> 
> So after discussion with zhenchao, I update code as it is now: In pre stage, we define an iscsidev instance to do some setup steps, then we store it in the env, and get it in the post stage to do some cleanup steps.

yes, just handle iscsidev in the same way to handle lvmdev in VT. 
But I just found that env can be 'pickled', do you have concern about that? @YongxueHong

**Comment by YongxueHong** [comment]
> > > Hi @aliang123 Would you like to explain the reason why register the iscsidev to env? Thanks.
> > > In original code,
> > > In pre stage, we define an iscsidev instance to do some setup steps, then in post stage, we re-define an iscsidev instance to do some cleanup steps, that's not reasonable, and we should operate the same iscsidev instance in pre and post stage.
> > 
> > 
> > So after discussion with zhenchao, I update code as it is now: In pre stage, we define an iscsidev instance to do some setup steps, then we store it in the env, and get it in the post stage to do some cleanup steps.
> 
> yes, just handle iscsidev in the same way to handle lvmdev in VT. But I just found that env can be 'pickled', do you have concern about that? @YongxueHong

Hi @aliang123 CC @zhencliu 
You mean the pre stage and post stage is the job stage or the test stage?
From the your patch, I think your requirements focus on the test stage which is to set up the environment for the test, so I suggest that we could use the `_setup_manager = test_setup.SetupManager()` then register your setup.
You can refer to:
```
    _setup_manager.initialize(test, params, env)
    _setup_manager.register(test_setup.UlimitConfig)
    _setup_manager.do_setup()
```
The registering objects in the `env` is aim to keep the objects to be calling among the multiple jobs, like vm object.
So I think it is not appropriate for registering in the `env`.

**Comment by YongxueHong** [comment]
> > > Hi @aliang123 Would you like to explain the reason why register the iscsidev to env? Thanks.
> > > In original code,
> > > In pre stage, we define an iscsidev instance to do some setup steps, then in post stage, we re-define an iscsidev instance to do some cleanup steps, that's not reasonable, and we should operate the same iscsidev instance in pre and post stage.
> > 
> > 
> > So after discussion with zhenchao, I update code as it is now: In pre stage, we define an iscsidev instance to do some setup steps, then we store it in the env, and get it in the post stage to do some cleanup steps.
> 
> yes, just handle iscsidev in the same way to handle lvmdev in VT. But I just found that env can be 'pickled', do you have concern about that? @YongxueHong

Hi @aliang123 CC @zhencliu 
You mean the pre stage and post stage is the job stage or the test stage?
From the your patch, I think your requirements focus on the test stage which is to set up the environment for the test, so I suggest that we could use the `_setup_manager = test_setup.SetupManager()` then register your setup.
You can refer to:
```
    _setup_manager.initialize(test, params, env)
    _setup_manager.register(test_setup.UlimitConfig)
    _setup_manager.do_setup()
```
The registering objects in the `env` is aim to keep the objects to be calling among the multiple jobs, like vm object.
So I think it is not appropriate for registering in the `env`.

**Comment by zhencliu** [comment]
> > > > Hi @aliang123 Would you like to explain the reason why register the iscsidev to env? Thanks.
> > > > In original code,
> > > > In pre stage, we define an iscsidev instance to do some setup steps, then in post stage, we re-define an iscsidev instance to do some cleanup steps, that's not reasonable, and we should operate the same iscsidev instance in pre and post stage.
> > > 
> > > 
> > > So after discussion with zhenchao, I update code as it is now: In pre stage, we define an iscsidev instance to do some setup steps, then we store it in the env, and get it in the post stage to do some cleanup steps.
> > 
> > 
> > yes, just handle iscsidev in the same way to handle lvmdev in VT. But I just found that env can be 'pickled', do you have concern about that? @YongxueHong
> 
> Hi @aliang123 CC @zhencliu You mean the pre stage and post stage is the job stage or the test stage? From the your patch, I think your requirements focus on the test stage which is to set up the environment for the test, so I suggest that we could use the `_setup_manager = test_setup.SetupManager()` then register your setup. You can refer to:
> 
> ```
>     _setup_manager.initialize(test, params, env)
>     _setup_manager.register(test_setup.UlimitConfig)
>     _setup_manager.do_setup()
> ```
> 
> The registering objects in the `env` is aim to keep the objects to be calling among the multiple jobs, like vm object. So I think it is not appropriate for registering in the `env`.
hi @YongxueHong , consider this situation:
job1: run the job with iscsi backend, then save env(iscsidev) to a file
job2: run the job with nfs backend, and restore env from job1, then the only way we can get iscsi backend info is to restore it from env. But I don't think we need to cover that test scenario, @aliang123 what do you think?
And a 3rd way is to keep the code unchanged, just do a small code change for aihua's tests.

**Comment by aliang123** [comment]
> _setup_manager

Hi, @YongxueHong 
   From the test aspect, iscsi setup and clean should be in job related stage, not in test case stage. So I think, add it to env is reasonable.
  cc @zhencliu

**Comment by YongxueHong** [comment]
> > _setup_manager
> 
> Hi, @YongxueHong From the test aspect, iscsi setup and clean should be in job related stage, not in test case stage. So I think, add it to env is reasonable. cc @zhencliu


Hi @aliang123 
From your code, I see that you unregister the iscsi during the postprocess stage.
```
    if params.get("storage_type") == "iscsi":
        ...
        env.unregister_iscsidev("iscsi_%s" % params["main_vm"])
```
I mean however the `env` will always unregister the iscsi dev after running the test case, maybe for the next job, it can not get the previous iscsi dev, seems like it can not reach the goal of the job-related stage.

**Comment by aliang123** [comment]
Close this patch for other solution has been adopted.

**Pull request closed without merging**
