### PR TITLE
qcontainer.py: add "wwn" property for device.

### PR DESCRIPTION
**Pull request by CongSmile**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1287509

### CODE REVIEW

**Comment by CongSmile** [comment]
Hi @xutian and @suqinhuang 

Could you help review this PR?

Thanks.

**Comment by xutian** [comment]
@CongSmile  virtio-blk device not wwn property, as we told you can use wwn for no-virtio device, serial for wwn device.

Thanks,
Xu

**Comment by xutian** [comment]
sorry, it should be virtio-blk device

**Comment by CongSmile** [comment]
@xutian 

Ok, will update it.

**Comment by CongSmile** [comment]
Close this PR, as the wwn option has been implemented in "blk_extra_params".

**Pull request closed without merging**
