### PR TITLE
remote: fix unexpect serial login timeout

### PR DESCRIPTION
**Pull request by xutian**
sometimes, linux kernel print messages into console
impact match login prompt, send a new line then try
again to avoid this kind of unexpect login timeout.

Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
After this patch applied, rerun about  50 failed cases that caused by following error, all pass in my test:
11:23:07 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-47.0-py2.7.egg/virttest/remote.py", line 197, in handle_prompts
11:23:07 ERROR|     raise LoginTimeoutError(e.output)
11:23:07 ERROR| LoginTimeoutError: Login timeout expired    (output: '')

**Comment by yanan-fu** [comment]
Acked-by:Yanan Fu  yfu@redhat.com

**Comment by xutian** [comment]
It's really a good news, thanks your test results.

**Comment by xutian** [comment]
Merged, thanks @yanan-fu

**Pull request merged**
