### PR TITLE
virttest: fix _open_log_file namespace issue

### PR DESCRIPTION
**Pull request by xutian**
close function of session object use variable '_open_log_file'
in module 'aexpect.utils.genio' to collect opened fds, this
commit put fd opened by 'log_line' function in it to avoid
fd not closed after close session.

ID: 1408179

Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
@CongLi and @suqinhuang  can you help to review this pull request.

**Comment by CongLi** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by CongLi** [comment]
@luckyh 

Could you please help review this PR?

Many thanks.

**Comment by suqinhuang** [comment]
fd is still increasing

**Comment by suqinhuang** [comment]
Looks good

Acked-by: Suqin Huang

**Comment by xutian** [comment]
merged, and thanks @CongLi , @suqinhuang and @luckyh

**Pull request merged**
