### PR TITLE
Add_one parameter into build_client_key to extend encrypt client key

### PR DESCRIPTION
**Pull request by chunfuwen**
Private key need to be encrypted by input password somehow

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
command log:
(p3-ve) [root@hp-dl360g9-16 avocado-vt]# certtool --generate-privkey --outfile x509-ca-key.pem --password "secret"
Assuming PKCS #8 format...
Generating a 3072 bit RSA private key...
(p3-ve) [root@hp-dl360g9-16 avocado-vt]#  certtool --key-info < x509-ca-key.pem | head -5
Encrypted structure detected...
Enter password: 
PKCS #8 information:
	Cipher: AES-128-CBC
	Schema: PBES2-AES128-CBC (2.16.840.1.101.3.4.1.2)
	Salt: c74f7976820c9a75f85f7b850a41f65613
	Salt size: 17

**Comment by chunfuwen** [comment]
@iccaszhulili 
@fangge1212 

Please take a look since previously both of them have some touch on this functionality.

**Comment by iccaszhulili** [comment]
@chunfuwen which kind of function will use the encrypt key?

**Comment by chunfuwen** [comment]
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.nbd.coldplug.enable_tls.private_key_encryption.disable_export.lifecycle_operate

**Comment by chunfuwen** [comment]
@iccaszhulili
tp-libvirt result uploaded

**Comment by fangge1212** [comment]
LGTM

**Review by iccaszhulili — APPROVED** [review]
LGTM

**Pull request merged**
