### PR TITLE
clean_partition: add clean partition command for Windows guest

### PR DESCRIPTION
**Pull request by ybduan**
ID: 1802011

Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by ybduan** [comment]
Please help review this PR, thanks! @XueqiangWei

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by: xuwei@redhat.com

**Comment by yanan-fu** [comment]
Ack

**Comment by ybduan** [comment]
Please help review this PR, thanks! @luckyh

**Comment by ybduan** [comment]
Will close this PR and move the configuration to specific case.

**Pull request closed without merging**
