### PR TITLE
Extend nbd utils to allow encrypted key

### PR DESCRIPTION
**Pull request by chunfuwen**
Somehow,clien key need to be encrypted,so add password and secret parameters to enable it

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
test result upload is in progress

**Comment by chunfuwen** [comment]
#2801 https://github.com/avocado-framework/avocado-vt/pull/2801

**Comment by chunfuwen** [comment]
[stdout] 
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.nbd.coldplug.enable_tls.private_key_encryption.disable_export.lifecycle_operate

**Review by dzhengfy — APPROVED** [review]
LGTM

**Comment by chunfuwen** [comment]
@lento-sun , please help take a look

**Review by lento-sun — APPROVED** [review]
LGTM

**Pull request merged**
