### PR TITLE
fix usb ehci bug on powerpc, and make the ohci as default controler

### PR DESCRIPTION
**Pull request by Zhengtong**
On ppc64&ppc64le platform , there is no uhci controller supported. instead of this , pci-ohci is supported. So add the pci-ohci controller to the script. 
Modified some cfg files to let it works better.

### CODE REVIEW

**Comment by Zhengtong** [comment]
ID: 1288377

**Comment by ldoktor** [comment]
Hello @Zhengtong, can I know something about the background of this patch? I really don't like it as it:

1. Moves the machine-specific handling from `machine.cfg` to `base.cfg`
2. It changes the usb type on one architecture. One should use config and not just say well we're on ppc, let's use `ohci` even when user asks for `ehci`. This way you'd execute 2 identical setups when running `ohci` and `ehci`.

**Comment by Zhengtong** [comment]
Hi, lodoktor.
For changes in shared/cfg/base.cfg.
The related configurations in machines.cfg which will overwrite base.cfg are deleted in this patch.

 
For changes in virttest/qemu_devices/qcontainer.py . 
Now, ich9-usb-ehci1 is still supported on ppc64&ppc64le qemu-kvm-rhev, So we should test the functions.  The methods of testing it is to add two sub-controllers(usb1.x) besides ich9-usb-ehci1 to make it compatible for usb1.0. on X86, it is ich9-usb-uhci. on PPC, it is pci-ohci, The behaviour just like complementation on ich9 chipset .  if not , the usb2.0 controller will not be attached with usb1.0 device. 

and for your last comment.
1. Now, In our daily tests with autotest, the order of cfg files included in tests-example.cfg is like this, base.cfg is the first, and  followed by subtests.cfg , machines.cfg is far behind that two. So the configuration in machines.cfg willl overwrite those in subtests.cfg.  but the configrations here are  global configurations for all tests for ppc64&ppc64le. It should not be added case by case. Strictly speaking. I think there should be a new configure for platform.cfg or others like this. but no this now , I think here should be the place.

2. I am not sure if I understand fully about this question. And what I want to add is that adding ohci is for testing ich9-usb-ehci1, see the explanation for changing qcontainer.py . not testing ohci. no problems  with testing ohci now.

**Comment by ldoktor** [comment]
@Zhengtong thank you, I understand the `ich9-usb-ehci1` part and it's in deed valid.

On the other hand I disagree with handling machine-specific types in `base.cfg`. The order is correct:

1. base.cfg - defaults (as simple as possible)
2. subtests.cfg - all tests with variants
3. machines.cfg - defines supported machines and overrides unsupported setting
4. ... (other HW and SW overrides)

If you need to reorder it, then send a PR with reasons to do it. But so far this worked well. One can always supply `--vt-extra-params` (or modify `tests-shared.cfg`) to enable setting not usually avaliable for certain platform.

I'm wondering where do you enable the `ich9-usb-ehci1`. Is it in subtests? Shouldn't you rather run the test loop with `ich9-usb-ehci1` set by `--vt-extra-params` (or custom cfg)?

**Comment by ldoktor** [comment]
Btw in `subtests.cfg` I only see `ich9-usb-ehci1` used in `io-github-autotest-qemu.systemtap_tracing.usb_d` test and `machines.cfg` would override the type of the first usb. But this can be easily fixed by using different name:

```
...
                    -@usb_d:
                        usb_devices = tablet1 hub
                        usbs = uhci1 ehci1
                        usb_type_uhci1 = ich9-usb-uhci1
                        usb_type_ehci1 = usb-ehci
...
```

wouldn't changes like this solve your issues? I really __REALY__ don't like polluting and actually separating the machine-specific options to `base.cfg`. Even reorder of the includes is IMO better (if supported by solid reasons and lots of testing). I don't see reason for splitting `machine` into `platform` and `machine` as I really don't see the point. Booth are `machine` so what would you like to put where? What are the purposes of each? Right now `machines.cfg` simply sets what's not supported by given machine. That's IMO pretty simple and understandable.

**Comment by ldoktor** [comment]
_PS: feel free to share the configs and examples of what do you want to achieve and what does not work using email, should that contain internal stuff..._

**Comment by Zhengtong** [comment]
@ldoktor , Thanks for the advise, but the ich9-usb-ehci1 I enabled for testing is in subtests.cfg:
io-github-autotest-qemu.usb: 
                    - ich9-ehci:
                        usb_type_usbtest = ich9-usb-ehci1
                        usb_controller = ehci
                        usb_max_port_usbtest = 6
                        drive_format_stg = "usb2"
 It is adopted from usb.cfg . 
I am thinking about how to modify the patch to comply with the rules. And any advices would be grateful.

**Comment by ldoktor** [comment]
Well the content of `machine.cfg` is:
```
    - @pseries:
        only ppc64, ppc64le
        machine_type = pseries
        # Currently only supports standard VGA
        vga = std
        # No support for USB-uhci
        usb_type = pci-ohci
        usb_type_usb1 = pci-ohci
        usb_controller_tablet1 = ohci
        del rtc_drift
```

Which means it does not overrides the `io-github-autotest-qemu.usb` test's setting. The tablet1 uses ohci (set in `machines.cfg`) and the test device `usbtest` uses `ich9-usb-ehci1` (set in `subtests.cfg`).

**Comment by Zhengtong** [comment]
But this will cause another problem. @ldoktor , For USB test io-github-autotest-qemu.usb,  we want the tablets's controller to be the controller tested(i.e. nec-usb-xhci ), not ohci. That is to say, there is not ohci controller on the target VM while we are testing nec-usb-xhci. So if we set usb_controller_tablet1 = ohci , there will be errors raised up.

**Comment by Zhengtong** [comment]
@ldoktor , I have reworked the patch with another method, In our testing , I put the machines.cfg just behind base.cfg , and changed related configuration in it to solve the issues, I have tried with the cases which may be caused  by the order switching, proving no conflict.

**Comment by ldoktor** [comment]
OK so there are actually 2 problems you're trying to solve:

1. the situation, where uhci is used on ppc64
2. the situation, where xhci is used on ppc64

ppc64 does not support uhci, therefor ohci is (nowadays) standard. On the other hand it also supports xhci and we do want to test it (as it's going to be the default soon). Hmm, I though about it deeply, because it's not an easy call. I don't want to digress from internal setup and moving `machines.cfg` is a big step. Your were right in the first place, putting it into base.cfg is probably right, because we deal with different defaults for different architectures.

I'm sorry for this huge slow down, but would you please put the `ppc64` default into the `base.cfg` with comment that saying something like `ppc64 does not support uhci, default bus is ohci.`

Then if we run the default on ppc64, we get ohci, with `--vt-extra params usb_type=nec-usb-xhci` we get xhci everywhere.

**Comment by Zhengtong** [comment]
Hi, @ldoktor ,I am trying to resolve is the problems here:
1. the situation, where ehci used on ppc64. Because ohci instead of uhci is supported on ppc64, we need add sub-controller for ehci with ohci. where this modification made  is in "qcontainer.py"
2. the previous "usb_controller" related params's place (in machines.cfg) is not suitable. "usb_controller_tablet1 = ohci" will overwrite the configuration set in subtests.cfg(for usb specific test part. not only for xhci.).

So, if you agree with the original patch. I will push the last one again.

**Comment by ldoktor** [comment]
Well I don't remember how the original version looked like, but I have nothing against the part where you set different default for usb_controller on ppc64 (please add there the explanation as well).

**Comment by ldoktor** [comment]
Thanks, @Zhengtong, I'm sorry it took so long.

**Pull request merged**
