### PR TITLE
guest-hw: Add suffix for rng param to avoid name conflict

### PR DESCRIPTION
**Pull request by vivianQizhu**
id: 1730607
Signed-off-by: Qianqian Zhu <qizhu@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@ybduan Please help test, thanks.

**Comment by ybduan** [comment]
(1/1) Host_RHEL.m7.u7.virtio_rng.rng_egd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.rng_bat: SKIP: Mandatory parameter 'chardev_backend' is missing. Check your cfg files for typos/mistakes

CMD:
python ConfigTest.py --testcase=rng_bat --platform=x86_64 --guestname=RHEL.7.7 --clone=no --rng_type=rng_egd

**Comment by vivianQizhu** [comment]
@ybduan Updated, please help test, thanks.

**Comment by yanan-fu** [comment]
@vivianQizhu  I remember we discussed this kind issue,  no need to use "$devicetype_chardev_backend", such as `serial_chardev_backend`, `network_chardev_backend`.
We use `chardev_backend_$devicename` at last.

So, in guest-hw, use `chardev_backend_rng0` is ok

**Comment by vivianQizhu** [comment]
@yanan-fu I had same thought with you, but it does not work well, since here: https://github.com/avocado-framework/avocado-vt/pull/2175/files#diff-87974b945618f3383424352c2c98c5cbR2162 it does not use `object_params()`, it requires a params exactly named `chardev_backend`. Bad design for rng params definition, but I don't want to reorganize it to follow our new rule, which requires rewrite whole rng part. Just rename it to `rng_chardev_backend` to avoid the name conflict.

**Comment by yanan-fu** [comment]
@vivianQizhu  oh, i see you first version now.  you are right `setup` did not use `object_params`.  If so, i am ok with it.

**Comment by ybduan** [comment]
(1/1) Host_RHEL.m7.u7.virtio_rng.rng_egd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.rng_bat: PASS (55.36 s)
 (1/1) Host_RHEL.m8.u1.virtio_rng.rng_egd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.rng_bat: PASS (115.94 s)

**Pull request merged**
