### PR TITLE
qemu_vm: Correct the cmdline of floppy devices for q35

### PR DESCRIPTION
**Pull request by luckyh**
q35 machine has the different cmdline for floppy devices, this patch
corrects the usage for it.

Signed-off-by: Xu Han <xuhan@redhat.com>

ID: 1613133

### CODE REVIEW

**Comment by luckyh** [comment]
@xiagao please help review it, thanks.

**Comment by peixiu** [comment]
Tested with this code:
 (1/2) Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.single_driver_install.with_netkvm.virtio_win_vfd_media.q35: PASS (183.14 s)
 (2/2) Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.single_driver_install.with_vioscsi.virtio_win_vfd_media.q35: PASS (177.58 s)

Acked-by: Peixiu phou@redhat.com

**Comment by xiagao** [comment]
'1-Host_RHEL.m7.u6.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.single_driver_install.with_viostor.virtio_win_vfd_media.q35' Finshed 2018-08-14 05:05:01 2018-08-14 05:07:31 PASS 149.498378
'1-Host_RHEL.m7.u6.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.single_driver_install.with_viostor.virtio_win_vfd_media' Finshed 2018-08-14 04:47:42 2018-08-14 04:50:32 PASS 170.255517

Ackeck by: Xiaoling Gao <xiagao@redhat.com>

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
