### PR TITLE
virttest.qemu_storage.QemuImg.resize: support luks

### PR DESCRIPTION
**Pull request by lolyu**
1. add image resize support for luks.
2. support preallocation mode in resize.

Signed-off-by: lolyu <lolyu@redhat.com>

### CODE REVIEW

**Comment by lolyu** [comment]
luks
```
 (1/2) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.resize_qemu_img.increase_size: PASS (9.57 s)
 (2/2) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.resize_qemu_img.shrink_size: PASS (9.35 s)
```
raw
```
 (1/2) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.resize_qemu_img.increase_size: PASS (2.16 s)
 (2/2) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.resize_qemu_img.shrink_size: PASS (2.11 s)
```
native qcow2
```
 (1/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.resize_qemu_img.increase_size: PASS (2.38 s)
 (2/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.resize_qemu_img.shrink_size: PASS (2.44 s)
```
luks inside qcow2
```
 (1/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.resize_qemu_img.increase_size: PASS (11.86 s)
 (2/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.resize_qemu_img.shrink_size: PASS (11.98 s)
```

**Comment by lolyu** [comment]
native qcow2
```
 (1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.qemu_img_convert.after_enlarge_snapshot: PASS (2.99 s)
```

**Comment by hellohellenmao** [comment]
Test result is pass, and the logs are good to me. 

'1-Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.resize_qemu_img.increase_size' Finshed 2019-09-19 02:24:43 2019-09-19 02:24:53 PASS 10.392037
'2-Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.resize_qemu_img.shrink_size' Finshed 2019-09-19 02:24:53 2019-09-19 02:25:04 PASS 10.300821

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
