### PR TITLE
Add preallocate context support to memory_backend_* object

### PR DESCRIPTION
**Pull request by zixi-chen**
ID: 2000

### CODE REVIEW

**Comment by zixi-chen** [comment]
(1/1) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.boot.q35: STARTED
 (1/1) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.boot.q35: PASS (61.71 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2024-02-29T01.16-641980f/results.html
JOB TIME   : 63.33 s
INFO | Avocado XML results file copied successfully.
# python3 ConfigTest.py --guestname=RHEL.9.4.0 --testcase=boot --clone=no --profile=Icelake_sgx

#cat Icelake_sgx
[before_subtest]
auto_cpu_model = "no"
cpu_model = "host"
use_mem = no
mem_devs = "epc0"
backend_mem_epc0 = "memory-backend-epc"
size_mem_epc0 = 2048M
prealloc_epc0 = on
vm_sgx_epc_devs = sgx0
vm_sgx_epc_memdev_sgx0 = epc0
vm_sgx_epc_node_sgx0 = 0
vm_thread_contexts = tc1
vm_thread_context_node-affinity = 0
prealloc-context_epc0 = thread_context-tc1

qemu-cmdline:
[stdlog]     -object '{"size": 2147483648, "prealloc": true, "prealloc-context": "thread_context-tc1", "id": "mem-epc0", "qom-type": "memory-backend-epc"}' \
[stdlog]     -object '{"size": 64424509440, "id": "mem-machine_mem", "qom-type": "memory-backend-ram"}' \
[stdlog]     -object thread-context,node-affinity=0,id=thread_context-tc1  \

**Comment by zixi-chen** [comment]
@zhencliu @YongxueHong @mcasquer Could you please help to review this patch?

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Review by zhencliu — APPROVED** [review]

**Review by mcasquer — APPROVED** [review]
LGTM

**Pull request merged**
