### PR TITLE
Job Lock: ignore lock files if the corresponding process is not alive

### PR DESCRIPTION
**Pull request by clebergnu**
If the process whose ID is referred to by the lock file is not alive,
we're probably talking about a stale lock file.  Let's just warn about
it and proceed with the job, and ignore the lock.

Signed-off-by: Cleber Rosa <crosa@redhat.com>

### CODE REVIEW

**Comment by ldoktor** [comment]
Don't forget to copy @svirt, who was interested in this fix...

**Comment by adereis** [comment]
I'm not familiar with the full lock implementation, so can you please explain why deleting the lock is not a good idea? I think someone mentioned a race as the reason.

```
Process is created (PID)
  Lock is checked/created
     Shared-resource is used
  Lock is removed
Process dies (PID is gone)
```

If the above is correct, then as long as we check the lock first and the PID second, I don't see a race in removing the lock file if the PID doesn't exist.

BTW, a race where the PID namespace is fully exhausted in a short period of time is not considered a security issue (and it would imply a DoS at most). The PID issue can also be mitigated by matching the process name, time, etc (info that could be added as contents of the lock file).

**Comment by adereis** [comment]
Notice we're using a shared tmp dir by default, which means unpriviledged users can't remove lock files created by others and that any user could create a malicious locking file, thus causing a DoS for the resource being shared.

But we discussed that as a problem for the sysadmin to handle (avocado can be configured to use a private directory). The documentation should be more explicit about that. Right now all it says is:

```
$ cat etc/avocado/conf.d/vt_joblock.conf 
[plugins.vtjoblock]
# Directory where the lock file will be located. Avocado should have permission
# to write to this directory.
dir=/tmp
```

(maybe it should say "the **user** running avocado should have permission to write to this directory" and mention the possibility of a DoS if any unpriviledge user can create files there as well, probably recommending a change if that's possible).

**Comment by ldoktor** [comment]
Well this implementation is quite simple and does not cover multiple existing lock files, which should be IMO covered.

Anyway regarding deleting the files... It's not that simple as one could think it is. Actually even now it's possible to obtain several locks without notice, because:

1. We query for the lockfiles
2. If not found we create the lock

Where the 1+2 is not atomic, so when two processes finish (1) at the same time, they both proceed. To test it you can use:

```diff
diff --git a/avocado_vt/plugins/vt_joblock.py b/avocado_vt/plugins/vt_joblock.py
index 2a224b0..705ad49 100644
--- a/avocado_vt/plugins/vt_joblock.py
+++ b/avocado_vt/plugins/vt_joblock.py
@@ -88,6 +88,8 @@ class VTJobLock(JobPre, JobPost):
 
     def _lock(self, job):
         filename, lock_pid = self._get_lock_file_pid()
+        import time
+        time.sleep(1)
         if lock_pid > 0:
             msg = ('Avocado-VT job lock file "%s" acquired by PID %u. '
                    'Aborting...' % (filename, lock_pid))
```

If you spawn 2 processes in the 1s, they both proceed.

**Comment by ldoktor** [comment]
It'd all be easier if we move to the idea of using `self.datadir`. It's `rw` for everybody, it's not shared with other users, therefor users with different datadir could run in parallel and we'd only have to create as imple `avocado-vt.lock` file. Any failure means we failed to obtain the lock. One way to solve this could be (but it could make all processes trying to obtain the lock fail):

1. create `lockfile + .pid` file
2. check if `lockfile` points to existing pid. If so, GOTO ERROR
3. check all `lockfile.*` files present in `datadir` (avocado-vt datadir), if any process is alive, GOTO ERROR
4. unlink `lockfile`
5. symlink `lockfile + .pid` to `lockfile`

This way when multiple processes reach 1, only single or no process obtains the lock.

**Comment by adereis** [comment]
> We query for the lockfiles
> If not found we create the lock

This is where the race is. We can't do it this way. The check and creation of the locking file has to be an atomic operation. That's why I listed them as one action in my example:

```
Process is created (PID)
  Lock is checked/created
     Shared-resource is used
  Lock is removed
Process dies (PID is gone)
```

Given the name includes a random string (because we're using a shared, unsafe directory), then we have to do it this way:

1. Create a lock file
2. Check the existence of any other (valid) lock files

If (2) is true, the lock was **not** acquired (and the file created in 1 should be removed). The only race in this case is that it might be possible that multiple avocado-vt runs try to acquire the locking and all of them fail (a temporary deadlock). But that's safe, because it's temporary.

Regarding the idea of locking the datadir, we've discussed it before and concluded there's no guarantee that tests in avocado-vt are not using other global resources. The avocado-vt lock is not a lock on the datadir. It's a lock on avocado-vt itself.

**Comment by ldoktor** [comment]
Yep, if we want to keep multiple files, then the opposite logic (create lock and then check if it's the only one) suffice.

Regarding the datadir, yes, some tests might not behave correctly when running concurrently, but wast majority was already replaced with tmpfiles inside workdir, so the only shared resource should be the datadir. Anyway I don't share my machine, so I don't have a strong opinion about datadir vs. global-lock.

**Comment by clebergnu** [comment]
The big issue here is that the lock check/creation is *not* atomic.  In theory two processes can check for lock files at the same time, and, finding nothing, both can create them. The current lock implementation has passed the quality criteria of "having a computer trying to create two VT jobs simulteanously", but it is not, in pratice, 100% safe.

The main issue is that we're favoring an approach of using a lock file pattern, which can not be guaranteed to be unique, say by the filesystem.  If we had a single lockfile path, which would then be vulnerable to security issues, the filesystem could guarantee the atomicity.

But then, the approach suggested by @adereis, reversing creation and check, makes thing safe.  The small cost of possible mutual exclusion seem small, so I'll try that out.

**Pull request closed without merging**
