### PR TITLE
Fix the issue that can not get event

### PR DESCRIPTION
**Pull request by yalzhang**
Fix the issue that it can not get detach event.

Signed-off-by: Yalan Zhang <yalzhang@redhat.com>

### CODE REVIEW

**Comment by yalzhang** [comment]
before the change, always got error like:
CmdError: Command '/bin/virsh event  --domain avocado-vt-vm1 --event device-removed --timeout 7' failed.stdout: b'event loop timed out\nevents received: 0\n\n'stderr: b''additional_info: None&#10;
after the change the test can pass with or without split daemon:
JOB ID     : feb1b5d5d1d544856ad3d31906f774b5b4c2317a
JOB LOG    : /root/avocado/job-results/job-2021-09-16T03.24-feb1b5d/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_target.flush_after_detach.flush_with_occupation.default: PASS (62.63 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 63.21 s

**Comment by yalzhang** [comment]
as  wait_remove_event  -> wait_for_event, I will check detach_device() use cases, and update this parameters if needed.

**Comment by chunfuwen** [comment]
@yalzhang 
Since this change will impact all cases which use detach_device.
You are highly encouraged to validate some of cases from below(frequently use detach-device) to  do more pre-checking
virsh.change_media 
virsh.change_media_matrix
virsh.update_device 
virsh.update_device_matrix

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by liuyd96** [comment]
It works for me. Thanks.
Before
```
avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio  virtual_network..flush_with_occupation                                                 
JOB ID     : b14c6e93d009d1379064c4b9e7de91099e01119a
JOB LOG    : /root/avocado/job-results/job-2021-09-27T01.56-b14c6e9/job.log
 (1/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_target.flush_after_detach.flush_with_occupation.default: ERROR: Command '/usr/bin/virsh event  --domain avocado-vt-vm1 --event device-removed --timeout 7' failed.\nstdout: b'event loop timed out\nevents received: 0\n\n'\nstderr: b''\nadditional_info: None (66.27 s)                                            
 (2/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_target.flush_after_detach.flush_with_occupation.macvtap: ERROR: Command '/usr/bin/virsh event  --domain avocado-vt-vm1 --event device-removed --timeout 7' failed.\nstdout: b'event loop timed out\nevents received: 0\n\n'\nstderr: b''\nadditional_info: None (70.01 s)                                            
 (3/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_target.no_flush_after_detach.flush_with_occupation.default: ERROR: Command '/usr/bin/virsh event  --domain avocado-vt-vm1 --event device-removed --timeout 7' failed.\nstdout: b'event loop timed out\nevents received: 0\n\n'\nstderr: b''\nadditional_info: None (66.42 s)
 (4/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_target.no_flush_after_detach.flush_with_occupation.macvtap: ERROR: Command '/usr/bin/virsh event  --domain avocado-vt-vm1 --event device-removed --timeout 7' failed.\nstdout: b'event loop timed out\nevents received: 0\n\n'\nstderr: b''\nadditional_info: None (69.55 s)
RESULTS    : PASS 0 | ERROR 4 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 273.11 s
```
After
```
# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio virtual_network..flush_with_occupation                                           
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.       
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.                          
JOB ID     : e9400cc760e34e3d1469f4c6de451a04745002c6
JOB LOG    : /root/avocado/job-results/job-2021-09-27T04.29-e9400cc/job.log
 (1/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_target.flush_after_detach.flush_with_occupation.default: PASS (62.04 s)                                                
 (2/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_target.flush_after_detach.flush_with_occupation.macvtap: ERROR: Command '/usr/bin/virsh attach-device avocado-vt-vm1 /tmp/xml_utils_temp_sfhoar7y.xml' failed.\nstdout: b'\n'\nstderr: b"error: Failed to attach device from /tmp/xml_utils_temp_sfhoar7y.xml\nerror: Cannot set interface flags on 'macvtap2': Address already i... (65.26 s)
 (3/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_target.no_flush_after_detach.flush_with_occupation.default: PASS (61.05 s)                                             
 (4/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_target.no_flush_after_detach.flush_with_occupation.macvtap: ERROR: Command '/usr/bin/virsh attach-device avocado-vt-vm1 /tmp/xml_utils_temp_0jdcv74t.xml' failed.\nstdout: b'\n'\nstderr: b"error: Failed to attach device from /tmp/xml_utils_temp_0jdcv74t.xml\nerror: Cannot set interface flags on 'macvtap2': Address already i... (63.40 s)
RESULTS    : PASS 2 | ERROR 2 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 252.63 s
```

**Comment by kylazhang** [comment]
@yalzhang according to pr in tp-libvirt with yingshun's comments, you may also need to update detach_interface

**Comment by yalzhang** [comment]
> @yalzhang
> Since this change will impact all cases which use detach_device.
> You are highly encouraged to validate some of cases from below(frequently use detach-device) to do more pre-checking
> virsh.change_media 
> virsh.change_media_matrix
> virsh.update_device
> virsh.update_device_matrix
change_media and update_device do not call detach_device(). So there is no impact.

**Review by kylazhang — APPROVED** [review]

**Pull request merged**
