### PR TITLE
utils_net: Update mac address with correct format

### PR DESCRIPTION
**Pull request by pingl2016**
Update mac address, using ":" as the separator instead of ".".

Signed-off-by: Ping Li <pingl@redhat.com>

### CODE REVIEW

**Comment by pingl2016** [comment]
ID: 1322493

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by spcui** [comment]
Acked-by: scui@redhat.com

**Comment by xutian** [comment]
Original code works for a long time, so I think this only happen in some guest. please test with more guest to ensure this change do not impact test on other guest.

Thanks,
Xu

**Comment by xutian** [comment]
delay to merge it,  this fix need more testing.

Thanks,
Xu

**Comment by pingl2016** [comment]
@xutian It is ok for test the patch with Win2008, Win7, Win8, Win10 and Win2012 guest.

**Comment by maxujun** [comment]
Acked-by: xuma@redhat.com

**Pull request merged**
