### PR TITLE
virsh: Fix can't get event info in some env

### PR DESCRIPTION
**Pull request by liuyd96**
Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>

### CODE REVIEW

**Comment by liuyd96** [comment]
Before
```

```

After
```
https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Results%20Dashboard/view/RHEL-8.6-aarch64-Report/job/libvirt-RHEL-8.6-runtest-aarch64-function-attach_detach_media/lastCompletedBuild/testReport/rhel.virsh/change_media_matrix/
```

**Comment by chunfuwen** [comment]
check with submitter offline, the PR was already run against event jobs ,and previous existed event not logs issue disappear.
Since it failed many events cases, let's merge it

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by chunfuwen** [comment]
locally test changes, didn't find any regression:
Command 'virsh list' finished with 0 after 0.031239032745361328s
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virsh.change_media_matrix.pre_vm_state_paused.cdrom_test.live_config.action_twice.live_config.eject_insert

**Pull request merged**
