### PR TITLE
virttest: add Q35 machine type with bridge devices support

### PR DESCRIPTION
**Pull request by xutian**
This is a new version of #657, original #657 can be reopen now because my mistake. sorry for inconvenient.

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1339038

**Comment by xutian** [comment]
@ldoktor  would you like to help review this PR when free. thanks.

**Comment by xutian** [comment]
@ngu-niny  can you retest with latest code. thanks.

**Comment by xutian** [comment]
@ldoktor  do you have any comments for this update?

**Comment by ngu-niny** [comment]
After retest, the patch works well:    

    -device xio3130-downstream,bus=pcie_switch,id=pcie_switch.0,addr=00,chassis=1 \
    -device virtio-serial-pci,id=virtio_serial_pci0,bus=pcie_switch.0,addr=00 \
   
    -object rng-egd,id=chardev-GthvOzOD,chardev=tcp-jbq9maAj \
    -device xio3130-downstream,bus=pcie_switch,id=pcie_switch.1,addr=01,chassis=2 \
    -device virtio-rng-pci,id=virtio-rng-pci-MSPrVdXQ,rng=chardev-GthvOzOD,bus=pcie_switch.1,addr=00  \

    -device xio3130-downstream,bus=pcie_switch,id=pcie_switch.2,addr=02,chassis=3 \
    -device virtio-blk-pci,id=image1,drive=drive_image1,bootindex=0,bus=pcie_switch.2,addr=00 \

    -device xio3130-downstream,bus=pcie_switch,id=pcie_switch.3,addr=03,chassis=4 \
    -device virtio-net-pci,mac=9a:88:89:8a:8b:8c,id=idYo7oDt,vectors=4,netdev=idY50qU4,bus=pcie_switch.3,addr=00  \

    -device xio3130-downstream,bus=pcie_switch,id=pcie_switch.3,addr=03,chassis=4 \
    -device virtio-balloon-pci,id=balloon0,bus=pcie_switch.3,addr=00

    -device xio3130-downstream,bus=pcie_switch,id=pcie_switch.0,addr=00,chassis=1 \
    -device virtio-scsi-pci,id=virtio_scsi_pci0,bus=pcie_switch.0,addr=00 \

**Comment by suqinhuang** [comment]
tested balloon, rng, blk, nic, it works well.

**Comment by xutian** [comment]
So long no any opposed comments and base on @ngu-niny  and @suqinhuang  test results, this PR works, so merged it.

Thanks @ngu-niny  and @suqinhuang test results.

Thanks,
Xu

**Pull request merged**
