### PR TITLE
Allow custom paths for postprocessed images

### PR DESCRIPTION
**Pull request by pevogam**
This is on par with the image preprocessing which already does it.

### CODE REVIEW

**Comment by pevogam** [comment]
@luckyh I hope this is fast to review. The deployment checks should work out if this gets rebased on version post-82.0 but 82.0 is the version we use at the moment and the one we can test more easily.

**Comment by luckyh** [comment]
@pevogam LGTM, just missing the signed-off signature.

**Comment by pevogam** [comment]
> @pevogam LGTM, just missing the signed-off signature.

I always forget that, thanks for reminding me. Pushed now.

**Comment by pevogam** [comment]
@sathnaga Is the improvement of this PR useful to you too enough to review?

**Review by sathnaga — APPROVED** [review]
LGTM

**Pull request merged**
