### PR TITLE
add support for snapshot disk source

### PR DESCRIPTION
**Pull request by nanli1**
Need disk source in snapshot xml
Signed-off-by: nanli <nanli@redhat.com>
For https://github.com/autotest/tp-libvirt/pull/5584

### CODE REVIEW

**Review by cliping — APPROVED** [review]
LGTM

**Review by chloerh — COMMENTED** [review]
Seems Disk class already has 'source', is it possible that we don't need to add it again?

**Comment by nanli1** [comment]
> Seems Disk class already has 'source', is it possible that we don't need to add it again?

hi haijiao ,Thanks your comment .This is disk > source tag is in snapshot xml instead of disk xml ,Did I get your point
```
# cat s1.xml
<domainsnapshot>
<description>Snapshot test</description>
<name>s1</name>
<memory snapshot='no'/>
<disks>
<disk name='vda' snapshot='no'/>
<disk name='vdb' snapshot='external'>
<source file="/var/lib/libvirt/images/vdb.s1"/>
</disk>
</disks>
</domainsnapshot>
```

**Comment by nanli1** [comment]
Haijiao has helped to check that we have inherit disk class , no need to give this support

**Pull request closed without merging**
