### PR TITLE
Rename plugins

### PR DESCRIPTION
**Pull request by lmr**
Implements

https://trello.com/c/AADo7pfQ/490-virt-test-vs-vt-test-confusion-in-the-plugin-names

I went a little further here to try to avoid any confusion across the board, going as far as renaming the actual plugin file names, the config file name and the config section names. If you guys think that this is going too far, I completely understand.

By the way, the output of the `avocado plugins` command should be:

    Plugins enabled:
        config          Implements the avocado 'config' subcommand
        distro          Implements the avocado 'distro' subcommand
        exec_path       Implements the avocado 'exec-path' subcommand
        gdb             Run tests with GDB goodies enabled
        htmlresult      HTML job report
        json            JSON output
        journal         Test journal
        multiplexer     Implements the avocado 'multiplex' subcommand
        plugins_list    Implements the avocado 'plugins' subcommand
        run_remote      Run tests on a remote machine
        run_vm          Run tests on a Virtual Machine
        sysinfo         Collect system information
        test_lister     Implements the avocado 'list' subcommand
        test_runner     Implements the avocado 'run' subcommand
        virt_bootstrap  Implements the avocado 'virt-bootstrap' subcommand
        vt_bootstrap    Avocado VT - implements the 'vt-bootstrap' subcommand
        virt            Add virtualization testing related options.
        vt              Avocado VT - legacy virt-test support
        vt_lister       Avocado VT - implements legacy virt-test listing
        wrapper         Implements the '--wrapper' flag for the 'run' subcommand
        xunit           xUnit output

### CODE REVIEW

**Comment by lmr** [comment]
If this is ever accepted, https://github.com/avocado-framework/avocado/pull/759 should be applied in sequence.

**Comment by lmr** [comment]
Just to mention, if we are only caring about `avocado plugins` output, we can do the same with less hassle, only changing the `name` attributes and the docstring classes and we'd get the exact same result.

**Comment by ldoktor** [comment]
Hmm, it seems to work fine. I'll do another couple of tests but I think it will be accepted :smile:

**Comment by ldoktor** [comment]
OK, let's :pray:

**Comment by lmr** [comment]
@ldoktor LOL

**Pull request merged**
