### PR TITLE
qemu_vm: avoid adding -mem-path option when numa node is defined

### PR DESCRIPTION
**Pull request by huangyum**
Signed-off-by: Yumei Huang <yuhuang@redhat.com>
ID: 2022232

### CODE REVIEW

**Comment by huangyum** [comment]
@xiagao @zhenyzha Would you pls help review, thanks.

**Comment by xiagao** [comment]
Results looks good to me with the following cfg.  
 setup_hugepages = yes
    pre_command_noncritical = yes
    pre_command = 'sync && echo 3 > /proc/sys/vm/drop_caches && echo 1 > /proc/sys/vm/compact_memory'
    vm_mem_share = yes
    backend_mem = memory-backend-file
    mem-path = /mnt/kvm_hugepage
    mem_devs = "mem0"
    guest_numa_nodes = "node0"
    numa_memdev_node0 = mem-mem0
    use_mem_mem0 = no
    share_mem = yes
    size_mem0 = ${mem}M


qemu-cmd line
03:41:52 DEBUG| [stderr]     -m 11264 \

03:41:52 DEBUG| [stderr]     -object memory-backend-file,size=11264M,mem-path=/mnt/kvm_hugepage,share=yes,id=mem-mem0  \

03:41:52 DEBUG| [stderr]     -smp 12,maxcpus=12,cores=6,threads=1,dies=1,sockets=2  \

03:41:52 DEBUG| [stderr]     -numa node,memdev=mem-mem0  \

**Comment by zhenyzha** [comment]
```
 (1/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_hugepage.with_numa.basic_test.with_cache.auto.arm64-pci: PASS (202.91 s)
 (2/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_hugepage.with_numa.basic_test.with_cache.always.arm64-pci: PASS (176.17 s)
 (3/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_hugepage.with_numa.basic_test.with_cache.none.arm64-pci: PASS (195.50 s)

```

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Comment by huangyum** [comment]
@YongxueHong Would you pls help review, thanks.

**Comment by YongxueHong** [comment]
LGTM.

**Comment by YongxueHong** [comment]
Hi, @yanan-fu 
Can you help to review, thanks.

**Comment by yanan-fu** [comment]
LGTM

**Review by yanan-fu — APPROVED** [review]
Acked-by: Yanan Fu <yfu@redhat.com>

**Pull request merged**
