### PR TITLE
Throw an error if SR-IOV VF device creation on host fails

### PR DESCRIPTION
**Pull request by bssrikanth**
This patch addresses below two current issues
   1. If SR-IOV VF device creation fails on the KVM host
    due to some reason, then current code not throwing any error
    messages to users.
    2. Return value from sr_iov_setup function is not considered
    to validate if SR-IOV VF creation on host succeeded or not.

### CODE REVIEW

**Comment by bssrikanth** [comment]
Version 1 of this PR [#609] was already reviewed and ack by @sathnaga and @CongLi . Due to some issues while squashing multiple commits to single commit I had to close that PR.

Please merge this PR.

**Comment by bssrikanth** [comment]
The build error is more of build environment issue I think..

**Comment by bssrikanth** [comment]
@ldoktor ^^^ travis ci error seems to be not related to my commit.

**Comment by bssrikanth** [comment]
@CongLi , @sathnaga this PR is as same as PR #609 which was ack'ed by you both. Can we have this merged? many thanks in advance.

**Comment by bssrikanth** [comment]
Any other things todo here? please let me know

**Comment by PandaWei** [comment]
@CongLi , @sathnaga @xutian 
We block this one for a long time.
I"m OK for this PR.
If you have no objection, I'll merge this one

**Comment by will-Do** [comment]
LGTM, let's merge this patch

**Pull request merged**
