### PR TITLE
virttest.bootstrap: Add "diff" to list of required programs

### PR DESCRIPTION
**Pull request by ldoktor**
We use "diff" to visualize differences between config files.

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>

### CODE REVIEW

**Comment by ldoktor** [comment]
@clebergnu are you the one with access to the `centos_8_1` container? Could you please add the `diff` command there so the CI passes? It is required and vt-bootstrap is failing without it (in case the files already exists).

**Comment by clebergnu** [comment]
Sure, I'll handle that in the morning.

**Comment by ldoktor** [comment]
No changes, just rebasing to re-trigger the CI.

**Comment by YongxueHong** [comment]
Hi @ldoktor 

For the existing `basic_program_requirements = ['xz', 'tcpdump', 'nc', 'ip', 'arping']`, I guess there are some test scenarios need them, for you wanna add `diff`, Could you explain which kind of test scenario might use it?
Thanks.

**Comment by ldoktor** [comment]
> Hi @ldoktor
> 
> For the existing `basic_program_requirements = ['xz', 'tcpdump', 'nc', 'ip', 'arping']`, I guess there are some test scenarios need them, for you wanna add `diff`, Could you explain which kind of test scenario might use it?
> Thanks.

In case the vt configuration already existed (eg. running the vt-bootstrap second time) the `diff` is used to compare the content of the existing cfg and the old ones. Running without diff makes "avocado vt-bootstrap" to crash.

**Comment by YongxueHong** [comment]
> > Hi @ldoktor
> > For the existing `basic_program_requirements = ['xz', 'tcpdump', 'nc', 'ip', 'arping']`, I guess there are some test scenarios need them, for you wanna add `diff`, Could you explain which kind of test scenario might use it?
> > Thanks.
> 
> In case the vt configuration already existed (eg. running the vt-bootstrap second time) the `diff` is used to compare the content of the existing cfg and the old ones. Running without diff makes "avocado vt-bootstrap" to crash.

Thanks for your explanation.

Test without this patch and remove diff package in advance: 
(workspace) [root@hp-dl388g8-16 avocado]#  avocado vt-bootstrap --vt-type qemu --yes-to-all --vt-update-providers --vt-skip-verify-download-assets
```

Running bootstrap for qemu

1 - Checking the mandatory programs and headers
...

2 - Checking the recommended programs
...

3 - Updating test providers repo configuration from local copy
...
4 - Updating the test providers from remote repos
...

5 - Verifying directories
...

6 - Syncing backend dirs /home/yhong/for-bug-1771912/kar/workspace/avocado-vt/backends -> /home/yhong/for-bug-1771912/kar/workspace/var/lib/avocado/data/avocado-vt/backends
Copying downloadable assets file definitions from /home/yhong/for-bug-1771912/kar/workspace/avocado-vt/shared/downloads into /home/yhong/for-bug-1771912/kar/workspace/var/lib/avocado/data/avocado-vt/downloads
Avocado crashed unexpectedly: [Errno 2] No such file or directory: 'diff' (diff -Naur /home/yhong/for-bug-1771912/kar/workspace/var/lib/avocado/data/avocado-vt/downloads/centos66-32.ini /home/yhong/for-bug-1771912/kar/workspace/avocado-vt/shared/downloads/centos66-32.ini): 'diff'
You can find details in /home/yhong/for-bug-1771912/kar/workspace/var/lib/avocado/data/crashes/avocado-traceback-2020-07-09_05:09:44-ox17plie.log

```

Test with this patch:
(workspace) [root@hp-dl388g8-16 avocado]#  avocado vt-bootstrap --vt-type qemu --yes-to-all --vt-update-providers --vt-skip-verify-download-assets
```
Running bootstrap for qemu

1 - Checking the mandatory programs and headers
/usr/bin/xz OK
/sbin/tcpdump OK
/usr/bin/nc OK
/sbin/ip OK
/sbin/arping OK
Required command diff is missing. You must install it
/usr/bin/gcc OK
/usr/include/python3.6m/Python.h OK
/usr/include/asm/socket.h OK
/usr/include/asm/types.h OK
/usr/include/asm/unistd.h OK
Missing (cmds/includes): diff
Install the missing programs and/or headers and re-run boostrap
```

LGTM.

**Comment by ldoktor** [comment]
@clebergnu would you please add the diff to the centos image so this can be merged?

**Review by sathnaga — APPROVED** [review]

**Comment by clebergnu** [comment]
> @clebergnu would you please add the diff to the centos image so this can be merged?

The image has been rebuilt (id 736bc2efb65e).  Also please review #2770 to make sure the image state is recorded in the repo.

**Comment by clebergnu** [comment]
I'm closing/reopening this to re-trigger CI.

**Comment by clebergnu** [comment]
@ldoktor it looks like it'll need a rebase for CI to pass.

**Comment by ldoktor** [comment]
Thank you, @clebergnu, the CI issue is resolved, I see 2 acks so merging.

**Pull request merged**
