### PR TITLE
shared.cfg.machines: Add pci-based arm64 machine [v2]

### PR DESCRIPTION
**Pull request by ldoktor**
Hello guys,

this PR is trying to cleanup the way other architectures are handled in order to be able to run various machine types on different host machines.

Additionally it adds `arm64-pci` machine type which is arm constructed using PCI devices (the old one is renamed to arm64-mmio). I tested it for a while, the only problem I'm having is that when the machine is installed as `arm64-pci` and then ran as `arm64-mmio` (and vice-verse), network won't start. I'll investigate this on Thursday, for now please have a look at the implementation and let me know if you see something obviously wrong.

v0: https://github.com/avocado-framework/avocado-vt/pull/187
v1: https://github.com/avocado-framework/avocado-vt/pull/205

Changes:

    v1: "--vt-additional-params" renamed to "--vt-extra-params"
    v2: Added missing variable when logging missing AAVMF file
    v2: Fixed commit message typo

### CODE REVIEW

**Comment by ldoktor** [comment]
@clebergnu there are not many people interested in arm, would you please review this one?

**Comment by ldoktor** [comment]
@clebergnu would you please look at this? It kind-of blocks my CI...

**Comment by lmr** [comment]
@ldoktor Other than checking for the presence of that `.fd` file, the support looks good. I'll merge this so it doesn't block your CI, and then you can send a patch addressing my command.

**Comment by ldoktor** [comment]
thanks

**Pull request merged**
