### PR TITLE
virttest/cpu.py: Extract variants cpu_types and cpu_types_re

### PR DESCRIPTION
**Pull request by vivianQizhu**
For global usage in some cpu test cases

id: 1856240
Signed-off-by: Qianqian Zhu <qizhu@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@nanliu-r @huangyum Please help review, thanks.

**Comment by huangyum** [comment]
Code looks good to me. Would you please provide test results?

**Comment by vivianQizhu** [comment]
Thanks @huangyum 
 (1/1) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.cpu_info_check: PASS (28.38 s)
>>> from virttest import cpu
>>> cpu.get_host_cpu_models()
['Skylake-Client', 'Skylake-Client-noTSX-IBRS', 'Broadwell', 'Broadwell-noTSX', 'Haswell', 'Haswell-noTSX', 'IvyBridge', 'SandyBridge', 'Westmere', 'Nehalem', 'Penryn', 'Conroe']

**Comment by nanliu-r** [comment]
Ack.

**Comment by vivianQizhu** [comment]
Thanks @huangyum @nanliu-r

**Pull request merged**
