### PR TITLE
virttest.utils_misc.py: typo fix of module name.

### PR DESCRIPTION
**Pull request by CongLi**
Signed-off-by: Cong Li <coli@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
id please.

**Comment by CongLi** [comment]
id: 1338614

**Comment by xutian** [comment]
looks good to me.

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by xutian** [comment]
merged, thanks @CongLi and @suqinhuang

**Pull request merged**
