### PR TITLE
Add missing package to setup.py

### PR DESCRIPTION
**Pull request by luckyh**
Commit b16ed10 introduced the package `virttest.utils_windows` but
forgot to add it to `setup.py`. Make this patch to fix the issue.

Signed-off-by: Xu Han <xuhan@redhat.com>

### CODE REVIEW

**Comment by hereischen** [comment]
@yanan-fu @peixiu This may related to the issue we discuessed last week.
Please have a look.

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by yanan-fu** [comment]
Acked-by: Yanan Fu <yfu@redhat.com>

**Comment by clebergnu** [comment]
@luckyh @hereischen there's nothing wrong with this change, but I'd suggest we consider the approach we've been successfully using in Avocado, and which avoids this kind of manual mistake. See  #1628.

**Comment by luckyh** [comment]
Oops, just made a misoperation, let me revert it.

**Pull request merged**
