### PR TITLE
Add log-level and remove enable_debug_mode param

### PR DESCRIPTION
**Pull request by qcheng-redhat**
Add log-level and remove enable_debug_mode parameter for virtiofsd 

ID: 2796

### CODE REVIEW

**Comment by qcheng-redhat** [comment]
@hellohellenmao Please help review this patch.

**Review by hellohellenmao — APPROVED** [review]

**Comment by qcheng-redhat** [comment]
Hello @luckyh @YongxueHong, please help review this patch. Thanks!

**Review by luckyh — APPROVED** [review]
LGTM

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
