### PR TITLE
Update include order of cfg files

### PR DESCRIPTION
**Pull request by suqinhuang**
put subtests.cfg to the end

Signed-off-by: Suqin Huang <shuang@redhat.com>

id: 1405894

### CODE REVIEW

**Comment by xutian** [comment]
better to move guest-hw.cfg before guest-os.cfg.  as you know some defeat for hw maybe fixed (sometime is a workaround) in guest-os.cfg.

**Comment by xutian** [comment]
My suggest sequence are
```
base.cfg
guest-hw.cfg
machine.cfg
guest-os.cfg
...
sub-tests.cfg 
```

**Comment by suqinhuang** [comment]
@ldoktor what's your opinion

**Comment by suqinhuang** [comment]
@luckyh @CongLi welcome for discussion

**Comment by ldoktor** [comment]
Hello guys, I don't really run any big test sets, so I'm flexible. I don't like many changes, but if the patch is reviewable (I mean it's not humongous) and the variants are simplified, I'm fine with both. Every solution will have some drawback, so if you have time to experiment and you find a nicer solution, than I'm fine (as far as the result is the same).

**Pull request closed without merging**
