### PR TITLE
Changed "mkdir" to "makedirs"

### PR DESCRIPTION
**Pull request by yanglei-rh**
Signed-off-by: Lei Yang <leiyang@redhat.com>

ID:2052787

### CODE REVIEW

**Comment by yanglei-rh** [comment]
Hello @PaulYuuu Could you please help me review it? Thanks in advance.

**Comment by yanglei-rh** [comment]
Hi @PaulYuuu Do I need to add test result for this patch? However, it should be noted that the test case involved fails the test result due to another problem.

**Comment by PaulYuuu** [comment]
> Hi @PaulYuuu Do I need to add test result for this patch? However, it should be noted that the test case involved fails the test result due to another problem.

@yanglei-rh, I don't have permission to merge patches in VT, so you need to invite other maintainers to review, thanks.

**Comment by yanglei-rh** [comment]
Hello @luckyh Could you please help me review it? Thanks in advance.

**Pull request merged**
