### PR TITLE
utils_disk: Fix regexp for getting first nvme disk

### PR DESCRIPTION
**Pull request by hs0210**
The current regexp can not used for getting nvme disk, so update the regexp.

### CODE REVIEW

**Review by chunfuwen — APPROVED** [review]
lgtm

**Comment by chunfuwen** [comment]
please upload test result as well

**Comment by hs0210** [comment]
Before:
```
ERROR| ERROR 1-type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_running.hot.blkiotune.weight.positive -> CmdError: Command 'cat /sys/block//queue/scheduler' failed.
stdout: b''
stderr: b'cat: /sys/block//queue/scheduler: No such file or directory\n'
additional_info: None
```
After:
```
INFO | PASS 1-type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_running.hot.blkiotune.weight.positive
```

Also checked entire guest_resource_control.control_cgroup test cases on a machine with only nvme disk, all passed with this patch and https://github.com/autotest/tp-libvirt/pull/5045
```
# /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type arm64-mmio guest_resource_control.control_cgroup --vt-connect-uri qemu:///system                                                                                                                     
JOB ID     : 828f544192733510e3f6c9f90d65ae1512a94854
JOB LOG    : /var/lib/avocado/job-results/job-2023-07-21T01.39-828f544/job.log
 (001/184) type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_running.hot.blkiotune.weight.positive: PASS (5.41 s)
 (002/184) type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_running.hot.blkiotune.weight.negative.value_over_limit: PASS (5.70 s)
 (003/184) type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_running.hot.blkiotune.weight.negative.value_negative: PASS (5.69 s)
 (004/184) type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_running.hot.blkiotune.weight.negative.value_not_int: PASS (5.48 s)
 (005/184) type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_running.hot.blkiotune.weight.negative.value_not_number: PASS (5.53 s)
 (006/184) type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_running.hot.blkiotune.device_weight.positive: PASS (5.55 s)
 (007/184) type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_running.hot.blkiotune.device_weight.negative.value_not_number: PASS (5.56 s)
......
 (179/184) type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_shutdown.config.schedinfo.global_quota.negative.value_not_number: PASS (4.54 s)                                                                                                                                                 
 (180/184) type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_shutdown.config.schedinfo.iothread_period.positive: PASS (25.22 s)
 (181/184) type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_shutdown.config.schedinfo.iothread_period.negative.value_not_number: PASS (4.38 s)                                                                                                                                              
 (182/184) type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_shutdown.config.schedinfo.iothread_quota.positive.value_positive: PASS (26.22 s)                                                                                                                                                
 (183/184) type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_shutdown.config.schedinfo.iothread_quota.positive.value_negative: PASS (25.23 s)                                                                                                                                                
 (184/184) type_specific.io-github-autotest-libvirt.guest_resource_control.control_cgroup.vm_shutdown.config.schedinfo.iothread_quota.negative.value_not_number: PASS (4.40 s)                                                                                                                                               
RESULTS    : PASS 184 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2023-07-21T01.39-828f544/results.html
JOB TIME   : 1487.79 s
```

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
