### PR TITLE
Enable the network xml to set with dhcp lease info

### PR DESCRIPTION
**Pull request by yalzhang**
Add the support for lease setting for ip/dhcp/range and
ip/dhcp/hosts.

Signed-off-by: Yalan Zhang <yalzhang@redhat.com>

### CODE REVIEW

**Comment by yalzhang** [comment]
test results refer to https://github.com/autotest/tp-libvirt/pull/3255#issuecomment-762295479

**Review by chunfuwen — APPROVED** [review]
LGTM

**Review by chloerh — APPROVED** [review]

**Comment by chloerh** [comment]
> @yalzhang I noticed you have made changes on Range, which might have been called in tp-libvirt. So, are you making those changes too?

Because if not, the changes of this pr could make some code of tp-libvirt invalid.

**Comment by yalzhang** [comment]
> > @yalzhang I noticed you have made changes on Range, which might have been called in tp-libvirt. So, are you making those changes too?
> 
> Because if not, the changes of this pr could make some code of tp-libvirt invalid.

Thank you for reminding me. I will update it.

**Pull request merged**
