### PR TITLE
Add support for SLES12 sp2 guest (x86_64)

### PR DESCRIPTION
**Pull request by yanan-fu**
Add support for SLES12 sp2 guest (x86_64)

id:1459763
Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
(003/132) smp_8.8192m.repeat1.Host_RHEL.m7.u4.spice.qcow2.virtio_scsi.up.virtio_net.SLES.12.2.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (601.37 s)
 (004/132) smp_8.8192m.repeat1.Host_RHEL.m7.u4.spice.qcow2.virtio_scsi.up.virtio_net.SLES.12.2.x86_64.io-github-autotest-qemu.shutdown: PASS (394.34 s)

**Comment by xutian** [comment]
looks OK to me

**Comment by luckyh** [comment]
Thanks @xutian @yanan-fu.

**Comment by morecache** [comment]
(1/1) io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native: PASS (665.44 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 665.44 s

**Comment by morecache** [comment]
Follow luckyh's comment, close #955 and upload the test result.
BTW, the tests for installation with virtio_blk or virtio_scsi are success.

**Comment by luckyh** [comment]
@morecache Ur, sorry, something seems to be misunderstood. This PR (https://github.com/avocado-framework/avocado-vt/pull/1028) did not contain `OpenSUSE.42.2.x86_64` part, so if that is still needed, please open a new PR (as you have already closed the original one) with the relevant files of  `OpenSUSE.42.2.x86_64`.

**Comment by morecache** [comment]
#1049 contains OpenSUSE.42.2.x86_64 part.

**Pull request merged**
